import { type AlwaysInjectFact, selectAlwaysInjectFromKnowledge } from '../knowledge/index.js';
import { logger } from '../lib/logger.js';
import { projectRulesText } from './facts/project-rules.js';
import { OPERATING_AFFORDANCES_TEXT } from './facts/registry.js';

/**
 * The line every generated orientation carries under its heading. The runner reads it
 * (`runner-workspace/src/orientation.rs:is_generated`) to tell an orientation Forge wrote from one a
 * person did, and refuses to write a body that lacks it.
 */
export const ORIENTATION_GENERATED_LINE =
  '<!-- Generated by Forge on device provision. Forge-owned; manual edits are overwritten. -->';

/**
 * The project's always-applied rules as an orientation reads them: its `injection: 'always'`
 * knowledge entries, or `unreadable` where the knowledge store could not be read.
 */
export type OrientationRules = { entries: readonly AlwaysInjectFact[] } | { unreadable: true };

/** The rules block, or a named absence: a box told nothing would read a project with no rules. */
function rulesText(projectId: string, rules: OrientationRules): string | null {
  if ('unreadable' in rules)
    return `## Project rules (always applied)

The project's knowledge could not be read when this orientation was written, so its rules are not here. Read them before you work: \`GET /api/projects/${projectId}/knowledge?injection=always\`.`;
  return rules.entries.length > 0 ? projectRulesText(rules.entries, 2) : null;
}

/**
 * The orientation a box writes into a checkout of project `slug` for a person's `claude` session
 * and for every run a master declares there, served on every provision and assignment read so the
 * box writes what it is sent. The affordances table is the one pipeline prompts carry
 * (`OPERATING_AFFORDANCES_TEXT`), and the project's always-applied knowledge entries are the block a
 * pipeline preamble carries (`projectRulesText`), so neither can drift from what a core-built prompt
 * says (REQ-43 BC-12). Deterministic for a project and its rules, so a re-provision writes
 * byte-identical output.
 */
export function checkoutOrientation(
  projectId: string,
  slug: string,
  rules: OrientationRules,
): string {
  const projectRules = rulesText(projectId, rules);
  return `# Forge orientation — ${slug}

${ORIENTATION_GENERATED_LINE}

This repo is managed by **Forge** — the control plane for its issues, pipeline, and durable
memory. Reach it through the REST API (\`forge-runner api <path>\`) or the \`forge\` CLI; the Forge MCP
server in \`.mcp.json\` carries only what neither covers, and its instructions name those tools.

- **projectId:** \`${projectId}\`  ·  **slug:** \`${slug}\`
- **Recall memory FIRST** — project memory is NOT auto-loaded. Before any task needing
  project context: \`POST /api/memory/search { "projectId": "${projectId}", "query": <topic>, "topK": 5 }\`.
  Treat hits as point-in-time — verify against live code/git before trusting.
- Codebase & project knowledge: \`GET /api/projects/${projectId}/knowledge\` or \`forge knowledge\`.
- Issues / tasks / status / dependencies: \`forge issue\`, \`forge new\`, \`forge comment\`, or
  \`/api/projects/${projectId}/issues\` and \`/api/issues/<id>\`.
- Before writing, rewriting, or tuning this project's pipeline skills, read the \`forge-skills\`
  MCP prompt (the always-latest authoring guide).

${OPERATING_AFFORDANCES_TEXT}
${projectRules ? `\n${projectRules.trimEnd()}\n` : ''}`;
}

/**
 * The orientation core serves a box for project `slug`, its rules read from the knowledge store. A
 * store that cannot be read is said in the orientation rather than failing the box's whole read,
 * which also carries which projects route to it.
 */
export async function servedCheckoutOrientation(projectId: string, slug: string): Promise<string> {
  let rules: OrientationRules;
  try {
    rules = { entries: await selectAlwaysInjectFromKnowledge(projectId) };
  } catch (err) {
    logger.error(
      { err: (err as Error).message, projectId },
      'checkout orientation: knowledge store unreadable, the orientation says so in place of the rules',
    );
    rules = { unreadable: true };
  }
  return checkoutOrientation(projectId, slug, rules);
}
