import { OPERATING_AFFORDANCES_TEXT } from './facts/registry.js';

/**
 * The line every generated orientation carries under its heading. The runner reads it
 * (`runner-workspace/src/orientation.rs:is_generated`) to tell an orientation Forge wrote from one a
 * person did, and refuses to write a body that lacks it.
 */
export const ORIENTATION_GENERATED_LINE =
  '<!-- Generated by Forge on device provision. Forge-owned; manual edits are overwritten. -->';

/**
 * The orientation a box writes into a checkout of project `slug` for a person's `claude` session,
 * served on every provision and assignment read so the box writes what it is sent. The affordances
 * table is the one pipeline prompts carry (`OPERATING_AFFORDANCES_TEXT`), so the two cannot drift.
 * Deterministic for a project, so a re-provision writes byte-identical output.
 */
export function checkoutOrientation(projectId: string, slug: string): string {
  return `# Forge orientation — ${slug}

${ORIENTATION_GENERATED_LINE}

This repo is managed by **Forge** — the control plane for its issues, pipeline, and durable
memory. Reach it through the REST API (\`forge-runner api <path>\`) or the \`forge\` CLI; the Forge MCP
server in \`.mcp.json\` carries only what neither covers, and its instructions name those tools.

- **projectId:** \`${projectId}\`  ·  **slug:** \`${slug}\`
- **Recall memory FIRST** — project memory is NOT auto-loaded. Before any task needing
  project context: \`POST /api/memory/search { "projectId": "${projectId}", "query": <topic>, "topK": 5 }\`.
  Treat hits as point-in-time — verify against live code/git before trusting.
- Codebase & project knowledge: \`GET /api/projects/${projectId}/knowledge\` or \`forge knowledge\`.
- Issues / tasks / status / dependencies: \`forge issue\`, \`forge new\`, \`forge comment\`, or
  \`/api/projects/${projectId}/issues\` and \`/api/issues/<id>\`.
- Before writing, rewriting, or tuning this project's pipeline skills, read the \`forge-skills\`
  MCP prompt (the always-latest authoring guide).

${OPERATING_AFFORDANCES_TEXT}
`;
}
