// @generated by archmap 0.1.4 — vendored copy, do not edit
import { readFileSync, existsSync } from 'node:fs';

// cm:why this module reconstructs the file the write WOULD produce, rather than letting the write
//   land and checking afterwards. Checking afterwards is what CI already does; the whole value of
//   the pre-write surface is that the cost of the fix is still zero.
// cm:edge contract -> src/hook/pre-edit.mjs — {ok:false, reason} here means CANNOT RUN, which that
//   module maps to allow-with-a-loud-warning, never to a deny and never to silence.

function readIfPresent(absPath) {
  if (!existsSync(absPath)) return '';
  return readFileSync(absPath, 'utf8');
}

function applyEdit(text, { old_string: oldStr, new_string: newStr, replace_all: all }) {
  if (typeof oldStr !== 'string' || typeof newStr !== 'string') {
    return { ok: false, reason: 'edit is missing old_string or new_string' };
  }
  // cm:guard an empty old_string means "create", which Claude Code only accepts on a new file.
  //   Treating it as a substring match would splice the new text in at offset 0 of an existing
  //   file and judge a tree that will never exist.
  if (oldStr === '') return { ok: true, text: newStr };
  if (!text.includes(oldStr)) {
    return { ok: false, reason: 'old_string was not found in the file on disk' };
  }
  return { ok: true, text: all ? text.split(oldStr).join(newStr) : text.replace(oldStr, newStr) };
}

/**
 * The bytes the file will hold once this tool call completes. `Write` states them outright; `Edit`
 * and `MultiEdit` are replayed against what is on disk right now.
 */
export function pendingText(input, absPath) {
  const tool = input?.tool_name;
  const ti = input?.tool_input ?? {};

  if (tool === 'Write') {
    if (typeof ti.content !== 'string') return { ok: false, reason: 'Write carried no content' };
    return { ok: true, text: ti.content };
  }

  let onDisk;
  try {
    onDisk = readIfPresent(absPath);
  } catch (e) {
    return { ok: false, reason: `could not read the file being edited: ${e.message}` };
  }

  if (tool === 'Edit') return applyEdit(onDisk, ti);

  if (tool === 'MultiEdit') {
    const edits = Array.isArray(ti.edits) ? ti.edits : null;
    if (!edits) return { ok: false, reason: 'MultiEdit carried no edits[]' };
    let text = onDisk;
    for (const edit of edits) {
      const r = applyEdit(text, edit ?? {});
      if (!r.ok) return r;
      text = r.text;
    }
    return { ok: true, text };
  }

  return { ok: false, reason: `unsupported tool "${tool ?? 'unknown'}"` };
}

/**
 * Source with comments removed and template literals reduced to what can legitimately be a
 * specifier. Ordinary quoted strings are copied through, because they are where the real
 * specifiers live.
 *
 * Returns `{ ok, code }`. `ok:false` means the scan hit end-of-input inside a string, a template or
 * a block comment — the remainder of the file was never seen, so no answer derived from `code` is
 * trustworthy and the caller must treat it as a cannot-run.
 */
export function stripNonCode(text) {
  let out = '';
  let ok = true;
  for (let i = 0; i < text.length;) {
    const c = text[i];
    if (c === '/' && text[i + 1] === '/') {
      while (i < text.length && text[i] !== '\n') i++;
      continue;
    }
    if (c === '/' && text[i + 1] === '*') {
      i += 2;
      while (i < text.length && !(text[i] === '*' && text[i + 1] === '/')) i++;
      if (i >= text.length) { ok = false; break; }
      i += 2;
      continue;
    }
    if (c === '`') {
      // cm:why a template body is KEPT when it is plain, and dropped when it is not. `import(`./x`)`
      //   is a real edge dependency-cruiser reports and the module system honours — dropping it
      //   wholesale made the hook silently blind to every dynamic import written that way. But a
      //   body holding an interpolation or a nested quote is either uncomputable or prose quoting
      //   code, and inventing an edge from prose denies a write on nothing. So: plain body kept
      //   verbatim between its backticks, anything else emptied. `${` and quotes are the test.
      const start = ++i;
      while (i < text.length && text[i] !== '`') {
        if (text[i] === '\\') { i += 2; continue; }
        i++;
      }
      if (i >= text.length) { ok = false; break; }
      const body = text.slice(start, i);
      i++;
      out += /[`'"]|\$\{/.test(body) || body.includes('\n') ? '``' : `\`${body}\``;
      continue;
    }
    if (c === '"' || c === "'") {
      out += c;
      i++;
      let closed = false;
      while (i < text.length && text[i] !== '\n') {
        if (text[i] === c) { closed = true; break; }
        if (text[i] === '\\' && text[i + 1] !== '\n') { out += text.slice(i, i + 2); i += 2; continue; }
        out += text[i];
        i++;
      }
      // cm:guard a quote left open at end of LINE is not a string — it is an apostrophe in JSX text
      //   or in prose. Ending it at the newline keeps the rest of the file in the scan; calling it
      //   unterminated would turn every `don't` in a component into a cannot-run. End of FILE is
      //   different: there is no rest of the file, so the source really was truncated.
      if (closed) { out += c; i++; continue; }
      if (i >= text.length) { ok = false; break; }
      continue;
    }
    out += c;
    i++;
  }
  return { ok, code: out };
}

const PATTERNS = [
  /\bfrom\s*['"`]([^'"`\n]+)['"`]/g,
  /\bimport\s+['"`]([^'"`\n]+)['"`]/g,
  /\bimport\s*\(\s*['"`]([^'"`\n]+)['"`]\s*\)/g,
  /\brequire\s*\(\s*['"`]([^'"`\n]+)['"`]\s*\)/g,
];

/**
 * Every import specifier the source mentions, as `{ ok, specs }`. A regex scan, deliberately: the
 * alternative is a parser this repo does not own, and the hook only ever ACTS on specifiers that
 * are new relative to what is already on disk — so an over-read costs a named line in a message,
 * not a wrong graph. `ok:false` propagates the unterminated-literal cannot-run from stripNonCode.
 */
export function importSpecs(text) {
  const { ok, code } = stripNonCode(text ?? '');
  const specs = new Set();
  for (const re of PATTERNS) {
    re.lastIndex = 0;
    for (let m = re.exec(code); m; m = re.exec(code)) specs.add(m[1]);
  }
  return { ok, specs };
}

export { readIfPresent };
