// @generated by archmap 0.1.3 — vendored copy, do not edit
import { closeSync, existsSync, lstatSync, mkdirSync, openSync, unlinkSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { tmpdir, userInfo } from 'node:os';
import { dirname, extname, isAbsolute, join, relative, resolve, sep } from 'node:path';
import { loadManifest, findRoot, ManifestError } from '../manifest.mjs';
import { normalize } from '../graph/normalize.mjs';
import { ContractError } from '../contracts/index.mjs';
import { collectGraph, loadBaseline, buildReport, baselineKey, VENDOR_GLOB } from '../check.mjs';
import { version, selfCopy } from '../install.mjs';
import { pendingText, importSpecs, readIfPresent } from './pending.mjs';
import { specTable, resolvePending, aliasPatterns, wouldName } from './resolve.mjs';

// cm:why the pre-write surface exists at all: CI says the right thing too late. By the time a
//   boundary violation reaches a pipeline the code is written, reviewed and often merged; before
//   the bytes land the cost of the fix is zero. NORTH-STAR §5's first clause is this file.
// cm:edge protocol -> claude-plugin/scripts/hook-pre-edit.mjs — that script only plumbs stdin to
//   decide() and stdout/stderr + exit code back out. All judgement is here, so it is testable.

// cm:guard EXIT CODES INVERT HERE, deliberately. In CLI form 2 means "the gate could not run"; in
//   PreToolUse form 2 means DENY (the client's protocol, not ours). So every cannot-run state maps
//   to exit 0 plus a loud warning, and exit 2 is reserved for a real, evidenced violation. Do not
//   "fix" a cannot-run into an exit 2: that turns an archmap outage into a blanket write block.
const ALLOW = 0;
const DENY = 2;

// cm:why the rollout guard, and why it is one constant. PLAYBOOK §A.4: do not install a boundary
//   gate on a repo that has not decided its boundaries yet — the findings are noise, the hook gets
//   switched off, and the next repo never gets it. Two LOCKED directional contracts is the issue's
//   paraphrase of that bar; a human moves it in one edit rather than reverse-engineering a policy.
export const MIN_DIRECTIONAL_CONTRACTS = 2;
const DIRECTIONAL = new Set(['layers', 'forbidden', 'independence']);

// cm:guard the internal budget sits UNDER the hooks.json timeout on purpose. If the client kills us
//   we decide nothing and the agent learns nothing; if we time out ourselves we still get to print
//   the warning that says the graph was not built. Measured end to end (stdin in, deny out): 1.4s
//   at 753 files, 2.0s at 2253 — so 12s is roughly 6x the largest repo measured, and it is a
//   WALL-CLOCK budget for the whole collection: collectGraph deducts what each provider spends.
export const DEFAULT_BUDGET_MS = 12_000;

const SOURCE_EXT = new Set(['.ts', '.tsx', '.mts', '.cts', '.js', '.jsx', '.mjs', '.cjs']);

// cm:guard extensions of a language archmap DOES gate in CI but this surface cannot judge yet: the
//   pending-edit resolver is TypeScript-shaped, so a Go write would be measured with the wrong
//   ruler. Silence here would be the worst answer — `src/providers/go.mjs` is a first-class provider
//   and a reader is entitled to assume a gate that ships for Go also guards Go. So: say so, once.
const UNJUDGED_EXT = new Set(['.go']);

const NOTICE_TTL_MS = 4 * 60 * 60 * 1000;

// cm:guard the label asks whether THIS copy is an installed one, not whether some repo's vendor
//   path points at it: the plugin script imports `<root>/.forge/archmap/src/hook/pre-edit.mjs` by
//   construction, so an installed copy here is that copy. Deciding it from the repo is what ISS-8
//   review round 4 closed in the CLI.
function stamp() {
  return selfCopy() !== null
    ? `archmap ${version()} · the repo's vendored copy (.forge/archmap)`
    : `archmap ${version()} · a source checkout`;
}

/**
 * True the first time a (root, kind) notice is due within the TTL. The inert-guard line and the
 * holed-graph line are otherwise printed on EVERY write in a qualifying repo, which is precisely
 * how a hook earns its way onto someone's disable list. Deny messages are never deduped.
 */
function noticeDue(root, kind, env) {
  if (env.ARCHMAP_HOOK_NOTICE === 'always') return true;
  try {
    // cm:guard the stamp path is derived from a repo path anyone can guess, and it lives in a
    //   world-writable directory on a shared host or CI runner. So: a per-user directory created
    //   0700, an lstat that refuses to follow anything that is not a regular file, and an exclusive
    //   create. Without those, a pre-planted symlink turns this stamp into a truncation of whatever
    //   it points at, running as the developer — and silences the notice on the way through.
    const dir = env.ARCHMAP_HOOK_STAMP_DIR || join(tmpdir(), `archmap-hook-${userInfo().uid ?? 'user'}`);
    mkdirSync(dir, { recursive: true, mode: 0o700 });
    const key = createHash('sha256').update(`${root}\0${kind}`).digest('hex').slice(0, 16);
    const path = join(dir, `${key}.stamp`);

    let st = null;
    try { st = lstatSync(path); } catch { /* not there yet */ }
    if (st) {
      // cm:guard anything that is not a regular file at this path was not written by us. Print the
      //   notice and write nothing — suppressing it is exactly what the planter wanted.
      if (!st.isFile()) return true;
      if (Date.now() - st.mtimeMs < NOTICE_TTL_MS) return false;
      unlinkSync(path);
    }
    closeSync(openSync(path, 'wx', 0o600));
    return true;
  } catch {
    // cm:guard an unwritable tmpdir must not silence the notice. Repeating is noise; skipping is
    //   a gate that never says it is inert, which reads exactly like a gate that found nothing.
    return true;
  }
}

const allow = (message = '') => ({ decision: 'allow', exitCode: ALLOW, message });

function warn(lines) {
  return allow(['archmap: WARNING — the architecture gate could not run on this write.', ...lines.map((l) => `  ${l}`),
    '  The write was ALLOWED. This is not a clean verdict; it is no verdict.',
    `  ${stamp()}`].join('\n'));
}

function notice(lines) {
  return allow([...lines, `  ${stamp()}`].join('\n'));
}

const deny = (message) => ({ decision: 'deny', exitCode: DENY, message });

// cm:edge protocol -> claude-plugin/scripts/hook-pre-edit.mjs — this module returns a VERDICT
//   ({decision, exitCode, message}) and never bytes on a stream. That script formats it, and it
//   accepts nothing else from here, so a tampered or stale copy of this file cannot reach the
//   client with a `permissionDecision: "allow"` and auto-approve a write nobody was asked about.
//   A deny is rendered there twice over: structured on stdout, where hookSpecificOutput is parsed,
//   and as readable text on stderr, which exit 2 feeds back to the agent. A warning rides on
//   `additionalContext` (the model reads it) and `systemMessage` (the human does) — a warning only
//   the transcript can see is a warning the decision-maker never gets.

function directionalCount(manifest) {
  return manifest.contracts.filter((c) => c.status === 'locked'
    && DIRECTIONAL.has(c.type)
    && (c.type !== 'layers' || (Array.isArray(c.order) && c.order.length >= 2))).length;
}

function holedGraphLines(stats) {
  return [
    `${stats.count} of ${stats.total} possible edges (${stats.pct}%) in this repo could not be resolved.`,
    'A contract over this graph can pass because its edges are ABSENT, not because the code obeys',
    'it — so this hook is partially blind here. Check that tsconfig `paths` aliases resolve:',
    'archmap check --json lists every unresolvable spec.',
  ];
}

/**
 * Splices the pending file's edges into a copy of the provider results.
 *
 * REPLACE, not merely add: edges from the pending file whose specifier did not survive the edit are
 * dropped, so removing an import can never produce a finding. The file itself is force-added to
 * `files` because a `Write` of a brand-new file has no graph entry to amend.
 */
function splice(results, { root, relFile, keepSpecs, resolved, unresolved, patterns }) {
  const keep = new Set(keepSpecs);
  const out = results.map((r) => ({ ...r }));
  let target = out.find((r) => r.ok && r.language === 'ts');
  if (!target) {
    target = { ok: true, language: 'ts', provider: 'pending', files: [], edges: [], unresolvable: [] };
    out.push(target);
  }

  const edges = [
    ...(target.edges ?? []).filter((e) => e.from !== relFile || keep.has(e.spec)),
    ...resolved.map(({ spec, to }) => ({ from: relFile, to, spec, dynamic: false })),
  ];
  const dangling = [
    ...(target.unresolvable ?? []).filter((u) => u.from !== relFile || keep.has(u.spec)),
    ...unresolved.map((spec) => ({ from: relFile, spec, why: 'could not resolve' })),
  ];

  // cm:why the OTHER files' dangling imports are re-resolved against this write. "Write the
  //   importer, then write the module it imports" is the ordinary way an agent builds a feature,
  //   and until the second write lands the first one's specifier resolves to nothing. Judging only
  //   the edges leaving the pending file means the write that COMPLETES the violation — the second
  //   one — is waved through, and the boundary is crossed by a pair of writes neither of which was
  //   ever denied. An absent edge makes a locked contract pass; that is the fail-open, once again.
  const stillDangling = [];
  for (const u of dangling) {
    if (u.from !== relFile && wouldName(root, u.from, u.spec, relFile, patterns)) {
      edges.push({ from: u.from, to: relFile, spec: u.spec, dynamic: false });
      continue;
    }
    stillDangling.push(u);
  }

  target.edges = edges;
  target.unresolvable = stillDangling;
  const files = new Set(target.files ?? []);
  files.add(relFile);
  for (const { to } of resolved) files.add(to);
  target.files = [...files];
  return out;
}

/** Whether `path` is `base` or sits inside it. Both must already be absolute. */
function inside(base, path) {
  return path === base || path.startsWith(base.endsWith(sep) ? base : base + sep);
}

/**
 * The whole decision. Returns what to print and what to exit with; it writes nothing itself, which
 * is what makes every branch below reachable from a test.
 */
export function decide(input, env = process.env) {
  if (env.ARCHMAP_HOOK === 'off') return allow();

  const target = input?.tool_input?.file_path;
  if (typeof target !== 'string' || !target) return allow();
  const abs = isAbsolute(target) ? target : resolve(target);

  const root = findRoot(dirname(abs));
  // cm:guard SILENT, not a notice. This plugin is installed per device and most repos have no
  //   .arch.json; a line here would print on every write in every unrelated repo, forever.
  if (!root) return allow();

  // cm:guard the manifest that decides this write must belong to the session's own project. findRoot
  //   walks to `/`, so without this a `.arch.json` planted in any writable ancestor — /tmp is the
  //   easy one — gets to answer for a scratch write, and its contracts run as the developer. A root
  //   ABOVE the project dir is legitimate (monorepo); one off to the side never is.
  const boundary = env.CLAUDE_PROJECT_DIR || input?.cwd;
  if (typeof boundary === 'string' && boundary) {
    const bound = resolve(boundary);
    if (!inside(bound, root) && !inside(root, bound)) return allow();
  }

  const relFile = relative(root, abs).split(sep).join('/');
  if (!relFile || relFile.startsWith('..')) return allow();
  const ext = extname(relFile);
  if (!SOURCE_EXT.has(ext) && !UNJUDGED_EXT.has(ext)) return allow();

  let manifest;
  try {
    manifest = loadManifest(root);
  } catch (e) {
    if (e instanceof ManifestError) return warn([`${root}/.arch.json could not be read: ${e.message}`]);
    throw e;
  }
  manifest.exclude = [VENDOR_GLOB, ...manifest.exclude];

  const directional = directionalCount(manifest);
  if (directional < MIN_DIRECTIONAL_CONTRACTS) {
    if (!noticeDue(root, 'guard', env)) return allow();
    return notice([
      `archmap: inert in this repo — ${directional} of ${MIN_DIRECTIONAL_CONTRACTS} locked directional`,
      '  contracts declared (layers / forbidden / independence). A boundary gate on a repo that has',
      '  not decided its boundaries produces noise, not signal, so this hook will never deny here.',
      '  Declare the boundaries in .arch.json and lock them to turn it on.',
    ]);
  }

  // cm:why this sits AFTER the rollout guard rather than with the other extension tests: a repo that
  //   has not declared its boundaries gets no archmap chatter at all, and "we cannot judge this
  //   language" is chatter in a repo where we would not have judged anything anyway.
  if (UNJUDGED_EXT.has(ext)) {
    if (!noticeDue(root, `unjudged${ext}`, env)) return allow();
    return notice([
      `archmap: BLIND SPOT — this hook does not judge ${ext} writes.`,
      `  ${ext} files ARE in the graph archmap builds and ARE gated by the same contracts in CI, but`,
      '  the pre-write resolver only understands TypeScript/JavaScript specifiers. A boundary this',
      '  write crosses will be caught by `archmap check`, not here.',
    ]);
  }

  const onDisk = (() => {
    try { return readIfPresent(abs); } catch { return null; }
  })();
  if (onDisk === null) return warn([`could not read ${relFile} to compute what the write would produce.`]);

  const pending = pendingText(input, abs);
  if (!pending.ok) return warn([`could not reconstruct ${relFile} after this write: ${pending.reason}.`]);

  const pendingSpecs = importSpecs(pending.text);
  const before = importSpecs(onDisk);
  // cm:guard an unterminated string or template means the scanner never saw the rest of the file, so
  //   "no new specifiers" would be an artefact of where it stopped rather than a fact about the
  //   code. That is a cannot-run, and cannot-run is loud.
  if (!pendingSpecs.ok || !before.ok) {
    return warn([`${relFile} could not be scanned for imports: a string or template literal is left`,
      'open at end of file, so the rest of it was never read.']);
  }
  const newSpecs = [...pendingSpecs.specs].filter((s) => !before.specs.has(s));

  // cm:why creating a file is never a cheap exit, even with no imports of its own. A file that did
  //   not exist is one that other files' imports could not resolve to; the moment it lands, every
  //   dangling specifier naming it becomes a real edge. See the splice.
  const creating = !existsSync(abs);
  // cm:why a write that adds no NEW specifier cannot introduce a new boundary finding: findings are
  //   derived from edges, and edges only come from specifiers. Removals are handled by the splice
  //   below, and a removal can only ever shrink the finding set. This is also the exit that keeps
  //   the common case (editing a function body) free of a 2-3s cruise.
  if (newSpecs.length === 0 && !creating) return allow();

  const budget = Number(env.ARCHMAP_HOOK_BUDGET_MS) || DEFAULT_BUDGET_MS;
  const { results, failures, notes } = collectGraph(manifest, ['.'], { timeoutMs: budget });
  // cm:guard ANY provider failure is a cannot-run. Judging a write on a partial graph is the
  //   ISS-1 fail-open in a surface with no CI log for anyone to read afterwards.
  if (failures.length > 0) return warn([`a provider could not run: ${failures.join('; ')}.`, ...notes]);
  if (results.length === 0) return warn(['no provider produced a graph.', ...notes]);
  const tsResult = results.find((r) => r.language === 'ts');
  if (tsResult?.provider === 'absent') {
    return warn([`${relFile} is TypeScript/JavaScript but this repo has no package.json, so the`,
      'graph is empty and no contract over it means anything.']);
  }

  const preGraph = normalize(manifest, results);
  // cm:guard the CLI dies with exit 2 on this ("scope matched no files"), and for the same reason:
  //   a graph with nothing in it is not a clean repo, it is a scope that matched nothing — an
  //   exclude that swallowed src/**, a module glob that never hit. Every contract over it passes
  //   trivially, so without this check the hook returns a silent allow on every write forever.
  if (preGraph.files.size === 0) {
    return warn(['the configured scope matched no files at all, so every contract passes over an',
      'empty graph. Check `modules` and `exclude` in .arch.json — `archmap check` fails outright here.']);
  }

  const patterns = aliasPatterns(root);
  const { resolved, unresolved } = resolvePending({
    root,
    relFile,
    specs: newSpecs,
    table: specTable(results),
    patterns,
  });

  const baseline = loadBaseline(root);
  let pre, post;
  try {
    pre = buildReport(manifest, preGraph, baseline, { failures, notes });
    post = buildReport(
      manifest,
      normalize(manifest, splice(results, {
        root, relFile, keepSpecs: pendingSpecs.specs, resolved, unresolved, patterns,
      })),
      baseline,
      { failures, notes },
    );
  } catch (e) {
    // cm:guard a contract with no evaluator means NOTHING was checked. Allowing loudly is the only
    //   honest answer; denying would block on a rule we never evaluated.
    if (e instanceof ContractError) return warn([`a contract could not be evaluated: ${e.message}.`]);
    throw e;
  }

  const seen = new Set(pre.blocking.map(baselineKey));
  const introduced = post.blocking.filter((f) => !seen.has(baselineKey(f)));

  if (introduced.length > 0) {
    return deny(denyMessage({ relFile, resolved, unresolved, introduced, post }));
  }

  const seenAdvisory = new Set(pre.advisory.map(baselineKey));
  const newAdvisory = post.advisory.filter((f) => !seenAdvisory.has(baselineKey(f)));

  const lines = [];
  if (newAdvisory.length > 0) {
    lines.push('archmap: this write introduces a DRAFT contract finding. Not blocking — the contract');
    lines.push('  is not locked yet — but it is the shape a locked one would stop:');
    for (const f of newAdvisory) lines.push(`  warn  [${f.contract}] ${f.message}`);
  }
  if (unresolved.length > 0) {
    lines.push(`archmap: BLIND SPOT — could not resolve ${unresolved.length === 1 ? 'a new import' : 'new imports'}`
      + ` in ${relFile}: ${unresolved.join(', ')}.`);
    lines.push('  Those edges are missing from the graph this write was judged against, so a locked');
    lines.push('  contract they would break has NOT been checked. Allowed, but unverified.');
  }
  // cm:guard the stamp is consumed BEFORE the || is evaluated, not inside it. Short-circuited, the
  //   holed-graph line printed alongside any other line never consumed its TTL slot — so it came
  //   back on the very next write instead of once every four hours, and the de-duplication that
  //   keeps this hook off someone's disable list applied only to the quietest case.
  const holedDue = post.unresolvableStats.above && noticeDue(root, 'holed', env);
  if (post.unresolvableStats.above && (lines.length > 0 || holedDue)) {
    lines.push('archmap: WARNING — this repo\'s graph has holes.');
    for (const l of holedGraphLines(post.unresolvableStats)) lines.push(`  ${l}`);
  }
  return lines.length > 0 ? notice(lines) : allow();
}

function denyMessage({ relFile, resolved, unresolved, introduced, post }) {
  const out = [
    'archmap: this write would introduce a locked architecture-contract violation. Denied before',
    'the bytes land, because after they land the fix is no longer free.',
    '',
    `  file        ${relFile}`,
  ];
  for (const { spec, to } of resolved) out.push(`  new import  ${spec}  ->  ${to}`);
  if (resolved.length === 0) {
    // cm:why this line exists: with no new import of its own, the write is denied because CREATING
    //   the file resolves an import another file already had. Without saying so the message reads
    //   as a verdict on bytes that plainly contain no dependency at all.
    out.push('  no new import of its own — creating this file completes an import made elsewhere');
  }
  out.push('');

  for (const f of introduced) {
    out.push(`  error  [${f.contract}] (${f.type}, ${f.status})`);
    out.push(`         ${f.message}`);
    if (f.from) out.push(`         ${f.from}${f.to ? ` -> ${f.to}` : ''}`);
  }
  out.push('');

  for (const type of new Set(introduced.map((f) => f.type))) {
    out.push(`${type}: ${post.remedies[type] ?? introduced.find((f) => f.type === type)?.remedy ?? ''}`);
  }
  out.push(post.policy || 'Fix the source, not the check: do not widen .arch.json to make this pass.');

  if (unresolved.length > 0) {
    out.push('');
    out.push(`Note: ${unresolved.join(', ')} could not be resolved, so this verdict does not cover ${unresolved.length === 1 ? 'it' : 'them'}.`);
  }
  // cm:guard the holed-graph warning rides on the DENY too, never deduped. A reader who has just
  //   been blocked is the one person guaranteed to be reading, and "we also cannot see 40% of this
  //   repo" changes how much the verdict is worth in both directions.
  if (post.unresolvableStats.above) {
    out.push('');
    out.push('WARNING — this verdict was reached over a graph with holes.');
    for (const l of holedGraphLines(post.unresolvableStats)) out.push(`  ${l}`);
  }
  out.push('');
  out.push(stamp());
  return out.join('\n');
}

/** Reads a JSON payload on stdin, decides, prints, and returns the exit code. */
export function runHook(stdinText, env = process.env) {
  let input;
  try {
    input = JSON.parse(stdinText);
  } catch {
    // cm:guard a payload we cannot parse is a cannot-run, so it allows — but LOUDLY, because the
    //   silent version of this is a hook that has been dead for months and looks installed.
    return warn(['the hook payload on stdin was not valid JSON.']);
  }
  try {
    return decide(input, env);
  } catch (e) {
    return warn([`the hook crashed: ${e?.message ?? e}.`]);
  }
}
