// @generated by archmap 0.1.3 — vendored copy, do not edit
import { readFileSync, statSync } from 'node:fs';
import { builtinModules } from 'node:module';
import { dirname, extname, isAbsolute, join, relative, resolve, sep } from 'node:path';
import { planTsConfig, collectFrom } from '../providers/tsconfig.mjs';

// cm:why SPEC §2.4 says archmap never resolves TypeScript itself, and this module does not overturn
//   that: dependency-cruiser still resolves the entire repo. It cannot resolve bytes that are not
//   on disk yet, and writing them into the scanned tree is forbidden (ts.mjs:119-121) — so this
//   resolves ONE thing, the specifiers a single pending edit introduces, and hands anything it is
//   not sure about to the caller as an unresolved blind spot rather than an assumed absence.
// cm:edge contract -> src/hook/pre-edit.mjs — { resolved, unresolved } is the splice's input

const EXTENSIONS = ['.ts', '.tsx', '.mts', '.cts', '.js', '.jsx', '.mjs', '.cjs'];

const BUILTIN = new Set(builtinModules);

function isFile(path) {
  try {
    return statSync(path).isFile();
  } catch {
    return false;
  }
}

function isDir(path) {
  try {
    return statSync(path).isDirectory();
  } catch {
    return false;
  }
}

/** `lodash/get` -> `lodash`, `@scope/pkg/sub` -> `@scope/pkg`. */
function packageOf(spec) {
  const parts = spec.split('/');
  return spec.startsWith('@') ? parts.slice(0, 2).join('/') : parts[0];
}

/** Every node_modules directory Node would consult, nearest first, bounded by the repo root. */
function packageDir(root, fromDir, pkg) {
  const stop = resolve(root);
  for (let dir = resolve(root, fromDir); ; dir = dirname(dir)) {
    const candidate = join(dir, 'node_modules', pkg);
    if (isDir(candidate)) return candidate;
    if (dir === stop || dirname(dir) === dir) return null;
  }
}

/**
 * The file inside an installed package that the specifier actually names — the same thing
 * dependency-cruiser reports, not a fabricated `node_modules/<spec>`. A key built from the fabricated
 * form never matches the one CI emits, so a baseline entry for a package edge silently stops
 * freezing it.
 */
function packageEntry(pkgDir, pkg, spec) {
  const sub = spec.slice(pkg.length).replace(/^\//, '');
  if (sub) return probe(join(pkgDir, sub));

  let main = null;
  try {
    const pj = JSON.parse(readFileSync(join(pkgDir, 'package.json'), 'utf8'));
    main = typeof pj.exports === 'string' ? pj.exports
      : (typeof pj.exports?.['.'] === 'string' ? pj.exports['.'] : null) ?? pj.module ?? pj.main ?? null;
  } catch { /* no readable manifest — fall through to index */ }

  return (main && probe(join(pkgDir, main))) || probe(join(pkgDir, 'index'));
}

// cm:why an installed package is a RESOLVED edge into unmapped territory, not a blind spot. That is
//   what dependency-cruiser reports for it (it resolves node_modules, it just does not follow), so
//   calling it unresolvable here would warn on every first `import react` — and a hook that cries
//   wolf on ordinary work is a hook someone turns off. A package that is NOT installed, or whose
//   entry file cannot be pinned, stays a blind spot rather than a guessed path.
function viaNodeModules(root, fromDir, spec) {
  const pkg = packageOf(spec);
  if (!pkg) return null;
  const dir = packageDir(root, fromDir, pkg);
  return dir ? packageEntry(dir, pkg, spec) : null;
}

// cm:why TypeScript's output-extension mapping is applied here. Under `moduleResolution: NodeNext` a
//   source file imports its sibling as `./x.js` and TS resolves that to `x.ts`. Without this every
//   new cross-directory import in a NodeNext repo lands in `unresolved` — a warn-allow — so the hook
//   degrades to a warning generator that can never deny, while CI reports the same edge as blocking.
const OUTPUT_EXT = { '.js': ['.ts', '.tsx'], '.jsx': ['.tsx'], '.mjs': ['.mts'], '.cjs': ['.cts'] };

/** An extensionless candidate probed the way a bundler would: exact, +ext, then /index+ext. */
function probe(absNoExt) {
  for (const ext of OUTPUT_EXT[extname(absNoExt)] ?? []) {
    const swapped = absNoExt.slice(0, -extname(absNoExt).length) + ext;
    if (isFile(swapped)) return swapped;
  }
  if (isFile(absNoExt)) return absNoExt;
  for (const ext of EXTENSIONS) if (isFile(absNoExt + ext)) return absNoExt + ext;
  for (const ext of EXTENSIONS) {
    const idx = join(absNoExt, `index${ext}`);
    if (isFile(idx)) return idx;
  }
  return null;
}

/**
 * Would `spec`, written in `fromFile`, name `pendingFile`? Answered LEXICALLY, because the pending
 * file is not on disk yet: this is how an import that is currently dangling becomes a real edge the
 * moment the write that creates its target lands.
 *
 * Both paths are repo-relative and POSIX-separated.
 */
export function wouldName(root, fromFile, spec, pendingFile, patterns = {}) {
  const candidates = [];
  if (RELATIVE(spec)) {
    const abs = resolve(root, dirname(fromFile), spec);
    const rel = toRel(root, abs);
    if (rel) candidates.push(rel);
  } else {
    for (const target of aliasTargets(patterns, spec)) {
      const rel = toRel(root, isAbsolute(target) ? target : resolve(target));
      if (rel) candidates.push(rel);
    }
  }

  for (const base of candidates) {
    if (base === pendingFile) return true;
    const swap = OUTPUT_EXT[extname(base)];
    if (swap) {
      const stem = base.slice(0, -extname(base).length);
      if (swap.some((e) => stem + e === pendingFile)) return true;
    }
    if (EXTENSIONS.some((e) => base + e === pendingFile)) return true;
    if (EXTENSIONS.some((e) => `${base}/index${e}` === pendingFile)) return true;
  }
  return false;
}

function toRel(root, abs) {
  const rel = relative(root, abs);
  if (!rel || rel.startsWith('..') || isAbsolute(rel)) return null;
  return rel.split(sep).join('/');
}

const RELATIVE = (spec) => spec.startsWith('./') || spec.startsWith('../');

function tableKey(fromDir, spec) {
  return RELATIVE(spec) ? `${fromDir}\0${spec}` : spec;
}

/**
 * Tier 1 — every (importing directory, specifier) pair dependency-cruiser already resolved in this
 * repo. Anything the codebase imports somewhere resolves here with zero new logic and zero risk of
 * disagreeing with the graph the contracts are evaluated over.
 */
export function specTable(providerResults) {
  const table = new Map();
  for (const r of providerResults ?? []) {
    if (!r.ok || r.language !== 'ts') continue;
    for (const e of r.edges ?? []) {
      if (typeof e.spec !== 'string' || !e.spec) continue;
      const key = tableKey(dirname(e.from), e.spec);
      if (!table.has(key)) table.set(key, e.to);
    }
  }
  return table;
}

/** Tier 3 — `compilerOptions.paths`, from wherever in the config graph it is actually written. */
export function aliasPatterns(root) {
  const plan = planTsConfig(root);
  if (plan.mode === 'merged') return plan.config?.compilerOptions?.paths ?? {};
  if (plan.mode === 'root') {
    const out = {};
    // targets from collectFrom are already absolute, per that module's contract
    for (const [pattern, targets] of collectFrom(plan.path).patterns) out[pattern] = targets;
    return out;
  }
  return {};
}

/** Every path a `paths` pattern maps `spec` onto, in declaration order and without touching disk. */
function aliasTargets(patterns, spec) {
  const out = [];
  for (const [pattern, targets] of Object.entries(patterns ?? {})) {
    const star = pattern.indexOf('*');
    let tail = null;
    if (star === -1) {
      if (pattern !== spec) continue;
      tail = '';
    } else {
      const head = pattern.slice(0, star);
      const rest = pattern.slice(star + 1);
      if (!spec.startsWith(head) || !spec.endsWith(rest)) continue;
      if (spec.length < head.length + rest.length) continue;
      tail = spec.slice(head.length, spec.length - rest.length);
    }
    for (const target of targets) out.push(target.includes('*') ? target.replace('*', tail) : target);
  }
  return out;
}

function viaAlias(patterns, spec) {
  for (const candidate of aliasTargets(patterns, spec)) {
    const hit = probe(isAbsolute(candidate) ? candidate : resolve(candidate));
    if (hit) return hit;
  }
  return null;
}

/**
 * Resolves the specifiers a pending edit introduces, cheapest authority first.
 *
 * Everything it cannot place lands in `unresolved` and is reported as a blind spot. It is never
 * treated as "resolves to nothing", because an absent edge makes a locked contract pass — the
 * fail-open this whole tool exists to make impossible.
 */
export function resolvePending({ root, relFile, specs, table = new Map(), patterns = null }) {
  const fromDir = dirname(relFile);
  const alias = patterns ?? aliasPatterns(root);
  const resolved = [];
  const unresolved = [];

  for (const spec of specs) {
    // cm:guard a core module is not an edge — the ts provider drops `coreModule` deps, so counting
    //   one here would put a node built-in in the graph the CI gate never sees.
    if (spec.startsWith('node:') || BUILTIN.has(spec)) continue;

    const fromTable = table.get(tableKey(fromDir, spec));
    if (fromTable) { resolved.push({ spec, to: fromTable, tier: 'graph' }); continue; }

    if (RELATIVE(spec)) {
      const hit = probe(resolve(root, fromDir, spec));
      const rel = hit && toRel(root, hit);
      if (rel) { resolved.push({ spec, to: rel, tier: 'relative' }); continue; }
      // cm:guard a relative specifier that hits nothing on disk is a genuine hole — the file may be
      //   about to be written by a later call — so it is reported, not silently discarded.
      unresolved.push(spec);
      continue;
    }

    const hit = viaAlias(alias, spec);
    const rel = hit && toRel(root, hit);
    if (rel) { resolved.push({ spec, to: rel, tier: 'alias' }); continue; }

    const pkgFile = viaNodeModules(root, fromDir, spec);
    const pkg = pkgFile && toRel(root, pkgFile);
    if (pkg) { resolved.push({ spec, to: pkg, tier: 'package' }); continue; }

    unresolved.push(spec);
  }

  return { resolved, unresolved };
}
