//! Provision step — seed Forge orientation for human `claude` sessions opened in
//! a Forge-managed consumer repo (pipeline jobs are oriented separately via the
//! per-stage system preamble; see core `prompt/system.ts`).
//!
//! Two artifacts, both NON-SECRET — so, unlike `.mcp.json` (which carries the
//! device token and is git-excluded), these are meant to be committed and shared
//! via git:
//!
//!   - `.forge/orientation.md` — Forge owns this file; it is fully overwritten on
//!     every provision. The content is DETERMINISTIC (projectId + slug + fixed
//!     pointers, nothing device-specific), so a re-provision rewrites identical
//!     bytes and leaves the git tree clean.
//!
//!   - `CLAUDE.md` — gets ONE fixed, marker-delimited block prepended IFF the
//!     marker is absent (idempotent). We never rewrite the rest of the file,
//!     never auto-commit, and never git-exclude it — a human commits the one-time
//!     diff. The block is a fixed `@import` pointer at the top, so the volatile
//!     details live in `.forge/orientation.md`, not in the project's CLAUDE.md.

use std::path::Path;

use crate::error::Result;

/// Marks the Forge-managed block in a consumer `CLAUDE.md`. Presence ⇒ already
/// oriented; we leave the file untouched.
const FORGE_BLOCK_MARKER: &str = "<!-- forge:orientation -->";

/// Full body of `.forge/orientation.md`. Deterministic for a given project so
/// re-provisioning produces byte-identical output (no git churn).
pub fn orientation_body(project_id: &str, slug: &str) -> String {
    format!(
        "# Forge orientation — {slug}\n\
\n\
<!-- Generated by Forge on device provision. Forge-owned; manual edits are overwritten. -->\n\
\n\
This repo is managed by **Forge** — the control plane for its issues, pipeline, and durable\n\
memory. The Forge MCP server is wired in `.mcp.json`; its instructions explain the tools.\n\
\n\
- **projectId:** `{project_id}`  ·  **slug:** `{slug}`\n\
- **Recall memory FIRST** — project memory is NOT auto-loaded. Before any task needing\n\
  project context: `forge_memory_search({{ projectId: '{project_id}', query: <topic>, topK: 5 }})`.\n\
  Treat hits as point-in-time — verify against live code/git before trusting.\n\
- Codebase & project knowledge: call `forge_knowledge` (list/get/search).\n\
- Issues / tasks / status / dependencies: `forge_issues`, `forge_comments`, `forge_pm_*`.\n\
- Before writing, rewriting, or tuning this project's pipeline skills, read the `forge-skills`\n\
  MCP prompt (the always-latest authoring guide).\n\
\n\
## Operating affordances\n\
Forge gives you a tool for things agents routinely do in prose. When you hit the trigger,\n\
reach for the tool — and avoid the red flag.\n\
\n\
| When you need | Use | Red flag (DON'T) |\n\
|---|---|---|\n\
| Ordering between issues | `forge_project_pm action=set_dependency kind:blocks` (`from` = the blocker) | Describing the dependency in prose instead of setting the edge — only a `blocks` edge gates dispatch |\n\
| To record a note / follow-up | create an issue at `draft` | Creating it at `open` — that auto-triages and spawns a pipeline run |\n\
| To change project config (`pipelineConfig.states`, `projectFacts`, …) | GET the current config first, then send a complete entry | Blind-patching a nested map you never read — you can clobber sibling keys |\n\
| Before you design / fix | `forge_memory_search` for prior conventions, gotchas, decisions | Skipping recall and rediscovering (or contradicting) settled work |\n\
| To park work that never started | leave it at `draft` | `on_hold` from `draft` — `on_hold` is a deliberate pause for ACTIVE work only |\n\
| To finish a fix made by hand, outside the pipeline | drive it through `status` and/or capture a `forge_memory` learning | Fixing it and forgetting — no status move, no learning recorded |\n\
\n\
**Forge red flags:** prose-deps · open-as-note · wholesale-config-clobber · skip-recall · on_hold-from-draft · fix-by-hand-and-forget.\n",
    )
}

/// The fixed block prepended to `CLAUDE.md`. Identical across every project (the
/// per-project details are imported from `.forge/orientation.md`), so it never
/// needs updating once present.
fn claude_md_block() -> String {
    format!(
        "{FORGE_BLOCK_MARKER}\n\
<!-- Forge-managed pointer (fixed). Project orientation lives in .forge/orientation.md. -->\n\
@.forge/orientation.md\n\
<!-- /forge:orientation -->\n",
    )
}

/// Write `.forge/orientation.md` (full overwrite) and ensure `CLAUDE.md` carries
/// the fixed forge block (prepended once, only when the marker is absent).
/// Best-effort by contract — the caller logs and continues on `Err`.
pub fn write_orientation(repo_path: &Path, project_id: &str, slug: &str) -> Result<()> {
    // 1. `.forge/orientation.md` — Forge owns it; overwrite fully.
    let forge_dir = repo_path.join(".forge");
    std::fs::create_dir_all(&forge_dir)?;
    std::fs::write(
        forge_dir.join("orientation.md"),
        orientation_body(project_id, slug),
    )?;

    // 2. `CLAUDE.md` — ensure the fixed block is present at the top. If the
    // marker already exists we leave the whole file untouched (idempotent and
    // never clobbers the project's own content).
    let claude_path = repo_path.join("CLAUDE.md");
    let existing = std::fs::read_to_string(&claude_path).unwrap_or_default();
    if existing.contains(FORGE_BLOCK_MARKER) {
        return Ok(());
    }
    let block = claude_md_block();
    let next = if existing.trim().is_empty() {
        block
    } else {
        format!("{block}\n{existing}")
    };
    std::fs::write(&claude_path, next)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn tmp_repo(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("forge-orient-{tag}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn writes_forge_dir_and_creates_claude_md_when_absent() {
        let repo = tmp_repo("fresh");
        write_orientation(&repo, "proj-123", "myslug").unwrap();

        let orient = std::fs::read_to_string(repo.join(".forge/orientation.md")).unwrap();
        assert!(orient.contains("proj-123"));
        assert!(orient.contains("myslug"));
        assert!(orient.contains("forge_memory_search"));
        // Operating-affordances table (trigger → tool → red-flag), not a noun-list.
        assert!(orient.contains("## Operating affordances"));
        assert!(orient.contains("set_dependency kind:blocks"));
        assert!(orient.contains("Forge red flags:"));

        let claude = std::fs::read_to_string(repo.join("CLAUDE.md")).unwrap();
        assert!(claude.starts_with(FORGE_BLOCK_MARKER));
        assert!(claude.contains("@.forge/orientation.md"));
        let _ = std::fs::remove_dir_all(&repo);
    }

    #[test]
    fn prepends_block_to_existing_claude_md_preserving_content() {
        let repo = tmp_repo("prepend");
        std::fs::write(
            repo.join("CLAUDE.md"),
            "# My Project\n\nProject rules here.\n",
        )
        .unwrap();
        write_orientation(&repo, "p", "s").unwrap();

        let claude = std::fs::read_to_string(repo.join("CLAUDE.md")).unwrap();
        assert!(claude.starts_with(FORGE_BLOCK_MARKER)); // block at top
        assert!(claude.contains("# My Project")); // original preserved
        assert!(claude.contains("Project rules here."));
        let _ = std::fs::remove_dir_all(&repo);
    }

    #[test]
    fn idempotent_when_marker_present() {
        let repo = tmp_repo("idem");
        write_orientation(&repo, "p", "s").unwrap();
        let after_first = std::fs::read_to_string(repo.join("CLAUDE.md")).unwrap();
        // a human appends content below the block
        std::fs::write(
            repo.join("CLAUDE.md"),
            format!("{after_first}\n## human notes\n"),
        )
        .unwrap();

        write_orientation(&repo, "p", "s").unwrap();
        let after_second = std::fs::read_to_string(repo.join("CLAUDE.md")).unwrap();
        // block not duplicated, human content survives
        assert_eq!(after_second.matches(FORGE_BLOCK_MARKER).count(), 1);
        assert!(after_second.contains("## human notes"));
        let _ = std::fs::remove_dir_all(&repo);
    }

    #[test]
    fn orientation_body_is_deterministic() {
        // Same inputs ⇒ byte-identical output (keeps the git tree clean on
        // re-provision).
        assert_eq!(orientation_body("p", "s"), orientation_body("p", "s"));
        let _ = tmp_repo("noop");
    }
}
