//! Provision step — seed Forge orientation for human `claude` sessions opened in
//! a Forge-managed consumer repo (pipeline jobs are oriented separately via the
//! per-stage system preamble; see core `prompt/system.ts`).
//!
//! Two artifacts, both NON-SECRET — so, unlike `.mcp.json` (which carries the
//! device token and is git-excluded), these are meant to be committed and shared
//! via git:
//!
//!   - `.forge/orientation.md` — Forge owns this file; it is fully overwritten on
//!     every provision. The content is deterministic in the project (projectId +
//!     slug + fixed pointers, nothing device-specific), so two boxes provisioning
//!     the same project write the same bytes.
//!
//!     It is NOT deterministic across versions of this crate, and the tree is
//!     only left clean when the committed copy already matches what
//!     `orientation_body` emits now. A hand edit to this file is lost at the next
//!     provision; the generator is the only place its content can be changed.
//!     On forge-dev the two had drifted apart on two table rows, so every
//!     provision dirtied `main` and silently reverted whichever row the generator
//!     lacked. Both rows are folded back here, and the test
//!     `this_repo_committed_orientation_matches_the_generator` is what keeps the
//!     paragraph above true rather than merely intended (ISS-1108).
//!
//!   - `CLAUDE.md` — gets ONE fixed, marker-delimited block prepended IFF the
//!     file does not already reach orientation. We never rewrite the rest of the
//!     file, never auto-commit, and never git-exclude it — a human commits the
//!     one-time diff. The block is a fixed `@import` pointer at the top, so the
//!     volatile details live in `.forge/orientation.md`, not in the project's
//!     CLAUDE.md.
//!
//!     "Already reaches orientation" is the import and not only our marker. A
//!     repo that wrote `@.forge/orientation.md` by hand and has no marker used to
//!     be given the block anyway, and the import is what the harness acts on — so
//!     the whole of orientation was then expanded into every prompt on that
//!     project twice, once per import. forge-dev's own CLAUDE.md carried the pair
//!     for as long as nobody counted them.

use std::path::Path;

use crate::error::Result;

/// Marks the Forge-managed block in a consumer `CLAUDE.md`. Presence ⇒ already
/// oriented; we leave the file untouched.
const FORGE_BLOCK_MARKER: &str = "<!-- forge:orientation -->";

/// The line that actually reaches the harness. A `CLAUDE.md` holding this is
/// already oriented, whether or not our marker is around it.
const FORGE_IMPORT: &str = "@.forge/orientation.md";

/// Full body of `.forge/orientation.md`. Deterministic for a given project so
/// re-provisioning produces byte-identical output (no git churn).
pub fn orientation_body(project_id: &str, slug: &str) -> String {
    format!(
        "# Forge orientation — {slug}\n\
\n\
<!-- Generated by Forge on device provision. Forge-owned; manual edits are overwritten. -->\n\
\n\
This repo is managed by **Forge** — the control plane for its issues, pipeline, and durable\n\
memory. The Forge MCP server is wired in `.mcp.json`; its instructions explain the tools.\n\
\n\
- **projectId:** `{project_id}`  ·  **slug:** `{slug}`\n\
- **Recall memory FIRST** — project memory is NOT auto-loaded. Before any task needing\n\
  project context: `forge_memory_search({{ projectId: '{project_id}', query: <topic>, topK: 5 }})`.\n\
  Treat hits as point-in-time — verify against live code/git before trusting.\n\
- Codebase & project knowledge: call `forge_knowledge` (list/get/search).\n\
- Issues / tasks / status / dependencies: `forge_issues`, `forge_comments`, `forge_pm_*`.\n\
- Before writing, rewriting, or tuning this project's pipeline skills, read the `forge-skills`\n\
  MCP prompt (the always-latest authoring guide).\n\
\n\
## Operating affordances\n\
Forge gives you a tool for things agents routinely do in prose. When you hit the trigger,\n\
reach for the tool — and avoid the red flag.\n\
\n\
An issue is a unit of WORK with a named deliverable and an owner, whose completion someone\n\
other than the author can verify. A note, a question, an audit finding and a record of\n\
something already done are NOT issues — the four admission gates and where each of those goes\n\
instead: guide `what-is-an-issue`.\n\
\n\
| When you need | Use | Red flag (DON'T) |\n\
|---|---|---|\n\
| Ordering between issues | Blocker known **at create time** → `forge_issues.create {{ data.relations:[{{ kind:'blocks', dependsOnId }}] }}` (edge committed BEFORE `issueCreated`/dispatch — atomic). Both issues already exist → `forge_issues.update {{ data.relations:[{{ kind:'blocks', dependsOnId }}] }}` (works with any credential; retract by re-sending with `validUntil` in the past), or `forge_project_pm action=set_dependency kind:blocks` (`from` = the blocker; needs a paired device). Verify with `forge_issues.get` → `relations`. | Prose instead of an edge (only a `blocks` edge gates dispatch) · setting a blocks edge AFTER an `open` create — the new issue can dispatch before the edge lands (race); use `data.relations` or create at `draft` first |\n\
| To record a note, learning, or decision | `forge_memory_write` (durable business logic → repo `docs/`) | Filing it as an issue — `draft` or not, nobody browses the issue list for notes |\n\
| To queue work that must actually happen LATER | create an issue at `draft` | Creating it at `open` — that auto-triages and spawns a pipeline run |\n\
| To report an issue | fill `title`, `description`, `priority`, `category` | Pre-filling `plan`/`acceptanceCriteria` — on a staged project those are written by the clarify/plan steps, on an autonomous one by the driver's own phases |\n\
| To change project config (`pipelineConfig.states`, …) | GET it first, then send `{{ base, patch }}` — `patch` naming ONLY the keys you changed (`null` deletes one), `base` the values you read them against | Sending a complete entry — the document is no longer replaced wholesale, and a resent key whose value moved is refused by name rather than silently winning (ISS-1170) |\n\
| To write or change the project's own prose (build commands, a rule, a guide) | `forge_knowledge` write, one entry per slug, `injection` deciding whether it reaches every prompt or is fetched on demand | Sending it to `forge_config` as `projectFacts` — retired in ISS-1048, and the call is refused by name |\n\
| Before you design / fix | `forge_memory_search` for prior conventions, gotchas, decisions | Skipping recall and rediscovering (or contradicting) settled work |\n\
| To park work that never started | leave it at `draft` | `on_hold` from `draft` — `on_hold` is a deliberate pause for ACTIVE work only |\n\
| To finish a fix made by hand, outside the pipeline | claim it shipped FIRST — `forge_issues action=mark` (or Mark merged on the issue's Properties rail), naming where it landed — then drive it through `status` and capture a `forge_memory` learning | Fixing it and forgetting — no status move, no learning recorded · reaching for `closed` without the mark: `closed` means the work shipped, and a close with no `merged_at` is refused by name |\n\
| An issue you are working turns out NOT to be work (a note, a question, a duplicate, already done) | Act on it yourself — comment saying which gate it fails and where the content went, THEN `needs_info` if a human owes you requirements, or `dropped` if it is not work at all | Leaving it filed for someone else to find · reaching for `closed` — that says the work shipped, and a close with no `merged_at` is refused by name (`CLOSE_REQUIRES_SHIPPED`) · moving status with no comment, so the next reader cannot tell why |\n\
| A bug, gap or defect you find WHILE working an issue | **Fix it now, in this issue**, and DECLARE it in your comment under `Extra fixes:` — extra work is REPORTED, never filed | Filing it instead of fixing it. A new `draft` is not a hand-off: nobody owns it, nothing ages it, and a two-minute fix becomes backlog nobody reads |\n\
| A residual genuinely out of reach (needs a human decision, or work no diff here can carry) | ONE of: a `blocks` edge onto the issue that would ship without it · a line in `docs/proposals/` · `waiting` + `reason` when it blocks THIS issue | Filing a new issue to carry it — that is not one of the options. Equally: staying silent because none of the three fit — say it in a comment on the issue you are on |\n\
\n\
**Forge red flags:** prose-deps · open-then-block · open-as-note · draft-as-note · plan-by-hand · wholesale-config-clobber · skip-recall · on_hold-from-draft · fix-by-hand-and-forget · close-as-drop · silent-nonwork · file-instead-of-fix.\n",
    )
}

/// The fixed block prepended to `CLAUDE.md`. Identical across every project (the
/// per-project details are imported from `.forge/orientation.md`), so it never
/// needs updating once present.
fn claude_md_block() -> String {
    format!(
        "{FORGE_BLOCK_MARKER}\n\
<!-- Forge-managed pointer (fixed). Project orientation lives in .forge/orientation.md. -->\n\
@.forge/orientation.md\n\
<!-- /forge:orientation -->\n",
    )
}

/// Write `.forge/orientation.md` (full overwrite) and ensure `CLAUDE.md` carries
/// the fixed forge block (prepended once, only when the marker is absent).
/// Best-effort by contract — the caller logs and continues on `Err`.
pub fn write_orientation(repo_path: &Path, project_id: &str, slug: &str) -> Result<()> {
    // 1. `.forge/orientation.md` — Forge owns it; overwrite fully.
    let forge_dir = repo_path.join(".forge");
    std::fs::create_dir_all(&forge_dir)?;
    std::fs::write(
        forge_dir.join("orientation.md"),
        orientation_body(project_id, slug),
    )?;

    // 2. `CLAUDE.md` — ensure the fixed block is present at the top. If the
    // marker already exists we leave the whole file untouched (idempotent and
    // never clobbers the project's own content).
    let claude_path = repo_path.join("CLAUDE.md");
    let existing = std::fs::read_to_string(&claude_path).unwrap_or_default();
    if existing.contains(FORGE_BLOCK_MARKER) {
        return Ok(());
    }
    if existing.contains(FORGE_IMPORT) {
        tracing::info!(
            "[provision] {} already imports .forge/orientation.md without Forge's marker around it — leaving the file alone. Prepending the block would give it a second import, and every prompt on this project would then carry the whole of orientation twice.",
            claude_path.display()
        );
        return Ok(());
    }
    let block = claude_md_block();
    let next = if existing.trim().is_empty() {
        block
    } else {
        format!("{block}\n{existing}")
    };
    std::fs::write(&claude_path, next)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    /// This repository IS the `forge-dev` project, and `.forge/orientation.md`
    /// at its root is a committed artifact of the generator below. Nothing else
    /// compares the two: a provision overwrites the file in silence, so an edit
    /// made to one side alone is reverted on the next daemon run and reads in
    /// git as noise somebody else introduced.
    const FORGE_DEV_PROJECT_ID: &str = "da368b0a-8e21-4763-9d90-8f7b9d0c7115";
    const FORGE_DEV_SLUG: &str = "forge-dev";

    fn repo_root() -> PathBuf {
        // crates/forge-runner-core -> crates -> packages/runner -> packages -> root
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../../..")
    }

    /// Why the committed file and the generator disagree, or `None` where they do not.
    ///
    /// The line-wise scan alone is blind to the difference that actually happens. `str::lines`
    /// strips a trailing `\r`, so a checkout that landed the file as CRLF agrees on every line
    /// and disagrees on every byte — and the old message called that "a length difference",
    /// which sends the reader hunting for content that is not there. It cost a Windows-only CI
    /// red whose cause was invisible in its own panic. Each arm below names its own cause.
    fn describe_orientation_drift(committed: &str, generated: &str) -> Option<String> {
        if committed == generated {
            return None;
        }

        if let Some((n, (a, b))) = committed
            .lines()
            .zip(generated.lines())
            .enumerate()
            .find(|(_, (a, b))| a != b)
        {
            return Some(format!(
                "line {}:\n  committed: {a}\n  generated: {b}",
                n + 1
            ));
        }

        // The two invisible causes come before the line count, because both of them ALSO move the
        // count — a trailing `\n` adds an empty line — and a report naming a blank line is the
        // unhelpful answer this function exists to stop giving.
        if committed.replace("\r\n", "\n") == generated {
            return Some(
                "every line agrees and every byte does not: the committed file holds CRLF line \
                 endings and `orientation_body` emits LF. That is a checkout, not an edit — git \
                 converts on checkout where `core.autocrlf` is set, which the GitHub Windows \
                 runner sets. `.gitattributes` pins this file to `eol=lf` so the checkout holds \
                 what the provision writes back; if you are seeing this, that pin is missing or \
                 the file was written by hand with CRLF."
                    .to_string(),
            );
        }

        // Shown rather than guessed at: `{:?}` renders a lone `\n` visibly, which is the whole
        // point — the cause here is bytes a reader cannot see in their editor.
        if let Some(tail) = committed.strip_prefix(generated) {
            return Some(format!(
                "one is a prefix of the other, so the difference is trailing bytes: the committed \
                 file is {} byte(s) against the generator's {}. What only the committed file has, \
                 at the end, is {tail:?}",
                committed.len(),
                generated.len(),
            ));
        }
        if let Some(tail) = generated.strip_prefix(committed) {
            return Some(format!(
                "one is a prefix of the other, so the difference is trailing bytes: the committed \
                 file is {} byte(s) against the generator's {}. What only the generator has, at \
                 the end, is {tail:?}",
                committed.len(),
                generated.len(),
            ));
        }

        let (committed_lines, generated_lines) =
            (committed.lines().count(), generated.lines().count());
        if committed_lines != generated_lines {
            let (longer, shorter, extra) = if committed_lines > generated_lines {
                (
                    "the committed file",
                    "the generator",
                    committed.lines().nth(generated_lines).unwrap_or(""),
                )
            } else {
                (
                    "the generator",
                    "the committed file",
                    generated.lines().nth(committed_lines).unwrap_or(""),
                )
            };
            return Some(format!(
                "every shared line agrees, but {longer} has {} line(s) and {shorter} has {}. \
                 The first line only {longer} has:\n  {extra}",
                committed_lines.max(generated_lines),
                committed_lines.min(generated_lines),
            ));
        }

        let at = committed
            .as_bytes()
            .iter()
            .zip(generated.as_bytes())
            .position(|(a, b)| a != b)
            .unwrap_or(0);
        Some(format!(
            "every line agrees and the bytes do not. First difference at byte {at}: the committed \
             file has {:?} and the generator has {:?}. A difference no line can show is a \
             line-ending or whitespace difference.",
            committed.as_bytes()[at] as char,
            generated.as_bytes()[at] as char,
        ))
    }

    #[test]
    fn this_repo_committed_orientation_matches_the_generator() {
        let path = repo_root().join(".forge/orientation.md");
        let committed = std::fs::read_to_string(&path).unwrap_or_else(|err| {
            panic!("cannot read {}: {err}", path.display());
        });
        let generated = orientation_body(FORGE_DEV_PROJECT_ID, FORGE_DEV_SLUG);

        if let Some(cause) = describe_orientation_drift(&committed, &generated) {
            panic!(
                "`.forge/orientation.md` has drifted from `orientation_body`, so the next \
                 provision of this repo will overwrite the committed file and dirty the tree. \
                 Edit the generator, then regenerate the file — never the file alone.\n{cause}"
            );
        }
    }

    #[test]
    fn drift_reports_nothing_when_the_two_agree() {
        let body = orientation_body(FORGE_DEV_PROJECT_ID, FORGE_DEV_SLUG);
        assert_eq!(describe_orientation_drift(&body, &body), None);
    }

    #[test]
    fn drift_names_line_endings_rather_than_a_length_difference() {
        // Exactly what a Windows checkout with `core.autocrlf=true` hands the test, and what CI
        // reported as "the two differ in length only" before this arm existed.
        let generated = orientation_body(FORGE_DEV_PROJECT_ID, FORGE_DEV_SLUG);
        let as_checked_out_on_windows = generated.replace('\n', "\r\n");

        let cause = describe_orientation_drift(&as_checked_out_on_windows, &generated)
            .expect("CRLF against LF is a drift");

        assert!(cause.contains("CRLF"), "{cause}");
        assert!(cause.contains("eol=lf"), "{cause}");
        assert!(!cause.contains("length only"), "{cause}");
    }

    #[test]
    fn drift_names_a_trailing_newline_rather_than_a_length_difference() {
        let generated = orientation_body(FORGE_DEV_PROJECT_ID, FORGE_DEV_SLUG);
        let with_an_extra_newline = format!("{generated}\n");

        let cause = describe_orientation_drift(&with_an_extra_newline, &generated)
            .expect("a trailing newline is a drift");

        assert!(cause.contains("trailing bytes"), "{cause}");
        // Rendered, not described: the reader sees the byte rather than a word for it.
        assert!(cause.contains("\\n"), "{cause}");
        assert!(!cause.contains("length only"), "{cause}");
    }

    #[test]
    fn drift_still_names_the_line_where_one_really_differs() {
        let generated = orientation_body(FORGE_DEV_PROJECT_ID, FORGE_DEV_SLUG);
        let edited = generated.replace("## Operating affordances", "## Operating affordanceS");

        let cause =
            describe_orientation_drift(&edited, &generated).expect("an edited line is a drift");

        assert!(cause.starts_with("line "), "{cause}");
        assert!(cause.contains("affordanceS"), "{cause}");
    }

    #[test]
    fn drift_names_the_line_only_one_side_has() {
        let generated = orientation_body(FORGE_DEV_PROJECT_ID, FORGE_DEV_SLUG);
        let with_a_row = format!("{generated}| a row the generator does not emit |\n");

        let cause =
            describe_orientation_drift(&with_a_row, &generated).expect("an extra line is a drift");

        assert!(
            cause.contains("a row the generator does not emit"),
            "{cause}"
        );
    }

    fn tmp_repo(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("forge-orient-{tag}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn writes_forge_dir_and_creates_claude_md_when_absent() {
        let repo = tmp_repo("fresh");
        write_orientation(&repo, "proj-123", "myslug").unwrap();

        let orient = std::fs::read_to_string(repo.join(".forge/orientation.md")).unwrap();
        assert!(orient.contains("proj-123"));
        assert!(orient.contains("myslug"));
        assert!(orient.contains("forge_memory_search"));
        // Operating-affordances table (trigger → tool → red-flag), not a noun-list.
        assert!(orient.contains("## Operating affordances"));
        assert!(orient.contains("set_dependency kind:blocks"));
        assert!(orient.contains("Forge red flags:"));

        let claude = std::fs::read_to_string(repo.join("CLAUDE.md")).unwrap();
        assert!(claude.starts_with(FORGE_BLOCK_MARKER));
        assert!(claude.contains("@.forge/orientation.md"));
        let _ = std::fs::remove_dir_all(&repo);
    }

    #[test]
    fn a_claude_md_that_already_imports_orientation_by_hand_is_not_given_a_second_one() {
        let repo = tmp_repo("hand-import");
        std::fs::write(
            repo.join("CLAUDE.md"),
            "# Their project\n\n@.forge/orientation.md\n\nTheir own rules.\n",
        )
        .unwrap();

        write_orientation(&repo, "proj-123", "myslug").unwrap();

        let claude = std::fs::read_to_string(repo.join("CLAUDE.md")).unwrap();
        assert_eq!(
            claude.matches(FORGE_IMPORT).count(),
            1,
            "the import is what the harness expands, so a second one expands the whole of orientation into every prompt twice: {claude}"
        );
        assert!(
            claude.contains("Their own rules."),
            "and nothing of theirs is touched either way: {claude}"
        );
        let _ = std::fs::remove_dir_all(&repo);
    }

    #[test]
    fn prepends_block_to_existing_claude_md_preserving_content() {
        let repo = tmp_repo("prepend");
        std::fs::write(
            repo.join("CLAUDE.md"),
            "# My Project\n\nProject rules here.\n",
        )
        .unwrap();
        write_orientation(&repo, "p", "s").unwrap();

        let claude = std::fs::read_to_string(repo.join("CLAUDE.md")).unwrap();
        assert!(claude.starts_with(FORGE_BLOCK_MARKER)); // block at top
        assert!(claude.contains("# My Project")); // original preserved
        assert!(claude.contains("Project rules here."));
        let _ = std::fs::remove_dir_all(&repo);
    }

    #[test]
    fn idempotent_when_marker_present() {
        let repo = tmp_repo("idem");
        write_orientation(&repo, "p", "s").unwrap();
        let after_first = std::fs::read_to_string(repo.join("CLAUDE.md")).unwrap();
        // a human appends content below the block
        std::fs::write(
            repo.join("CLAUDE.md"),
            format!("{after_first}\n## human notes\n"),
        )
        .unwrap();

        write_orientation(&repo, "p", "s").unwrap();
        let after_second = std::fs::read_to_string(repo.join("CLAUDE.md")).unwrap();
        // block not duplicated, human content survives
        assert_eq!(after_second.matches(FORGE_BLOCK_MARKER).count(), 1);
        assert!(after_second.contains("## human notes"));
        let _ = std::fs::remove_dir_all(&repo);
    }

    #[test]
    fn orientation_body_is_deterministic() {
        // Same inputs ⇒ byte-identical output (keeps the git tree clean on
        // re-provision).
        assert_eq!(orientation_body("p", "s"), orientation_body("p", "s"));
        let _ = tmp_repo("noop");
    }
}
