// @generated by archmap 0.1.3 — vendored copy, do not edit
import { existsSync, readFileSync, realpathSync, statSync } from 'node:fs';
import { createRequire } from 'node:module';
import { basename, dirname, isAbsolute, join, resolve } from 'node:path';

// cm:why this module does NOT resolve modules — principle §2.4 is intact, tsc still does every
//   resolution. It only locates WHERE `compilerOptions.paths` is written. In the TS project-
//   references layout (the default of `npm create vite` on TS 5+) the root config is
//   `{ files: [], references: [...] }` and `paths` lives in a referenced child, so handing tsc the
//   root config alone yields zero alias edges and no error: contracts then pass because the edges
//   are ABSENT, not because the code obeys them. Measured on a dogfood repo as 111 unresolvable.
// cm:why hand-rolled instead of `typescript`'s own ts.readConfigFile: typescript is not a declared
//   peer of archmap, so using it needs a resolve-or-fallback branch — two code paths for four
//   fields. One always-exercised path is worth more here than reusing a loader we cannot rely on.
// cm:edge contract -> src/providers/ts.mjs — planTsConfig's three modes are that provider's contract
const MAX_DEPTH = 8;
const ROOT_CONFIGS = ['tsconfig.json', 'jsconfig.json'];

function isFile(path) {
  try {
    return statSync(path).isFile();
  } catch {
    return false;
  }
}

function isDir(path) {
  try {
    return statSync(path).isDirectory();
  } catch {
    return false;
  }
}

/**
 * JSON with comments and trailing commas, which is what a real tsconfig is — vite's generated
 * `tsconfig.app.json` carries both and `JSON.parse` throws on it. Without tolerance here the fix
 * silently does nothing on the exact layout it targets. Returns null rather than throwing: an
 * unreadable config must degrade to today's behaviour, never break the run.
 */
export function readJsonc(text) {
  if (typeof text !== 'string') return null;

  // cm:why chunked rather than one regex pass: a `//` or a `,}` INSIDE a string literal is data, and
  //   a global regex cannot tell the two apart. String literals are copied through untouched and the
  //   trailing-comma cut is applied only to the code between them.
  const out = [];
  let buf = '';
  const flush = () => {
    out.push(buf.replace(/,(\s*[}\]])/g, '$1'));
    buf = '';
  };

  for (let i = 0; i < text.length;) {
    const c = text[i];
    if (c === '"') {
      flush();
      let lit = '"';
      i++;
      while (i < text.length) {
        const ch = text[i];
        if (ch === '\\') { lit += text.slice(i, i + 2); i += 2; continue; }
        lit += ch;
        i++;
        if (ch === '"') break;
      }
      out.push(lit);
      continue;
    }
    if (c === '/' && text[i + 1] === '/') {
      while (i < text.length && text[i] !== '\n') i++;
      continue;
    }
    if (c === '/' && text[i + 1] === '*') {
      i += 2;
      while (i < text.length && !(text[i] === '*' && text[i + 1] === '/')) i++;
      i += 2;
      continue;
    }
    buf += c;
    i++;
  }
  flush();

  try {
    return JSON.parse(out.join(''));
  } catch {
    return null;
  }
}

/** A tsconfig as an object, or null when it is missing or unparseable. Never throws. */
export function readConfig(path) {
  try {
    if (!isFile(path)) return null;
    return readJsonc(readFileSync(path, 'utf8'));
  } catch {
    return null;
  }
}

/**
 * A `references[].path`, which may name a file or a directory, resolved against the DECLARING
 * config's directory. Returns null when it does not exist on disk.
 */
export function resolveRef(fromConfigPath, refPath) {
  if (typeof refPath !== 'string' || !refPath) return null;
  const abs = isAbsolute(refPath) ? refPath : resolve(dirname(fromConfigPath), refPath);
  if (isDir(abs)) {
    const inDir = join(abs, 'tsconfig.json');
    return isFile(inDir) ? inDir : null;
  }
  if (isFile(abs)) return abs;
  return isFile(`${abs}.json`) ? `${abs}.json` : null;
}

function resolveExtends(configPath, spec) {
  if (typeof spec !== 'string' || !spec) return null;
  if (spec.startsWith('.') || isAbsolute(spec)) {
    const abs = isAbsolute(spec) ? spec : resolve(dirname(configPath), spec);
    for (const candidate of [abs, `${abs}.json`, join(abs, 'tsconfig.json')]) {
      if (isFile(candidate)) return candidate;
    }
    return null;
  }
  // cm:guard a package spec (`@tsconfig/node20/tsconfig.json`) is best-effort only: it needs the
  //   TARGET repo's resolution, and a config living in a dependency we cannot resolve must be
  //   skipped, not thrown. Union-of-targets means a miss costs a candidate, never a wrong answer.
  for (const attempt of [spec, join(spec, 'tsconfig.json')]) {
    try {
      return createRequire(configPath).resolve(attempt);
    } catch { /* not resolvable from here */ }
  }
  return null;
}

function extendsOf(config) {
  const e = config.extends;
  if (typeof e === 'string') return [e];
  return Array.isArray(e) ? e.filter((s) => typeof s === 'string') : [];
}

/** Appends `source`'s targets after `target`'s, per pattern, deduped. Order is precedence. */
function mergeInto(target, source) {
  for (const [pattern, targets] of source) {
    const list = target.get(pattern) ?? [];
    for (const t of targets) if (!list.includes(t)) list.push(t);
    target.set(pattern, list);
  }
}

function keyOf(path) {
  try {
    return realpathSync(path);
  } catch {
    return path;
  }
}

/**
 * One config plus its `extends` chain, folded into absolute `paths` targets and absolute
 * include globs. `references` are NOT followed here — planTsConfig walks those, so that a child's
 * own extends chain is collected the same way the root's is.
 *
 * The config's OWN targets come first and inherited ones after: tsc tries a pattern's targets in
 * array order and falls through when one does not exist on disk, so ordering is precedence and a
 * wrong guess costs an extra candidate rather than the right answer.
 */
export function collectFrom(configPath, seen = new Set(), depth = 0) {
  const empty = { patterns: new Map(), includes: [], baseUrl: null };
  if (depth > MAX_DEPTH) return empty;
  const key = keyOf(configPath);
  if (seen.has(key)) return empty;
  seen.add(key);

  const config = readConfig(configPath);
  if (!config || typeof config !== 'object') return empty;

  const dir = dirname(configPath);
  const co = (config.compilerOptions && typeof config.compilerOptions === 'object')
    ? config.compilerOptions
    : {};
  // cm:why `paths` targets are absolutised against THEIR OWN declaring config's baseUrl. That is
  //   what makes children with different baseUrl values mergeable at all — one synthesized baseUrl
  //   cannot serve two children that disagree about it.
  const ownBaseUrl = typeof co.baseUrl === 'string' ? resolve(dir, co.baseUrl) : null;
  const base = ownBaseUrl ?? dir;

  const patterns = new Map();
  if (co.paths && typeof co.paths === 'object') {
    for (const [pattern, targets] of Object.entries(co.paths)) {
      if (!Array.isArray(targets)) continue;
      patterns.set(pattern, targets
        .filter((t) => typeof t === 'string')
        .map((t) => (isAbsolute(t) ? t : resolve(base, t))));
    }
  }

  const includes = [];
  for (const field of ['include', 'files']) {
    const entries = config[field];
    if (!Array.isArray(entries)) continue;
    for (const entry of entries) {
      if (typeof entry !== 'string' || !entry) continue;
      includes.push(isAbsolute(entry) ? entry : resolve(dir, entry));
    }
  }

  let inheritedBaseUrl = null;
  for (const spec of extendsOf(config)) {
    const basePath = resolveExtends(configPath, spec);
    if (!basePath) continue;
    const inherited = collectFrom(basePath, seen, depth + 1);
    mergeInto(patterns, inherited.patterns);
    includes.push(...inherited.includes);
    inheritedBaseUrl ??= inherited.baseUrl;
  }

  return { patterns, includes, baseUrl: ownBaseUrl ?? inheritedBaseUrl };
}

function walkRefs(configPath, out, seenConfigs, seenRefs, depth = 0) {
  if (depth > MAX_DEPTH) return;
  const key = keyOf(configPath);
  if (seenRefs.has(key)) return;
  seenRefs.add(key);

  const config = readConfig(configPath);
  const refs = Array.isArray(config?.references) ? config.references : [];
  for (const ref of refs) {
    const child = resolveRef(configPath, ref?.path);
    if (!child) continue;
    const collected = collectFrom(child, seenConfigs, 0);
    mergeInto(out.patterns, collected.patterns);
    out.includes.push(...collected.includes);
    out.from.push(child);
    walkRefs(child, out, seenConfigs, seenRefs, depth + 1);
  }
}

function addsNothing(merged, own) {
  for (const [pattern, targets] of merged) {
    const mine = own.get(pattern);
    if (!mine) return false;
    if (targets.some((t) => !mine.includes(t))) return false;
  }
  return true;
}

/**
 * What to hand dependency-cruiser as `--ts-config`:
 *
 * - `{ mode: 'none' }`   no root config — the caller must behave exactly as it did before.
 * - `{ mode: 'root' }`   pass `path` verbatim. Chosen whenever the root declares no `references`,
 *                        or the merge adds nothing the root did not already declare, so the common
 *                        layout keeps today's byte-identical invocation.
 * - `{ mode: 'merged' }` write `config` somewhere outside the scanned repo and pass that path.
 */
// cm:guard a monorepo may have NO config at `root` at all — aliases live in each package and the
//   workspace root carries none, so discovery there returns `none` and every aliased import lands in
//   `unresolvable`, which is DROPPED rather than reported: contracts over that package then pass on
//   an empty graph. Measured on a pnpm workspace, 1000 unresolvable of 5368 possible edges (18.6%)
//   with discovery alone versus 171 against a map the manifest named. `declared` is that escape
//   hatch, and a declared path that is not a file is `mode: 'missing'` — an unrunnable gate, never a
//   quiet fall-through to discovery, because falling through is what made this invisible.
export function planTsConfig(root, declared = null) {
  const rootPath = declared
    ? (isFile(resolve(root, declared)) ? resolve(root, declared) : null)
    : ROOT_CONFIGS.map((f) => join(root, f)).find((p) => isFile(p));
  if (!rootPath) return declared ? { mode: 'missing', declared } : { mode: 'none' };

  const config = readConfig(rootPath);
  const refs = Array.isArray(config?.references) ? config.references : [];
  if (refs.length === 0) return { mode: 'root', path: rootPath };

  const seenConfigs = new Set();
  const own = collectFrom(rootPath, seenConfigs, 0);
  const out = { patterns: new Map(), includes: [...own.includes], from: [rootPath] };
  mergeInto(out.patterns, own.patterns);
  walkRefs(rootPath, out, seenConfigs, new Set());

  if (addsNothing(out.patterns, own.patterns)) return { mode: 'root', path: rootPath };

  const paths = {};
  for (const [pattern, targets] of out.patterns) paths[pattern] = targets;

  // cm:why `extends` the root config rather than restating it: that is what carries jsx, allowJs,
  //   moduleResolution and the rest, so merging aliases cannot silently change how anything else
  //   resolves. baseUrl is emitted ONLY when the root chain declares one — inventing a baseUrl
  //   would make bare `src/x` specifiers resolve that tsc itself would reject, and an invented edge
  //   fails a contract on nothing. Targets are absolute, so paths needs no baseUrl of its own.
  // cm:guard the absolute `exclude` is load-bearing: the default excludes resolve relative to the
  //   CONFIG's directory (a temp dir), so without it tsc enumerates the scanned repo's node_modules.
  const compilerOptions = { paths };
  if (own.baseUrl) compilerOptions.baseUrl = own.baseUrl;

  const includes = [...new Set(out.includes)];
  return {
    mode: 'merged',
    path: rootPath,
    from: out.from,
    names: out.from.map((p) => basename(p)),
    config: {
      extends: rootPath,
      compilerOptions,
      // cm:guard a config whose include/files matches no input is TS18003 (or TS18002 for a bare
      //   `files: []`), which produces empty stdout and no graph at all. `--ts-config` drives
      //   compilerOptions only and never scope, so this include exists purely to keep tsc quiet.
      include: includes.length ? includes : [join(root, '**', '*')],
      exclude: [join(root, 'node_modules', '**')],
    },
  };
}
