// The codes a conversation write is refused under, at REST and MCP alike (the refusal envelope).

export const CONVERSATION_REFUSAL_CODES = [
	"CONVERSATION_REFUSED",
	"CONVERSATION_UNADDRESSED",
	"CONVERSATION_PROJECT_CONFLICT",
	"CONVERSATION_ADAPTER_CONFLICT",
	"CONVERSATION_SHAPE_CONFLICT",
	"CONVERSATION_SCOPE_AMBIGUOUS",
	"CONVERSATION_SCOPE_FIXED",
	"CONVERSATION_NOT_WEB",
	"CONVERSATION_MODE_SETTLED",
	"CONVERSATION_BA_ASSISTANT_ONLY",
	"CONVERSATION_AGENT_NO_DEVICE",
	"CONVERSATION_ATTACHMENT_FOREIGN",
	"CONVERSATION_TURN_HANDED_OFF",
	"CONVERSATION_TURN_ON_ANOTHER_CORE",
	"CONVERSATION_NOTHING_RUNNING",
	"CONVERSATION_LAST_HANDLE",
	"CONVERSATION_LAST_PERSON",
	"HANDLE_NOT_FOUND",
	"HANDLE_NOT_AN_AGENT",
	"HANDLE_HAS_NO_NAME",
	"HANDLE_NOT_ON_PROJECT",
	"PARTICIPANT_UNIDENTIFIED",
	"ECOSYSTEM_NOT_MEMBER",
	"INVALID_NAME",
	"EMPTY_FILE",
	"FILE_TOO_LARGE",
	"MIME_NOT_ALLOWED",
] as const;

export type ConversationRefusalCode = (typeof CONVERSATION_REFUSAL_CODES)[number];
