// One declaration of the ecosystem module's refusal codes: core throws them, both doors answer them
// in the refusal envelope, and the web reads them by name.

import { PERMISSION_REFUSAL_CODES } from "./permissions.js";
import type { RefusalStatuses } from "./refusal.js";

export const LINK_REFUSAL_CODES = [
	"LINK_STATE_UNKNOWN",
	"LINK_GUIDE_WITHOUT_CALL_SITE",
	"LINK_DUPLICATE",
	"LINK_CONSUMER_NOT_MEMBER",
	"LINK_PROVIDER_NOT_MEMBER",
	"LINK_ECOSYSTEM_MISSING",
	"LINK_IDENTITY_IMMUTABLE",
	"PATH_OUTSIDE_REPO",
	"CALL_SITE_KIND_MISMATCH",
	"ARTEFACT_KIND_UNKNOWN",
	"BUILDER_RUN_NOT_MEMBER",
	"BUILDER_RUN_LINK_UNKNOWN",
	"BUILDER_RUN_IMMUTABLE",
	"BUILDER_RUN_ALREADY_OPEN",
	"BUILDER_RUN_HEAD_UNREADABLE",
	"BUILDER_RUN_NOT_OPEN",
	"BUILDER_RUN_SUPERSEDED",
	"BUILDER_RUN_SUPERSEDE_WITHOUT_REASON",
	"BUILDER_TRIGGER_UNKNOWN",
	"STEP_STATUS_UNKNOWN",
	"FINDING_CLASSIFICATION_UNKNOWN",
] as const;
export type LinkRefusalCode = (typeof LINK_REFUSAL_CODES)[number];

export const CHANNEL_REFUSAL_CODES = [
	"DOCUMENT_TYPE_UNKNOWN",
	"DOCUMENT_TYPE_IMMUTABLE",
	"DOCUMENT_STATE_NOT_ALLOWED",
	"MEMBERSHIP_NOT_ACTIVE",
	"RECIPIENT_NOT_COUNTERPARTY",
	"RECIPIENTS_NOT_DERIVED",
	"NUMBER_NOT_IN_CHANNEL",
	"NUMBER_TYPE_MISMATCH",
	"PUBLISHED_WITHOUT_GATE",
	"GATE_MODE_MISMATCH",
	"GATE_RETURN_WITHOUT_NOTE",
	"REPLY_WITHOUT_PARENT",
	"REPLY_TO_ENDED",
	"REPLY_TYPE_NOT_ALLOWED",
	"REPLY_FROM_NON_RECIPIENT",
	"DISPOSITION_NOT_FOR_TYPE",
	"ADAPT_AFTER_SUNSET",
	"CONTRACT_NOT_SENDERS",
	"CLASSIFICATION_BELOW_MEASURED",
	"MEASURED_CHANGE_OMITTED",
	"EFFECTIVE_BEFORE_DUE",
	"SUNSET_BEFORE_NOTICE_PERIOD",
	"DEADLINE_BEFORE_REACHABLE",
	"DUE_BY_TOO_SOON",
	"CONTENT_CODE",
	"CONTENT_INTERNAL_REF",
	"CONTENT_SECRET",
	"CONTENT_PRESCRIBES_IMPLEMENTATION",
	"THREAD_HELD",
	"THREAD_ALREADY_HELD",
	"THREAD_NOT_HELD",
	"HOLD_NOT_AUTHORISED",
	"HOLD_WITHOUT_REASON",
	"WITHDRAW_WITHOUT_REASON",
	"SUPERSEDE_WITHOUT_REASON",
	"SUPERSEDE_NOT_A_REPLACEMENT",
	"CHANNEL_NO_ROLE",
	"CHANNEL_WRITE_NOT_AUTHORISED",
	"CHANNEL_NOT_A_PARTY",
	"CHANNEL_TURN_UNBOUND",
	"CHANNEL_ARGUMENT_INVALID",
	"CHANNEL_ECOSYSTEM_AMBIGUOUS",
	"CHANNEL_PROJECT_UNNAMED",
	"CHANNEL_PROJECT_OUTSIDE_TOKEN",
] as const;
export type ChannelRefusalCode = (typeof CHANNEL_REFUSAL_CODES)[number];

/** What `forge_ecosystem` refuses before a service is asked; everything after is the service's own code. */
export const ECOSYSTEM_TOOL_REFUSAL_CODES = [
	"ECOSYSTEM_ARGUMENT_INVALID",
	"ECOSYSTEM_TURN_UNBOUND",
	"ECOSYSTEM_PROJECT_UNNAMED",
	"ECOSYSTEM_PROJECT_OUTSIDE_TOKEN",
	"ECOSYSTEM_WRITE_NOT_AUTHORISED",
	"ECOSYSTEM_NOT_AUTHORISED",
	"ECOSYSTEM_RECORD_NOT_FOUND",
] as const;
export type EcosystemToolRefusalCode =
	(typeof ECOSYSTEM_TOOL_REFUSAL_CODES)[number];

export const CONTRACT_REFUSAL_CODES = [
	"CONTRACT_NOT_PUBLISHED",
	"ARTIFACT_MEASURED_FROM_GIT",
	"NOTHING_TO_RECORD",
	"SEMANTIC_WITH_ARTIFACT",
	"SEMANTIC_BELOW_UNKNOWN",
	"SEMANTIC_WITHOUT_VERSION",
	"VERSION_NOT_IN_SCHEME",
	"VERSION_BUMP_TOO_SMALL",
	"ELEMENT_NOT_IN_CONTRACT",
	"EXAMPLE_NOT_IN_CONTRACT",
	"CONTRACT_PATTERN_UNSAFE",
	"ARTIFACT_UNREADABLE",
	"CONTRACT_KIND_UNKNOWN",
	"CONTRACT_KIND_MISMATCH",
	"CONTRACT_ARTIFACT_NOT_MOCKABLE",
] as const;
export type ContractRefusalCode = (typeof CONTRACT_REFUSAL_CODES)[number];

export const CONTRACT_APPROVAL_REFUSAL_CODES = [
	"CONTRACT_VERSION_NOT_PROPOSED",
	"CONTRACT_DECISION_REASON_MISSING",
	...PERMISSION_REFUSAL_CODES,
] as const;
export type ContractApprovalRefusalCode =
	(typeof CONTRACT_APPROVAL_REFUSAL_CODES)[number];

export const ECOSYSTEM_REFUSAL_CODES = [
	"STALE_BASE",
	"ECOSYSTEM_ID_IMMUTABLE",
	"ECOSYSTEM_SLUG_TAKEN",
	"CHANNEL_CODE_TAKEN",
	"CHANNEL_CODE_IN_USE",
	"RESPONSE_WINDOW_EXCEEDS_ECOSYSTEM",
	"PROJECT_ID_IMMUTABLE",
	"CONTRACT_TYPE_UNKNOWN",
	"ARTIFACT_FOR_OPAQUE",
	"ARTIFACT_MISSING",
	"REF_UNRESOLVED",
	"REF_NOT_PUBLISHED",
	"ECOSYSTEM_NOT_SHARED",
	"ECOSYSTEM_NOT_MEMBER",
	"SELF_CONSUMPTION",
	"CONSUMPTION_ECOSYSTEM_MISSING",
	"VERSION_UNKNOWN",
	"CONSUMPTION_DUPLICATE",
	"CONTRACT_IN_USE",
	"MEMBERSHIP_EXISTS",
	"MEMBERSHIP_TRANSITION_NOT_ALLOWED",
	"MEMBERSHIP_REASON_REQUIRED",
	"MEMBERSHIP_IN_USE",
	"ECOSYSTEM_REFUSED",
	...CHANNEL_REFUSAL_CODES,
	...ECOSYSTEM_TOOL_REFUSAL_CODES,
	...CONTRACT_REFUSAL_CODES,
	...CONTRACT_APPROVAL_REFUSAL_CODES,
	...LINK_REFUSAL_CODES,
] as const;
export type EcosystemRefusalCode = (typeof ECOSYSTEM_REFUSAL_CODES)[number];
export const ECOSYSTEM_REFUSAL_STATUSES = {
	STALE_BASE: 409,
	THREAD_HELD: 409,
	THREAD_ALREADY_HELD: 409,
	THREAD_NOT_HELD: 409,
	HOLD_NOT_AUTHORISED: 403,
	CHANNEL_NO_ROLE: 403,
	CHANNEL_WRITE_NOT_AUTHORISED: 403,
	ECOSYSTEM_WRITE_NOT_AUTHORISED: 403,
	ECOSYSTEM_NOT_AUTHORISED: 403,
} as const satisfies RefusalStatuses<EcosystemRefusalCode | ChannelRefusalCode | EcosystemToolRefusalCode>;

// The channel tool's actions: reads answer, writes change a channel document.
export const CHANNEL_READS = [
	"register",
	"inbox",
	"outbox",
	"unanswered",
	"read",
	"thread",
	"contracts",
] as const;
export const CHANNEL_WRITES = [
	"draft",
	"reply",
	"edit",
	"submit",
	"hold",
	"release",
	"withdraw",
	"supersede",
	"gate",
] as const;
export const CHANNEL_ACTIONS = [...CHANNEL_READS, ...CHANNEL_WRITES] as const;
export type ChannelAction = (typeof CHANNEL_ACTIONS)[number];

/** `<project slug>/<contract slug>@<version>`, the form a landing names an implemented version in. */
export const LANDED_CONTRACT = /^([a-z][a-z0-9-]{0,62})\/([a-z][a-z0-9-]{0,62})@([A-Za-z0-9][A-Za-z0-9._+-]{0,39})$/;

/** The doors a person writes through: the assistant, the web, or the CLI with a token. */
export const PERSON_VIAS = ["assistant", "web", "cli"] as const;
export type PersonVia = (typeof PERSON_VIAS)[number];
