import type { RefusalStatuses } from "./refusal.js";
import { STOREFRONT_DRAFT_REFUSAL_CODES } from "./verdict-identity.js";

export type { ReleaseNotes, ReleaseNotesSection } from "./release-notes.js";

// Rule refusals an issue write answers in the refusal envelope (packages/contracts/src/refusal.ts).

export const CRITERIA_REFUSAL_CODES = [
	"CRITERIA_REFUSED",
	"CRITERIA_TEXT_UNPARSEABLE",
	"CRITERIA_LOCKED",
	"CRITERIA_INPUT_INVALID",
] as const;
export type CriteriaRefusalCode = (typeof CRITERIA_REFUSAL_CODES)[number];

export const VERDICT_REFUSAL_CODES = [
	"VERDICT_REFUSED",
	"VERDICT_VALUE_UNKNOWN",
	"VERDICT_SKIP_REASON_REQUIRED",
	"VERDICT_IDENTITY_REQUIRED",
	"VERDICT_COMMIT_NOT_FULL",
	"VERDICT_RUNTIME_NOT_FULL",
	"VERDICT_DESIGN_SHAPE",
	"VERDICT_CONTRACT_SHAPE",
	"VERDICT_CRITERION_UNKNOWN",
	"VERDICT_DESIGN_UNKNOWN",
	"VERDICT_DESIGN_UNAPPROVED",
	"VERDICT_CONTRACT_UNKNOWN",
	...STOREFRONT_DRAFT_REFUSAL_CODES,
] as const;
export type VerdictRefusalCode = (typeof VERDICT_REFUSAL_CODES)[number];

export const ATTRIBUTE_REFUSAL_CODES = [
	"ATTRIBUTE_REFUSED",
	"UNREGISTERED_KEY",
	"WRONG_TYPE",
	"OBLIGATION_UNOWNED",
	"EMPTY_TEXT",
	"SOURCE_COMMENT_NOT_FOUND",
	"SOURCE_COMMENT_OFF_ISSUE",
] as const;
export type AttributeRefusalCode = (typeof ATTRIBUTE_REFUSAL_CODES)[number];

export const COMMIT_LANDING_REFUSAL_CODES = [
	"COMMIT_NOT_IN_REPOSITORY",
	"COMMIT_NOT_THIS_ISSUE",
	"COMMIT_NOT_LANDED",
	"COMMIT_UNVERIFIED",
] as const;
export type CommitLandingRefusalCode =
	(typeof COMMIT_LANDING_REFUSAL_CODES)[number];

export const MERGE_REFUSAL_CODES = [
	"MERGE_MARK_REFUSED",
	"NO_WORK_EVIDENCE",
	"UNMARK_REQUIRES_NOT_CLOSED",
	"LANDING_REQUIRED",
	"LANDING_NOT_THIS_SHAPE",
	"MARK_ALREADY_STANDS",
	"ARTIFACTS_NOT_THIS_SHAPE",
	"ARTIFACTS_NOT_DESIGN",
	"ARTIFACT_CARRIER_UNKNOWN",
	"ARTIFACT_CARRIER_SELF",
	"ARTIFACT_CARRIER_SHIPPED",
	"ARTIFACT_CARRIER_DESIGN",
	"CHANGED_PATHS_NOT_THIS_SHAPE",
	"CHANGED_PATHS_UNMATCHED",
	"TARGET_REQUIRED",
	"PROJECT_DOCUMENT_NOT_FOUND",
	"NO_PULL_REQUEST",
	"PROJECTION_EMPTY",
	"MERGE_REFUSED",
	"MERGE_REQUESTER_MISSING",
	"MERGE_RUN_NOT_FOUND",
	"MERGE_RUN_OF_ANOTHER_PROJECT",
	"NO_BINDING",
	...COMMIT_LANDING_REFUSAL_CODES,
] as const;
export type MergeRefusalCode = (typeof MERGE_REFUSAL_CODES)[number];

export const ARCHIVE_REFUSAL_CODES = [
	"ARCHIVE_REFUSED",
	"ARCHIVE_KEY_UNKNOWN",
	"ARCHIVE_STATUS_NOT_TERMINAL",
	"ARCHIVE_ISSUE_NOT_TERMINAL",
	"ARCHIVE_EDGE_LOAD_BEARING",
] as const;
export type ArchiveRefusalCode = (typeof ARCHIVE_REFUSAL_CODES)[number];

export const ISSUE_ATTACHMENT_REFUSAL_CODES = [
	"ATTACHMENT_REFUSED",
	"MIME_NOT_ALLOWED",
	"FILE_TOO_LARGE",
	"EMPTY_FILE",
	"INVALID_NAME",
	"INVALID_BASE64",
	"PAYLOAD_TOO_LARGE",
	"ATTACHMENT_NAME_TAKEN",
] as const;
export type IssueAttachmentRefusalCode =
	(typeof ISSUE_ATTACHMENT_REFUSAL_CODES)[number];

export const DEPENDENCY_REFUSAL_CODES = [
	"DEPENDENCY_REFUSED",
	"SELF_DEP",
	"CROSS_PROJECT",
	"CYCLE_DETECTED",
	"CYCLE_DEPTH_EXCEEDED",
	"ISSUE_ARCHIVED",
	"EDGE_MISMATCH",
] as const;
export type DependencyRefusalCode = (typeof DEPENDENCY_REFUSAL_CODES)[number];

export const LABEL_ATTACH_REFUSAL_CODES = [
	"LABELS_REFUSED",
	"INVALID_LABELS",
	"PRIMARY_NOT_MODULE",
	"MULTIPLE_PRIMARY",
] as const;
export type LabelAttachRefusalCode =
	(typeof LABEL_ATTACH_REFUSAL_CODES)[number];

export const ISSUE_CREATE_REFUSAL_CODES = [
	"ISSUE_CREATE_REFUSED",
	"INVALID_STATUS",
	"INVALID_DETECTOR_KEY",
] as const;
export type IssueCreateRefusalCode =
	(typeof ISSUE_CREATE_REFUSAL_CODES)[number];

export const ISSUE_TAKE_REFUSAL_CODES = [
	"ISSUE_TAKE_REFUSED",
	"ISSUE_BLOCKED",
	"ISSUE_LEASE_HELD",
	"ISSUE_NOT_FOUND",
	"ISSUE_LEASE_KEY_SHAPE",
	"ISSUE_LEASE_KEY_UNKNOWN_PREFIX",
	"ISSUE_LEASE_KEY_PROJECT_MISMATCH",
] as const;
export type IssueTakeRefusalCode = (typeof ISSUE_TAKE_REFUSAL_CODES)[number];
export const ISSUE_TAKE_REFUSAL_STATUSES = {
	ISSUE_LEASE_HELD: 409,
	ISSUE_NOT_FOUND: 404,
	ISSUE_LEASE_KEY_SHAPE: 400,
	ISSUE_LEASE_KEY_UNKNOWN_PREFIX: 404,
	ISSUE_LEASE_KEY_PROJECT_MISMATCH: 400,
} as const satisfies RefusalStatuses<IssueTakeRefusalCode>;

export const ISSUE_UPDATE_REFUSAL_CODES = [
	"ISSUE_UPDATE_REFUSED",
	"SESSION_CONTEXT_DROPS_UNREAD_KEYS",
	"SESSION_CONTEXT_MISMATCH",
	"BRANCH_SELF_REFERENCE",
	"ASSIGNEE_NOT_MEMBER",
	"STATUS_MOVES_BY_TRANSITION",
] as const;
export type IssueUpdateRefusalCode =
	(typeof ISSUE_UPDATE_REFUSAL_CODES)[number];

export const ISSUE_UPDATE_REFUSAL_STATUSES = {
	STATUS_MOVES_BY_TRANSITION: 400,
} as const satisfies RefusalStatuses<IssueUpdateRefusalCode>;
