// The registry of what core says (`said.ts`): every sentence key, its English template and the kind
// of each value it carries. Core builds its English text from these templates, so the text and the
// structured form cannot disagree; a reader in another language holds its own template per key
// (web-v2's copy files, composed by `product-copy.ts`), and a contract test refuses a key one language lacks.

import type { SaidEntry } from "./said.js";

export const SAID = {
	"standing.text": { en: "{text}", vars: { text: "text" } },
	"standing.who.named": { en: "{name}", vars: { name: "name" } },
	"standing.who.namesMore": { en: "{names} +{n}", vars: { names: "name", n: "count" } },
	"standing.act.none": { en: "" },
	"feedback.notice.agent": { en: "The reporter is an agent without a bell: tell it directly." },
	"feedback.notice.autoVerified": { en: "Verified automatically after {n} days with no reply", vars: { n: "count" } },
	"feedback.notice.before": { en: "Shipped before release notices existed on this project ({date}).", vars: { date: "date" } },
	"feedback.told.message": { en: "a message from {by}", vars: { by: "name" } },
	"feedback.told.messageUnnamed": { en: "a message to the reporters" },
	"feedback.told.relayed": { en: "{by} told them outside Forge", vars: { by: "name" } },
	"feedback.told.relayedUnnamed": { en: "a member told them outside Forge" },
	"feedback.act.tellNow": { en: "Tell the reporter now" },
	"feedback.notice.noDedup": { en: "triage without dedup: the item's vector is {status}", vars: { status: "code" } },
	"feedback.notice.noRelease": { en: "No release carries it, so none told the reporter: tell them yourself." },
	"feedback.notice.silent": { en: "{release} shipped it and sent the reporter no notice.", vars: { release: "version" } },
	"feedback.notice.turnedOff": { en: "The reporter turned this notice off: tell them yourself." },
	"integrations.detail.disabled": { en: "integration disabled" },
	"integrations.detail.lastHealth": { en: "last health: {status}", vars: { status: "health" } },
	"integrations.detail.lastHealthWhy": { en: "last health: {status} — {detail}", vars: { status: "health", detail: "said" } },
	"integrations.detail.localPath": { en: "a local path no host serves: commits unreadable; declare the hosted repository" },
	"integrations.detail.neverGithub": { en: "Never checked — Test connection probes the App installation and repository." },
	"integrations.detail.neverGitlab": { en: "Never checked — Test connection probes the token and project webhook." },
	"integrations.detail.neverTested": { en: "never test-connected" },
	"integrations.detail.noRepository": { en: "the project document declares no repository" },
	"integrations.detail.noneConfigured": { en: "no {provider} integration configured", vars: { provider: "name" } },
	"integrations.detail.readThrough": { en: "read through {provider} — last health: {status}", vars: { provider: "name", status: "health" } },
	"integrations.detail.readThroughNever": { en: "read through {provider} — never health-checked", vars: { provider: "name" } },
	"integrations.detail.switchedOff": { en: "the {provider} binding is switched off: commits and branches unreadable", vars: { provider: "name" } },
	"integrations.detail.unreachedBind": { en: "no source host binding reaches {host}: bind a connection serving {host}", vars: { host: "name" } },
	"integrations.detail.unreachedConnect": { en: "no source host binding reaches {host}: connect {provider} to fix it", vars: { host: "name", provider: "name" } },
	"integrations.row.neverChecked": { en: "never health-checked" },
	"issues.blocker.actAnswer": { en: "Answer it" },
	"issues.blocker.actOpenBlocker": { en: "Open blocking issue" },
	"issues.blocker.actResumeAt": { en: "Resume at {status}", vars: { status: "statusLabel" } },
	"issues.blocker.actResumeRun": { en: "Resume run" },
	"issues.blocker.answered": { en: "The question this issue asked has an answer on the thread." },
	"issues.blocker.boxReads": { en: "Answered; a box registered to read the answer back." },
	"issues.blocker.designMany": { en: "Blocked by {keys}, which deliver designs not yet approved: {holds}.", vars: { keys: "key", holds: "text" } },
	"issues.blocker.designOne": { en: "Blocked by {keys}, which delivers a design not yet approved: {holds}.", vars: { keys: "key", holds: "text" } },
	"issues.blocker.finishBlockers": { en: "Finish the blocking issue(s) first." },
	"issues.blocker.landedMany": { en: "Blocked by {keys}, which have landed and wait on a judge.", vars: { keys: "key" } },
	"issues.blocker.landedOne": { en: "Blocked by {keys}, which has landed and waits on a judge.", vars: { keys: "key" } },
	"issues.blocker.noLeftStatus": { en: "Answered, but no left status was recorded, so it could not return." },
	"issues.blocker.noResumeAt": { en: "No resume point recorded — Move anyway… lists every move." },
	"issues.blocker.noResumeFromHold": { en: "No resume point recorded — the status menu lists every option." },
	"issues.blocker.openMany": { en: "Blocked by {n} open issues.", vars: { n: "count" } },
	"issues.blocker.openOne": { en: "Blocked by 1 open issue." },
	"issues.blocker.otherQuestion": { en: "Answered, but another question is still open ({ids}).", vars: { ids: "text" } },
	"issues.blocker.owesDecision": { en: "Waiting for a decision only a person can make." },
	"issues.blocker.owesInformation": { en: "This issue is waiting for information — an answer to a question." },
	"issues.blocker.owesResource": { en: "Waiting for an account, credential or data only a person can supply." },
	"issues.blocker.paused": { en: "The issue is paused." },
	"issues.blocker.refused": { en: "Its question was answered, and returning it to work was refused: {code} — {detail}", vars: { code: "code", detail: "text" } },
	"issues.blocker.sentToRun": { en: "Answered; sent to the asking run (session {id}).", vars: { id: "text" } },
	"issues.blocker.staged": { en: "Answered; this project is not autonomous, so nothing moves." },
	"issues.blocker.stillWaits": { en: "Its question was answered, and the answer says it still waits: {why}", vars: { why: "text" } },
	"issues.blocker.stopped": { en: "This issue is stopped until a person acts." },
	"issues.blocker.unreadable": { en: "What it waits on could not be read — read the thread." },
	"issues.blocker.unrecorded": { en: "Answered, but no effect was recorded." },
	"issues.blocker.waitsOnKey": { en: "Answered; it still waits on {key}: {why}", vars: { key: "key", why: "text" } },
	"issues.blocker.whoAnswered": { en: "Resume it once the answer is enough." },
	"issues.blocker.whoBoxReads": { en: "The run on that box moves it on after reading." },
	"issues.blocker.whoDecision": { en: "Whoever owns the call decides, then resumes it where it stopped." },
	"issues.blocker.whoDesignMany": { en: "The design approver decides the revision {keys} deliver; approval releases this.", vars: { keys: "key" } },
	"issues.blocker.whoDesignOne": { en: "The design approver decides the revision {keys} delivers; approval releases this.", vars: { keys: "key" } },
	"issues.blocker.whoInformation": { en: "Anyone on the project can answer it; the question is below." },
	"issues.blocker.whoLandedMany": { en: "A judge verdicts each criterion of {keys}; passing releases this.", vars: { keys: "key" } },
	"issues.blocker.whoLandedOne": { en: "A judge verdicts each criterion of {keys}; passing releases this.", vars: { keys: "key" } },
	"issues.blocker.whoNamesWhere": { en: "A person names its destination; resume from the status menu." },
	"issues.blocker.whoOtherQuestion": { en: "It moves on once that question is answered." },
	"issues.blocker.whoPaused": { en: "An operator can resume it when the work is wanted again." },
	"issues.blocker.whoRefused": { en: "Clear what the refusal names, then move it on. Resume it from the status menu once it can go on." },
	"issues.blocker.whoResource": { en: "Supply it, then resume it where it stopped." },
	"issues.blocker.whoResumes": { en: "A person resumes it from the status menu." },
	"issues.blocker.whoRunReads": { en: "That run moves the issue on once it reads the answer." },
	"issues.blocker.whoSettles": { en: "{key} settles first; its blocks edge holds this issue until then.", vars: { key: "key" } },
	"issues.blocker.whoWaitOver": { en: "A person resumes it from the status menu once the wait ends." },
	"issues.gate.issue_busy.detail": { en: "Another job is already active on this issue." },
	"issues.gate.issue_busy.who": { en: "Wait for the active run to finish." },
	"issues.gate.job_held_clears.detail": { en: "A step is held until its condition clears." },
	"issues.gate.job_held_clears.who": { en: "No action — it resumes itself, alerting if the hold persists." },
	"issues.gate.job_held_stays.detail": { en: "A step is held and will not clear on its own." },
	"issues.gate.job_held_stays.who": { en: "Fix the cause, then cancel the step so the issue can move." },
	"issues.gate.retry_cooldown.detail": { en: "The step failed and is cooling down before retrying." },
	"issues.gate.retry_cooldown.who": { en: "No action — it retries itself. If failures repeat, read the error." },
	"issues.gate.run_not_running.detail": { en: "Queued, but its run is paused or closed; nothing will dispatch it." },
	"issues.gate.run_not_running.who": { en: "Resume the run, or cancel it and reopen the issue." },
	"issues.gate.runner_stale.detail": { en: "No runner online — every host is offline, stale or rate-limited." },
	"issues.gate.runner_stale.who": { en: "Bring a runner back (see Runners); it dispatches next tick." },
	"issues.gate.runner_too_old.detail": { en: "Every online runner is too old to claim work." },
	"issues.gate.runner_too_old.who": { en: "Update the runner; it dispatches once the new version reports." },
	"issues.pause.at": { en: " at {at}", vars: { at: "text" } },
	"issues.pause.byOperator": { en: "{base} An operator paused it.", vars: { base: "said" } },
	"issues.pause.heldBy": { en: "{base} It is held by {kind}{at}.", vars: { base: "said", kind: "text", at: "said?" } },
	"issues.pause.machine.detail": { en: "The run is paused until its condition clears." },
	"issues.pause.machine.who": { en: "No action — it resumes itself once the condition clears." },
	"issues.pause.operator.detail": { en: "The run is paused. Nothing dispatches, whatever the status says." },
	"issues.pause.operator.who": { en: "Resume the run, or cancel it if work should stop." },
	"issues.pause.sweeper.detail": { en: "The run is paused for a reason this build no longer knows." },
	"issues.pause.sweeper.who": { en: "No action — the sweeper frees it next tick; else resume manually." },
	"issues.rule.admitted": { en: "admitted and unwithheld, so the project's master owes it a run" },
	"issues.rule.approval": { en: "merged; each release needs a person's approval on Releases" },
	"issues.rule.approved": { en: "the plan checkpoint holds; the next run goes straight to build" },
	"issues.rule.blocked": { en: "a live blocks edge from {key}, not yet settled", vars: { key: "key" } },
	"issues.rule.blockedDesign": { en: "blocked by {key}, delivering design {design}; settles once approved", vars: { key: "key", design: "name" } },
	"issues.rule.blockedLanded": { en: "blocked by {key}, landed but unsettled until a judge passes every criterion", vars: { key: "key" } },
	"issues.rule.criteriaStale": { en: "{n} of {total} criteria lack a current pass; held until judged again", vars: { n: "count", total: "count" } },
	"issues.rule.designReturned": { en: "design {flow} r{r} was returned: a run owes the revised design", vars: { flow: "name", r: "count" } },
	"issues.rule.draft": { en: "a draft is not work until a person accepts it" },
	"issues.rule.ended": { en: "the issue is {status}", vars: { status: "status" } },
	"issues.rule.landed": { en: "landed at `{status}`: the next run judges it for `awaiting_release`", vars: { status: "status" } },
	"issues.rule.leaseHeld": { en: "lease held by {holder}", vars: { holder: "name" } },
	"issues.rule.leaseHeldSession": { en: "lease held by a run session that has not ended" },
	"issues.rule.needsInfo": { en: "parked at needs_info: a person owes the answer; it wakes the master" },
	"issues.rule.noApproval": { en: "its work merged; the project releases without an approval" },
	"issues.rule.noHolder": { en: "in_progress, but no live lease, job or run" },
	"issues.rule.noNote": { en: "no release note (RELEASE_RECORD_MISSING); the master writes it next pass" },
	"issues.rule.parked": { en: "a run parked it on_hold: {why}; the master resumes it", vars: { why: "said" } },
	"issues.rule.parkedAsked": { en: "a run parked it on_hold with a question for a person: {why}", vars: { why: "said" } },
	"issues.rule.parkedBehind": { en: "a run parked it on_hold behind {key}, which still holds it: {why}", vars: { key: "key", why: "said" } },
	"issues.rule.personPaused": { en: "a person paused it; a person resumes it" },
	"issues.rule.queued": { en: "a job is queued; no run session holds it yet" },
	"issues.rule.releaseRunning": { en: "a release run holds it" },
	"issues.rule.reopen": { en: "sent back with a reason; a master takes it again" },
	"issues.rule.runAsked": { en: "a run asked a question only a person can answer" },
	"issues.rule.staleDraftAsked": { en: "Forge asked whether to merge, drop or keep a {days}-day-old draft", vars: { days: "count" } },
	"issues.rule.withheld": { en: "{code}: {detail} No master is handed it until then.", vars: { code: "code", detail: "text" } },
	"issues.standing.act.answer": { en: "answer a question" },
	"issues.standing.act.answerOther": { en: "answer the other question" },
	"issues.standing.act.approveContract": { en: "approve a contract version" },
	"issues.standing.act.approveDesign": { en: "approve the design" },
	"issues.standing.act.approveOnReleases": { en: "Approve release on Releases" },
	"issues.standing.act.buildNext": { en: "build next" },
	"issues.standing.act.decidePattern": { en: "approve or return the new pattern" },
	"issues.standing.act.cameBack": { en: "came back" },
	"issues.standing.act.decide": { en: "make a decision" },
	"issues.standing.act.declarePolicy": { en: "declare the policy" },
	"issues.standing.act.declarePolicyState": { en: "declare its policy state" },
	"issues.standing.act.designApproval": { en: "design approval" },
	"issues.standing.act.dispatch": { en: "dispatch a run" },
	"issues.standing.act.dropped": { en: "dropped" },
	"issues.standing.act.judgeAgain": { en: "judge it again" },
	"issues.standing.act.landedClaim": { en: "landed · claim it and judge what landed" },
	"issues.standing.act.landedWaitsJudge": { en: "landed, waits on a judge" },
	"issues.standing.act.moveOn": { en: "move it on" },
	"issues.standing.act.moveOnRefused": { en: "move it on: {code}", vars: { code: "code" } },
	"issues.standing.act.needsPerson": { en: "needs a person" },
	"issues.standing.act.nextRelease": { en: "next release" },
	"issues.standing.act.noLiveRun": { en: "in progress with no live run" },
	"issues.standing.act.notStarted": { en: "not started" },
	"issues.standing.act.paused": { en: "paused" },
	"issues.standing.act.readAnswer": { en: "read the answer" },
	"issues.standing.act.readAnswerBack": { en: "read the answer back" },
	"issues.standing.act.rerun": { en: "re-run after reopen" },
	"issues.standing.act.resume": { en: "resume it" },
	"issues.standing.act.resumeOnce": { en: "resume once: {why}", vars: { why: "said" } },
	"issues.standing.act.reviseDesign": { en: "revise design {flow} · revision {r} returned", vars: { flow: "name", r: "count" } },
	"issues.standing.act.running": { en: "running" },
	"issues.standing.act.shipped": { en: "shipped" },
	"issues.standing.act.step": { en: "{step}", vars: { step: "step" } },
	"issues.standing.act.stepFor": { en: "{step} · {n} min", vars: { step: "step", n: "count" } },
	"issues.standing.act.supply": { en: "supply what it asks for" },
	"issues.standing.act.takeOnOrDrop": { en: "take on or drop" },
	"issues.standing.act.waitOn": { en: "wait on {key}", vars: { key: "key" } },
	"issues.standing.act.working": { en: "working" },
	"issues.standing.who.contractProvider": { en: "The contract provider" },
	"issues.standing.who.designApprover": { en: "A design approver" },
	"issues.standing.who.nextRun": { en: "Next run" },
	"issues.standing.who.noHolder": { en: "No holder" },
	"issues.standing.who.patternReviewer": { en: "A pattern reviewer" },
	"issues.standing.who.queuedRun": { en: "Queued run" },
	"issues.standing.who.release": { en: "Release" },
	"issues.standing.who.run": { en: "Run" },
	"releases.effect.split": { en: "Cuts the oldest {limit} merged issues; {left} wait for the next release.", vars: { limit: "count", left: "said" } },
	"releases.effect.splitOthers": { en: "the others" },
	"releases.effect.splitRest": { en: "the other {n}", vars: { n: "count" } },
	"requirements.history.text.accepted": { en: "Accepted r{r}", vars: { r: "count" } },
	"requirements.history.text.acceptedSuggestion": { en: "Accepted {what}", vars: { what: "said" } },
	"requirements.history.text.acceptedSuggestionWhy": { en: "Accepted {what}: {rest}", vars: { what: "said", rest: "text" } },
	"requirements.history.text.acceptedWhy": { en: "Accepted r{r}: {rest}", vars: { r: "count", rest: "text" } },
	"requirements.history.text.agreed": { en: "Agreed r{r}", vars: { r: "count" } },
	"requirements.history.text.agreedWhy": { en: "Agreed r{r}: {rest}", vars: { r: "count", rest: "text" } },
	"requirements.history.text.deferred": { en: "Deferred out of the current release: {rest}", vars: { rest: "text" } },
	"requirements.history.text.deferredFor": { en: "Deferred out of the current release (for {phase}): {rest}", vars: { phase: "name", rest: "text" } },
	"requirements.history.text.deliveryAccepted": { en: "Accepted the delivery" },
	"requirements.history.text.deliveryAcceptedWhy": { en: "Accepted the delivery: {rest}", vars: { rest: "text" } },
	"requirements.history.text.dropped": { en: "Dropped: {rest}", vars: { rest: "text" } },
	"requirements.history.text.pictureDrawn": { en: "Drew the picture of r{r}, a rough sketch: {rest}", vars: { r: "count", rest: "text" } },
	"requirements.history.text.pictureReplaced": { en: "Replaced the picture of r{r}, a rough sketch: {rest}", vars: { r: "count", rest: "text" } },
	"requirements.history.text.proposed": { en: "Proposed r{r}", vars: { r: "count" } },
	"requirements.history.text.withdrawn": { en: "Withdrew r{r}: {rest}", vars: { r: "count", rest: "text" } },
	"requirements.history.text.rejectedSuggestion": { en: "Rejected {what}", vars: { what: "said" } },
	"requirements.history.text.rejectedSuggestionWhy": { en: "Rejected {what}: {rest}", vars: { what: "said", rest: "text" } },
	"requirements.history.text.followedPinOnly": { en: "Forge followed {rest} (pin-only)", vars: { rest: "text" } },
	"requirements.history.text.repinned": { en: "Re-pinned r{r} onto the approved designs", vars: { r: "count" } },
	"requirements.history.text.repinnedWhy": { en: "Re-pinned r{r} onto the approved designs: {rest}", vars: { r: "count", rest: "text" } },
	"requirements.history.text.returned": { en: "Returned r{r}: {rest}", vars: { r: "count", rest: "text" } },
	"requirements.history.text.suggested": { en: "Suggested {what}", vars: { what: "said" } },
	"requirements.history.text.undeferred": { en: "Undeferred" },
	"requirements.history.text.undeferredWhy": { en: "Undeferred: {rest}", vars: { rest: "text" } },
	"requirements.history.text.wrote": { en: "Wrote r{r}: {rest}", vars: { r: "count", rest: "text" } },
	"requirements.history.text.wroteSuggested": { en: "Wrote r{r} (an accepted suggestion): {rest}", vars: { r: "count", rest: "text" } },
	"requirements.history.text.wroteBare": { en: "Wrote r{r}", vars: { r: "count" } },
	"requirements.history.text.wroteSuggestedBare": { en: "Wrote r{r} (an accepted suggestion)", vars: { r: "count" } },
	"requirements.history.what.breakdown": { en: "a breakdown" },
	"requirements.history.what.change": { en: "a change" },
	"requirements.history.what.duplicate": { en: "a duplicate" },
	"requirements.history.what.readiness": { en: "a readiness check" },
	"requirements.history.what.requirement_draft": { en: "a requirement draft" },
	"requirements.history.what.revision_diff": { en: "a revision" },
	"requirements.history.what.triage": { en: "a triage" },
	"requirements.history.who.agent": { en: "An agent" },
	"requirements.history.who.assistant": { en: "BA assistant" },
	"requirements.history.who.signer": { en: "A signer" },
	"requirements.history.who.someone": { en: "Someone" },
	"standing.act.acceptR": { en: "accept r{r}", vars: { r: "count" } },
	"standing.act.acceptRevisionN": { en: "accept revision {r} of {req}", vars: { r: "count", req: "key" } },
	"standing.act.acceptRevisionOf": { en: "accept the revision of {req}", vars: { req: "key" } },
	"standing.act.agreeIt": { en: "agree it" },
	"standing.act.agreeR": { en: "agree r{r}", vars: { r: "count" } },
	"standing.act.answerReturn": { en: "answer the return" },
	"standing.act.approve": { en: "approve" },
	"standing.act.approveCarrierRelease": { en: "Approve the release that carries it" },
	"standing.act.approveDesign": { en: "approve design {what}", vars: { what: "name" } },
	"standing.act.approveOrReturn": { en: "approve or return {v}", vars: { v: "version" } },
	"standing.act.approveReleaseV": { en: "Approve release {v}", vars: { v: "version" } },
	"standing.act.askApproval": { en: "ask for approval" },
	"standing.act.beAccepted": { en: "be accepted" },
	"standing.act.beAgreedDelivered": { en: "be agreed and delivered" },
	"standing.act.beDelivered": { en: "be delivered" },
	"standing.act.beResolved": { en: "be resolved" },
	"standing.act.breakDown": { en: "break down" },
	"standing.act.breakDownBy": { en: "break down, {when}", vars: { when: "said" } },
	"standing.act.bringIssueToGate": { en: "bring an issue to the release gate" },
	"standing.act.check": { en: "check {codes} against the traceability matrix, {when}", vars: { codes: "key", when: "said" } },
	"standing.act.checkCouldNotRun": { en: "a check could not run" },
	"standing.act.confirmAnswer": { en: "Confirm the answer" },
	"standing.act.cut": { en: "cut {v}{more}", vars: { v: "version", more: "said?" } },
	"standing.act.cutCarrierRelease": { en: "cut the release that carries {what}", vars: { what: "said" } },
	"standing.act.cutThenApprove": { en: "cut {v}, then approve it", vars: { v: "version" } },
	"standing.act.cutWaiting": { en: "cut the issues that are waiting" },
	"standing.act.declareProbe": { en: "declare a source probe on production" },
	"standing.act.declareCarried": { en: "say what carries {v}: nothing, tag, release commit, artifact or notice", vars: { v: "version" } },
	"standing.act.declareProduction": { en: "declare a production environment" },
	"standing.act.declareTarget": { en: "declare where releases land" },
	"standing.act.deploying": { en: "deploying" },
	"standing.act.finishDraft": { en: "finish draft" },
	"standing.act.fixFailing": { en: "fix {codes}, failing on {keys}", vars: { codes: "key", keys: "key" } },
	"standing.act.fixSchedule": { en: "fix a failing schedule" },
	"standing.act.judgeCriteria": { en: "judge the criteria still owed" },
	"standing.act.judgeOn": { en: "judge {codes} on {keys}", vars: { codes: "key", keys: "key" } },
	"standing.act.labelRunner": { en: "label a runner for releases" },
	"standing.act.markMerge": { en: "mark the merge{on}", vars: { on: "said?" } },
	"standing.act.noHolder": { en: "{act}: nobody holds {perm}; grant it under Settings → Members", vars: { act: "said", perm: "permission" } },
	"standing.act.pairRunner": { en: "pair a runner" },
	"standing.act.productionReadable": { en: "give production a way to be read" },
	"standing.act.promoteDraft": { en: "promote 1 draft issue" },
	"standing.act.promoteDrafts": { en: "promote {n} draft issues", vars: { n: "count" } },
	"standing.act.proposeDesign": { en: "propose design {what}", vars: { what: "name" } },
	"standing.act.proposeOrDrop": { en: "propose or drop r{r}", vars: { r: "count" } },
	"standing.act.proposeR": { en: "propose r{r}", vars: { r: "count" } },
	"standing.act.proposeRevisionN": { en: "propose revision {r} of {req}", vars: { r: "count", req: "key" } },
	"standing.act.proposeRevisionOf": { en: "propose the revision of {req}", vars: { req: "key" } },
	"standing.act.queuedBehind": { en: "queued behind {v}", vars: { v: "version" } },
	"standing.act.releaseByHand": { en: "release {what} by hand and close it", vars: { what: "said" } },
	"standing.act.releaseItByHand": { en: "release it by hand and close it" },
	"standing.act.releaseRunning": { en: "a release is running" },
	"standing.act.replan": { en: "re-plan {keys}", vars: { keys: "key" } },
	"standing.act.retie": { en: "tie {keys} to the current wording of {codes}, then judge it", vars: { codes: "key", keys: "key" } },
	"standing.act.reviewBreakdown": { en: "review the breakdown" },
	"standing.act.reviseReturned": { en: "revise returned r{r}", vars: { r: "count" } },
	"standing.act.reviseThenProposeOrDrop": { en: "revise returned r{r}, then propose or drop it", vars: { r: "count" } },
	"standing.act.runnerOnline": { en: "bring a runner online" },
	"standing.act.running": { en: "Running {a} of {b}", vars: { a: "count", b: "count" } },
	"standing.act.ship": { en: "ship" },
	"standing.act.shippedOf": { en: "Shipped {a} of {b}", vars: { a: "count", b: "count" } },
	"standing.act.splitRelease": { en: "split this release into smaller releases" },
	"standing.act.starting": { en: "starting" },
	"standing.act.takeOverSchedule": { en: "take over a schedule whose owner is gone" },
	"standing.act.takeNext": { en: "take {keys} next", vars: { keys: "key" } },
	"standing.act.onIssue": { en: "{act} on {key}", vars: { act: "said", key: "key" } },
	"standing.act.trace": { en: "trace {codes} to an issue criterion", vars: { codes: "key" } },
	"standing.act.triage": { en: "triage {what}", vars: { what: "name" } },
	"standing.act.triageAgain": { en: "triage it again" },
	"standing.act.triageIt": { en: "triage it" },
	"standing.act.triageMany": { en: "triage {n} feedback items", vars: { n: "count" } },
	"standing.act.triageReport": { en: "triage a report" },
	"standing.act.updateToContract": { en: "Update to the current version of {contract} ({v})", vars: { contract: "name", v: "version" } },
	"standing.act.updateToDesign": { en: "Update to the approved design: {design} (revision {r})", vars: { design: "name", r: "count" } },
	"standing.act.reviseForDesign": { en: "revise {codes} for {design} (revision {r}): {steps}", vars: { codes: "key", design: "name", r: "count", steps: "name" } },
	"standing.act.reviewSuggestedRevision": { en: "review the suggested revision" },
	"standing.act.mergeOrDrop": { en: "answer whether to merge, drop or keep this draft" },
	"standing.act.draftAnswerByHand": { en: "carry out the answer to the merge-or-drop question by hand" },
	"standing.rule.draftAnswerRefused": { en: "Forge could not carry out the answer by rule ({code}): {detail}", vars: { code: "code", detail: "text" } },
	"standing.act.verdictsNotReread": { en: "verdicts not re-read" },
	"standing.act.verifyFix": { en: "verify the fix" },
	"standing.act.verifyFixIn": { en: "verify the fix shipped in {v}", vars: { v: "version" } },
	"standing.act.sayIfGone": { en: "say whether the problem is gone" },
	"standing.act.tellShippedIn": { en: "tell {who} that it shipped in {v}", vars: { who: "name", v: "version" } },
	"standing.act.tellShipped": { en: "tell {who} that it shipped", vars: { who: "name" } },
	"standing.act.verifying": { en: "verifying" },
	"standing.act.writeReleaseNote": { en: "write the release note{on}", vars: { on: "said?" } },
	"standing.due": { en: "due {date}", vars: { date: "date" } },
	"standing.effect.follow": { en: "Follows {names} from now on; delivery acceptance waits until then.", vars: { names: "saidSeries" } },
	"standing.gate.claimed": { en: "{subject} {verb} not at the release gate, or another release holds {obj}.", vars: { subject: "said", verb: "agreement", obj: "agreement" } },
	"standing.gate.empty": { en: "Nothing at the release gate to cut." },
	"standing.gate.heldBack": { en: "{owes}. {they} held back until {their} criteria are earned; the others ship.", vars: { owes: "saidList", they: "agreement", their: "agreement" } },
	"standing.gate.nearGate": { en: "Nothing at the release gate. {n} {issues} {verb} at {their} test step.", vars: { n: "count", issues: "agreement", verb: "agreement", their: "agreement" } },
	"standing.gate.noGate": { en: "This project ships on close; there is no release to cut." },
	"standing.gate.noRunner": { en: "No runner paired, so no machine can run a release." },
	"standing.gate.noRunnerOnline": { en: "Runners are paired, but none can take a release now." },
	"standing.gate.noteMissing": { en: "{subject} {verb} no release note; the release would ship it undescribed.", vars: { subject: "said", verb: "agreement" } },
	"standing.gate.nowhere": { en: "No release target. An admin completes the production environment." },
	"standing.gate.on": { en: " on {subject}", vars: { subject: "said" } },
	"standing.gate.oversize": { en: "{n} {issues} {verb} waiting; a release carries at most {limit}. Split them.", vars: { n: "count", issues: "agreement", verb: "agreement", limit: "count" } },
	"standing.gate.oversizeUncounted": { en: "More issues wait; a release carries at most {limit}. Split, oldest first.", vars: { limit: "count" } },
	"standing.gate.owes": { en: "{key} owes {word} {list}", vars: { key: "key", word: "agreement", list: "text" } },
	"standing.gate.preference": { en: "No runner has the requested release label; using the pool." },
	"standing.gate.running": { en: "Another release is running. Let it finish first." },
	"standing.gate.subject.atGate": { en: "Issues at the gate" },
	"standing.gate.subject.count": { en: "{n} {issues}", vars: { n: "count", issues: "agreement" } },
	"standing.gate.subject.keys": { en: "{keys}", vars: { keys: "key" } },
	"standing.gate.subject.more": { en: "{keys} and {n} more", vars: { keys: "key", n: "count" } },
	"standing.gate.subject.some": { en: "Some issues" },
	"standing.gate.versionUndecided": { en: "{v} attempt {n} ended without saying what carries {v}; say so first.", vars: { v: "version", n: "count" } },
	"standing.gate.title.claimed": { en: "Issues already claimed" },
	"standing.gate.title.empty": { en: "Nothing at the gate" },
	"standing.gate.title.heldBack": { en: "Some issues held back" },
	"standing.gate.title.noGate": { en: "No release step" },
	"standing.gate.title.noRunner": { en: "No runner paired" },
	"standing.gate.title.noRunnerOnline": { en: "No runner can take it" },
	"standing.gate.title.noteMissing": { en: "Release note missing" },
	"standing.gate.title.nowhere": { en: "Nowhere to land" },
	"standing.gate.title.oversize": { en: "Too many issues" },
	"standing.gate.title.versionUndecided": { en: "Version undecided" },
	"standing.gate.title.preference": { en: "Preferred runner missing" },
	"standing.gate.title.running": { en: "A release is running" },
	"standing.gate.title.uncorroborated": { en: "Verdicts not re-read" },
	"standing.gate.title.unearned": { en: "Criteria still owed" },
	"standing.gate.title.unevaluated": { en: "A check could not run" },
	"standing.gate.title.unmerged": { en: "Work not marked merged" },
	"standing.gate.title.unprovable": { en: "Production cannot be proved" },
	"standing.gate.title.unreadable": { en: "Production cannot be read" },
	"standing.gate.uncorroborated": { en: "{subject} {verb} a verdict production could not re-read: weaker evidence.", vars: { subject: "said", verb: "agreement" } },
	"standing.gate.unearned": { en: "{owes}. The unattended sweep needs a passing verdict on every criterion.", vars: { owes: "saidList" } },
	"standing.gate.unevaluated": { en: "The {check} check could not run; reasons may be missing.", vars: { check: "code" } },
	"standing.gate.unmerged": { en: "{subject} {verb} no merge Forge saw, so {their} work is unconfirmed.", vars: { subject: "said", verb: "agreement", their: "agreement" } },
	"standing.gate.unprovable": { en: "Production has no source-commit probe, so releases cannot be proved. Add one." },
	"standing.gate.unreadable": { en: "Production is unreadable, so no verdict can earn an unattended release." },
	"standing.more": { en: " and {n} more", vars: { n: "count" } },
	"standing.overdueSince": { en: "overdue since {date}", vars: { date: "date" } },
	"standing.risk.apiRemoved": { en: "{ref} is removed: callers still using it are refused", vars: { ref: "name" } },
	"standing.risk.dataChanged": { en: "{ref} changes shape: old rows are read by the new shape", vars: { ref: "name" } },
	"standing.risk.dataRemoved": { en: "{ref} is removed: its data is lost on rollback", vars: { ref: "name" } },
	"standing.who.baOrOwner": { en: "BA or owner" },
	"standing.who.signerAdmitter": { en: "a BA or owner who can admit issues" },
	"standing.who.currentRevision": { en: "The current revision" },
	"standing.who.holderOf": { en: "A holder of {perm}", vars: { perm: "permission" } },
	"standing.who.independentJudge": { en: "Independent judge" },
	"standing.who.issues": { en: "Issues" },
	"standing.who.itsAuthor": { en: "Its author" },
	"standing.who.itsRoot": { en: "Its root {root}", vars: { root: "key" } },
	"standing.who.linkedIssue": { en: "The linked issue" },
	"standing.who.linkedWork": { en: "The linked work" },
	"standing.who.master": { en: "Master" },
	"standing.who.newRequirement": { en: "The new requirement" },
	"standing.who.nobody": { en: "Nobody" },
	"standing.who.projectMaster": { en: "The project's master" },
	"standing.who.releaseGate": { en: "Release gate" },
	"standing.who.releaseRun": { en: "Release run" },
	"standing.who.revisionProposal": { en: "The revision proposal" },
	"standing.who.scheduleOwner": { en: "The schedule owner" },
	"standing.who.you": { en: "You" },
	"issues.blocker.otherQuestionUnnamed": { en: "Answered, but another question is still open (unnamed)." },
	"issues.rule.noWriter": { en: "{rule}; no person holds {perm} on this project", vars: { rule: "said", perm: "permission" } },
	"issues.rule.noReason": { en: "the run named no reason" },
	"issues.rule.answered": { en: "{reason} {who}", vars: { reason: "said", who: "said" } },
	"runs.rule.withRef": { en: "{rule} ({ref})", vars: { rule: "said", ref: "said" } },
	"runs.rule.lockNoHolder": { en: "DEPLOY_ENVIRONMENT_LOCKED: {environment} refused at {at}; holder and deadline unreadable", vars: { environment: "name", at: "instant" } },
	"runs.rule.lockUnnamedSubject": { en: "an unnamed subject" },
	"runs.rule.lockSince": { en: " since {at}", vars: { at: "instant" } },
	"runs.rule.lockUntilExpiry": { en: "until that deploy ends or its hold expires at {at}", vars: { at: "instant" } },
	"runs.rule.lockUntilEnds": { en: "until that deploy ends" },
	"runs.act.answerQuestion": { en: "answer the question" },
	"runs.ref.question": { en: "question {id} (blocker_kind human)", vars: { id: "key" } },
	"runs.ref.questionOn": { en: "question {id} on {key} (blocker_kind human)", vars: { id: "key", key: "key" } },
	"runs.rule.question": { en: "an open question with blocker_kind human: only a person can answer it" },
	"runs.ref.approval": { en: "release_approvals: no decision (RELEASE_AWAITING_APPROVAL)" },
	"runs.rule.approval": { en: "waits on approval by a releases.approve holder" },
	"runs.act.resumeRun": { en: "resume the run" },
	"runs.ref.pauseReason": { en: "pauseReason {reason}", vars: { reason: "code" } },
	"runs.ref.pausedByPerson": { en: "paused by a person" },
	"runs.rule.personPause": { en: "the run is paused, and only a person resumes this pause" },
	"runs.rule.pausedBy": { en: "paused ({reason}); the {resumer} resumes it, no deadline", vars: { reason: "code", resumer: "code" } },
	"runs.act.resumeJob": { en: "resume the job" },
	"runs.ref.jobHeld": { en: "job held: {reason}", vars: { reason: "code" } },
	"runs.rule.jobHeld": { en: "the job is held ({reason}), a hold that does not resume itself", vars: { reason: "code" } },
	"runs.act.bindCheckout": { en: "bind a checkout on the box" },
	"runs.ref.checkoutUnbound": { en: "pipeline health reads checkout_unbound (POOL_CHECKOUT_UNBOUND)" },
	"runs.rule.checkoutUnbound": { en: "every box lacks a checkout: run `forge-runner bind <slug> --path <dir>`" },
	"runs.act.answerDialog": { en: "answer the dialog {pane} is stopped on: \"{text}\"", vars: { pane: "said", text: "text" } },
	"runs.act.itsMasterPane": { en: "its master pane" },
	"runs.ref.masterDialog": { en: "master session {id} metadata.paneDialog", vars: { id: "key" } },
	"runs.rule.masterDialog": { en: "MASTER_PANE_DIALOG: the master pane is stopped on a dialog awaiting a person" },
	"runs.act.answerRun": { en: "answer the run" },
	"runs.ref.ledgerBlocked": { en: "run ledger: work blocked, blockerKind human" },
	"runs.rule.ledgerBlocked": { en: "the box reports the run blocked on a person" },
	"runs.ref.issueAt": { en: "{key} at {status}", vars: { key: "key", status: "status" } },
	"runs.rule.noTransition": { en: " (no kernel transition records when it moved there)" },
	"runs.gate.issueBusy": { en: "another session or job is live on this issue; dispatch follows" },
	"runs.gate.contractWait": { en: "CONTRACT_WAIT_UNSETTLED: waits on a contract version not yet approved" },
	"runs.gate.patternReview": { en: "PATTERN_REVIEW_PENDING: a new pattern awaits a patterns.approve reviewer" },
	"runs.gate.runnerStale": { en: "no box has beaten recently; dispatch follows once one does" },
	"runs.gate.runnerTooOld": { en: "no box runs a build that can take it; update one" },
	"runs.gate.tokenCannotReach": { en: "no box's credential reaches this project: dispatch takes it once one does" },
	"runs.rule.heldRetry": { en: "held {reason}: the release sweep retries it once jobs.retry_after_at has passed", vars: { reason: "code" } },
	"runs.rule.heldClears": { en: "held {reason}: it re-queues when its condition clears, which has no deadline", vars: { reason: "code" } },
	"runs.rule.retryCooldown": { en: "jobs.retry_after_at is in the future: dispatch skips the job until then" },
	"runs.rule.dispatchGate": { en: "pipeline health reads {gate}: {why}, which has no deadline", vars: { gate: "code", why: "said" } },
	"runs.rule.paren": { en: " ({text})", vars: { text: "text" } },
	"runs.rule.declarationRefused": { en: "the box declared this run and core refuses to admit it ({code}, {attempts} attempt(s), last {at}): {detail}", vars: { code: "code", attempts: "count", at: "instant", detail: "text" } },
	"runs.rule.running": { en: "running: its holder is working it" },
	"runs.rule.claimed": { en: "claimed: its holder has not started it" },
	"runs.who.machine": { en: "Machine" },
	"runs.act.noSlot": { en: "no free slot ({inUse} of {max} in use)", vars: { inUse: "count", max: "count" } },
	"runs.rule.noSlot": { en: "no free slot: {inUse} of {max} in use (masters/standing.slots)", vars: { inUse: "count", max: "count" } },
	"runs.act.dispatchIt": { en: "dispatch it" },
	"runs.rule.queuedMaster": { en: "queued: the project master takes it in a pass" },
	"runs.rule.queuedNothing": { en: "queued: nothing is dispatched on the run" },
	"runs.rule.lockHeld": { en: "DEPLOY_ENVIRONMENT_LOCKED at {at}: run {run} holds {environment}, deploying {subject}{since}; refused {until}", vars: { at: "instant", run: "key", environment: "name", subject: "said", since: "said?", until: "said" } },
	"runs.rule.issueParked": { en: "the issue is parked at {status} while its run is live{unrecorded}", vars: { status: "status", unrecorded: "said?" } },
	"runs.rule.blockedOn": { en: "the box reports the run blocked on {kind}{on}, which no person clears", vars: { kind: "code", on: "said?" } },
	"runs.act.actsNext": { en: "acts next" },
	"runs.rule.stuck": { en: "stuck ({rule}): the master acts next; a person may cancel it{ended}", vars: { rule: "code", ended: "said?" } },
	"runs.rule.rootEnded": { en: "; its root already ended: {rule}", vars: { rule: "said" } },
	"runs.rule.finished": { en: "finished" },
	"automation.rule.failing": { en: "failing: its owner fixes it, pauses it or takes it over" },
	"automation.rule.ownerGone": { en: "owner gone: an admin saves it to take it over" },
	"automation.rule.off": { en: "off: nothing fires until it is turned on" },
	"automation.rule.nextFire": { en: "next fire at {at}", vars: { at: "instant" } },
	"automation.rule.noNextFire": { en: "no next fire set" },
	"automation.rule.toOwner": { en: "a report a fire filed goes to its schedule owner first" },
	"automation.rule.toWriters": { en: "no schedule owner, so any member with write access triages it" },
	"automation.who.harnessTriage": { en: "Harness triage" },
	"automation.rule.harness": { en: "an issue run's harness report, triaged on Automation, Reports" },
	"automation.rule.reportsWait": { en: "{n} of its reports wait for triage: {rule}", vars: { n: "count", rule: "said" } },
	"automation.rule.running": { en: "running" },
	"automation.rule.fireWaitsOnNobody": { en: "nothing about this fire waits on a person" },
	"automation.rule.filedFeedback": { en: "filed as {key}, at {phase}", vars: { key: "key", phase: "code" } },
	"automation.rule.filedIssue": { en: "filed as {key}, at {status}", vars: { key: "key", status: "status" } },
	"automation.rule.triaged": { en: "triaged {triage}", vars: { triage: "code" } },
	"standing.keysAnd": { en: "{keys} and {last}", vars: { keys: "key", last: "key" } },
	"feedback.act.triageAfterSnooze": { en: "triage it once the snooze ends, {date}", vars: { date: "date" } },
	"feedback.rule.snoozed": { en: "{phase}: snoozed until {until}, then back to New", vars: { phase: "code", until: "instant" } },
	"feedback.rule.masterOwes": { en: "{phase}: the project's master owes a triage; feedback.approve holders may triage first", vars: { phase: "code" } },
	"feedback.rule.triagerTriages": { en: "{phase}: a holder of feedback.approve triages it", vars: { phase: "code" } },
	"feedback.act.route": { en: "route it to work" },
	"feedback.rule.noRoute": { en: "triaged with no route; a feedback.approve holder routes it" },
	"feedback.rule.carrierGone": { en: "triaged, but its carrier is gone; a feedback.approve holder reroutes it" },
	"feedback.rule.answered": { en: "resolved: answered; the reporter confirms it settled it" },
	"feedback.rule.relay": { en: "resolved without a notice; a feedback.approve holder tells the reporter" },
	"feedback.rule.verifyByRecord": { en: "resolved: after the window, Forge verifies it only if its criterion passes" },
	"feedback.rule.verifyByPerson": { en: "resolved: it names no criterion, so only a person can verify it" },
	"feedback.rule.verifyHeld": { en: "resolved: the record could not verify it: {why}", vars: { why: "text" } },
	"standing.who.nothing": { en: "Nothing" },
	"feedback.rule.nothingOwed": { en: "{phase}: nothing is owed", vars: { phase: "code" } },
	"feedback.who.theLinkedIssue": { en: "the linked issue" },
	"feedback.rule.issuesCarry": { en: "planned: its issues carry it" },
	"feedback.rule.issueCarries": { en: "planned: its issue carries it" },
	"feedback.rule.noReleaseModel": { en: "planned: {issue} {waits} at awaiting_release; no release model, so a person releases", vars: { issue: "said", waits: "agreement" } },
	"feedback.rule.approvalRequired": { en: "planned: {issue} {waits} at awaiting_release for a releases.approve holder", vars: { issue: "said", waits: "agreement" } },
	"feedback.rule.manualCut": { en: "planned: {issue} {waits} at awaiting_release for a project.admin to cut", vars: { issue: "said", waits: "agreement" } },
	"feedback.rule.newRequirement": { en: "planned: a new requirement carries it" },
	"standing.who.itsRootUnnamed": { en: "Its root" },
	"feedback.rule.duplicate": { en: "planned: the root item it duplicates carries it" },
	"feedback.rule.linkedWork": { en: "planned: the linked work carries it" },
	"feedback.rule.proposal": { en: "planned: a requirement revision proposal carries it, and a person decides it" },
	"feedback.rule.acceptance": { en: "planned: a requirements.approve holder accepts the proposed revision" },
	"feedback.rule.drafted": { en: "planned: its revision was returned to draft; its author proposes it" },
	"feedback.rule.delivery": { en: "planned: its revision is current; the delivering work carries it" },
	"feedback.who.revision": { en: "{req} r{r}", vars: { req: "key", r: "count" } },
	"standing.act.acceptRevision": { en: "accept the revision" },
	"standing.act.acceptRevisionNum": { en: "accept revision {r}", vars: { r: "count" } },
	"standing.act.proposeRevision": { en: "propose the revision" },
	"standing.act.proposeRevisionNum": { en: "propose revision {r}", vars: { r: "count" } },
	"feedback.notice.noDedupUnwritten": { en: "triage without dedup: the item's vector is not written yet" },
	"releases.rule.ended": { en: "the release has ended" },
	"forecast.event.transition": { en: "{key} moved to {status}", vars: { key: "key", status: "statusLabel" } },
	"forecast.event.filed": { en: "{key} was filed", vars: { key: "key" } },
	"forecast.event.blockerAdded": { en: "{key} now waits on {blocker}", vars: { key: "key", blocker: "key" } },
	"forecast.event.blockerEnded": { en: "{key} no longer waits on {blocker}", vars: { key: "key", blocker: "key" } },
	"forecast.event.runStarted": { en: "a run started on {key}", vars: { key: "key" } },
	"forecast.event.runStartedAny": { en: "a run started" },
	"forecast.event.runEnded": { en: "a run on {key} ended", vars: { key: "key" } },
	"forecast.event.runEndedAny": { en: "a run ended" },
	"forecast.event.none": { en: "nothing has moved in this project yet" },
	"releases.refused.notVerified": { en: "Production does not serve every change this release landed, so its close could not be proven." },
	"releases.refused.nothingRecorded": { en: "Nothing in this release was recorded as shipped, so there was nothing to close." },
	"releases.refused.allShippedEarlier": { en: "Every issue in it had already shipped in an earlier release." },
	"releases.refused.otherCommit": { en: "Production serves another commit than the one this release finished on." },
	"releases.refused.providerNotLive": { en: "A contract this release depends on is not live at its provider." },
	"releases.refused.criteriaUnearned": { en: "Some criteria of its issues have no passing verdict." },
	"releases.refused.finishErrored": { en: "Finishing the release failed with an error." },
	"releases.refused.other": { en: "The release was refused ({code}).", vars: { code: "code" } },
	"releases.rule.gated": { en: "{n} {reasons} {verb} against cutting {v}", vars: { n: "count", reasons: "agreement", verb: "agreement", v: "version" } },
	"standing.act.andMore": { en: "{act}{more}", vars: { act: "said", more: "said" } },
	"releases.rule.queuedBehindRun": { en: "the release already running finishes before {v} can be cut", vars: { v: "version" } },
	"releases.rule.adminCuts": { en: "merged issues wait at the release gate; an admin cuts the version" },
	"releases.rule.noRequest": { en: "the project requires approval before production and no request is open" },
	"releases.rule.asked": { en: "{name} asked; a holder of releases.approve approves or returns it", vars: { name: "name" } },
	"releases.rule.noneLeft": { en: "{rule}, and none is left", vars: { rule: "said" } },
	"releases.rule.returned": { en: "an admin returned it; the master answers before it asks again" },
	"releases.rule.returnedWhy": { en: "an admin returned it: {why}; the master answers before it asks again", vars: { why: "text" } },
	"releases.rule.inProgress": { en: "the release run is working on production" },
	"releases.rule.issueShipped": { en: "the issue has shipped" },
	"requirements.dedup.notChecked": { en: "dedup was not checked: the head revision's vector is {status}", vars: { status: "code" } },
	"requirements.dedup.notWritten": { en: "dedup was not checked: the head revision's vector is not written yet" },
	"requirements.history.text.noted": { en: "{text}{note}", vars: { text: "said", note: "said" } },
	"requirements.history.note.dedup": { en: " ({why})", vars: { why: "said" } },
	"requirements.history.note.ready": { en: " (ready){dedup}", vars: { dedup: "said?" } },
	"requirements.history.note.noResult": { en: " (no readiness result){dedup}", vars: { dedup: "said?" } },
	"requirements.history.note.notReady": { en: " (not ready: {failed}){dedup}", vars: { failed: "code", dedup: "said?" } },
	"requirements.history.who.forge": { en: "Forge" },
	"standing.empty": { en: "" },
	"standing.acts": { en: "{acts}", vars: { acts: "saidList" } },
	"standing.effect.designAt": { en: "{title} revision {r}", vars: { title: "name", r: "count" } },
	"standing.effect.contractAt": { en: "{contract} {v}", vars: { contract: "name", v: "version" } },
	"requirements.rule.noRunner": { en: "no runner bound, so no master acts; a person acts instead" },
	"requirements.rule.draftAuthor": { en: "an open draft revision waits on its author to propose it" },
	"requirements.rule.agentReturned": { en: "its signer returned this agent revision; the agent's master revises it" },
	"requirements.rule.agentDraft": { en: "an agent wrote this draft; its master proposes or drops it" },
	"requirements.rule.designsFirst": { en: "linked designs must be approved first (REQUIREMENT_DESIGN_UNAPPROVED); then a signer agrees" },
	"requirements.rule.unjudged": { en: "{codes} hold no passing verdict yet", vars: { codes: "key" } },
	"requirements.rule.failed": { en: "{codes} failed", vars: { codes: "key" } },
	"requirements.rule.untraced": { en: "no issue criterion traces to {codes}", vars: { codes: "key" } },
	"requirements.rule.notDelivered": { en: "every linked issue has shipped, but {parts}, so it is not delivered{undeclared}", vars: { parts: "saidList", undeclared: "said?" } },
	"requirements.rule.noJudge": { en: "; no policy names a judge, so the master judges" },
	"requirements.rule.designsFirstR": { en: "linked designs must be approved first (REQUIREMENT_DESIGN_UNAPPROVED); then a signer agrees r{r}", vars: { r: "count" } },
	"standing.who.dash": { en: "—" },
	"requirements.rule.feedbackWaits": { en: "feedback about it waits on a person to pick its route: {keys}", vars: { keys: "key" } },
	"requirements.rule.ended": { en: "the requirement is {status}", vars: { status: "code" } },
	"requirements.rule.deferred": { en: "deferred out of the current release; it waits on nobody" },
	"requirements.rule.proposed": { en: "a proposed revision waits on a sign-off" },
	"requirements.rule.unagreed": { en: "a current revision not yet agreed waits on a sign-off" },
	"requirements.rule.pinBehind": { en: "A followed design or contract has a newer approved version." },
	"requirements.rule.check": { en: "delivered at r{r}; the BA checks criteria by {date} ({days} working days){overdue}", vars: { r: "count", date: "date", days: "count", overdue: "said?" } },
	"requirements.rule.overdue": { en: ", and it is overdue" },
	"requirements.who.ba": { en: "BA" },
	"requirements.rule.breakdownWaits": { en: "a breakdown suggestion waits on a person" },
	"requirements.rule.replan": { en: "planned against an earlier revision than r{r} (REQUIREMENT_CHANGED_SINCE_PLAN)", vars: { r: "count" } },
	"requirements.rule.replanUnknown": { en: "planned against an earlier revision than r? (REQUIREMENT_CHANGED_SINCE_PLAN)" },
	"requirements.rule.breakdownDue": { en: "agreed without issues; breakdown due {date}, {days} working days after agreeing", vars: { date: "date", days: "count" } },
	"requirements.rule.noIssue": { en: "agreed with no linked issue" },
	"requirements.rule.onlyDrafts": { en: "its only live issues are drafts awaiting promotion" },
	"requirements.rule.moving": { en: "agreed and its issues are being worked" },
	"requirements.rule.parked": { en: "{keys} parked, blocking delivery; {key} waits because {rule}", vars: { keys: "key", key: "key", rule: "said" } },
	"requirements.rule.allLanded": { en: "every unshipped issue landed ({n}) and waits on release: {reason}", vars: { n: "count", reason: "said" } },
	"requirements.rule.releasesOnItsOwn": { en: "the project releases a landed change on its own" },
	"requirements.rule.queued": { en: "no issue in progress: {keys} wait for the master", vars: { keys: "key" } },
	"requirements.who.noOwner": { en: "No owner" },
	"requirements.act.assignOwner": { en: "assign one" },
	"requirements.rule.noOwner": { en: "no owner is set" },
	"requirements.rule.untouched": { en: "untouched for {days} days or more", vars: { days: "count" } },
	"requirements.rule.tracedStepChanged": { en: "the approved design changed a traced step; the assistant drafts revised criteria" },
	"requirements.rule.revisionSuggested": { en: "a traced design step changed; a suggested criteria revision awaits a person" },
	"requirements.rule.staleDraft": { en: "untouched for {days} days; the assistant asked: merge, drop or keep", vars: { days: "count" } },
	"forecast.who.whoeverReaches": { en: "Whoever can reach {device}", vars: { device: "name" } },
	"masters.who.whoeverReachesPane": { en: "Whoever can reach the master pane" },
	"masters.act.answerDialog": { en: "Answer the dialog {pane} is stopped on: \"{text}\"", vars: { pane: "said", text: "text" } },
	"masters.act.theMasterPane": { en: "the master pane" },
	"forecast.act.turnBoxOn": { en: "turn the box back on" },
	"forecast.act.unretire": { en: "return the runner to service" },
	"forecast.act.startRunner": { en: "start the runner" },
	"forecast.act.runnerOnline": { en: "bring the runner back online" },
	"forecast.act.signIn": { en: "sign the box in again" },
	"forecast.act.waitUsage": { en: "wait for the usage limit to reset" },
	"forecast.act.quarantine": { en: "wait out the quarantine or clear it" },
	"forecast.act.provision": { en: "finish provisioning the checkout" },
	"forecast.act.updateRunner": { en: "update the runner" },
	"forecast.act.bringRunnerBack": { en: "bring a runner back" },
	"forecast.reason.noRunner": { en: "no runner registered, so nothing can take its work" },
	"forecast.reason.heldDevice": { en: "{device} is {reason}{detail}", vars: { device: "name", reason: "code", detail: "said?" } },
	"forecast.reason.runnersHeld": { en: "no runner can take this project's work: {held}", vars: { held: "saidList" } },
	"forecast.reason.masterSilent": { en: "the project's master has been silent since {at}, so nothing is dispatched", vars: { at: "instant" } },
	"forecast.reason.masterSilentFromStart": { en: "the project's master has been silent since starting; nothing dispatched" },
	"forecast.act.restartMaster": { en: "restart the master" },
	"forecast.reason.masterDialog": { en: "the project's master is stopped on a dialog ({rule})", vars: { rule: "code" } },
	"forecast.act.waitOut": { en: "wait out the {reason}", vars: { reason: "code" } },
	"forecast.reason.passRefused": { en: "the master's last pass was refused ({reason}): {detail}", vars: { reason: "code", detail: "text" } },
	"forecast.act.releaseToMaster": { en: "release it to the master" },
	"forecast.reason.manualIntake": { en: "manual intake: open issues wait for a person to release them" },
	"forecast.act.breakCycle": { en: "break the cycle" },
	"forecast.reason.cycle": { en: "{key} sits on a blocks cycle, so none can start", vars: { key: "key" } },
	"forecast.act.landFirst": { en: "land first" },
	"forecast.reason.notForecast": { en: "{item} waits on {key}, which is not open work this project forecasts", vars: { item: "key", key: "key" } },
	"forecast.reason.waitsOn": { en: "waits on {key}: {reason}", vars: { key: "key", reason: "said" } },
	"forecast.act.cutNextThenApprove": { en: "cut the next version, then approve it" },
	"forecast.act.cutNext": { en: "cut the next version" },
	"forecast.reason.approval": { en: "each release needs a releases.approve holder{holders}, so no date", vars: { holders: "said?" } },
	"forecast.reason.manual": { en: "manual releases by a project.admin, so no date is forecast" },
	"forecast.reason.noProduction": { en: "no production environment, so no release carries landed changes" },
	"forecast.reason.allLanded": { en: "every included issue has landed; {reason}", vars: { reason: "said" } },
	"contracts.act.approveOrReturn": { en: "approve or return {v} · measured {measured}", vars: { v: "version", measured: "code" } },
	"contracts.rule.proposed": { en: "providedTurn: a recorded version is proposed until its approver decides it (contract/approval.ts:approverRefusal)" },
	"contracts.who.orgAdmin": { en: "An org admin" },
	"contracts.who.consumers": { en: "{n} consumers", vars: { n: "count" } },
	"contracts.act.adoptBy": { en: "adopt {v} by {date}", vars: { v: "version", date: "date" } },
	"contracts.rule.window": { en: "providedTurn: breaking version approved; a consumer still builds on an older one" },
	"contracts.act.noConsumer": { en: "no consumer yet" },
	"contracts.act.everyConsumerOn": { en: "every consumer is on {v}", vars: { v: "version" } },
	"contracts.act.behind": { en: "{n} of {total} {consumers} behind, no window open", vars: { n: "count", total: "count", consumers: "agreement" } },
	"contracts.rule.providedSteady": { en: "providedTurn: nothing is proposed or owed inside a window" },
	"contracts.act.adaptBy": { en: "adapt to {v} by {date}", vars: { v: "version", date: "date" } },
	"contracts.rule.breaking": { en: "consumedTurn: breaking version approved; one item per consumer until verified or declined" },
	"contracts.who.projectMember": { en: "A project member" },
	"contracts.act.noVersion": { en: "the provider has published no version" },
	"contracts.act.onLatest": { en: "on the latest, {v}", vars: { v: "version" } },
	"contracts.act.builtAgainst": { en: "built against {ours}; {v} is current", vars: { ours: "version", v: "version" } },
	"contracts.act.builtAgainstNone": { en: "built against no version; {v} is current", vars: { v: "version" } },
	"contracts.rule.consumedSteady": { en: "consumedTurn: no breaking item is open" },
	"workflows.act.decideNode": { en: "decide keep, rewrite or delete" },
	"workflows.rule.code": { en: "{code}", vars: { code: "code" } },
	"workflows.act.reviseToWording": { en: "revise the design to the new wording" },
	"workflows.act.reviseToContract": { en: "revise the design to the contract" },
	"workflows.act.repairToDesign": { en: "repair the build to the approved design" },
	"workflows.act.observeAgain": { en: "observe the workflow again" },
	"workflows.act.proposeRevision": { en: "propose a design revision" },
	"workflows.act.repairBuild": { en: "repair the build" },
	"workflows.act.recoverRun": { en: "recover the {state} run", vars: { state: "code" } },
	"workflows.act.decideSuggestion": { en: "accept or reject the suggestion" },
	"workflows.act.keep": { en: "propose a revision adopting the code, or build to the plan" },
	"workflows.act.rewrite": { en: "break the rewrite into issues" },
	"workflows.act.delete": { en: "break the deletion into issues" },
	"workflows.rule.decided": { en: "the node is decided {verdict}", vars: { verdict: "code" } },
	"workflows.rule.notInDesign": { en: "code outside the design awaits a decision: keep, rewrite or delete" },
	"workflows.rule.rewriteDue": { en: "due a rewrite ({rule}); keeping it is a recorded decision", vars: { rule: "code" } },
	"workflows.act.buildToPlan": { en: "build it to the plan" },
	"workflows.rule.upcoming": { en: "a planned node no code builds yet is built to the plan" },
	"workflows.act.decideInRound": { en: "decide keep or rewrite in the decision round" },
	"workflows.rule.belowThreshold": { en: "an undecided Wrong node below threshold waits on the orchestrator" },
	"designs.act.approveOrReturn": { en: "approve or return revision {r}", vars: { r: "count" } },
	"designs.rule.youDecide": { en: "revision {r} is proposed and you may decide it", vars: { r: "count" } },
	"designs.rule.approverDecides": { en: "decided by any workflow-designs.approve holder, person or agent" },
	"designs.act.repin": { en: "re-pin basedOn" },
	"designs.title.repinBatch": { en: "{n} {designs} only {need} {its} pin moved → r{r}", vars: { n: "count", designs: "agreement", need: "agreement", its: "agreement", r: "count" } },
	"designs.act.repinBatch": { en: "approve {n} pin-only {changes} → r{r}", vars: { n: "count", changes: "agreement", r: "count" } },
	"designs.rule.repinBatch": { en: "{flow} approved at r{r}; these differ only in pinned base, approved together", vars: { flow: "name", r: "count" } },
	"designs.act.revise": { en: "revise it" },
	"designs.act.reviseR": { en: "revise revision {r}", vars: { r: "count" } },
	"designs.rule.returned": { en: "returned; the project's master owes the next revision" },
	"designs.act.finish": { en: "finish and propose it" },
	"designs.rule.draft": { en: "a draft design is proposed once its master finishes drawing it" },
	"designs.rule.approved": { en: "revision {r} is approved; work that builds it may start", vars: { r: "count" } },
	"designs.rule.notUnderApproval": { en: "this workflow is not under design approval" },
	"modules.act.queued": { en: "{n} queued", vars: { n: "count" } },
	"modules.act.paused": { en: "{n} paused", vars: { n: "count" } },
	"modules.act.counts": { en: "{parts}", vars: { parts: "saidDots" } },
	"modules.act.nothingOpen": { en: "nothing open" },
	"modules.rule.quiet": { en: "Nothing here waits on you, is stuck or holds a lease" },
	"questions.rule.unheld": { en: "a run's question no item holds; answer it on Agents" },
	"designs.who.aPerson": { en: "A person" },
	"designs.act.settleMarkers": { en: "settle {n} health {markers}", vars: { n: "count", markers: "agreement" } },
	"designs.rule.needsYou": { en: "a source awaits a person, or a node awaits decision (REQ-17 BC-18)" },
	"runs.step.masterGone": { en: "opened for a resident master with no live session; nothing holds it" },
	"runs.step.masterNamed": { en: "resident master `{name}`'s own run: no step; residentMaster.lastHeartbeatAt is its heartbeat", vars: { name: "name" } },
	"runs.step.masterSession": { en: "master session {id}'s own run: no step; residentMaster.lastHeartbeatAt is its heartbeat", vars: { id: "key" } },
	"runs.step.boxOver": { en: "a box drives this over {keys} with no phase open; no step", vars: { keys: "key" } },
	"runs.step.boxOverUnnamed": { en: "a box drives this over an unnamed group, no phase open" },
	"runs.step.jobNone": { en: "no pipeline step has been stamped on this run yet" },
	"runs.step.noLane": { en: "no step stamped, and on neither the job nor run-session lane" },
	"runs.final.unclassified": { en: "failed with no FAILURE_CAUSES cause recorded, so unclassified" },
	"runs.final.failed": { en: "failed: {cause}", vars: { cause: "code" } },
	"runs.final.noStopRecord": { en: "no kernel_transitions row records who stopped it" },
	"runs.final.landedNote": { en: " (it landed at {at}, and no move to an outcome followed)", vars: { at: "instant" } },
	"runs.final.close": { en: "{close}", vars: { close: "code" } },
	"runs.final.unrecordedClose": { en: "an unrecorded close" },
	"runs.final.closedDone": { en: "the box closed the session ({close}); every issue reached an outcome", vars: { close: "said" } },
	"runs.final.noCloseRecord": { en: "no kernel_transitions row records the close of this session" },
	"runs.final.unreadable": { en: "closed ({close}); none of {keys} readable, so no outcome credited", vars: { close: "said", keys: "key" } },
	"runs.final.unreadableNone": { en: "closed ({close}); no issue readable, so no outcome credited", vars: { close: "said" } },
	"runs.final.gaveBack": { en: "closed {close}: the box gave the work back before an outcome", vars: { close: "said" } },
	"runs.final.shortOf": { en: "the session closed ({close}) with {missed}, short of an outcome", vars: { close: "said", missed: "saidSeries" } },
	"runs.final.missed": { en: "{key} at {status}{landed}", vars: { key: "key", status: "status", landed: "said?" } },
	"runs.final.runCancelled": { en: "the pipeline run is cancelled" },
	"runs.final.sessionEnded": { en: "its session ended {why}", vars: { why: "code" } },
	"runs.final.completed": { en: "the pipeline run completed" },
	"runs.final.noCompletionRecord": { en: "no kernel_transitions row records the completion of this run" },
	"runs.live.dispatchedRunning": { en: "jobs.status dispatched and its agent session running" },
	"runs.live.notAcked": { en: "jobs.status dispatched: a box took it and has not acked" },
	"runs.live.heldByMaster": { en: "jobs.held_by: a master prepared it and has not started it" },
	"runs.live.admitted": { en: "admitted, and no box or master has taken it" },
	"runs.live.starting": { en: "the run session is starting (runtimeState or ledger incarnation starting)" },
	"runs.live.sessionIs": { en: "the run session is {status}", vars: { status: "code" } },
	"runs.live.openNothing": { en: "the run is open and nothing has been dispatched on it yet" },
	"runs.live.noSession": { en: "run {status} with {n} live job(s), no live session; ISS-109 decides stuck", vars: { status: "code", n: "count" } },
	"runs.stuck.boxLive": { en: "box reports {incarnation}; core ended session {session}; pipeline_runs.status is {status}", vars: { incarnation: "code", session: "code", status: "code" } },
	"runs.stuck.rootEnded": { en: "pipeline_runs.status is still {status} while its root ended ({rule})", vars: { status: "code", rule: "said" } },
	"runs.stuck.boxExited": { en: "the box reports the process gone; core still has it running" },
	"runs.stuck.abandoned": { en: "{holder}'s claim on {key} stopped beating while the run is live", vars: { key: "key", holder: "name" } },
	"runs.stuck.claimStopped": { en: "{holder}'s claim on {key} stopped at {at} while the run is live", vars: { key: "key", holder: "name", at: "instant" } },
	"runs.stuck.claimLapsed": { en: "{holder}'s claim on {key} lapsed at {at} while the run is live", vars: { key: "key", holder: "name", at: "instant" } },
	"runs.stuck.silent": { en: "no live job; last sign ({column} at {at}) older than {mins} min", vars: { column: "code", at: "instant", mins: "count" } },
	"runs.stuck.stranded": { en: "{key} stranded at {status} ({reason}) while the run is live", vars: { key: "key", status: "status", reason: "code" } },
	"runs.stuck.lockOverdue": { en: "the {environment} deploy lock expired at {at}, unreclaimed for {mins} min", vars: { environment: "name", at: "instant", mins: "count" } },
	"runs.stuck.refusalOverdue": { en: "{environment} refused until {at}, held by run {run}; untaken {mins} min after", vars: { environment: "name", at: "instant", run: "key", mins: "count" } },
	"runs.stuck.gateOverdue": { en: "the {gate} gate was due at {at}; no attempt in {mins} min", vars: { gate: "code", at: "instant", mins: "count" } },
	"runs.stuck.clearQueued": { en: "queued: untaken, and stuck rules read started runs only" },
	"runs.stuck.clearClaimed": { en: "claimed but unstarted; the start reapers own that window" },
	"runs.stuck.clearPerson": { en: "waiting on a person is never stuck" },
	"runs.stuck.clearGate": { en: "the gate has not passed its own deadline by the stuck threshold" },
	"runs.stuck.finished": { en: "a finished run is never stuck" },
	"runs.stuck.clearMoved": { en: "the root moved within {mins} min; no lapse, disagreement or stranding", vars: { mins: "count" } },
	"runs.stuck.noReaper": { en: "no reaper times this out; the master or a person ends it" },
	"runs.stuck.after": { en: "stuck after {mins} min: {detail}", vars: { mins: "count", detail: "said" } },
	"runs.holder.foreignClaim": { en: "{holder}'s claim on {key} was taken in {tree}, not {worktree}", vars: { key: "key", holder: "name", tree: "name", worktree: "name" } },
	"runs.holder.claimIs": { en: "the claim on {key} is {verdict}: {detail}", vars: { key: "key", verdict: "code", detail: "text" } },
	"runs.holder.claimRule": { en: "issue_work_state.lease by {holder}: renewedAt + minutes", vars: { holder: "name" } },
	"runs.holder.claimRuleStopped": { en: "issue_work_state.lease by {holder}: renewedAt + minutes, stopped", vars: { holder: "name" } },
	"runs.holder.noDispatchedAt": { en: "dispatched without dispatched_at, so the ack reaper has no clock" },
	"runs.holder.reportedNoAck": { en: "reported but unacked; reapers skip it until a session runs" },
	"runs.holder.ackClock": { en: "unacked dispatches fail after {mins} min + {grace} s (dispatch_unclaimed); dispatched {at}", vars: { mins: "count", grace: "count", at: "instant" } },
	"runs.holder.sessionNotRunning": { en: "session is {status}; the heartbeat reaper fails running sessions only", vars: { status: "code" } },
	"runs.holder.awaitingInput": { en: "session awaits input, exempt from the heartbeat reaper; no silence clock" },
	"runs.holder.notReaped": { en: "the heartbeat reaper does not sweep this session kind; no silence clock" },
	"runs.holder.noBeat": { en: "session has no beat, start or update time; no silence clock" },
	"runs.holder.heartbeatClock": { en: "running sessions silent {mins} min fail (heartbeat_timeout); last beat {at}", vars: { mins: "count", at: "instant" } },
	"runs.holder.notPipeline": { en: "queued but not a pipeline session; the queue hop skips it" },
	"runs.holder.turnClock": { en: "no turn in {mins} min fails it (turn_never_reported); last beat {at}", vars: { mins: "count", at: "instant" } },
	"runs.holder.noQueueTime": { en: "the job's queued session carries no dispatch or create time" },
	"runs.holder.queueClock": { en: "unclaimed for {mins} min fails it (queue_timeout); queued {at}", vars: { mins: "count", at: "instant" } },
	"runs.holder.resultClock": { en: "stale after {mins} min without progress, plus {grace} s grace; last {at}", vars: { mins: "count", grace: "count", at: "instant" } },
	"runs.holder.boxSilentClock": { en: "the run-session reaper fails sessions silent {mins} min (run_session_box_silent); last beat {at}", vars: { mins: "count", at: "instant" } },
	"runs.holder.masterClock": { en: "master holds clear after {mins} min silent; last beat {at}", vars: { mins: "count", at: "instant" } },
	"runs.holder.noMasterRoot": { en: "no master owns this run: a root, no live master or hold" },
	"runs.holder.passUnknown": { en: "no stored master pass spans the run's opening; taking pass unknown" },
	"runs.holder.finished": { en: "a finished run holds nothing: its lease went with its end" },
	"runs.holder.runSession": { en: "Run session" },
	"runs.holder.job": { en: "{type} job", vars: { type: "code" } },
	"runs.holder.queued": { en: "no holder yet: queued, untaken by any box or master" },
	"runs.holder.parked": { en: "parked: holds no box while a person owes the next act" },
	"runs.holder.gate": { en: "no holder: the run waits on a gate with no box taken" },
	"runs.holder.nothing": { en: "no live session, job or deploy lock holds this run" },
	"runs.holder.lockRule": { en: "deploy_locks.expires_at on {environment}: the next deploy reclaims the environment after it", vars: { environment: "name" } },
	"runs.holder.noClock": { en: "no readable claim, deploy lock or beat; no clock ends the hold" },
	"runs.step.earlier": { en: "issue_work_state.step reads {step} since {since}, before this run started {started}", vars: { step: "code", since: "instant", started: "instant" } },
	"runs.step.finished": { en: "{detail}; finished runs keep no step of their own", vars: { detail: "said" } },
	"runs.title.release": { en: "Release {v}", vars: { v: "version" } },
	"runs.title.releaseBatch": { en: "Release batch" },
	"runs.title.deploy": { en: "Deploy {subject} to {environment}", vars: { subject: "name", environment: "name" } },
	"runs.title.run": { en: "Run" },
	"runs.attempt.noIssue": { en: "no issue, so no earlier runs are counted" },
	"runs.master.none": { en: "no master owns this run: no parent session or hold" },
	"runs.list.scopeRule": { en: "live: running or paused; finished: completed, failed, cancelled; stuck: live, root ended" },
	"runs.list.excludedChat": { en: "a chat's one-shot run is a conversation, not an agent run" },
	"runs.list.excludedMaster": { en: "a resident master's own run is served by `master` (masters/standing)" },
	"automation.state.off": { en: "paused: an off schedule is never claimed" },
	"automation.state.ownerGone": { en: "ownerId null: fires refused SCHEDULE_OWNER_GONE until an admin saves it" },
	"automation.state.failing": { en: "last {n} fires failed (scheduleFailStreak {limit}); a successful fire clears it", vars: { n: "count", limit: "count" } },
	"automation.state.firing": { en: "its newest fire is running" },
	"automation.state.underStreak": { en: "{n} failed in a row, under scheduleFailStreak {limit} or outside the window", vars: { n: "count", limit: "count" } },
	"automation.state.on": { en: "enabled, and its newest fire did not fail" },
	"overview.signal.ciNote": { en: "Core stores pull request checks only, so dev itself is unread." },
	"overview.signal.postMergeNote": { en: "Post-merge jobs run on GitHub; core receives and stores no event." },
	"overview.signal.noSlotsNote": { en: "No live master serves this project, so no slots declared." },
	"overview.record.waiting": { en: "{n} {issues} waiting", vars: { n: "count", issues: "agreement" } },
	"overview.record.notOnLive": { en: "{title} · {sha} not on {branch}", vars: { title: "text", sha: "code", branch: "name" } },
	"designs.gate.open": { en: "issues that build it may be dispatched: revision {r} is approved", vars: { r: "text" } },
	"designs.gate.held": { en: "building issues are held until a revision is approved; {why}", vars: { why: "said" } },
	"designs.gate.noApproval": { en: "the design has no approval yet" },
	"designs.gate.waitsApprover": { en: "revision {r} waits on its approver", vars: { r: "text" } },
	"designs.gate.status": { en: "the design is {status}", vars: { status: "code" } },
	"workflows.reconcile.unobserved": { en: "the code has not been observed against this design" },
	"workflows.reconcile.undecided": { en: "{n} marked node(s) wait on a keep, rewrite or delete decision", vars: { n: "count" } },
	"workflows.reconcile.cleaning": { en: "{n} decided node(s) wait on their build issue to close", vars: { n: "count" } },
	"workflows.reconcile.unbuilt": { en: "{n} decided node(s) have no build issue or adopting approved revision", vars: { n: "count" } },
	"workflows.reconcile.nothingMarked": { en: "no node is marked or decided, so nothing waits on a reconciliation" },
	"workflows.reconcile.unreleased": { en: "{keys} is not in a released version yet", vars: { keys: "key" } },
	"workflows.reconcile.carried": { en: "every marked node is decided and {v} carried its builds", vars: { v: "version" } },
	"workflows.reconcile.kept": { en: "every decided node is kept by an approved revision matching the code" },
	"masters.verdict.standingUnreadable": { en: "stand-down state unreadable, so the box does not assume driving" },
	"masters.verdict.stoodDownAlive": { en: "stood down, yet a pane is up; the box leaves it alone" },
	"masters.verdict.restarting": { en: "handing over to a new build ({cause}); no new work admitted", vars: { cause: "text" } },
	"masters.verdict.runnerNotAccepting": { en: "this box's runner is {status}: no new work, no master placed", vars: { status: "code" } },
	"masters.verdict.stoodDown": { en: "its owner stood this master down; none placed until stood up" },
	"masters.verdict.noTerminal": { en: "the box has no terminal multiplexer, so no master pane" },
	"masters.verdict.idleWindowWork": { en: "there was work inside the idle window" },
	"masters.verdict.childrenUnfinished": { en: "child runs whose close has not finished: {names}", vars: { names: "text" } },
	"masters.verdict.paneUnheard": { en: "no hook heard from its pane; whether a turn runs is unknown" },
	"masters.verdict.paneDoing": { en: "its pane is {doing}", vars: { doing: "code" } },
	"masters.verdict.paneReported": { en: "its pane reported `{event}` {m}m ago", vars: { event: "code", m: "count" } },
	"masters.verdict.childClosed": { en: "a child run closed {m}m ago", vars: { m: "count" } },
	"masters.verdict.noChildDeclared": { en: "it declared no child run" },
	"masters.verdict.childrenClosed": { en: "all {n} child run(s) it declared are closed{last}", vars: { n: "count", last: "said?" } },
	"masters.verdict.lastClosedAgo": { en: ", the last {m}m ago", vars: { m: "count" } },
	"masters.verdict.retire": { en: "idle: last hook `{event}` {m}m ago, nothing claimable for {idle}m, and {declared}", vars: { event: "code", m: "count", idle: "count", declared: "said" } },
	"masters.verdict.noConversation": { en: "no conversation recorded, so a successor would start cold" },
	"masters.verdict.noTranscript": { en: "conversation {id} has no transcript here, so a successor would start cold", vars: { id: "code" } },
	"masters.verdict.noHome": { en: "no home directory to find conversation {id}'s transcript, so no resume", vars: { id: "code" } },
	"masters.verdict.placementUnreadable": { en: "placement record unreadable ({why}), so fit with this box is unknown", vars: { why: "text" } },
	"masters.verdict.placementUnrecorded": { en: "no placement record, so fit with this box is unknown" },
	"masters.verdict.inputChanged": { en: "{name} (placed {placed}, now {now})", vars: { name: "code", placed: "code", now: "code" } },
	"masters.verdict.inputsChanged": { en: "what it runs on changed since it was placed: {changed}", vars: { changed: "saidList" } },
	"masters.verdict.heldNoWork": { en: "no admissible work, so a successor would have nothing to do" },
	"masters.verdict.heldRuns": { en: "it holds {n} open run(s) whose subagent may still be working: {names}", vars: { n: "count", names: "text" } },
	"masters.verdict.heldTurnUnknown": { en: "hooks and transcript cannot say whether its turn is over" },
	"masters.verdict.inherited": { en: "{name} — {ended}", vars: { name: "name", ended: "text" } },
	"masters.verdict.replaceIdle": { en: "outdated ({why}) and holds no run and no turn", vars: { why: "said" } },
	"masters.verdict.replaceInherits": { en: "outdated ({why}), idle with no working run; its successor inherits {runs}", vars: { why: "said", runs: "saidList" } },
	"masters.verdict.keptDrains": { en: "outdated ({why}); replacement waits: {held}. Draining: no new runs taken", vars: { why: "said", held: "saidList" } },
	"masters.verdict.keptCold": { en: "outdated ({why}); replacement waits: {held}. Not drained: successor would start cold", vars: { why: "said", held: "saidList" } },
	"masters.verdict.keptNudge": { en: "{kept}; nudge: {nudge}", vars: { kept: "said", nudge: "said" } },
	"masters.verdict.deafNoWork": { en: "no admissible work, so no replacement would be placed" },
	"masters.verdict.deafNoServers": { en: "the project's MCP servers are unreadable, so no replacement would be placed" },
	"masters.verdict.deafElsewhere": { en: "its conversation may run in the background, so a replacement would exit" },
	"masters.verdict.deafLeave": { en: "its pane cannot be heard and {left}", vars: { left: "said" } },
	"masters.verdict.deafReplace": { en: "its pane holds a replaced session's capability, so every declaration is refused" },
	"masters.verdict.nudgeNothingOwed": { en: "nothing is owed a pass" },
	"masters.verdict.nudgeNever": { en: "it has not been nudged about this work" },
	"masters.verdict.nudgeLimitPassed": { en: "it sits behind its account limit and the refresh window has passed" },
	"masters.verdict.nudgeLimitInside": { en: "it sits behind its account limit and was asked inside the window" },
	"masters.verdict.nudgeChangedOpen": { en: "the work changed and its pass is still open" },
	"masters.verdict.nudgeChanged": { en: "the work changed since its last nudge" },
	"masters.verdict.nudgeRetry": { en: "its last nudge read {since} and the refresh window has passed", vars: { since: "code" } },
	"masters.verdict.nudgeRead": { en: "its last nudge read {since}", vars: { since: "code" } },
	"masters.verdict.nothingClaimable": { en: "it has nothing claimable and no pane of its own running" },
	"masters.verdict.conversationElsewhere": { en: "its pane exited: a background process runs its conversation; replacing would repeat" },
	"masters.verdict.conversationUnaskable": { en: "its pane exited over a background session; the process table is unreadable" },
	"masters.verdict.placeResume": { en: "work waits; resuming conversation {id}", vars: { id: "code" } },
	"masters.verdict.placeColdNone": { en: "work waits; starting cold, as no conversation is recorded for it" },
	"masters.verdict.placeColdNoTranscript": { en: "work waits; starting cold, conversation {id} has no transcript", vars: { id: "code" } },
	"masters.refusal.slotsUndeclared": { en: "send maxJobPanes, a whole number from 1 to {max} (runner max_job_panes); core holds no default (runner {version})", vars: { max: "count", version: "said" } },
	"masters.refusal.versionUnknown": { en: "version unknown" },
	"masters.refusal.passName": { en: "the {verb} pass started {at}{on}", vars: { verb: "code", at: "instant", on: "said?" } },
	"masters.refusal.passOn": { en: " on {key}", vars: { key: "key" } },
	"masters.refusal.passAlreadyOpen": { en: "this master already has {pass} open, id {id}; the next opens after it ends ({settle})", vars: { pass: "said", id: "code", settle: "code" } },
	"masters.refusal.passOpenNow": { en: " The pass open now is {pass}, id {id}.", vars: { pass: "said", id: "code" } },
	"masters.refusal.noPassOpen": { en: " No pass is open; open one with {call} first.", vars: { call: "code" } },
	"masters.refusal.passEnded": { en: "{pass} ended {at}, and a closed pass is final, so this settle changed nothing.{now}", vars: { pass: "said", at: "instant", now: "said" } },
	"masters.refusal.noSuchPass": { en: "this master has no pass {id}.{now}", vars: { id: "code", now: "said" } },
	"masters.refusal.sessionEnded": { en: "this master session is {status}; register again (POST /api/devices/me/master-session), then open the pass", vars: { status: "code" } },
	"masters.refusal.slotsNotDeclared": { en: "{device} has not declared max_job_panes and core holds no default, so the cap is unknown", vars: { device: "name" } },
	"runs.group.job": { en: "a job-lane run carries its one issue in its own column" },
	"runs.group.master": { en: "a resident master's run holds no group; dispatched issues get their own" },
	"runs.group.system": { en: "this run was not opened over a group of issues" },
	"runs.group.unrecoverable": { en: "opened before groups were recorded; every issue given back, so group unrecoverable" },
	"onboarding.hint.designOne": { en: "{n} design", vars: { n: "count" } },
	"onboarding.hint.designMany": { en: "{n} designs", vars: { n: "count" } },
	"onboarding.hint.askForDesigns": { en: "Ask for designs" },
	"onboarding.hint.contextUnapproved": { en: "System context not approved yet." },
	"onboarding.hint.contextDrafted": { en: "System-context design drafted; approve it in Workflows, or let the agent continue." },
	"onboarding.hint.noContext": { en: "No system context yet." },
	"onboarding.hint.agentCan": { en: "The agent can read the code, draft key designs and ask questions." },
	"onboarding.hint.openQuestions": { en: "Open questions {n}{waiting}", vars: { n: "count", waiting: "said?" } },
	"onboarding.hint.waitingDays": { en: " · waiting {n} days", vars: { n: "count" } },
	"onboarding.hint.readAndDrafted": { en: "The agent read the code and drafted {designs} · {tail}", vars: { designs: "said", tail: "said" } },
	"onboarding.hint.answerQuestions": { en: "Answer the questions" },
	"onboarding.hint.onboardingLead": { en: "Onboarding:" },
	"onboarding.hint.followUp": { en: "follow-up round waits on you · {tail}", vars: { tail: "said" } },
	"onboarding.hint.continue": { en: "Continue onboarding" },
	"onboarding.hint.waitsGate": { en: "Waits on the {gate} gate; the project works meanwhile.", vars: { gate: "code" } },
	"onboarding.hint.waitingOnMachine": { en: "Waiting on {who}{act}; the project works meanwhile.", vars: { who: "said", act: "said?" } },
	"onboarding.hint.colonAct": { en: ": {act}", vars: { act: "said" } },
	"onboarding.hint.waitsOn": { en: "Waits on {who}{act}; the project works meanwhile.", vars: { who: "said", act: "said?" } },
	"onboarding.hint.toAct": { en: " to {act}", vars: { act: "said" } },
	"onboarding.hint.jobQueued": { en: "The analysis job is queued for a runner; the project works meanwhile." },
	"onboarding.hint.jobRunning": { en: "One analysis job is running; the project works meanwhile." },
	"onboarding.hint.openOnboarding": { en: "Open onboarding" },
	"onboarding.hint.done": { en: "Onboarding done." },
	"onboarding.hint.waitApproval": { en: "{designs} wait on your approval.", vars: { designs: "said" } },
	"onboarding.hint.updating": { en: "Onboarding: updating designs." },
	"onboarding.hint.reading": { en: "Onboarding: reading the code." },
	"onboarding.hint.failed": { en: "Onboarding analysis failed." },
	"onboarding.hint.mapStays": { en: "The last code map stays." },
	"onboarding.hint.askReanalysis": { en: "Ask for a re-analysis" },
	"onboarding.hint.inProgress": { en: "Onboarding in progress." },
	"onboarding.hint.drafted": { en: "{designs} drafted.", vars: { designs: "said" } },
	"onboarding.hint.waitingAnalysis": { en: "Waiting for the analysis." },
	"workflows.marker.reworded": { en: "{key} reworded in r{since} after design r{approved} was approved", vars: { key: "key", since: "count", approved: "count" } },
	"workflows.marker.contractBreaking": { en: "{contract} v{v} is breaking; the baseline pins v{pinned}", vars: { contract: "name", v: "version", pinned: "version" } },
	"workflows.marker.builtBehind": { en: "built against r{built}, the step changed in r{changed}", vars: { built: "count", changed: "count" } },
	"workflows.marker.drift": { en: "the code moved under this step at {sha}: {why}", vars: { sha: "code", why: "said" } },
	"workflows.marker.changesStep": { en: "r{r} changes this step", vars: { r: "count" } },
	"workflows.marker.changesLine": { en: "r{r} changes this line", vars: { r: "count" } },
	"workflows.marker.verdictFail": { en: "{key} criterion {n} failed{why}", vars: { key: "key", n: "count", why: "said?" } },
	"workflows.marker.colonWhy": { en: ": {why}", vars: { why: "said" } },
	"workflows.marker.reopened": { en: "{key} was reopened and is not closed again", vars: { key: "key" } },
	"workflows.marker.removesStep": { en: "r{r} removes this step", vars: { r: "count" } },
	"workflows.marker.rewires": { en: "r{r} rewires this line to {to}", vars: { r: "count", to: "name" } },
	"workflows.marker.removesLine": { en: "r{r} removes this line", vars: { r: "count" } },
	"workflows.marker.unbuilt": { en: "no code builds this yet (observed at {sha})", vars: { sha: "code" } },
	"workflows.marker.diverged": { en: "the code differs from the plan in {aspects}", vars: { aspects: "code" } },
	"workflows.marker.observedOnly": { en: "the code holds this, the design does not" },
	"requirements.history.kind.Revision": { en: "Revision" },
	"requirements.history.kind.Decision": { en: "Decision" },
	"requirements.history.kind.Question": { en: "Question" },
	"requirements.history.kind.Answer": { en: "Answer" },
	"requirements.history.kind.Suggestion": { en: "Suggestion" },
	"requirements.history.kind.Agreed": { en: "Agreed" },
	"requirements.history.kind.Returned": { en: "Returned" },
	"requirements.history.kind.Status": { en: "Status" },
	"requirements.history.kind.Record": { en: "Record" },
	"requirements.history.kind.Picture": { en: "Picture" },
	"needsYou.title.designProposed": { en: "{title} · revision {revision} proposed", vars: { title: "said", revision: "count" } },
	"needsYou.title.question": { en: "A question a run asked" },
	"needsYou.title.release": { en: "Release {version}", vars: { version: "version" } },
	"integrations.health.both": { en: "{first} {second}", vars: { first: "said", second: "said" } },
	"integrations.health.unknownError": { en: "unknown error" },
	"integrations.health.connectedTo": { en: "Connected to {name}", vars: { name: "name" } },
	"integrations.health.timedOut": { en: "healthcheck timed out after {seconds}s", vars: { seconds: "count" } },
	"integrations.health.crashed": { en: "healthcheck crashed: {why}", vars: { why: "said" } },
	"integrations.health.github.noCredential": { en: "this connection holds no GitHub App credential" },
	"integrations.health.github.notInstalled": { en: "the App is not installed for this binding" },
	"integrations.health.github.noRepo": { en: "no owner/repo configured for this binding" },
	"integrations.health.github.notPermitted": { en: "App lacks permission on {repository} (HTTP 403): grant it on the installation", vars: { repository: "text" } },
	"integrations.health.github.notAmong": { en: "{repository} is not among the repositories this App was installed on", vars: { repository: "text" } },
	"integrations.health.github.http": { en: "GitHub returned HTTP {status}", vars: { status: "code" } },
	"integrations.health.github.noWebhook": { en: "{repository} answers, but this App has no webhook address: no deliveries arrive", vars: { repository: "text" } },
	"integrations.health.github.webhookOff": { en: "{repository} answers, but the App webhook at {url} is off; re-enable it", vars: { repository: "text", url: "text" } },
	"integrations.health.gitlab.noToken": { en: "this connection holds no GitLab access token" },
	"integrations.health.gitlab.unrecognised": { en: "GitLab does not recognise this token (HTTP 401 on {path})", vars: { path: "text" } },
	"integrations.health.gitlab.needsScope": { en: "GitLab refuses {path} (HTTP 403): needs {scope} scope and Developer role", vars: { path: "text", scope: "code" } },
	"integrations.health.gitlab.notVisible": { en: "this token cannot see {project} on {base} (HTTP 404)", vars: { project: "text", base: "text" } },
	"integrations.health.gitlab.http": { en: "GitLab returned HTTP {status} for {path}", vars: { status: "code", path: "text" } },
	"integrations.health.gitlab.noProject": { en: "token valid (as {user}), but this binding names no GitLab project", vars: { user: "said" } },
	"integrations.health.gitlab.unnamedUser": { en: "an unnamed user" },
	"integrations.health.gitlab.hooksUnread": { en: "GitLab answered HTTP {status} listing webhooks; that needs the Maintainer role", vars: { status: "code" } },
	"integrations.health.gitlab.noHook": { en: "no GitLab webhook; add one at {url} with the binding's secret token", vars: { url: "said" } },
	"integrations.health.gitlab.hookPath": { en: "this core's /api/webhooks/in/<project slug>" },
	"integrations.health.gitlab.hookMissing": { en: "the GitLab webhook at {url} does not send {events}; tick them", vars: { url: "text", events: "text" } },
	"integrations.health.autoflow.noToken": { en: "no Autoflow access token configured" },
	"integrations.health.autoflow.mintHint": { en: "no refresh token: sign in at {base} via {mcp}; store the token", vars: { base: "text", mcp: "text" } },
	"integrations.health.autoflow.mintHintShop": { en: "no refresh token: sign in at {base} via {mcp}, pick site \"{shop}\"", vars: { base: "text", mcp: "text", shop: "name" } },
	"integrations.health.autoflow.expired": { en: "Autoflow access token expired and no refresh token is stored ({reason}); {hint}", vars: { reason: "code", hint: "said" } },
	"integrations.health.autoflow.refused": { en: "Autoflow refused the access token ({why}); {hint}", vars: { why: "said", hint: "said" } },
	"integrations.health.autoflow.http": { en: "Autoflow API error (HTTP {status}) at {url}", vars: { status: "code", url: "text" } },
	"integrations.health.autoflow.gqlError": { en: "Autoflow answered apiKeyContext with an error: {why}", vars: { why: "said" } },
	"integrations.health.autoflow.sites": { en: "the token resolves to {n} sites; Autoflow tokens are for one; {hint}", vars: { n: "count", hint: "said" } },
	"integrations.health.autoflow.otherSite": { en: "token minted for site \"{site}\", binding names shop \"{shop}\"; {hint}", vars: { site: "said", shop: "name", hint: "said" } },
	"integrations.health.autoflow.noSlug": { en: "(no slug)" },
	"integrations.health.autoflow.valid": { en: "Autoflow access token is valid" },
	"integrations.health.autoflow.refreshRefused": { en: "Autoflow refresh refused ({reason}); sign in again at {base} via MCP and store new tokens and client id", vars: { reason: "code", base: "text" } },
	"integrations.health.sentry.noHost": { en: "no Sentry host configured" },
	"integrations.health.sentry.noToken": { en: "no Sentry auth token configured" },
	"integrations.health.sentry.authenticated": { en: "Authenticated — {n} organization(s) accessible", vars: { n: "count" } },
	"integrations.health.sentry.valid": { en: "Sentry auth token is valid" },
	"integrations.health.epodsystem.noKey": { en: "no Epodsystem API key configured" },
	"integrations.health.epodsystem.invalidKey": { en: "invalid Epodsystem API key" },
	"integrations.health.epodsystem.http": { en: "Epodsystem API error (HTTP {status})", vars: { status: "code" } },
	"integrations.health.epodsystem.valid": { en: "Epodsystem API key is valid" },
	"integrations.health.rocketchat.noServer": { en: "no Rocket.Chat serverUrl configured" },
	"integrations.health.rocketchat.noBot": { en: "no Rocket.Chat bot credentials configured" },
	"integrations.health.rocketchat.rejected": { en: "Rocket.Chat rejected the bot credential (HTTP {status})", vars: { status: "code" } },
	"integrations.health.rocketchat.http": { en: "Rocket.Chat /api/v1/me returned HTTP {status}", vars: { status: "code" } },
	"integrations.health.rocketchat.notOk": { en: "Rocket.Chat /api/v1/me not ok" },
	"integrations.health.coolify.forbidden": { en: "Coolify refused {route} (HTTP 403): token lacks {missing}; widen it in Coolify", vars: { route: "said", missing: "said" } },
	"integrations.health.coolify.theRoute": { en: "the requested route" },
	"integrations.health.coolify.ability": { en: "the {ability} ability ({token})", vars: { ability: "code", token: "code" } },
	"integrations.health.coolify.theAbility": { en: "the ability that route requires" },
	"integrations.health.coolify.noTargets": { en: "no deploy targets configured" },
	"integrations.health.coolify.reached": { en: "Reached {name}", vars: { name: "text" } },
	"integrations.health.coolify.reachedMany": { en: "Reached {n} resources: {names}", vars: { n: "count", names: "text" } },
	"designs.rule.baseUnapprovedAt": { en: "r{r} builds on {bases}; its writer must re-pin basedOn before approval", vars: { r: "count", bases: "saidList" } },
	"designs.base.stale": { en: "{flow} r{r}, which is approved at r{approved} now", vars: { flow: "name", r: "count", approved: "count" } },
	"designs.base.unapproved": { en: "{flow} r{r}, which is not approved", vars: { flow: "name", r: "count" } },
	"designs.base.missing": { en: "{flow}, which is no workflow of this project", vars: { flow: "name" } },
	"pulse.gap.cut": { en: "{base} is {ahead} commits ahead of {live}; only {listed} read, rest unplaced", vars: { base: "name", ahead: "count", live: "name", listed: "count" } },
	"pulse.gap.lateOne": { en: "1 closed issue merged after the {at} reading; the next places it", vars: { at: "instant" } },
	"pulse.gap.lateMany": { en: "{n} closed issues merged after the {at} reading; the next places them", vars: { n: "count", at: "instant" } },
	"pulse.gap.ownerlessOne": { en: "1 commit waiting on {base} belongs to no issue", vars: { base: "name" } },
	"pulse.gap.ownerlessMany": { en: "{n} commits waiting on {base} belong to no issue", vars: { n: "count", base: "name" } },
	"pulse.gap.all": { en: "{parts}", vars: { parts: "saidList" } },
	"designs.reason.repinOnly": { en: "Pin-only, act {act} (\"{actWords}\" on {flow}): {pins}; fingerprint {fp} matches r{r}", vars: { act: "code", actWords: "said", flow: "name", pins: "text", fp: "code", r: "count" } },
	"designs.reason.pinOnlyKernel": { en: "Approved by Forge: only pins changed from r{r} ({pins}); fingerprint {fp} matches", vars: { r: "count", pins: "text", fp: "code" } },
} as const satisfies Record<string, SaidEntry>;
