// The registry of what core says (`said.ts`): every sentence key, its English template and the kind
// of each value it carries. Core builds its English text from these templates, so the text and the
// structured form cannot disagree; a reader in another language holds its own template per key
// (web-v2 `product-copy.json`), and a contract test refuses a key one language lacks.

import type { SaidEntry } from "./said.js";

export const SAID = {
	"standing.text": { en: "{text}", vars: { text: "text" } },
	"standing.who.named": { en: "{name}", vars: { name: "name" } },
	"standing.who.namesMore": { en: "{names} +{n}", vars: { names: "name", n: "count" } },
	"standing.act.none": { en: "" },
	"feedback.notice.agent": { en: "The reporter is an agent, which has no bell: tell it where it listens." },
	"feedback.notice.autoVerified": { en: "Verified automatically after {n} days with no reply", vars: { n: "count" } },
	"feedback.notice.before": { en: "Shipped before release notices existed on this project ({date}).", vars: { date: "date" } },
	"feedback.told.message": { en: "a message from {by}", vars: { by: "name" } },
	"feedback.told.messageUnnamed": { en: "a message to the reporters" },
	"feedback.told.relayed": { en: "{by} told them outside Forge", vars: { by: "name" } },
	"feedback.told.relayedUnnamed": { en: "a member told them outside Forge" },
	"feedback.act.tellNow": { en: "Tell the reporter now" },
	"feedback.notice.noDedup": { en: "triage without dedup: the item's vector is {status}", vars: { status: "code" } },
	"feedback.notice.noRelease": { en: "No release carries it, so none told the reporter: tell them yourself." },
	"feedback.notice.silent": { en: "{release} shipped it and sent the reporter no notice.", vars: { release: "version" } },
	"feedback.notice.turnedOff": { en: "The reporter has turned this notice off, so it reached nobody: tell them yourself." },
	"integrations.detail.disabled": { en: "integration disabled" },
	"integrations.detail.lastHealth": { en: "last health: {status}", vars: { status: "health" } },
	"integrations.detail.lastHealthWhy": { en: "last health: {status} — {detail}", vars: { status: "health", detail: "text" } },
	"integrations.detail.localPath": { en: "a local path no host serves: Forge cannot read its commits, merge into it or compare branches, so a release cannot tell what already shipped. Its head is read from a runner's bound checkout; declare the hosted repository to read the rest" },
	"integrations.detail.neverGithub": { en: "Never checked — run Test connection to probe the App installation and the repository." },
	"integrations.detail.neverGitlab": { en: "Never checked — run Test connection to probe the token and the project webhook." },
	"integrations.detail.neverTested": { en: "never test-connected" },
	"integrations.detail.noRepository": { en: "the project document declares no repository" },
	"integrations.detail.noneConfigured": { en: "no {provider} integration configured", vars: { provider: "name" } },
	"integrations.detail.readThrough": { en: "read through {provider} — last health: {status}", vars: { provider: "name", status: "health" } },
	"integrations.detail.readThroughNever": { en: "read through {provider} — never health-checked", vars: { provider: "name" } },
	"integrations.detail.switchedOff": { en: "the {provider} binding that reaches it is switched off: Forge cannot read its commits, merge into it or compare branches, so a release cannot tell what already shipped", vars: { provider: "name" } },
	"integrations.detail.unreachedBind": { en: "no source host binding reaches {host}: Forge cannot read its commits, merge into it or compare branches, so a release cannot tell what already shipped. Bind a source host connection serving {host} to fix it", vars: { host: "name" } },
	"integrations.detail.unreachedConnect": { en: "no source host binding reaches {host}: Forge cannot read its commits, merge into it or compare branches, so a release cannot tell what already shipped. Connect {provider} to fix it", vars: { host: "name", provider: "name" } },
	"integrations.row.neverChecked": { en: "never health-checked" },
	"issues.blocker.actAnswer": { en: "Answer it" },
	"issues.blocker.actOpenBlocker": { en: "Open blocking issue" },
	"issues.blocker.actResumeAt": { en: "Resume at {status}", vars: { status: "statusLabel" } },
	"issues.blocker.actResumeRun": { en: "Resume run" },
	"issues.blocker.answered": { en: "The question this issue asked has an answer on the thread." },
	"issues.blocker.boxReads": { en: "Its question was answered, and a box registered to read that answer back." },
	"issues.blocker.designMany": { en: "Blocked by {keys}, which deliver designs not yet approved: {holds}.", vars: { keys: "key", holds: "text" } },
	"issues.blocker.designOne": { en: "Blocked by {keys}, which delivers a design not yet approved: {holds}.", vars: { keys: "key", holds: "text" } },
	"issues.blocker.finishBlockers": { en: "Finish the blocking issue(s) first." },
	"issues.blocker.landedMany": { en: "Blocked by {keys}, which have landed and wait on a judge.", vars: { keys: "key" } },
	"issues.blocker.landedOne": { en: "Blocked by {keys}, which has landed and waits on a judge.", vars: { keys: "key" } },
	"issues.blocker.noLeftStatus": { en: "Its question was answered, and nothing recorded the status this park left, so the answer could not return it." },
	"issues.blocker.noResumeAt": { en: "Nothing says where this issue picks up again — Move anyway… in the status menu lists every move." },
	"issues.blocker.noResumeFromHold": { en: "Nothing says where this issue picks up again — the status menu lists every status it may return to." },
	"issues.blocker.openMany": { en: "Blocked by {n} open issues.", vars: { n: "count" } },
	"issues.blocker.openOne": { en: "Blocked by 1 open issue." },
	"issues.blocker.otherQuestion": { en: "Its question was answered, and another question on it is still open ({ids}).", vars: { ids: "text" } },
	"issues.blocker.owesDecision": { en: "This issue is waiting for a decision — a judgement only a person can make." },
	"issues.blocker.owesInformation": { en: "This issue is waiting for information — an answer to a question." },
	"issues.blocker.owesResource": { en: "This issue is waiting for something only a person can supply — an account, a credential, or data." },
	"issues.blocker.paused": { en: "The issue is paused." },
	"issues.blocker.refused": { en: "Its question was answered, and returning it to work was refused: {code} — {detail}", vars: { code: "code", detail: "text" } },
	"issues.blocker.sentToRun": { en: "Its question was answered, and the answer went to the run that asked (session {id}).", vars: { id: "text" } },
	"issues.blocker.staged": { en: "Its question was answered; this project is not autonomous, so an answer moves nothing." },
	"issues.blocker.stillWaits": { en: "Its question was answered, and the answer says it still waits: {why}", vars: { why: "text" } },
	"issues.blocker.stopped": { en: "This issue is stopped until a person acts." },
	"issues.blocker.unreadable": { en: "What it waits on could not be read — read the thread." },
	"issues.blocker.unrecorded": { en: "Its question was answered, and nothing recorded what the answer did to it." },
	"issues.blocker.waitsOnKey": { en: "Its question was answered, and the answer says it still waits on {key}: {why}", vars: { key: "key", why: "text" } },
	"issues.blocker.whoAnswered": { en: "Resume it where it stopped once the answer is enough to go on." },
	"issues.blocker.whoBoxReads": { en: "The run on that box moves the issue on once it reads the answer." },
	"issues.blocker.whoDecision": { en: "Whoever owns the call decides, then resumes it where it stopped." },
	"issues.blocker.whoDesignMany": { en: "The design approver decides the revision {keys} deliver; this issue is released once it is approved.", vars: { keys: "key" } },
	"issues.blocker.whoDesignOne": { en: "The design approver decides the revision {keys} delivers; this issue is released once it is approved.", vars: { keys: "key" } },
	"issues.blocker.whoInformation": { en: "Anyone on the project can answer it; the question is below." },
	"issues.blocker.whoLandedMany": { en: "A judge records a verdict on each criterion of {keys}; this issue is released once they pass.", vars: { keys: "key" } },
	"issues.blocker.whoLandedOne": { en: "A judge records a verdict on each criterion of {keys}; this issue is released once it passes.", vars: { keys: "key" } },
	"issues.blocker.whoNamesWhere": { en: "A person names where it goes. Resume it from the status menu once it can go on." },
	"issues.blocker.whoOtherQuestion": { en: "It moves on once that question is answered." },
	"issues.blocker.whoPaused": { en: "An operator can resume it when the work is wanted again." },
	"issues.blocker.whoRefused": { en: "Clear what the refusal names, then move it on. Resume it from the status menu once it can go on." },
	"issues.blocker.whoResource": { en: "Supply it, then resume it where it stopped." },
	"issues.blocker.whoResumes": { en: "A person resumes it where it stopped. Resume it from the status menu once it can go on." },
	"issues.blocker.whoRunReads": { en: "That run moves the issue on once it reads the answer." },
	"issues.blocker.whoSettles": { en: "{key} settles first; its blocks edge holds this issue until then.", vars: { key: "key" } },
	"issues.blocker.whoWaitOver": { en: "A person resumes it once that wait is over. Resume it from the status menu once it can go on." },
	"issues.gate.issue_busy.detail": { en: "Another job is already active on this issue." },
	"issues.gate.issue_busy.who": { en: "Wait for the active run to finish." },
	"issues.gate.job_held_clears.detail": { en: "A step is held: it could not run and is waiting for the condition to clear." },
	"issues.gate.job_held_clears.who": { en: "No action — it resumes itself, and alerts if the hold outlives the condition." },
	"issues.gate.job_held_stays.detail": { en: "A step is held: it could not run, and this hold does not clear on its own." },
	"issues.gate.job_held_stays.who": { en: "Fix the cause, then cancel the step — the issue can only move on once it is cancelled." },
	"issues.gate.retry_cooldown.detail": { en: "The step failed and is waiting out a cooldown before its next attempt." },
	"issues.gate.retry_cooldown.who": { en: "No action — the retry fires itself. If the attempts keep failing, read the step's error rather than waiting." },
	"issues.gate.run_not_running.detail": { en: "The step is queued, but its pipeline run is paused or already closed — nothing will dispatch it." },
	"issues.gate.run_not_running.who": { en: "Resume the run (or cancel it and re-open the issue for a fresh one)." },
	"issues.gate.runner_stale.detail": { en: "No runner is online for this project — every host is offline, stale, or rate-limited." },
	"issues.gate.runner_stale.who": { en: "Bring a runner back (check the Runners tab); the step dispatches on the next tick." },
	"issues.gate.runner_too_old.detail": { en: "Every online runner for this project is running a build too old to claim work." },
	"issues.gate.runner_too_old.who": { en: "Update the runner on that host; the step dispatches on the next tick once it reports the new version." },
	"issues.pause.at": { en: " at {at}", vars: { at: "text" } },
	"issues.pause.byOperator": { en: "{base} An operator paused it.", vars: { base: "said" } },
	"issues.pause.heldBy": { en: "{base} It is held by {kind}{at}.", vars: { base: "said", kind: "text", at: "said?" } },
	"issues.pause.machine.detail": { en: "The pipeline run for this issue is paused, waiting for the condition that paused it to clear." },
	"issues.pause.machine.who": { en: "No action — it resumes itself once the condition clears." },
	"issues.pause.operator.detail": { en: "The pipeline run for this issue is paused. No step will dispatch while it is, whatever this issue's status says." },
	"issues.pause.operator.who": { en: "Resume the run — nothing else will. Cancel it instead if the work should not continue." },
	"issues.pause.sweeper.detail": { en: "The pipeline run for this issue is paused for a reason this build no longer has code for." },
	"issues.pause.sweeper.who": { en: "No action — the sweeper frees it on its next tick. Resume it by hand only if it is still paused after that." },
	"issues.rule.admitted": { en: "admitted and nothing withholds it, so the project's master owes it a run; reading whether it is real is the first thing that master's pass does with it, not a gate before it" },
	"issues.rule.approval": { en: "every criterion passed; this project requires a person to approve each release, once per release on Releases (Cut the version, then Approve release), never once per issue" },
	"issues.rule.approved": { en: "the plan checkpoint holds; the next run goes straight to build" },
	"issues.rule.blocked": { en: "a live blocks edge from {key}, not yet settled", vars: { key: "key" } },
	"issues.rule.blockedDesign": { en: "a live blocks edge from {key}, which delivers a design: {design}; it settles once that revision is approved", vars: { key: "key", design: "name" } },
	"issues.rule.blockedLanded": { en: "a live blocks edge from {key}, which has landed and is not settled until a judge passes every criterion", vars: { key: "key" } },
	"issues.rule.criteriaStale": { en: "{n} of {total} criteria have no verdict that passes now, such as one judged on a storefront draft the source has moved past or cannot read back; the release hold keeps it until a run judges them again", vars: { n: "count", total: "count" } },
	"issues.rule.designReturned": { en: "its approver returned design {flow} revision {r}, drawn under this issue: what it owes is the revised design, which a run writes and proposes again, not a judgement of what landed", vars: { flow: "name", r: "count" } },
	"issues.rule.draft": { en: "a draft is not work until a person accepts it" },
	"issues.rule.ended": { en: "the issue is {status}", vars: { status: "status" } },
	"issues.rule.landed": { en: "the change landed and the issue stands at `{status}`: the run that claims it next judges what landed and moves it to `awaiting_release` rather than building it", vars: { status: "status" } },
	"issues.rule.leaseHeld": { en: "lease held by {holder}", vars: { holder: "name" } },
	"issues.rule.leaseHeldSession": { en: "lease held by a run session that has not ended" },
	"issues.rule.needsInfo": { en: "parked at needs_info: a person owes the answer; it wakes the master" },
	"issues.rule.noApproval": { en: "every criterion passed; the project releases without an approval" },
	"issues.rule.noHolder": { en: "in_progress, but no lease is live and no job or run is in flight" },
	"issues.rule.noNote": { en: "no release note: a release refuses to carry an issue without one (RELEASE_RECORD_MISSING), and writing it is the master's act, which it is told on its next pass" },
	"issues.rule.parked": { en: "a run parked it on_hold: {why}; the master resumes it once that clears", vars: { why: "said" } },
	"issues.rule.parkedAsked": { en: "a run parked it on_hold and asked a question only a person can answer: {why}", vars: { why: "said" } },
	"issues.rule.parkedBehind": { en: "a run parked it on_hold behind {key}, which still holds it: {why}", vars: { key: "key", why: "said" } },
	"issues.rule.personPaused": { en: "a person paused it; a person resumes it" },
	"issues.rule.queued": { en: "a job is queued on it and no run session holds it yet" },
	"issues.rule.releaseRunning": { en: "a release run holds it" },
	"issues.rule.reopen": { en: "sent back with a reason; a master takes it again" },
	"issues.rule.runAsked": { en: "a run asked a question only a person can answer" },
	"issues.rule.withheld": { en: "{code}: {detail} No master is handed it until then.", vars: { code: "code", detail: "text" } },
	"issues.standing.act.answer": { en: "answer a question" },
	"issues.standing.act.answerOther": { en: "answer the other question" },
	"issues.standing.act.approveContract": { en: "approve a contract version" },
	"issues.standing.act.approveDesign": { en: "approve the design" },
	"issues.standing.act.approveOnReleases": { en: "Approve release on Releases" },
	"issues.standing.act.buildNext": { en: "build next" },
	"issues.standing.act.cameBack": { en: "came back" },
	"issues.standing.act.decide": { en: "make a decision" },
	"issues.standing.act.declarePolicy": { en: "declare the policy" },
	"issues.standing.act.declarePolicyState": { en: "declare its policy state" },
	"issues.standing.act.designApproval": { en: "design approval" },
	"issues.standing.act.dispatch": { en: "dispatch a run" },
	"issues.standing.act.dropped": { en: "dropped" },
	"issues.standing.act.judgeAgain": { en: "judge it again" },
	"issues.standing.act.landedClaim": { en: "landed · claim it and judge what landed" },
	"issues.standing.act.landedWaitsJudge": { en: "landed, waits on a judge" },
	"issues.standing.act.moveOn": { en: "move it on" },
	"issues.standing.act.moveOnRefused": { en: "move it on: {code}", vars: { code: "code" } },
	"issues.standing.act.needsPerson": { en: "needs a person" },
	"issues.standing.act.nextRelease": { en: "next release" },
	"issues.standing.act.noLiveRun": { en: "in progress with no live run" },
	"issues.standing.act.notStarted": { en: "not started" },
	"issues.standing.act.paused": { en: "paused" },
	"issues.standing.act.readAnswer": { en: "read the answer" },
	"issues.standing.act.readAnswerBack": { en: "read the answer back" },
	"issues.standing.act.rerun": { en: "re-run after reopen" },
	"issues.standing.act.resume": { en: "resume it" },
	"issues.standing.act.resumeOnce": { en: "resume once: {why}", vars: { why: "said" } },
	"issues.standing.act.reviseDesign": { en: "revise design {flow} · revision {r} returned", vars: { flow: "name", r: "count" } },
	"issues.standing.act.running": { en: "running" },
	"issues.standing.act.shipped": { en: "shipped" },
	"issues.standing.act.step": { en: "{step}", vars: { step: "step" } },
	"issues.standing.act.stepFor": { en: "{step} · {n} min", vars: { step: "step", n: "count" } },
	"issues.standing.act.supply": { en: "supply what it asks for" },
	"issues.standing.act.takeOnOrDrop": { en: "take on or drop" },
	"issues.standing.act.waitOn": { en: "wait on {key}", vars: { key: "key" } },
	"issues.standing.act.working": { en: "working" },
	"issues.standing.who.contractProvider": { en: "The contract provider" },
	"issues.standing.who.designApprover": { en: "A design approver" },
	"issues.standing.who.nextRun": { en: "Next run" },
	"issues.standing.who.noHolder": { en: "No holder" },
	"issues.standing.who.queuedRun": { en: "Queued run" },
	"issues.standing.who.release": { en: "Release" },
	"issues.standing.who.run": { en: "Run" },
	"releases.effect.split": { en: "Cuts the oldest {limit} merged issues as this release and leaves {left} at the release gate for the next one.", vars: { limit: "count", left: "said" } },
	"releases.effect.splitOthers": { en: "the others" },
	"releases.effect.splitRest": { en: "the other {n}", vars: { n: "count" } },
	"requirements.history.text.accepted": { en: "Accepted r{r}", vars: { r: "count" } },
	"requirements.history.text.acceptedSuggestion": { en: "Accepted {what}", vars: { what: "said" } },
	"requirements.history.text.acceptedSuggestionWhy": { en: "Accepted {what}: {rest}", vars: { what: "said", rest: "text" } },
	"requirements.history.text.acceptedWhy": { en: "Accepted r{r}: {rest}", vars: { r: "count", rest: "text" } },
	"requirements.history.text.agreed": { en: "Agreed r{r}", vars: { r: "count" } },
	"requirements.history.text.agreedWhy": { en: "Agreed r{r}: {rest}", vars: { r: "count", rest: "text" } },
	"requirements.history.text.deferred": { en: "Deferred out of the current release: {rest}", vars: { rest: "text" } },
	"requirements.history.text.deferredFor": { en: "Deferred out of the current release (for {phase}): {rest}", vars: { phase: "name", rest: "text" } },
	"requirements.history.text.deliveryAccepted": { en: "Accepted the delivery" },
	"requirements.history.text.deliveryAcceptedWhy": { en: "Accepted the delivery: {rest}", vars: { rest: "text" } },
	"requirements.history.text.dropped": { en: "Dropped: {rest}", vars: { rest: "text" } },
	"requirements.history.text.proposed": { en: "Proposed r{r}", vars: { r: "count" } },
	"requirements.history.text.rejectedSuggestion": { en: "Rejected {what}", vars: { what: "said" } },
	"requirements.history.text.rejectedSuggestionWhy": { en: "Rejected {what}: {rest}", vars: { what: "said", rest: "text" } },
	"requirements.history.text.repinned": { en: "Re-pinned r{r} onto the approved designs", vars: { r: "count" } },
	"requirements.history.text.repinnedWhy": { en: "Re-pinned r{r} onto the approved designs: {rest}", vars: { r: "count", rest: "text" } },
	"requirements.history.text.returned": { en: "Returned r{r}: {rest}", vars: { r: "count", rest: "text" } },
	"requirements.history.text.suggested": { en: "Suggested {what}", vars: { what: "said" } },
	"requirements.history.text.undeferred": { en: "Undeferred" },
	"requirements.history.text.undeferredWhy": { en: "Undeferred: {rest}", vars: { rest: "text" } },
	"requirements.history.text.wrote": { en: "Wrote r{r}: {rest}", vars: { r: "count", rest: "text" } },
	"requirements.history.text.wroteSuggested": { en: "Wrote r{r} (an accepted suggestion): {rest}", vars: { r: "count", rest: "text" } },
	"requirements.history.what.breakdown": { en: "a breakdown" },
	"requirements.history.what.change": { en: "a change" },
	"requirements.history.what.duplicate": { en: "a duplicate" },
	"requirements.history.what.readiness": { en: "a readiness check" },
	"requirements.history.what.requirement_draft": { en: "a requirement draft" },
	"requirements.history.what.revision_diff": { en: "a revision" },
	"requirements.history.what.triage": { en: "a triage" },
	"requirements.history.who.agent": { en: "An agent" },
	"requirements.history.who.assistant": { en: "BA assistant" },
	"requirements.history.who.signer": { en: "A signer" },
	"requirements.history.who.someone": { en: "Someone" },
	"standing.act.acceptR": { en: "accept r{r}", vars: { r: "count" } },
	"standing.act.acceptRevisionN": { en: "accept revision {r} of {req}", vars: { r: "count", req: "key" } },
	"standing.act.acceptRevisionOf": { en: "accept the revision of {req}", vars: { req: "key" } },
	"standing.act.agreeIt": { en: "agree it" },
	"standing.act.agreeR": { en: "agree r{r}", vars: { r: "count" } },
	"standing.act.answerReturn": { en: "answer the return" },
	"standing.act.approve": { en: "approve" },
	"standing.act.approveCarrierRelease": { en: "Approve the release that carries it" },
	"standing.act.approveDesign": { en: "approve design {what}", vars: { what: "name" } },
	"standing.act.approveOrReturn": { en: "approve or return {v}", vars: { v: "version" } },
	"standing.act.approveReleaseV": { en: "Approve release {v}", vars: { v: "version" } },
	"standing.act.askApproval": { en: "ask for approval" },
	"standing.act.beAccepted": { en: "be accepted" },
	"standing.act.beAgreedDelivered": { en: "be agreed and delivered" },
	"standing.act.beDelivered": { en: "be delivered" },
	"standing.act.beResolved": { en: "be resolved" },
	"standing.act.breakDown": { en: "break down" },
	"standing.act.breakDownBy": { en: "break down, {when}", vars: { when: "said" } },
	"standing.act.bringIssueToGate": { en: "bring an issue to the release gate" },
	"standing.act.check": { en: "check {codes} against the traceability matrix, {when}", vars: { codes: "key", when: "said" } },
	"standing.act.checkCouldNotRun": { en: "a check could not run" },
	"standing.act.confirmAnswer": { en: "Confirm the answer" },
	"standing.act.cut": { en: "cut {v}{more}", vars: { v: "version", more: "said?" } },
	"standing.act.cutCarrierRelease": { en: "cut the release that carries {what}", vars: { what: "said" } },
	"standing.act.cutThenApprove": { en: "cut {v}, then approve it", vars: { v: "version" } },
	"standing.act.cutWaiting": { en: "cut the issues that are waiting" },
	"standing.act.declareProbe": { en: "declare a source probe on production" },
	"standing.act.declareCarried": { en: "say what outside Forge carries {v}: nothing, or the tag, release commit, artifact or notice", vars: { v: "version" } },
	"standing.act.declareProduction": { en: "declare a production environment" },
	"standing.act.declareTarget": { en: "declare where releases land" },
	"standing.act.deploying": { en: "deploying" },
	"standing.act.finishDraft": { en: "finish draft" },
	"standing.act.fixFailing": { en: "fix {codes}, failing on {keys}", vars: { codes: "key", keys: "key" } },
	"standing.act.fixSchedule": { en: "fix a failing schedule" },
	"standing.act.judgeCriteria": { en: "judge the criteria still owed" },
	"standing.act.judgeOn": { en: "judge {codes} on {keys}", vars: { codes: "key", keys: "key" } },
	"standing.act.labelRunner": { en: "label a runner for releases" },
	"standing.act.markMerge": { en: "mark the merge{on}", vars: { on: "said?" } },
	"standing.act.noHolder": { en: "{act}: no person on this project holds {perm} until it is granted under Settings → Members", vars: { act: "said", perm: "permission" } },
	"standing.act.pairRunner": { en: "pair a runner" },
	"standing.act.productionReadable": { en: "give production a way to be read" },
	"standing.act.promoteDraft": { en: "promote 1 draft issue" },
	"standing.act.promoteDrafts": { en: "promote {n} draft issues", vars: { n: "count" } },
	"standing.act.proposeDesign": { en: "propose design {what}", vars: { what: "name" } },
	"standing.act.proposeOrDrop": { en: "propose or drop r{r}", vars: { r: "count" } },
	"standing.act.proposeR": { en: "propose r{r}", vars: { r: "count" } },
	"standing.act.proposeRevisionN": { en: "propose revision {r} of {req}", vars: { r: "count", req: "key" } },
	"standing.act.proposeRevisionOf": { en: "propose the revision of {req}", vars: { req: "key" } },
	"standing.act.queuedBehind": { en: "queued behind {v}", vars: { v: "version" } },
	"standing.act.releaseByHand": { en: "release {what} by hand and close it", vars: { what: "said" } },
	"standing.act.releaseItByHand": { en: "release it by hand and close it" },
	"standing.act.releaseRunning": { en: "a release is running" },
	"standing.act.replan": { en: "re-plan {keys}", vars: { keys: "key" } },
	"standing.act.reviewBreakdown": { en: "Review how this requirement is split into work" },
	"standing.act.reviseReturned": { en: "revise returned r{r}", vars: { r: "count" } },
	"standing.act.reviseThenProposeOrDrop": { en: "revise returned r{r}, then propose or drop it", vars: { r: "count" } },
	"standing.act.runnerOnline": { en: "bring a runner online" },
	"standing.act.running": { en: "Running {a} of {b}", vars: { a: "count", b: "count" } },
	"standing.act.ship": { en: "ship" },
	"standing.act.shippedOf": { en: "Shipped {a} of {b}", vars: { a: "count", b: "count" } },
	"standing.act.splitRelease": { en: "split this release into smaller releases" },
	"standing.act.starting": { en: "starting" },
	"standing.act.takeOverSchedule": { en: "take over a schedule whose owner is gone" },
	"standing.act.trace": { en: "trace {codes} to an issue criterion", vars: { codes: "key" } },
	"standing.act.triage": { en: "triage {what}", vars: { what: "name" } },
	"standing.act.triageAgain": { en: "triage it again" },
	"standing.act.triageIt": { en: "triage it" },
	"standing.act.triageMany": { en: "triage {n} feedback items", vars: { n: "count" } },
	"standing.act.triageReport": { en: "triage a report" },
	"standing.act.updateToContract": { en: "Update to the current version of {contract} ({v})", vars: { contract: "name", v: "version" } },
	"standing.act.updateToDesign": { en: "Update to the approved design: {design} (revision {r})", vars: { design: "name", r: "count" } },
	"standing.act.verdictsNotReread": { en: "verdicts not re-read" },
	"standing.act.verifyFix": { en: "verify the fix" },
	"standing.act.verifyFixIn": { en: "verify the fix shipped in {v}", vars: { v: "version" } },
	"standing.act.tellShippedIn": { en: "tell {who} that it shipped in {v}", vars: { who: "name", v: "version" } },
	"standing.act.tellShipped": { en: "tell {who} that it shipped", vars: { who: "name" } },
	"standing.act.verifying": { en: "verifying" },
	"standing.act.writeReleaseNote": { en: "write the release note{on}", vars: { on: "said?" } },
	"standing.due": { en: "due {date}", vars: { date: "date" } },
	"standing.effect.follow": { en: "Records that this requirement follows {names} from now on. Its wording and criteria do not change, and its delivery is not offered for acceptance until then.", vars: { names: "saidSeries" } },
	"standing.gate.claimed": { en: "{subject} {verb} not at the release gate, or another release already holds {obj}. Pick the issues that are waiting.", vars: { subject: "said", verb: "agreement", obj: "agreement" } },
	"standing.gate.empty": { en: "No issue is waiting at the release gate, so there is nothing to cut." },
	"standing.gate.heldBack": { en: "{owes}. {they} held back until {their} criteria are earned; the others ship.", vars: { owes: "saidList", they: "agreement", their: "agreement" } },
	"standing.gate.nearGate": { en: "No issue is waiting at the release gate. {n} {issues} {verb} one step short of it, at {their} test step.", vars: { n: "count", issues: "agreement", verb: "agreement", their: "agreement" } },
	"standing.gate.noGate": { en: "This project ships when an issue closes, so there is no release to cut." },
	"standing.gate.noRunner": { en: "No runner is paired to this project, so no machine can run a release." },
	"standing.gate.noRunnerOnline": { en: "Runners are paired, and none of them can take a release right now." },
	"standing.gate.noteMissing": { en: "{subject} {verb} no release note, so the release would claim a ship nobody described.", vars: { subject: "said", verb: "agreement" } },
	"standing.gate.nowhere": { en: "Nothing says where this project’s releases land. An admin completes its production environment in the project document." },
	"standing.gate.on": { en: " on {subject}", vars: { subject: "said" } },
	"standing.gate.oversize": { en: "{n} {issues} {verb} waiting, and one release carries at most {limit}. Split them into smaller releases, oldest merge first.", vars: { n: "count", issues: "agreement", verb: "agreement", limit: "count" } },
	"standing.gate.oversizeUncounted": { en: "More issues are waiting, and one release carries at most {limit}. Split them into smaller releases, oldest merge first.", vars: { limit: "count" } },
	"standing.gate.owes": { en: "{key} owes {word} {list}", vars: { key: "key", word: "agreement", list: "text" } },
	"standing.gate.preference": { en: "No runner carries the release label this project asks for, so the release goes to the pool it has." },
	"standing.gate.running": { en: "Another release is already running for this project. Let it finish before cutting another." },
	"standing.gate.subject.atGate": { en: "Issues at the gate" },
	"standing.gate.subject.count": { en: "{n} {issues}", vars: { n: "count", issues: "agreement" } },
	"standing.gate.subject.keys": { en: "{keys}", vars: { keys: "key" } },
	"standing.gate.subject.more": { en: "{keys} and {n} more", vars: { keys: "key", n: "count" } },
	"standing.gate.subject.some": { en: "Some issues" },
	"standing.gate.versionUndecided": { en: "{v} was cut for these same issues, and its attempt {n} ended without saying whether a tag, a release commit, an artifact or a notice outside Forge carries {v}. The next attempt can neither wear {v} nor take a new version until someone says.", vars: { v: "version", n: "count" } },
	"standing.gate.title.claimed": { en: "Issues already claimed" },
	"standing.gate.title.empty": { en: "Nothing at the gate" },
	"standing.gate.title.heldBack": { en: "Some issues held back" },
	"standing.gate.title.noGate": { en: "No release step" },
	"standing.gate.title.noRunner": { en: "No runner paired" },
	"standing.gate.title.noRunnerOnline": { en: "No runner can take it" },
	"standing.gate.title.noteMissing": { en: "Release note missing" },
	"standing.gate.title.nowhere": { en: "Nowhere to land" },
	"standing.gate.title.oversize": { en: "Too many issues" },
	"standing.gate.title.versionUndecided": { en: "Version undecided" },
	"standing.gate.title.preference": { en: "Preferred runner missing" },
	"standing.gate.title.running": { en: "A release is running" },
	"standing.gate.title.uncorroborated": { en: "Verdicts not re-read" },
	"standing.gate.title.unearned": { en: "Criteria still owed" },
	"standing.gate.title.unevaluated": { en: "A check could not run" },
	"standing.gate.title.unmerged": { en: "Work not marked merged" },
	"standing.gate.title.unprovable": { en: "Production cannot be proved" },
	"standing.gate.title.unreadable": { en: "Production cannot be read" },
	"standing.gate.uncorroborated": { en: "{subject} {verb} a verdict earned where nothing could re-read production. It counts, and it is weaker evidence.", vars: { subject: "said", verb: "agreement" } },
	"standing.gate.unearned": { en: "{owes}. The unattended sweep carries an issue only when every criterion holds a passing verdict.", vars: { owes: "saidList" } },
	"standing.gate.unevaluated": { en: "The {check} check could not run, so this list may be missing a reason.", vars: { check: "code" } },
	"standing.gate.unmerged": { en: "{subject} {verb} no merge Forge saw land, so nothing says {their} work is in this release.", vars: { subject: "said", verb: "agreement", their: "agreement" } },
	"standing.gate.unprovable": { en: "Production declares no probe that identifies the source commit, so a release there could never be proved. An admin adds one to the production environment." },
	"standing.gate.unreadable": { en: "Nothing can read what production serves, so no verdict can earn an issue its place in an unattended release." },
	"standing.more": { en: " and {n} more", vars: { n: "count" } },
	"standing.overdueSince": { en: "overdue since {date}", vars: { date: "date" } },
	"standing.risk.apiRemoved": { en: "{ref} is removed: a caller still using it is refused after this ships", vars: { ref: "name" } },
	"standing.risk.dataChanged": { en: "{ref} changes shape: rows written before it are read by the new shape", vars: { ref: "name" } },
	"standing.risk.dataRemoved": { en: "{ref} is removed: data it held does not come back with a rollback", vars: { ref: "name" } },
	"standing.who.baOrOwner": { en: "BA or owner" },
	"standing.who.currentRevision": { en: "The current revision" },
	"standing.who.holderOf": { en: "A holder of {perm}", vars: { perm: "permission" } },
	"standing.who.independentJudge": { en: "Independent judge" },
	"standing.who.issues": { en: "Issues" },
	"standing.who.itsAuthor": { en: "Its author" },
	"standing.who.itsRoot": { en: "Its root {root}", vars: { root: "key" } },
	"standing.who.linkedIssue": { en: "The linked issue" },
	"standing.who.linkedWork": { en: "The linked work" },
	"standing.who.master": { en: "Master" },
	"standing.who.newRequirement": { en: "The new requirement" },
	"standing.who.nobody": { en: "Nobody" },
	"standing.who.projectMaster": { en: "The project's master" },
	"standing.who.releaseGate": { en: "Release gate" },
	"standing.who.releaseRun": { en: "Release run" },
	"standing.who.revisionProposal": { en: "The revision proposal" },
	"standing.who.scheduleOwner": { en: "The schedule owner" },
	"standing.who.you": { en: "You" },
	"issues.blocker.otherQuestionUnnamed": { en: "Its question was answered, and another question on it is still open (unnamed)." },
	"issues.rule.noWriter": { en: "{rule}; no person holds {perm} on this project", vars: { rule: "said", perm: "permission" } },
	"issues.rule.noReason": { en: "the run named no reason" },
	"issues.rule.answered": { en: "{reason} {who}", vars: { reason: "said", who: "said" } },
	"runs.rule.withRef": { en: "{rule} ({ref})", vars: { rule: "said", ref: "said" } },
	"runs.rule.lockNoHolder": { en: "DEPLOY_ENVIRONMENT_LOCKED: this release's deploy was refused the {environment} environment at {at} while another acquisition was in flight and uncommitted; no holder or deadline was readable, so none is served", vars: { environment: "name", at: "instant" } },
	"runs.rule.lockUnnamedSubject": { en: "an unnamed subject" },
	"runs.rule.lockSince": { en: " since {at}", vars: { at: "instant" } },
	"runs.rule.lockUntilExpiry": { en: "until that deploy ends or its hold expires at {at}, when the next deploy reclaims it", vars: { at: "instant" } },
	"runs.rule.lockUntilEnds": { en: "until that deploy ends" },
	"runs.act.answerQuestion": { en: "answer the question" },
	"runs.ref.question": { en: "question {id} (blocker_kind human)", vars: { id: "key" } },
	"runs.ref.questionOn": { en: "question {id} on {key} (blocker_kind human)", vars: { id: "key", key: "key" } },
	"runs.rule.question": { en: "an open question with blocker_kind human: only a person can answer it" },
	"runs.ref.approval": { en: "release_approvals: no decision (RELEASE_AWAITING_APPROVAL)" },
	"runs.rule.approval": { en: "the release waits on a pending approval, which a holder of releases.approve decides" },
	"runs.act.resumeRun": { en: "resume the run" },
	"runs.ref.pauseReason": { en: "pauseReason {reason}", vars: { reason: "code" } },
	"runs.ref.pausedByPerson": { en: "paused by a person" },
	"runs.rule.personPause": { en: "the run is paused, and only a person resumes this pause" },
	"runs.rule.pausedBy": { en: "the run is paused ({reason}); the {resumer} resumes it, and no deadline is recorded", vars: { reason: "code", resumer: "code" } },
	"runs.act.resumeJob": { en: "resume the job" },
	"runs.ref.jobHeld": { en: "job held: {reason}", vars: { reason: "code" } },
	"runs.rule.jobHeld": { en: "the job is held ({reason}), a hold that does not resume itself", vars: { reason: "code" } },
	"runs.act.bindCheckout": { en: "bind a checkout on the box" },
	"runs.ref.checkoutUnbound": { en: "pipeline health reads checkout_unbound (POOL_CHECKOUT_UNBOUND)" },
	"runs.rule.checkoutUnbound": { en: "every box serving this project is bound with no checkout, so its claim is refused: `forge-runner bind <slug> --path <dir>` on the box, or PATCH the runner's repoPath, and dispatch takes it" },
	"runs.act.answerDialog": { en: "answer the dialog {pane} is stopped on: \"{text}\"", vars: { pane: "said", text: "text" } },
	"runs.act.itsMasterPane": { en: "its master pane" },
	"runs.ref.masterDialog": { en: "master session {id} metadata.paneDialog", vars: { id: "key" } },
	"runs.rule.masterDialog": { en: "MASTER_PANE_DIALOG: the master pane this run works in is stopped on a dialog, and nothing in it moves until a person answers" },
	"runs.act.answerRun": { en: "answer the run" },
	"runs.ref.ledgerBlocked": { en: "run ledger: work blocked, blockerKind human" },
	"runs.rule.ledgerBlocked": { en: "the box reports the run blocked on a person" },
	"runs.ref.issueAt": { en: "{key} at {status}", vars: { key: "key", status: "status" } },
	"runs.rule.noTransition": { en: " (no kernel transition records when it moved there)" },
	"runs.gate.issueBusy": { en: "another session or job is live on this issue: dispatch takes this one once it ends" },
	"runs.gate.contractWait": { en: "CONTRACT_WAIT_UNSETTLED: the issue waits on a contract version no approved version reaches yet: the approval releases it" },
	"runs.gate.runnerStale": { en: "no box serving this project has beaten recently: dispatch takes it once one does" },
	"runs.gate.runnerTooOld": { en: "no box serving this project runs a build that can take it: dispatch takes it once one is updated" },
	"runs.rule.heldRetry": { en: "held {reason}: the release sweep retries it once jobs.retry_after_at has passed", vars: { reason: "code" } },
	"runs.rule.heldClears": { en: "held {reason}: it re-queues when its condition clears, which has no deadline", vars: { reason: "code" } },
	"runs.rule.retryCooldown": { en: "jobs.retry_after_at is in the future: dispatch skips the job until then" },
	"runs.rule.dispatchGate": { en: "pipeline health reads {gate}: {why}, which has no deadline", vars: { gate: "code", why: "said" } },
	"runs.rule.paren": { en: " ({text})", vars: { text: "text" } },
	"runs.rule.declarationRefused": { en: "the box declared this run and core refuses to admit it ({code}, {attempts} attempt(s), last {at}): {detail}", vars: { code: "code", attempts: "count", at: "instant", detail: "text" } },
	"runs.rule.running": { en: "running: its holder is working it" },
	"runs.rule.claimed": { en: "claimed: its holder has not started it" },
	"runs.who.machine": { en: "Machine" },
	"runs.act.noSlot": { en: "no free slot ({inUse} of {max} in use)", vars: { inUse: "count", max: "count" } },
	"runs.rule.noSlot": { en: "no free slot: {inUse} of {max} in use (masters/standing.slots)", vars: { inUse: "count", max: "count" } },
	"runs.act.dispatchIt": { en: "dispatch it" },
	"runs.rule.queuedMaster": { en: "queued: the project master takes it in a pass" },
	"runs.rule.queuedNothing": { en: "queued: nothing is dispatched on the run" },
	"runs.rule.lockHeld": { en: "DEPLOY_ENVIRONMENT_LOCKED: this release's deploy was refused at {at}: pipeline run {run} holds the {environment} environment, deploying {subject}{since}; refused {until}", vars: { at: "instant", run: "key", environment: "name", subject: "said", since: "said?", until: "said" } },
	"runs.rule.issueParked": { en: "the issue is parked at {status} while its run is live; a person moves it next{unrecorded}", vars: { status: "status", unrecorded: "said?" } },
	"runs.rule.blockedOn": { en: "the box reports the run blocked on {kind}{on}, which no person clears", vars: { kind: "code", on: "said?" } },
	"runs.act.actsNext": { en: "acts next" },
	"runs.rule.stuck": { en: "stuck ({rule}): the project master acts next, and a person may cancel the run or revoke its lease{ended}", vars: { rule: "code", ended: "said?" } },
	"runs.rule.rootEnded": { en: "; its root already ended: {rule}", vars: { rule: "said" } },
	"runs.rule.finished": { en: "finished" },
	"automation.rule.failing": { en: "failing: its owner fixes it, pauses it or takes it over" },
	"automation.rule.ownerGone": { en: "owner gone: an admin saves it to take it over, and runs it as themselves from then on" },
	"automation.rule.off": { en: "off: nothing fires until it is turned on" },
	"automation.rule.nextFire": { en: "next fire at {at}", vars: { at: "instant" } },
	"automation.rule.noNextFire": { en: "no next fire set" },
	"automation.rule.toOwner": { en: "a report a fire filed goes to its schedule owner first" },
	"automation.rule.toWriters": { en: "its schedule has no owner, so any member with write access triages it" },
	"automation.who.harnessTriage": { en: "Harness triage" },
	"automation.rule.harness": { en: "no fire filed it: an issue run reported the harness it worked under, which is triaged on Automation, Reports and is not a project member’s to-do" },
	"automation.rule.reportsWait": { en: "{n} of its reports wait for triage: {rule}", vars: { n: "count", rule: "said" } },
	"automation.rule.running": { en: "running" },
	"automation.rule.fireWaitsOnNobody": { en: "nothing about this fire waits on a person" },
	"automation.rule.filedFeedback": { en: "filed as {key}, at {phase}", vars: { key: "key", phase: "code" } },
	"automation.rule.filedIssue": { en: "filed as {key}, at {status}", vars: { key: "key", status: "status" } },
	"automation.rule.triaged": { en: "triaged {triage}", vars: { triage: "code" } },
	"standing.keysAnd": { en: "{keys} and {last}", vars: { keys: "key", last: "key" } },
	"feedback.act.triageAfterSnooze": { en: "triage it once the snooze ends, {date}", vars: { date: "date" } },
	"feedback.rule.snoozed": { en: "{phase}: snoozed until {until}, when it returns to New for a holder of feedback.approve", vars: { phase: "code", until: "instant" } },
	"feedback.rule.masterOwes": { en: "{phase}: untriaged feedback owes the project's master a triage; a holder of feedback.approve may triage it first", vars: { phase: "code" } },
	"feedback.rule.triagerTriages": { en: "{phase}: a holder of feedback.approve triages it", vars: { phase: "code" } },
	"feedback.act.route": { en: "route it to work" },
	"feedback.rule.noRoute": { en: "triaged: it was accepted with no route yet, so a holder of feedback.approve routes it" },
	"feedback.rule.carrierGone": { en: "triaged: the route's carrier is gone, so a holder of feedback.approve routes it anew" },
	"feedback.rule.answered": { en: "resolved: the question was answered, and the reporter confirms the answer settled it" },
	"feedback.rule.relay": { en: "resolved: no notice told the reporter the work shipped, so a holder of feedback.approve tells them, by a message to reporters or by recording what they told them outside Forge" },
	"feedback.rule.verify": { en: "resolved: anyone on the project, or the reporter, may confirm the fix, and Forge verifies it when nobody has within the project’s verify window" },
	"standing.who.nothing": { en: "Nothing" },
	"feedback.rule.nothingOwed": { en: "{phase}: nothing is owed", vars: { phase: "code" } },
	"feedback.who.theLinkedIssue": { en: "the linked issue" },
	"feedback.rule.issuesCarry": { en: "planned: its issues carry it" },
	"feedback.rule.issueCarries": { en: "planned: its issue carries it" },
	"feedback.rule.noReleaseModel": { en: "planned: {issue} {waits} at awaiting_release and this project declares no release model (no production environment), so no release carries it and a person releases it", vars: { issue: "said", waits: "agreement" } },
	"feedback.rule.approvalRequired": { en: "planned: {issue} {waits} at awaiting_release and this project requires a holder of releases.approve to approve its release", vars: { issue: "said", waits: "agreement" } },
	"feedback.rule.manualCut": { en: "planned: {issue} {waits} at awaiting_release and this project's production does not deploy on land, so a holder of project.admin cuts its release", vars: { issue: "said", waits: "agreement" } },
	"feedback.rule.newRequirement": { en: "planned: a new requirement carries it" },
	"standing.who.itsRootUnnamed": { en: "Its root" },
	"feedback.rule.duplicate": { en: "planned: the root item it duplicates carries it" },
	"feedback.rule.linkedWork": { en: "planned: the linked work carries it" },
	"feedback.rule.proposal": { en: "planned: a requirement revision proposal carries it, and a person decides it" },
	"feedback.rule.acceptance": { en: "planned: the accepted suggestion proposed its revision, and a holder of requirements.approve accepts it" },
	"feedback.rule.drafted": { en: "planned: its revision is a draft, returned by a signer, and its author proposes it" },
	"feedback.rule.delivery": { en: "planned: its requirement revision is current, and the work delivering it carries it" },
	"feedback.who.revision": { en: "{req} r{r}", vars: { req: "key", r: "count" } },
	"standing.act.acceptRevision": { en: "accept the revision" },
	"standing.act.acceptRevisionNum": { en: "accept revision {r}", vars: { r: "count" } },
	"standing.act.proposeRevision": { en: "propose the revision" },
	"standing.act.proposeRevisionNum": { en: "propose revision {r}", vars: { r: "count" } },
	"feedback.notice.noDedupUnwritten": { en: "triage without dedup: the item's vector is not written yet" },
	"releases.rule.ended": { en: "the release has ended" },
	"releases.rule.gated": { en: "{n} {reasons} {verb} against cutting {v}", vars: { n: "count", reasons: "agreement", verb: "agreement", v: "version" } },
	"standing.act.andMore": { en: "{act}{more}", vars: { act: "said", more: "said" } },
	"releases.rule.queuedBehindRun": { en: "the release already running finishes before {v} can be cut", vars: { v: "version" } },
	"releases.rule.adminCuts": { en: "merged issues wait at the release gate, no gate holds them, and an admin cuts the version" },
	"releases.rule.noRequest": { en: "the project requires approval before production and no request is open" },
	"releases.rule.asked": { en: "{name} asked; a holder of releases.approve approves or returns it", vars: { name: "name" } },
	"releases.rule.noneLeft": { en: "{rule}, and none is left", vars: { rule: "said" } },
	"releases.rule.returned": { en: "an admin returned it; the master answers before it asks again" },
	"releases.rule.returnedWhy": { en: "an admin returned it: {why}; the master answers before it asks again", vars: { why: "text" } },
	"releases.rule.inProgress": { en: "the release run is working on production" },
	"releases.rule.issueShipped": { en: "the issue has shipped" },
	"requirements.dedup.notChecked": { en: "dedup was not checked: the head revision's vector is {status}", vars: { status: "code" } },
	"requirements.dedup.notWritten": { en: "dedup was not checked: the head revision's vector is not written yet" },
	"requirements.history.text.noted": { en: "{text}{note}", vars: { text: "said", note: "said" } },
	"requirements.history.note.dedup": { en: " ({why})", vars: { why: "said" } },
	"requirements.history.note.ready": { en: " (ready){dedup}", vars: { dedup: "said?" } },
	"requirements.history.note.noResult": { en: " (no readiness result){dedup}", vars: { dedup: "said?" } },
	"requirements.history.note.notReady": { en: " (not ready: {failed}){dedup}", vars: { failed: "code", dedup: "said?" } },
	"requirements.history.who.forge": { en: "Forge" },
	"standing.empty": { en: "" },
	"standing.acts": { en: "{acts}", vars: { acts: "saidList" } },
	"standing.effect.designAt": { en: "{title} revision {r}", vars: { title: "name", r: "count" } },
	"standing.effect.contractAt": { en: "{contract} {v}", vars: { contract: "name", v: "version" } },
	"requirements.rule.draftAuthor": { en: "an open draft revision waits on its author to propose it" },
	"requirements.rule.agentReturned": { en: "its signer returned this agent-written revision with a reason, so the master that runs that agent revises it: core wakes it on the return and its box carries the return to every pass until it is proposed or dropped" },
	"requirements.rule.agentDraft": { en: "an agent wrote this draft, under whichever account it is paired with, so the master that runs it proposes or drops it" },
	"requirements.rule.designsFirst": { en: "every linked design is approved before the agree pins it (REQUIREMENT_DESIGN_UNAPPROVED); then a signer agrees it" },
	"requirements.rule.unjudged": { en: "{codes} hold no passing verdict yet", vars: { codes: "key" } },
	"requirements.rule.failed": { en: "{codes} failed", vars: { codes: "key" } },
	"requirements.rule.untraced": { en: "no issue criterion traces to {codes}", vars: { codes: "key" } },
	"requirements.rule.notDelivered": { en: "every linked issue has shipped, but {parts}, so it is not delivered{undeclared}", vars: { parts: "saidList", undeclared: "said?" } },
	"requirements.rule.noJudge": { en: "; no policy names a judge, so the master judges" },
	"requirements.rule.designsFirstR": { en: "every linked design is approved before the agree pins it (REQUIREMENT_DESIGN_UNAPPROVED); then a signer agrees r{r}", vars: { r: "count" } },
	"standing.who.dash": { en: "—" },
	"requirements.rule.feedbackWaits": { en: "feedback about it waits on a person to pick its route: {keys}", vars: { keys: "key" } },
	"requirements.rule.ended": { en: "the requirement is {status}", vars: { status: "code" } },
	"requirements.rule.deferred": { en: "deferred out of the current release; it waits on nobody" },
	"requirements.rule.proposed": { en: "a proposed revision waits on a sign-off" },
	"requirements.rule.unagreed": { en: "a current revision not yet agreed waits on a sign-off" },
	"requirements.rule.pinBehind": { en: "The design this requirement follows has a newer approved revision, or a contract it relies on has a newer version. Updating records that it follows the newer one." },
	"requirements.rule.check": { en: "delivered at r{r}; the BA checks the business criteria by {date}, {days} working days after delivery{overdue}", vars: { r: "count", date: "date", days: "count", overdue: "said?" } },
	"requirements.rule.overdue": { en: ", and it is overdue" },
	"requirements.who.ba": { en: "BA" },
	"requirements.rule.breakdownWaits": { en: "a breakdown suggestion waits on a person" },
	"requirements.rule.replan": { en: "planned against an earlier revision than r{r} (REQUIREMENT_CHANGED_SINCE_PLAN)", vars: { r: "count" } },
	"requirements.rule.replanUnknown": { en: "planned against an earlier revision than r? (REQUIREMENT_CHANGED_SINCE_PLAN)" },
	"requirements.rule.breakdownDue": { en: "agreed with no linked issue; the breakdown is due {date}, {days} working days after the agree", vars: { date: "date", days: "count" } },
	"requirements.rule.noIssue": { en: "agreed with no linked issue" },
	"requirements.rule.onlyDrafts": { en: "its only live issues are drafts, which nothing works until a person promotes them" },
	"requirements.rule.moving": { en: "agreed and its issues are being worked" },
	"requirements.who.noOwner": { en: "No owner" },
	"requirements.act.assignOwner": { en: "assign one" },
	"requirements.rule.noOwner": { en: "no owner is set" },
	"requirements.rule.untouched": { en: "untouched for {days} days or more", vars: { days: "count" } },
	"forecast.who.whoeverReaches": { en: "Whoever can reach {device}", vars: { device: "name" } },
	"masters.who.whoeverReachesPane": { en: "Whoever can reach the master pane" },
	"masters.act.answerDialog": { en: "Answer the dialog {pane} is stopped on: \"{text}\"", vars: { pane: "said", text: "text" } },
	"masters.act.theMasterPane": { en: "the master pane" },
	"forecast.act.turnBoxOn": { en: "turn the box back on" },
	"forecast.act.unretire": { en: "return the runner to service" },
	"forecast.act.startRunner": { en: "start the runner" },
	"forecast.act.runnerOnline": { en: "bring the runner back online" },
	"forecast.act.signIn": { en: "sign the box in again" },
	"forecast.act.waitUsage": { en: "wait for the usage limit to reset" },
	"forecast.act.quarantine": { en: "wait out the quarantine or clear it" },
	"forecast.act.provision": { en: "finish provisioning the checkout" },
	"forecast.act.updateRunner": { en: "update the runner" },
	"forecast.act.bringRunnerBack": { en: "bring a runner back" },
	"forecast.reason.noRunner": { en: "no runner is registered for this project, so nothing can take its work" },
	"forecast.reason.heldDevice": { en: "{device} is {reason}{detail}", vars: { device: "name", reason: "code", detail: "said?" } },
	"forecast.reason.runnersHeld": { en: "no runner can take this project's work: {held}", vars: { held: "saidList" } },
	"forecast.reason.masterSilent": { en: "the project's master has been silent since {at}, so nothing is dispatched", vars: { at: "instant" } },
	"forecast.reason.masterSilentFromStart": { en: "the project's master has been silent since it started, so nothing is dispatched" },
	"forecast.act.restartMaster": { en: "restart the master" },
	"forecast.reason.masterDialog": { en: "the project's master is stopped on a dialog ({rule})", vars: { rule: "code" } },
	"forecast.act.waitOut": { en: "wait out the {reason}", vars: { reason: "code" } },
	"forecast.reason.passRefused": { en: "the master's last pass was refused ({reason}): {detail}", vars: { reason: "code", detail: "text" } },
	"forecast.act.releaseToMaster": { en: "release it to the master" },
	"forecast.reason.manualIntake": { en: "the project's intake is manual: an open issue reaches a master only once a person releases it" },
	"forecast.act.breakCycle": { en: "break the cycle" },
	"forecast.reason.cycle": { en: "{key} sits on a cycle of blocks edges, so none of them can start", vars: { key: "key" } },
	"forecast.act.landFirst": { en: "land first" },
	"forecast.reason.notForecast": { en: "{item} waits on {key}, which is not open work this project forecasts", vars: { item: "key", key: "key" } },
	"forecast.reason.waitsOn": { en: "waits on {key}: {reason}", vars: { key: "key", reason: "said" } },
	"forecast.act.cutNextThenApprove": { en: "cut the next version, then approve it" },
	"forecast.act.cutNext": { en: "cut the next version" },
	"forecast.reason.approval": { en: "this project requires a holder of releases.approve to approve each release{holders}, so no date is forecast for it", vars: { holders: "said?" } },
	"forecast.reason.manual": { en: "this project's production does not deploy on land, so a holder of project.admin cuts each release and no date is forecast for it" },
	"forecast.reason.noProduction": { en: "this project declares no production environment, so no release carries a landed change" },
	"forecast.reason.allLanded": { en: "every included issue has landed; {reason}", vars: { reason: "said" } },
	"contracts.act.approveOrReturn": { en: "approve or return {v} · measured {measured}", vars: { v: "version", measured: "code" } },
	"contracts.rule.proposed": { en: "providedTurn: a recorded version is proposed until its approver decides it (contract/approval.ts:approverRefusal)" },
	"contracts.who.orgAdmin": { en: "An org admin" },
	"contracts.who.consumers": { en: "{n} consumers", vars: { n: "count" } },
	"contracts.act.adoptBy": { en: "adopt {v} by {date}", vars: { v: "version", date: "date" } },
	"contracts.rule.window": { en: "providedTurn: a breaking version is approved and a consumer is still built against an older one inside the window" },
	"contracts.act.noConsumer": { en: "no consumer yet" },
	"contracts.act.everyConsumerOn": { en: "every consumer is on {v}", vars: { v: "version" } },
	"contracts.act.behind": { en: "{n} of {total} {consumers} behind, no window open", vars: { n: "count", total: "count", consumers: "agreement" } },
	"contracts.rule.providedSteady": { en: "providedTurn: nothing is proposed or owed inside a window" },
	"contracts.act.adaptBy": { en: "adapt to {v} by {date}", vars: { v: "version", date: "date" } },
	"contracts.rule.breaking": { en: "consumedTurn: the provider approved a breaking version; core filed one item per consumer, open until it is verified or declined" },
	"contracts.who.projectMember": { en: "A project member" },
	"contracts.act.noVersion": { en: "the provider has published no version" },
	"contracts.act.onLatest": { en: "on the latest, {v}", vars: { v: "version" } },
	"contracts.act.builtAgainst": { en: "built against {ours}; {v} is current", vars: { ours: "version", v: "version" } },
	"contracts.act.builtAgainstNone": { en: "built against no version; {v} is current", vars: { v: "version" } },
	"contracts.rule.consumedSteady": { en: "consumedTurn: no breaking item is open" },
	"workflows.act.decideNode": { en: "decide keep, rewrite or delete" },
	"workflows.rule.code": { en: "{code}", vars: { code: "code" } },
	"workflows.act.reviseToWording": { en: "revise the design to the new wording" },
	"workflows.act.reviseToContract": { en: "revise the design to the contract" },
	"workflows.act.repairToDesign": { en: "repair the build to the approved design" },
	"workflows.act.observeAgain": { en: "observe the workflow again" },
	"workflows.act.proposeRevision": { en: "propose a design revision" },
	"workflows.act.repairBuild": { en: "repair the build" },
	"workflows.act.recoverRun": { en: "recover the {state} run", vars: { state: "code" } },
	"workflows.act.decideSuggestion": { en: "accept or reject the suggestion" },
	"workflows.act.keep": { en: "propose a revision that adopts the code, or build it to the plan" },
	"workflows.act.rewrite": { en: "break the rewrite into issues" },
	"workflows.act.delete": { en: "break the deletion into issues" },
	"workflows.rule.decided": { en: "the node is decided {verdict}", vars: { verdict: "code" } },
	"workflows.rule.notInDesign": { en: "code the design does not hold waits on a decision: keep, rewrite or delete" },
	"workflows.rule.rewriteDue": { en: "the node is due a rewrite ({rule}); keeping it is a recorded decision against the default", vars: { rule: "code" } },
	"workflows.act.buildToPlan": { en: "build it to the plan" },
	"workflows.rule.upcoming": { en: "a planned node no code builds yet is built to the plan" },
	"workflows.act.decideInRound": { en: "decide keep or rewrite in the decision round" },
	"workflows.rule.belowThreshold": { en: "an undecided Wrong node below the rewrite threshold waits on the orchestrator, not on a person" },
	"designs.act.approveOrReturn": { en: "approve or return revision {r}", vars: { r: "count" } },
	"designs.rule.youDecide": { en: "revision {r} is proposed and you may decide it", vars: { r: "count" } },
	"designs.rule.approverDecides": { en: "a design is decided by whoever holds workflow-designs.approve on the project (project admin, or an org owner or admin), person or agent" },
	"designs.act.repin": { en: "re-pin basedOn" },
	"designs.rule.baseUnapproved": { en: "{code}: {detail} Its approver cannot approve it until its writer writes it again with basedOn re-pinned", vars: { code: "code", detail: "text" } },
	"designs.title.repinBatch": { en: "{n} {designs} only {need} {its} pin moved → r{r}", vars: { n: "count", designs: "agreement", need: "agreement", its: "agreement", r: "count" } },
	"designs.act.repinBatch": { en: "approve {n} pin-only {changes} → r{r}", vars: { n: "count", changes: "agreement", r: "count" } },
	"designs.rule.repinBatch": { en: "{flow} is approved at revision {r}, and these designs differ from their approved revisions only in the base revision they pin: one act re-pins and approves them together, one recorded decision each", vars: { flow: "name", r: "count" } },
	"designs.act.revise": { en: "revise it" },
	"designs.act.reviseR": { en: "revise revision {r}", vars: { r: "count" } },
	"designs.rule.returned": { en: "a returned design is owed by the project's master, whoever wrote it: core wakes it on the return and its box carries the return to every pass until the next revision is proposed" },
	"designs.act.finish": { en: "finish and propose it" },
	"designs.rule.draft": { en: "a draft design is proposed once its master finishes drawing it" },
	"designs.rule.approved": { en: "revision {r} is approved; work that builds it may start", vars: { r: "count" } },
	"designs.rule.notUnderApproval": { en: "this workflow is not under design approval" },
	"modules.act.queued": { en: "{n} queued", vars: { n: "count" } },
	"modules.act.paused": { en: "{n} paused", vars: { n: "count" } },
	"modules.act.counts": { en: "{parts}", vars: { parts: "saidDots" } },
	"modules.act.nothingOpen": { en: "nothing open" },
	"modules.rule.quiet": { en: "No issue in this module waits on you, is stuck, or holds a live lease" },
	"questions.rule.unheld": { en: "a run asked a question that no issue, requirement or feedback holds, and only the Agents screen can take the answer" },
	"designs.who.aPerson": { en: "A person" },
	"designs.act.settleMarkers": { en: "settle {n} health {markers}", vars: { n: "count", markers: "agreement" } },
	"designs.rule.needsYou": { en: "a design needs you when a marker source waits on a person, or a node is Rewrite due or Not in design with no decision (REQ-17 BC-18)" },
	"runs.step.masterGone": { en: "this run was opened for a resident master and no master session on it is live, so nothing holds it" },
	"runs.step.masterNamed": { en: "this is the resident master `{name}`'s own run: a master dispatches issues rather than taking steps, so it holds no step, and residentMaster.lastHeartbeatAt is its heartbeat", vars: { name: "name" } },
	"runs.step.masterSession": { en: "this is the resident master session {id}'s own run: a master dispatches issues rather than taking steps, so it holds no step, and residentMaster.lastHeartbeatAt is its heartbeat", vars: { id: "key" } },
	"runs.step.boxOver": { en: "a box drives this run over {keys} and its driver has no phase open, so core holds no step for it", vars: { keys: "key" } },
	"runs.step.boxOverUnnamed": { en: "a box drives this run over a group this row no longer names and its driver has no phase open, so core holds no step for it" },
	"runs.step.jobNone": { en: "no pipeline step has been stamped on this run yet" },
	"runs.step.noLane": { en: "nothing has stamped a step on this run, and it is on neither the job nor the run-session lane, so neither of their step writers ever runs for it" },
	"runs.final.unclassified": { en: "failed, and no FAILURE_CAUSES cause was recorded on the session or the job, so it reads unclassified" },
	"runs.final.failed": { en: "failed: {cause}", vars: { cause: "code" } },
	"runs.final.noStopRecord": { en: "no kernel_transitions row records who stopped it" },
	"runs.final.landedNote": { en: " (it landed at {at}, and no move to an outcome followed)", vars: { at: "instant" } },
	"runs.final.close": { en: "{close}", vars: { close: "code" } },
	"runs.final.unrecordedClose": { en: "an unrecorded close" },
	"runs.final.closedDone": { en: "the box closed the session ({close}) with every issue it carried moved on to an outcome", vars: { close: "said" } },
	"runs.final.noCloseRecord": { en: "no kernel_transitions row records the close of this session" },
	"runs.final.unreadable": { en: "the session closed ({close}) and none of {keys} can be read back, so no outcome is credited", vars: { close: "said", keys: "key" } },
	"runs.final.unreadableNone": { en: "the session closed ({close}) and none of its issues can be read back, so no outcome is credited", vars: { close: "said" } },
	"runs.final.gaveBack": { en: "the session closed {close}: the box gave the work back before its outcome", vars: { close: "said" } },
	"runs.final.shortOf": { en: "the session closed ({close}) with {missed}, short of an outcome", vars: { close: "said", missed: "saidSeries" } },
	"runs.final.missed": { en: "{key} at {status}{landed}", vars: { key: "key", status: "status", landed: "said?" } },
	"runs.final.runCancelled": { en: "the pipeline run is cancelled" },
	"runs.final.sessionEnded": { en: "its session ended {why}", vars: { why: "code" } },
	"runs.final.completed": { en: "the pipeline run completed" },
	"runs.final.noCompletionRecord": { en: "no kernel_transitions row records the completion of this run" },
	"runs.live.dispatchedRunning": { en: "jobs.status dispatched and its agent session running" },
	"runs.live.notAcked": { en: "jobs.status dispatched: a box took it and has not acked" },
	"runs.live.heldByMaster": { en: "jobs.held_by: a master prepared it and has not started it" },
	"runs.live.admitted": { en: "admitted, and no box or master has taken it" },
	"runs.live.starting": { en: "the run session is starting (runtimeState or ledger incarnation starting)" },
	"runs.live.sessionIs": { en: "the run session is {status}", vars: { status: "code" } },
	"runs.live.openNothing": { en: "the run is open and nothing has been dispatched on it yet" },
	"runs.live.noSession": { en: "the pipeline run is {status} with {n} live job(s) and no live session; ISS-109 decides whether that is stuck", vars: { status: "code", n: "count" } },
	"runs.stuck.boxLive": { en: "the box reports the run {incarnation} while core ended its session {session}, and pipeline_runs.status is still {status}", vars: { incarnation: "code", session: "code", status: "code" } },
	"runs.stuck.rootEnded": { en: "pipeline_runs.status is still {status} while its root ended ({rule})", vars: { status: "code", rule: "said" } },
	"runs.stuck.boxExited": { en: "the box reports the process gone while core still has the run session running" },
	"runs.stuck.abandoned": { en: "the claim on {key} by {holder} stopped beating past its tolerance, while the run is still live", vars: { key: "key", holder: "name" } },
	"runs.stuck.claimStopped": { en: "the claim on {key} by {holder} was stopped at {at}, while the run is still live", vars: { key: "key", holder: "name", at: "instant" } },
	"runs.stuck.claimLapsed": { en: "the claim on {key} by {holder} lapsed at {at}, while the run is still live", vars: { key: "key", holder: "name", at: "instant" } },
	"runs.stuck.silent": { en: "no live job, and the last sign of life ({column} at {at}) is older than {mins} min", vars: { column: "code", at: "instant", mins: "count" } },
	"runs.stuck.stranded": { en: "the idle-issues sweep found {key} stranded at {status} ({reason}), while the run is still live", vars: { key: "key", status: "status", reason: "code" } },
	"runs.stuck.lockOverdue": { en: "the deploy lock on {environment} expired at {at} and nobody reclaimed it in {mins} min", vars: { environment: "name", at: "instant", mins: "count" } },
	"runs.stuck.refusalOverdue": { en: "this release's deploy was refused the {environment} environment until {at}, held by pipeline run {run}, and nothing took it in {mins} min after", vars: { environment: "name", at: "instant", run: "key", mins: "count" } },
	"runs.stuck.gateOverdue": { en: "the {gate} gate was due to resume at {at} and no new attempt came in {mins} min", vars: { gate: "code", at: "instant", mins: "count" } },
	"runs.stuck.clearQueued": { en: "queued: nothing has taken it yet, and the stuck rules read a run that started" },
	"runs.stuck.clearClaimed": { en: "claimed: its holder has not started it, and the start reapers own that window" },
	"runs.stuck.clearPerson": { en: "waiting on a person is never stuck: a named person owes the next act" },
	"runs.stuck.clearGate": { en: "the gate has not passed its own deadline by the stuck threshold" },
	"runs.stuck.finished": { en: "a finished run is never stuck" },
	"runs.stuck.clearMoved": { en: "the root moved inside {mins} min, no claim lapsed, the box and core agree, and no stranded finding stands", vars: { mins: "count" } },
	"runs.stuck.noReaper": { en: "no silence reaper times this run out: it has no live session or job to time, so the project master or a person ends it" },
	"runs.stuck.after": { en: "stuck after {mins} min: {detail}", vars: { mins: "count", detail: "said" } },
	"runs.holder.foreignClaim": { en: "the claim on {key} by {holder} was taken in {tree}, not in this run's worktree {worktree}, so it times nothing for this run", vars: { key: "key", holder: "name", tree: "name", worktree: "name" } },
	"runs.holder.claimIs": { en: "the claim on {key} is {verdict}: {detail}", vars: { key: "key", verdict: "code", detail: "text" } },
	"runs.holder.claimRule": { en: "issue_work_state.lease by {holder}: renewedAt + minutes", vars: { holder: "name" } },
	"runs.holder.claimRuleStopped": { en: "issue_work_state.lease by {holder}: renewedAt + minutes, stopped", vars: { holder: "name" } },
	"runs.holder.noDispatchedAt": { en: "the job is dispatched but carries no dispatched_at, so the ack reaper has no clock to start" },
	"runs.holder.reportedNoAck": { en: "the job is dispatched with job events but no ack: the ack reaper skips a job that has reported, and the heartbeat reaper needs a running session" },
	"runs.holder.ackClock": { en: "the loop monitor fails a dispatch no runner acked within {mins} min, after a {grace} s kill grace (dispatch_unclaimed); dispatched {at}", vars: { mins: "count", grace: "count", at: "instant" } },
	"runs.holder.sessionNotRunning": { en: "the job's session is {status}, and the heartbeat reaper only fails a running session", vars: { status: "code" } },
	"runs.holder.awaitingInput": { en: "the job's session is awaiting input, which the heartbeat reaper exempts, so no silence clock runs" },
	"runs.holder.notReaped": { en: "the job's session is not of a kind the heartbeat reaper sweeps, so no silence clock runs" },
	"runs.holder.noBeat": { en: "the job's session carries no beat, start or update time, so no silence clock runs" },
	"runs.holder.heartbeatClock": { en: "the loop monitor fails a running session silent for {mins} min (heartbeat_timeout); last beat {at}", vars: { mins: "count", at: "instant" } },
	"runs.holder.notPipeline": { en: "the job's session is queued but not a pipeline session, so the queue hop does not sweep it" },
	"runs.holder.turnClock": { en: "the loop monitor fails a queued session that beat once and reported no turn for {mins} min (turn_never_reported); last beat {at}", vars: { mins: "count", at: "instant" } },
	"runs.holder.noQueueTime": { en: "the job's queued session carries no dispatch or create time" },
	"runs.holder.queueClock": { en: "the loop monitor fails a queued session no worker claimed within {mins} min (queue_timeout); queued {at}", vars: { mins: "count", at: "instant" } },
	"runs.holder.resultClock": { en: "the loop monitor fails a job with no event or phase for {mins} min, after a {grace} s kill grace (stale); last progress {at}", vars: { mins: "count", grace: "count", at: "instant" } },
	"runs.holder.boxSilentClock": { en: "the run-session reaper fails a session silent for {mins} min (run_session_box_silent); last beat {at}", vars: { mins: "count", at: "instant" } },
	"runs.holder.masterClock": { en: "the master reaper clears the holds of a master silent for {mins} min; last beat {at}", vars: { mins: "count", at: "instant" } },
	"runs.holder.noMasterRoot": { en: "no master owns this run: it opened as a root, with no live master on its box and no master hold" },
	"runs.holder.passUnknown": { en: "no stored pass of this master spans the moment the run opened, so the pass that took it is not known" },
	"runs.holder.finished": { en: "a finished run holds nothing: its lease went with its end" },
	"runs.holder.runSession": { en: "Run session" },
	"runs.holder.job": { en: "{type} job", vars: { type: "code" } },
	"runs.holder.queued": { en: "no holder yet: the run is queued and no box or master has taken it" },
	"runs.holder.parked": { en: "parked: the run holds no box while a person owes the next act" },
	"runs.holder.gate": { en: "no holder: the run waits on a gate with no box taken" },
	"runs.holder.nothing": { en: "no live session, job or deploy lock holds this run" },
	"runs.holder.lockRule": { en: "deploy_locks.expires_at on {environment}: the next deploy reclaims the environment after it", vars: { environment: "name" } },
	"runs.holder.noClock": { en: "no claim, deploy lock or beat is readable for this holder, so no clock ends its hold" },
	"runs.step.earlier": { en: "issue_work_state.step reads {step} since {since}, before this run started at {started}: an earlier run or a park left it, and this run has reported no step of its own", vars: { step: "code", since: "instant", started: "instant" } },
	"runs.step.finished": { en: "{detail}; a finished run keeps no step of its own, as issue_work_state.step belongs to whichever run holds the issue now", vars: { detail: "said" } },
	"runs.title.release": { en: "Release {v}", vars: { v: "version" } },
	"runs.title.releaseBatch": { en: "Release batch" },
	"runs.title.deploy": { en: "Deploy {subject} to {environment}", vars: { subject: "name", environment: "name" } },
	"runs.title.run": { en: "Run" },
	"runs.attempt.noIssue": { en: "this run carries no issue, so no earlier run over the same work is counted" },
	"runs.master.none": { en: "no master owns this run: no parent master session and no master hold" },
	"runs.list.scopeRule": { en: "scope reads the pipeline run status: live is running or paused, finished is completed, failed or cancelled; a run whose own status is still live while its root ended is served under live as stuck, rule disagreement (run-live-root-ended)" },
	"runs.list.excludedChat": { en: "a chat's one-shot run is a conversation with a person, not an agent run" },
	"runs.list.excludedMaster": { en: "a resident master's own run is the master; `master` beside the list serves it from masters/standing" },
	"automation.state.off": { en: "paused: an off schedule is never claimed" },
	"automation.state.ownerGone": { en: "ownerId is null: the account it ran as is gone, so a prompt fire is refused SCHEDULE_OWNER_GONE until an admin saves it and takes it over" },
	"automation.state.failing": { en: "its last {n} fires failed, at or above scheduleFailStreak {limit} (a no-device or project-not-found skip counts, nothing-to-do and gate-refused do not); it clears on the next successful fire, not on an edit", vars: { n: "count", limit: "count" } },
	"automation.state.firing": { en: "its newest fire is running" },
	"automation.state.underStreak": { en: "{n} failed in a row, under scheduleFailStreak {limit} or outside the active window", vars: { n: "count", limit: "count" } },
	"automation.state.on": { en: "enabled, and its newest fire did not fail" },
	"overview.signal.ciNote": { en: "Core stores check runs for pull requests only, never for a branch head, so it holds no reading of dev itself." },
	"overview.signal.postMergeNote": { en: "A push to a gated branch carries its post-merge jobs on GitHub; core receives no event for them and stores none." },
	"overview.signal.noSlotsNote": { en: "No live master serves this project, so no box has declared slots for it." },
	"overview.record.waiting": { en: "{n} {issues} waiting", vars: { n: "count", issues: "agreement" } },
	"overview.record.notOnLive": { en: "{title} · {sha} not on {branch}", vars: { title: "text", sha: "code", branch: "name" } },
	"designs.gate.open": { en: "issues that build it may be dispatched: revision {r} is approved", vars: { r: "text" } },
	"designs.gate.held": { en: "issues that build it are held out of dispatch until a revision is approved; {why}", vars: { why: "said" } },
	"designs.gate.noApproval": { en: "the design has no approval yet" },
	"designs.gate.waitsApprover": { en: "revision {r} waits on its approver", vars: { r: "text" } },
	"designs.gate.status": { en: "the design is {status}", vars: { status: "code" } },
	"workflows.reconcile.unobserved": { en: "the code has not been observed against this design" },
	"workflows.reconcile.undecided": { en: "{n} marked node(s) wait on a keep, rewrite or delete decision", vars: { n: "count" } },
	"workflows.reconcile.cleaning": { en: "{n} decided node(s) wait on their build issue to close", vars: { n: "count" } },
	"workflows.reconcile.unbuilt": { en: "{n} decided node(s) have no build issue linked after the decision, and no approved revision adopting a kept one was observed", vars: { n: "count" } },
	"workflows.reconcile.nothingMarked": { en: "no node is marked or decided, so nothing waits on a reconciliation" },
	"workflows.reconcile.unreleased": { en: "{keys} is not in a released version yet", vars: { keys: "key" } },
	"workflows.reconcile.carried": { en: "every marked node is decided and {v} carried its builds", vars: { v: "version" } },
	"workflows.reconcile.kept": { en: "every decided node is kept by an approved revision the code was observed to match" },
} as const satisfies Record<string, SaidEntry>;
