// The templates about systems and data: system-context, the master list of systems the others name;
// integration-sequence, the calls between them; data-flow, where patient data goes; and
// decision-model, the table behind a rule.

import { WORKFLOW_TEMPLATE_SCHEMA_ID, type WorkflowTemplate } from './workflow-template-schema.js';

const T = WORKFLOW_TEMPLATE_SCHEMA_ID;

export const systemContext: WorkflowTemplate = {
  $schema: T,
  id: 'system-context',
  version: 1,
  title: 'System context',
  purpose:
    'Use when you are drawing where the product sits between its users and the systems around it (C4 levels 1 and 2): the people, the systems (who owns each), the containers that run, and how they talk — each relationship with its description and protocol (HL7v2, FHIR REST, webhook). It is the list of systems integration-sequence and data-flow designs name, so draw it first.',
  layout: { family: 'boundaries', direction: 'down' },
  lanes: { from: 'design', noun: 'boundary' },
  nodeTypes: [
    {
      id: 'PERSON',
      label: 'Person',
      tooltip: 'A role that uses the systems.',
      icon: 'user',
      colour: 'orange',
      required: ['label'],
    },
    {
      id: 'SYSTEM',
      label: 'System',
      tooltip: 'A software system, ours or outside, with its owner.',
      icon: 'server',
      colour: 'slate',
      required: ['label', 'owner'],
    },
    {
      id: 'CONTAINER',
      label: 'Container',
      tooltip: 'A thing that runs inside a system: an app, a database, a queue, a worker.',
      icon: 'cpu',
      colour: 'blue',
      required: ['label', 'purpose'],
    },
  ],
  edgeKinds: [
    {
      id: 'uses',
      label: 'Uses',
      tooltip: 'One talks to the other: what for (`label`), over what (`protocol`).',
      direction: 'forward',
      required: ['label', 'protocol'],
      line: 'solid',
      colour: 'neutral',
    },
    {
      id: 'reads-from',
      label: 'Reads from',
      tooltip: 'Reads an outside system.',
      direction: 'forward',
      required: ['label', 'protocol'],
      toTypes: ['SYSTEM'],
      line: 'dotted',
      colour: 'teal',
    },
    {
      id: 'writes-to',
      label: 'Writes to',
      tooltip: 'Writes into an outside system.',
      direction: 'forward',
      required: ['label', 'protocol'],
      toTypes: ['SYSTEM'],
      line: 'dashed',
      colour: 'amber',
    },
  ],
  defaultEdgeKind: 'uses',
  rules: ['acyclic'],
};

export const integrationSequence: WorkflowTemplate = {
  $schema: T,
  id: 'integration-sequence',
  version: 1,
  title: 'Integration sequence',
  purpose:
    "Use when you are drawing the calls between systems in order: who calls whom, sync or async, what each message carries, and what happens on a timeout or a failure. Every participant is a system of the project's system-context design.",
  layout: { family: 'lifeline', direction: 'down' },
  lanes: { from: 'none' },
  nodeTypes: [
    {
      id: 'PARTICIPANT',
      label: 'Participant',
      tooltip: 'A system or container taking part, as system-context names it.',
      icon: 'server',
      colour: 'slate',
      required: ['label'],
      entry: true,
      links: [
        {
          template: 'system-context',
          types: ['SYSTEM', 'CONTAINER'],
          required: true,
          tooltip: 'The system this participant is.',
        },
      ],
    },
    {
      id: 'MESSAGE',
      label: 'Message',
      tooltip: 'One call or event, with what it carries (`payload`).',
      icon: 'send',
      colour: 'blue',
      required: ['label', 'payload'],
    },
    {
      id: 'FRAGMENT',
      label: 'Fragment',
      tooltip: 'alt, opt, loop or par around messages, with its condition.',
      icon: 'git-branch',
      colour: 'violet',
      required: ['label', 'conditions'],
    },
    {
      id: 'NOTE',
      label: 'Note',
      tooltip: 'A remark on the sequence.',
      icon: 'flag',
      colour: 'neutral',
      required: ['label'],
    },
  ],
  edgeKinds: [
    {
      id: 'sync',
      label: 'Sync call',
      tooltip:
        'A call that waits for its reply; it retries once, safely (`idempotency`), and says what a failure does.',
      direction: 'forward',
      required: ['label', 'idempotency', 'onFailure'],
      line: 'solid',
      colour: 'neutral',
    },
    {
      id: 'async',
      label: 'Async call',
      tooltip: 'A call that does not wait.',
      direction: 'forward',
      required: ['label', 'onFailure'],
      line: 'dashed',
      colour: 'blue',
    },
    {
      id: 'reply',
      label: 'Reply',
      tooltip: 'The answer to a call.',
      direction: 'forward',
      required: ['label'],
      line: 'dotted',
      colour: 'neutral',
    },
    {
      id: 'event',
      label: 'Event',
      tooltip: 'Published for whoever listens.',
      direction: 'forward',
      required: ['label'],
      line: 'dashed',
      colour: 'orange',
    },
  ],
  defaultEdgeKind: 'sync',
  rules: ['acyclic'],
};

export const dataFlow: WorkflowTemplate = {
  $schema: T,
  id: 'data-flow',
  version: 1,
  title: 'Data flow',
  purpose:
    "Use when you are drawing where patient data goes: the source systems it comes from, the datasets it lands in (each with its owner), the processes that move it and the outside parties it reaches, inside the trust boundaries the design declares in `lanes` (hospital, product, outside channels). Its shape is OpenLineage's jobs and datasets; every source is a system of the project's system-context design.",
  layout: { family: 'boundaries', direction: 'right' },
  lanes: { from: 'design', noun: 'trust boundary' },
  nodeTypes: [
    {
      id: 'SOURCE_SYSTEM',
      label: 'Source system',
      tooltip: 'Where the data is first recorded, as system-context names it.',
      icon: 'database',
      colour: 'slate',
      required: ['label'],
      entry: true,
      links: [
        {
          template: 'system-context',
          types: ['SYSTEM'],
          required: true,
          tooltip: 'The system this source is.',
        },
      ],
    },
    {
      id: 'DATASET',
      label: 'Dataset',
      tooltip: 'Data at rest, with the role that owns it.',
      icon: 'table',
      colour: 'indigo',
      required: ['label', 'owner'],
    },
    {
      id: 'PROCESS',
      label: 'Process',
      tooltip: 'A job that reads, derives or publishes data.',
      icon: 'refresh',
      colour: 'blue',
      required: ['label'],
    },
    {
      id: 'EXTERNAL_ENTITY',
      label: 'Outside party',
      tooltip: 'Someone outside the boundaries the data reaches: a channel, a partner.',
      icon: 'send',
      colour: 'orange',
      required: ['label'],
    },
  ],
  edgeKinds: [
    {
      id: 'reads',
      label: 'Reads',
      tooltip: 'A process reads data.',
      direction: 'forward',
      required: ['label'],
      fromTypes: ['SOURCE_SYSTEM', 'DATASET'],
      toTypes: ['PROCESS'],
      line: 'solid',
      colour: 'neutral',
    },
    {
      id: 'writes',
      label: 'Writes',
      tooltip: 'A process writes a dataset.',
      direction: 'forward',
      required: ['label'],
      fromTypes: ['PROCESS'],
      toTypes: ['DATASET'],
      line: 'solid',
      colour: 'blue',
    },
    {
      id: 'derives',
      label: 'Derives',
      tooltip: 'A dataset is derived from another.',
      direction: 'forward',
      required: ['label'],
      fromTypes: ['DATASET'],
      toTypes: ['DATASET'],
      line: 'dotted',
      colour: 'indigo',
    },
    {
      id: 'publishes',
      label: 'Publishes',
      tooltip: 'Data leaves to an outside party.',
      direction: 'forward',
      required: ['label'],
      fromTypes: ['PROCESS', 'DATASET'],
      toTypes: ['EXTERNAL_ENTITY'],
      line: 'dashed',
      colour: 'orange',
    },
  ],
  defaultEdgeKind: 'reads',
  rules: ['acyclic'],
};

export const decisionModel: WorkflowTemplate = {
  $schema: T,
  id: 'decision-model',
  version: 1,
  title: 'Decision model',
  purpose:
    'Use when you are drawing how one decision is reached: the decision and its table (inputs, `conditions` rows, outputs), the input data it takes, the policy it follows and the reusable logic it calls (DMN-lite). A decision tree is a view of the table.',
  layout: { family: 'decision-model', direction: 'down' },
  lanes: { from: 'none' },
  nodeTypes: [
    {
      id: 'DECISION',
      label: 'Decision',
      tooltip: 'A decision and its table: inputs, one row per case, outputs.',
      icon: 'diamond',
      colour: 'violet',
      required: ['label', 'inputs', 'conditions', 'outputs'],
    },
    {
      id: 'INPUT_DATA',
      label: 'Input data',
      tooltip: 'Data the decision takes.',
      icon: 'database',
      colour: 'teal',
      required: ['label'],
      entry: true,
      links: [
        {
          template: 'operational-flow',
          types: ['CONTEXT', 'ENTITY'],
          required: false,
          tooltip: 'The context or record of the operational flow this data is.',
        },
      ],
    },
    {
      id: 'KNOWLEDGE_SOURCE',
      label: 'Knowledge source',
      tooltip: 'The policy or guideline the decision follows, and who owns it.',
      icon: 'flag',
      colour: 'amber',
      required: ['label', 'owner'],
      entry: true,
    },
    {
      id: 'BKM',
      label: 'Business knowledge',
      tooltip: 'Reusable decision logic: a function more than one decision calls.',
      icon: 'filter',
      colour: 'indigo',
      required: ['label'],
      entry: true,
    },
  ],
  edgeKinds: [
    {
      id: 'requires-info',
      label: 'Requires',
      tooltip: 'The decision takes this data, or another decision’s answer.',
      direction: 'forward',
      required: [],
      fromTypes: ['INPUT_DATA', 'DECISION'],
      toTypes: ['DECISION'],
      line: 'solid',
      colour: 'neutral',
    },
    {
      id: 'requires-knowledge',
      label: 'Calls',
      tooltip: 'The decision calls reusable logic.',
      direction: 'forward',
      required: [],
      fromTypes: ['BKM'],
      toTypes: ['DECISION', 'BKM'],
      line: 'dashed',
      colour: 'indigo',
    },
    {
      id: 'authority',
      label: 'Governed by',
      tooltip: 'The policy the decision or logic follows.',
      direction: 'forward',
      required: [],
      fromTypes: ['KNOWLEDGE_SOURCE'],
      toTypes: ['DECISION', 'BKM'],
      line: 'dotted',
      colour: 'amber',
    },
  ],
  defaultEdgeKind: 'requires-info',
  rules: ['acyclic'],
};
