// The kernel's built-in diagram templates, each versioned: a changed one is a new version, so a
// design drawn in an old one keeps reading the vocabulary it was approved in.

import {
  type TemplateRef,
  WORKFLOW_TEMPLATE_SCHEMA_ID,
  type WorkflowTemplate,
} from './workflow-template-schema.js';

const T = WORKFLOW_TEMPLATE_SCHEMA_ID;

const journeyBands: WorkflowTemplate = {
  $schema: T,
  id: 'journey-bands',
  version: 1,
  title: 'Journey in bands',
  purpose:
    'Use when you are drawing an operational journey a business runs end to end — a source event, the facts and context read about it, the rules that decide, the case and tasks people work, what they do, the result, and the feedback that re-checks the rules. Each band is a question an approver asks; HOP-style post-care journeys are drawn in it.',
  layout: { family: 'layered-bands', direction: 'down' },
  lanes: {
    from: 'template',
    bands: [
      {
        id: 'trigger',
        label: 'Trigger',
        tooltip: 'What starts it.',
        types: ['EVENT', 'STEP'],
      },
      {
        id: 'understand',
        label: 'Understand',
        tooltip: 'The facts and context read about the subject.',
        types: ['CONTEXT', 'STEP'],
      },
      {
        id: 'decide',
        label: 'Decide',
        tooltip: 'The rules, the state they derive, and the target to meet.',
        types: ['RULE', 'STATE', 'EXPECTATION', 'STEP'],
      },
      {
        id: 'organise',
        label: 'Organise work',
        tooltip: 'The case, the tasks, their owners and deadlines, and what is late.',
        types: ['CASE', 'TASK', 'ATTENTION', 'STEP'],
      },
      {
        id: 'act',
        label: 'Act',
        tooltip: 'What people actually do.',
        types: ['ACTION', 'STEP'],
      },
      {
        id: 'result',
        label: 'Result',
        tooltip: 'What happened.',
        types: ['OUTCOME', 'STEP'],
      },
      {
        id: 'feedback',
        label: 'Feedback',
        tooltip: 'Learn from the result and re-check the rules.',
        types: ['CONTEXT', 'RULE', 'STATE', 'STEP'],
      },
      {
        id: 'close',
        label: 'Close',
        tooltip: 'Done.',
        types: ['OUTCOME', 'STEP'],
      },
    ],
  },
  nodeTypes: [
    {
      id: 'EVENT',
      label: 'Event',
      tooltip: 'Something happened in a source system that starts the flow.',
      icon: 'bolt',
      colour: 'orange',
      required: ['outputs'],
      band: 'trigger',
    },
    {
      id: 'CONTEXT',
      label: 'Context',
      tooltip: 'Who the subject is and what is known about them.',
      icon: 'user',
      colour: 'teal',
      required: ['inputs', 'outputs'],
      band: 'understand',
    },
    {
      id: 'RULE',
      label: 'Rule',
      tooltip:
        'Turns facts and context into decisions; its conditions are a rule table with tests.',
      icon: 'diamond',
      colour: 'violet',
      required: ['inputs', 'conditions', 'outputs', 'tests'],
      band: 'decide',
    },
    {
      id: 'STATE',
      label: 'State',
      tooltip: 'The operational status the rules derived, with its history.',
      icon: 'flag',
      colour: 'blue',
      required: ['outputs'],
      band: 'decide',
    },
    {
      id: 'EXPECTATION',
      label: 'Expectation',
      tooltip: 'What must happen next and by when; missing it raises attention.',
      icon: 'target',
      colour: 'amber',
      required: ['sla', 'expectedOutcome'],
      band: 'decide',
    },
    {
      id: 'CASE',
      label: 'Case',
      tooltip: 'One container tracking all the work for an episode until it closes.',
      icon: 'folder',
      colour: 'pink',
      required: ['owner', 'sla'],
      band: 'organise',
    },
    {
      id: 'TASK',
      label: 'Task',
      tooltip:
        'Work for a person, with an owner, a deadline, an expected outcome and what they may do.',
      icon: 'check-square',
      colour: 'green',
      required: ['owner', 'sla', 'expectedOutcome', 'permissions'],
      band: 'organise',
    },
    {
      id: 'ATTENTION',
      label: 'Attention',
      tooltip: 'Surfaces what needs a person now: overdue, unowned, unreachable.',
      icon: 'bell',
      colour: 'red',
      required: ['conditions', 'owner'],
      band: 'organise',
    },
    {
      id: 'ACTION',
      label: 'Action',
      tooltip: 'What staff actually did: a call, a message, a booking.',
      icon: 'arrow-right',
      colour: 'cyan',
      required: ['owner'],
      band: 'act',
    },
    {
      id: 'OUTCOME',
      label: 'Outcome',
      tooltip: 'The structured result of an action or of the case.',
      icon: 'check-circle',
      colour: 'emerald',
      required: ['outputs'],
      band: 'result',
    },
    {
      id: 'STEP',
      label: 'Step',
      tooltip: 'A plain step — a source read, a write — that is none of the journey types.',
      icon: 'database',
      colour: 'slate',
      required: [],
      band: 'understand',
    },
  ],
  defaultNodeType: 'STEP',
  edgeKinds: [
    {
      id: 'flow',
      label: 'Flow',
      tooltip: 'The journey moves on to the next step.',
      direction: 'forward',
      required: [],
      line: 'solid',
      colour: 'neutral',
    },
    {
      id: 'escalation',
      label: 'Escalation',
      tooltip: 'Raised to attention when its condition holds: late, unowned, unreachable.',
      direction: 'forward',
      required: ['condition'],
      line: 'dashed',
      colour: 'amber',
    },
    {
      id: 'feedback',
      label: 'Re-evaluate',
      tooltip: 'A later result returns to an earlier rule and re-checks it.',
      direction: 'return',
      required: ['reevaluates', 'condition', 'action', 'mapping', 'idempotency', 'onFailure'],
      line: 'dashed',
      colour: 'violet',
    },
  ],
  defaultEdgeKind: 'flow',
  rules: ['acyclic', 'band-order'],
};

const stateMachine: WorkflowTemplate = {
  $schema: T,
  id: 'state-machine',
  version: 1,
  title: 'State machine',
  purpose:
    'Use when you are drawing the states one thing moves through and the guarded transitions between them — an issue lifecycle, an order status, a document approval. One initial state, declared terminal states; a transition back (reopen) is a return.',
  layout: { family: 'state-machine', direction: 'down' },
  lanes: { from: 'none' },
  nodeTypes: [
    {
      id: 'STATE',
      label: 'State',
      tooltip:
        'A status the thing rests in; mark the one it starts in `initial` and the ones it ends in `terminal`.',
      icon: 'circle',
      colour: 'blue',
      required: ['purpose'],
    },
  ],
  defaultNodeType: 'STATE',
  edgeKinds: [
    {
      id: 'transition',
      label: 'Transition',
      tooltip: 'Moves to the next state when its guard (`condition`) holds.',
      direction: 'forward',
      required: ['condition'],
      line: 'solid',
      colour: 'neutral',
    },
    {
      id: 'back',
      label: 'Back',
      tooltip: 'Returns to an earlier state (reopen, rework) when its guard holds.',
      direction: 'return',
      required: ['condition'],
      line: 'dashed',
      colour: 'amber',
    },
  ],
  defaultEdgeKind: 'transition',
  rules: ['acyclic', 'single-initial', 'terminal-declared'],
};

const processSwimlanes: WorkflowTemplate = {
  $schema: T,
  id: 'process-swimlanes',
  version: 1,
  title: 'Process in swimlanes',
  purpose:
    'Use when you are drawing who does what in a business process — one lane per actor or system, the tasks each does, the gateways where it branches, and the events that start and end it (BPMN-lite). The design declares its lanes.',
  layout: { family: 'swimlane-actors', direction: 'right' },
  lanes: { from: 'design', noun: 'actor' },
  nodeTypes: [
    {
      id: 'START',
      label: 'Start',
      tooltip: 'The event that starts the process.',
      icon: 'play',
      colour: 'emerald',
      required: [],
    },
    {
      id: 'TASK',
      label: 'Task',
      tooltip: 'Work an actor does, with what it should produce.',
      icon: 'check-square',
      colour: 'green',
      required: ['expectedOutcome'],
    },
    {
      id: 'GATEWAY',
      label: 'Gateway',
      tooltip: 'Where the process branches; its conditions say which way.',
      icon: 'diamond',
      colour: 'violet',
      required: ['conditions'],
    },
    {
      id: 'EVENT',
      label: 'Event',
      tooltip: 'Something that happens mid-process: a timer, a message received.',
      icon: 'circle-dot',
      colour: 'orange',
      required: [],
    },
    {
      id: 'END',
      label: 'End',
      tooltip: 'Where the process ends.',
      icon: 'stop',
      colour: 'red',
      required: [],
    },
  ],
  edgeKinds: [
    {
      id: 'sequence',
      label: 'Sequence',
      tooltip: 'The next step in the process.',
      direction: 'forward',
      required: [],
      line: 'solid',
      colour: 'neutral',
    },
    {
      id: 'message',
      label: 'Message',
      tooltip: 'A hand-off to another lane.',
      direction: 'forward',
      required: ['action'],
      line: 'dashed',
      colour: 'blue',
    },
    {
      id: 'rework',
      label: 'Rework',
      tooltip: 'Back to an earlier step when its condition holds.',
      direction: 'return',
      required: ['condition'],
      line: 'dashed',
      colour: 'amber',
    },
  ],
  defaultEdgeKind: 'sequence',
  rules: ['acyclic', 'single-entry'],
};

const integrationSequence: WorkflowTemplate = {
  $schema: T,
  id: 'integration-sequence',
  version: 1,
  title: 'Integration sequence',
  purpose:
    'Use when you are drawing how systems talk to each other in time order — a source system (HIS) sending to a platform (HOP), what each receives, stores and answers, and the contract of every message: mapping, idempotency, what happens on failure. One lane per system, declared by the design.',
  layout: { family: 'sequence', direction: 'right' },
  lanes: { from: 'design', noun: 'system' },
  nodeTypes: [
    {
      id: 'SEND',
      label: 'Send',
      tooltip: 'A system sends a message or event.',
      icon: 'send',
      colour: 'orange',
      required: ['outputs'],
    },
    {
      id: 'RECEIVE',
      label: 'Receive',
      tooltip: 'A system receives and checks a message.',
      icon: 'inbox',
      colour: 'blue',
      required: ['inputs'],
    },
    {
      id: 'PROCESS',
      label: 'Process',
      tooltip: 'A system works on what it received.',
      icon: 'refresh',
      colour: 'slate',
      required: [],
    },
    {
      id: 'STORE',
      label: 'Store',
      tooltip: 'A system persists what it received or derived.',
      icon: 'database',
      colour: 'teal',
      required: ['outputs'],
    },
    {
      id: 'RESPOND',
      label: 'Respond',
      tooltip: 'A system answers the sender.',
      icon: 'arrow-right',
      colour: 'emerald',
      required: ['outputs'],
    },
  ],
  edgeKinds: [
    {
      id: 'message',
      label: 'Message',
      tooltip: 'A message between systems, with its whole contract.',
      direction: 'forward',
      required: ['mapping', 'idempotency', 'onFailure'],
      line: 'solid',
      colour: 'neutral',
    },
    {
      id: 'local',
      label: 'Local',
      tooltip: 'The same system goes on to its next step.',
      direction: 'forward',
      required: [],
      line: 'dotted',
      colour: 'neutral',
    },
    {
      id: 'retry',
      label: 'Retry',
      tooltip: 'A failed message is sent again from an earlier step.',
      direction: 'return',
      required: ['condition', 'idempotency', 'onFailure'],
      line: 'dashed',
      colour: 'amber',
    },
  ],
  defaultEdgeKind: 'local',
  rules: ['acyclic', 'single-entry'],
};

const decisionTree: WorkflowTemplate = {
  $schema: T,
  id: 'decision-tree',
  version: 1,
  title: 'Decision tree',
  purpose:
    'Use when you are drawing how one decision is reached — the questions asked in order, the branch each answer takes, and the rule tables (with tests) that settle it. Eligibility, triage, pricing rules.',
  layout: { family: 'decision-tree', direction: 'right' },
  lanes: { from: 'none' },
  nodeTypes: [
    {
      id: 'QUESTION',
      label: 'Question',
      tooltip: 'A question the decision asks; its conditions are the answers.',
      icon: 'diamond',
      colour: 'violet',
      required: ['inputs', 'conditions'],
    },
    {
      id: 'TABLE',
      label: 'Rule table',
      tooltip: 'A rule table: when … then … rows, with tests.',
      icon: 'table',
      colour: 'indigo',
      required: ['inputs', 'conditions', 'outputs', 'tests'],
    },
    {
      id: 'DECISION',
      label: 'Decision',
      tooltip: 'Where a branch ends: the decision reached.',
      icon: 'check-circle',
      colour: 'emerald',
      required: ['outputs'],
    },
  ],
  edgeKinds: [
    {
      id: 'branch',
      label: 'Branch',
      tooltip: 'The way taken when its answer holds.',
      direction: 'forward',
      required: ['condition'],
      line: 'solid',
      colour: 'neutral',
    },
  ],
  defaultEdgeKind: 'branch',
  rules: ['acyclic', 'single-entry', 'tree'],
};

const dataLineage: WorkflowTemplate = {
  $schema: T,
  id: 'data-lineage',
  version: 1,
  title: 'Data lineage',
  purpose:
    'Use when you are drawing where data comes from and where it goes — the sources, the transforms over them, the stores they land in, and who reads them — with the field mapping of every hop.',
  layout: { family: 'lineage', direction: 'right' },
  lanes: {
    from: 'template',
    bands: [
      {
        id: 'source',
        label: 'Sources',
        tooltip: 'Where the data is born.',
        types: ['SOURCE'],
      },
      {
        id: 'transform',
        label: 'Transforms',
        tooltip: 'What reshapes it.',
        types: ['TRANSFORM'],
      },
      {
        id: 'store',
        label: 'Stores',
        tooltip: 'Where it lands.',
        types: ['STORE'],
      },
      {
        id: 'consume',
        label: 'Consumers',
        tooltip: 'Who reads it.',
        types: ['CONSUMER'],
      },
    ],
  },
  nodeTypes: [
    {
      id: 'SOURCE',
      label: 'Source',
      tooltip: 'A system or file the data comes from.',
      icon: 'server',
      colour: 'orange',
      required: ['outputs', 'owner'],
      band: 'source',
    },
    {
      id: 'TRANSFORM',
      label: 'Transform',
      tooltip: 'A job or view that reshapes it.',
      icon: 'filter',
      colour: 'violet',
      required: ['inputs', 'outputs'],
      band: 'transform',
    },
    {
      id: 'STORE',
      label: 'Store',
      tooltip: 'A table, index or bucket it lands in.',
      icon: 'database',
      colour: 'teal',
      required: ['inputs', 'owner'],
      band: 'store',
    },
    {
      id: 'CONSUMER',
      label: 'Consumer',
      tooltip: 'A report, a screen, a model that reads it.',
      icon: 'eye',
      colour: 'blue',
      required: ['inputs'],
      band: 'consume',
    },
  ],
  edgeKinds: [
    {
      id: 'feeds',
      label: 'Feeds',
      tooltip: 'Data moves from one to the next, mapped field by field.',
      direction: 'forward',
      required: ['mapping'],
      line: 'solid',
      colour: 'neutral',
    },
  ],
  defaultEdgeKind: 'feeds',
  rules: ['acyclic', 'band-order'],
};

const uxFlow: WorkflowTemplate = {
  $schema: T,
  id: 'ux-flow',
  version: 1,
  title: 'UI/UX flow',
  purpose:
    "Use when you are drawing what a person sees and does on screen — the screens, the states each can fall into (empty, loading, error, no permission), the actions they take, the branches on their input, and the business steps their submits drive. Drawn in stage bands (Arrive · Interact · System · Result); each SCREEN names its persona from the design's `personas`, and each SYSTEM_STEP points at the step of another design it invokes.",
  layout: { family: 'layered-bands', direction: 'down' },
  lanes: {
    from: 'template',
    bands: [
      {
        id: 'arrive',
        label: 'Arrive',
        tooltip: 'Where the person lands.',
        types: ['SCREEN', 'DECISION'],
      },
      {
        id: 'interact',
        label: 'Interact',
        tooltip: 'What they see and do.',
        types: ['SCREEN', 'UI_STATE', 'USER_ACTION', 'DECISION'],
      },
      {
        id: 'system',
        label: 'System',
        tooltip: 'What the system does for them, and the business step it drives.',
        types: ['SYSTEM_STEP', 'DECISION'],
      },
      {
        id: 'result',
        label: 'Result',
        tooltip: 'Where they end up.',
        types: ['SCREEN', 'UI_STATE', 'EXIT'],
      },
    ],
  },
  nodeTypes: [
    {
      id: 'SCREEN',
      label: 'Screen',
      tooltip:
        'A screen: what it is for, who sees it, the data it shows and the actions it offers; `wireframe` names the board drawn for it.',
      icon: 'monitor',
      colour: 'blue',
      required: ['purpose', 'persona', 'dataShown', 'actions'],
      band: 'interact',
    },
    {
      id: 'UI_STATE',
      label: 'UI state',
      tooltip: 'A state a screen falls into: empty, loading, error or permission-denied.',
      icon: 'alert-triangle',
      colour: 'amber',
      required: ['variant'],
      band: 'interact',
    },
    {
      id: 'USER_ACTION',
      label: 'User action',
      tooltip: 'What the person does — its trigger and the validation it passes.',
      icon: 'pointer',
      colour: 'green',
      required: ['trigger', 'validation'],
      band: 'interact',
    },
    {
      id: 'DECISION',
      label: 'Decision',
      tooltip: "A branch on the person's input or permission.",
      icon: 'diamond',
      colour: 'violet',
      required: ['conditions'],
      band: 'interact',
    },
    {
      id: 'SYSTEM_STEP',
      label: 'System step',
      tooltip:
        'What the system does, pointing at the step of another design it drives (`invokes`).',
      icon: 'cpu',
      colour: 'slate',
      required: ['invokes'],
      band: 'system',
    },
    {
      id: 'EXIT',
      label: 'Exit',
      tooltip: 'Where the flow ends for the person.',
      icon: 'log-out',
      colour: 'emerald',
      required: [],
      band: 'result',
    },
  ],
  edgeKinds: [
    {
      id: 'navigate',
      label: 'Navigate',
      tooltip: 'The person moves on to the next screen or action.',
      direction: 'forward',
      required: [],
      toTypes: ['SCREEN', 'USER_ACTION', 'DECISION', 'EXIT'],
      line: 'solid',
      colour: 'neutral',
    },
    {
      id: 'submit',
      label: 'Submit',
      tooltip:
        'An action sends its payload to a system step; success and failure say where the person goes next.',
      direction: 'forward',
      required: ['payload', 'success', 'failure'],
      fromTypes: ['USER_ACTION'],
      toTypes: ['SYSTEM_STEP'],
      line: 'solid',
      colour: 'blue',
    },
    {
      id: 'error',
      label: 'Error',
      tooltip: 'Falls into a UI state when its condition holds.',
      direction: 'forward',
      required: ['condition'],
      toTypes: ['UI_STATE'],
      line: 'dashed',
      colour: 'red',
    },
    {
      id: 'back',
      label: 'Back',
      tooltip: 'The person goes back to an earlier screen.',
      direction: 'return',
      required: [],
      line: 'dashed',
      colour: 'neutral',
    },
  ],
  defaultEdgeKind: 'navigate',
  rules: [
    'acyclic',
    'screen-error-state',
    'submit-targets',
    'invokes-resolve',
    'personas-declared',
  ],
};

export const BUILTIN_WORKFLOW_TEMPLATES: readonly WorkflowTemplate[] = [
  journeyBands,
  stateMachine,
  processSwimlanes,
  integrationSequence,
  decisionTree,
  dataLineage,
  uxFlow,
];

/** The template a version 2 design written before templates is read in. */
export const LEGACY_V2_TEMPLATE: TemplateRef = {
  id: 'journey-bands',
  version: 1,
};
