// @generated by archmap 0.1.3 — vendored copy, do not edit
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { BASELINE_NAME } from './manifest.mjs';
import { evaluate } from './contracts/index.mjs';
import { VENDOR_DIR } from './install.mjs';
import * as ts from './providers/ts.mjs';
import * as go from './providers/go.mjs';

// cm:why the collect -> evaluate -> report pipeline lives HERE rather than in cli.mjs, where it
//   started: the pre-write hook has to reach the same verdict the CI gate would. A hook that
//   denies on rules CI does not enforce (or misses ones it does) is worse than no hook, and two
//   copies of this sequence is exactly how that drift happens.
// cm:edge lockstep -> src/install.mjs — every provider here must also be in MODULES, or the
//   vendored copy crashes on import and the gate cannot run at all.
export const PROVIDERS = { ts, go };

// cm:guard excluded unconditionally, never through the manifest's own `exclude` — a repo onboarded
//   by an older release carries that list frozen in its file, and would then scan the vendored copy
export const VENDOR_GLOB = `**/${VENDOR_DIR.split('/').join('/')}/**`;

export function loadBaseline(root) {
  const path = join(root, BASELINE_NAME);
  if (!existsSync(path)) return { entries: new Set(), present: false };
  try {
    const raw = JSON.parse(readFileSync(path, 'utf8'));
    return { entries: new Set(raw.frozen ?? []), present: true };
  } catch {
    return { entries: new Set(), present: false, unreadable: true };
  }
}

// cm:why the baseline key is the normalised EDGE, never file:line or a text hash — renaming a file,
//   moving code and reformatting must all be free. A line-keyed baseline unfreezes wholesale on
//   the first reflow, which is the failure this key shape exists to avoid.
export function baselineKey(f) {
  return `${f.contract}|${f.edge}`;
}

// cm:guard `timeoutMs` is a WALL-CLOCK budget for the whole collection, not a per-provider one. The
//   pre-write hook lives under a client-side timeout that kills it dead — no output at all, which is
//   the one outcome the hook's cannot-run contract says must never happen. Handing the full budget
//   to each provider in turn (and, inside the ts provider, to each cruise) is how N providers turn a
//   12s budget into N x 12s and blow a 15s ceiling.
export function collectGraph(manifest, roots, { timeoutMs } = {}) {
  const exclude = [...manifest.exclude, ...manifest.generated.globs];
  const deadline = timeoutMs ? Date.now() + timeoutMs : null;
  const remaining = () => (deadline === null ? undefined : Math.max(1, deadline - Date.now()));
  const results = [];
  const failures = [];
  // cm:why a provider's notes are surfaced even when it FAILED — "the synthesized tsconfig produced
  //   no output" is exactly the line that explains an otherwise inexplicable graph, and dropping it
  //   on the failure path hides the diagnosis in the one case that needs it.
  const notes = [];
  for (const [lang, provider] of Object.entries(PROVIDERS)) {
    const r = provider.collect({
      root: manifest.root,
      roots,
      exclude,
      timeoutMs: remaining(),
      tsConfig: manifest.tsConfig,
    });
    for (const n of r.notes ?? []) notes.push(`${lang}: ${n}`);
    if (!r.ok) failures.push(`${lang}: ${r.reason}`);
    else results.push(r);
  }
  return { results, failures, notes };
}

/**
 * The verdict object every surface renders. `evaluate` may throw ContractError — that is a gate
 * which COULD NOT RUN and the caller must map it to its own cannot-run signal, never to a clean
 * report.
 */
export function buildReport(manifest, graph, baseline, { failures = [], notes = [] } = {}) {
  const { findings, absent } = evaluate(manifest, graph);

  const fresh = [];
  let frozen = 0;
  for (const f of findings) {
    if (baseline.entries.has(baselineKey(f))) { frozen++; continue; }
    fresh.push(f);
  }

  const blocking = fresh.filter((f) => f.status === 'locked');
  const advisory = fresh.filter((f) => f.status !== 'locked');

  return {
    ok: blocking.length === 0,
    coverage: graph.coverage,
    graph: { edgeCount: graph.edges.length },
    contractCount: manifest.contracts.length,
    unresolvable: graph.unresolvable,
    unresolvableStats: graph.unresolvableStats,
    blocking,
    advisory,
    frozen,
    // cm:why absent is separate from blocking/advisory and `ok` ignores it on purpose (SPEC §3),
    //   but it is COUNTED — an unevaluated-looking zero is what ISS-2 removed.
    absent,
    absentCount: absent.length,
    fanOut: tallyFanOut(graph),
    remedies: Object.fromEntries(fresh.map((f) => [f.type, f.remedy])),
    policy: fresh[0]?.policy ?? '',
    providerFailures: failures,
    providerNotes: notes,
  };
}

export function tallyFanOut(graph) {
  const reach = new Map();
  for (const e of graph.edges) {
    if (!e.toModule || e.fromModule === e.toModule) continue;
    if (!reach.has(e.fromFile)) reach.set(e.fromFile, new Set());
    reach.get(e.fromFile).add(e.toModule);
  }
  const hist = new Map();
  for (const mods of reach.values()) hist.set(mods.size, (hist.get(mods.size) ?? 0) + 1);
  return [...hist.entries()].sort((a, b) => a[0] - b[0]);
}
