use std::path::{Path, PathBuf};

// Capture the build target triple so the updater can pick the matching release
// asset at runtime (e.g. "x86_64-unknown-linux-gnu").
fn main() {
    let target = std::env::var("TARGET").unwrap_or_default();
    println!("cargo:rustc-env=FORGE_RUNNER_TARGET={target}");

    embed_bundled_skills();
}

/// Generate the `BUNDLED_FILES` table read by `workspace::bundled_skills` from
/// whatever lives under `packages/runner/skills/`. Walking the tree at build
/// time (rather than hand-listing paths) is what stops a newly added skill file
/// from being silently absent at runtime — the failure mode a manual list has.
fn embed_bundled_skills() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let skills_dir = manifest_dir
        .join("..")
        .join("..")
        .join("skills")
        .canonicalize()
        .expect("packages/runner/skills must exist — it is the source of the bundled skill set");

    println!("cargo:rerun-if-changed={}", skills_dir.display());

    let mut files = Vec::new();
    collect(&skills_dir, &skills_dir, &mut files);
    files.sort();

    let mut out = String::from(
        "// @generated by build.rs from packages/runner/skills — do not edit.\n\
         pub static BUNDLED_FILES: &[(&str, &str)] = &[\n",
    );
    for (rel, abs) in &files {
        println!("cargo:rerun-if-changed={}", abs.display());
        out.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            rel,
            abs.display().to_string()
        ));
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("bundled_skills.rs");
    std::fs::write(&dest, out).expect("write generated bundled skill table");
}

fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.filter_map(Result::ok) {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, out);
        } else if path.extension().is_some_and(|e| e == "md") {
            let rel = path
                .strip_prefix(root)
                .expect("walked path is under root")
                .to_string_lossy()
                .replace('\\', "/");
            // Only files INSIDE a skill directory are part of a skill. A file
            // at the root (the dir's own README) has no owning skill, and
            // embedding it would invent one named after the file.
            if rel.contains('/') {
                out.push((rel, path));
            }
        }
    }
}
