// AUTO-GENERATED by scripts/gen-help-content.mjs from content/help/. Do not edit.
// Run `pnpm gen:help` (or it runs automatically on dev/build).
export const HELP_SLUGS: readonly string[] = [
  "connect-an-assistant/claude-code",
  "connect-an-assistant/claude-desktop",
  "connect-an-assistant/cursor",
  "connect-an-assistant/other-apps",
  "connect-an-assistant/what-this-does",
  "connect-an-assistant/what-you-can-ask",
  "connect-an-assistant/when-it-does-not-work",
  "file-a-request",
  "getting-started",
  "issue-statuses",
  "manage-your-organization",
  "pair-a-runner",
  "troubleshooting",
  "what-done-means"
];
