// AUTO-GENERATED by scripts/gen-help-content.mjs from content/help/. Do not edit.
// Run `pnpm gen:help` (or it runs automatically on dev/build).
export const HELP_SLUGS: readonly string[] = [
  "file-a-request",
  "getting-started",
  "issue-statuses",
  "manage-your-organization",
  "pair-a-runner",
  "troubleshooting",
  "what-done-means"
];
