ALTER TABLE "criterion_verdicts" DROP CONSTRAINT "criterion_verdicts_identity_chk";--> statement-breakpoint
ALTER TABLE "criterion_verdicts" ADD COLUMN "storefront_workflow_id" text;--> statement-breakpoint
ALTER TABLE "criterion_verdicts" ADD COLUMN "storefront_draft_version" text;--> statement-breakpoint
ALTER TABLE "criterion_verdicts" ADD COLUMN "storefront_environment" text;--> statement-breakpoint
ALTER TABLE "criterion_verdicts" ADD COLUMN "corroboration" text;--> statement-breakpoint
ALTER TABLE "criterion_verdicts" ADD COLUMN "corroboration_note" text;--> statement-breakpoint
ALTER TABLE "criterion_verdicts" ADD CONSTRAINT "criterion_verdicts_storefront_chk" CHECK (("criterion_verdicts"."identity_kind" = 'storefront_draft' AND "criterion_verdicts"."storefront_workflow_id" ~ '^[A-Za-z0-9][A-Za-z0-9_-]{0,99}$' AND "criterion_verdicts"."storefront_draft_version" ~ '^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$' AND "criterion_verdicts"."storefront_environment" ~ '^[a-z][a-z0-9-]{0,62}$' AND "criterion_verdicts"."corroboration" IN ('corroborated', 'uncorroborated') AND ("criterion_verdicts"."corroboration" = 'corroborated' OR coalesce("criterion_verdicts"."corroboration_note", '') ~ '[^[:space:]]'))
        OR ("criterion_verdicts"."identity_kind" IS DISTINCT FROM 'storefront_draft' AND "criterion_verdicts"."storefront_workflow_id" IS NULL AND "criterion_verdicts"."storefront_draft_version" IS NULL AND "criterion_verdicts"."storefront_environment" IS NULL AND "criterion_verdicts"."corroboration" IS NULL AND "criterion_verdicts"."corroboration_note" IS NULL));--> statement-breakpoint
ALTER TABLE "criterion_verdicts" ADD CONSTRAINT "criterion_verdicts_identity_chk" CHECK (("criterion_verdicts"."identity_kind" IS NULL AND "criterion_verdicts"."commit_sha" IS NULL AND "criterion_verdicts"."runtime_ref" IS NULL AND "criterion_verdicts"."design_workflow_id" IS NULL AND "criterion_verdicts"."design_revision" IS NULL AND "criterion_verdicts"."contract_ref" IS NULL AND "criterion_verdicts"."contract_version" IS NULL)
        OR ("criterion_verdicts"."identity_kind" = 'commit' AND "criterion_verdicts"."commit_sha" ~ '^[0-9a-f]{40}$' AND "criterion_verdicts"."runtime_ref" IS NULL AND "criterion_verdicts"."design_workflow_id" IS NULL AND "criterion_verdicts"."design_revision" IS NULL AND "criterion_verdicts"."contract_ref" IS NULL AND "criterion_verdicts"."contract_version" IS NULL)
        OR ("criterion_verdicts"."identity_kind" = 'commit_unresolved' AND "criterion_verdicts"."backfilled" AND "criterion_verdicts"."commit_sha" ~ '^[0-9a-f]{7,39}$' AND "criterion_verdicts"."runtime_ref" IS NULL AND "criterion_verdicts"."design_workflow_id" IS NULL AND "criterion_verdicts"."design_revision" IS NULL AND "criterion_verdicts"."contract_ref" IS NULL AND "criterion_verdicts"."contract_version" IS NULL)
        OR ("criterion_verdicts"."identity_kind" = 'runtime' AND "criterion_verdicts"."runtime_ref" ~ '^[0-9a-f]{40,64}$' AND "criterion_verdicts"."commit_sha" IS NULL AND "criterion_verdicts"."design_workflow_id" IS NULL AND "criterion_verdicts"."design_revision" IS NULL AND "criterion_verdicts"."contract_ref" IS NULL AND "criterion_verdicts"."contract_version" IS NULL)
        OR ("criterion_verdicts"."identity_kind" = 'design' AND "criterion_verdicts"."design_workflow_id" IS NOT NULL AND "criterion_verdicts"."design_revision" >= 1 AND "criterion_verdicts"."commit_sha" IS NULL AND "criterion_verdicts"."runtime_ref" IS NULL AND "criterion_verdicts"."contract_ref" IS NULL AND "criterion_verdicts"."contract_version" IS NULL)
        OR ("criterion_verdicts"."identity_kind" = 'contract' AND "criterion_verdicts"."contract_ref" ~ '[^[:space:]]' AND "criterion_verdicts"."contract_version" ~ '[^[:space:]]' AND "criterion_verdicts"."commit_sha" IS NULL AND "criterion_verdicts"."runtime_ref" IS NULL AND "criterion_verdicts"."design_workflow_id" IS NULL AND "criterion_verdicts"."design_revision" IS NULL)
        OR ("criterion_verdicts"."identity_kind" = 'storefront_draft' AND "criterion_verdicts"."commit_sha" IS NULL AND "criterion_verdicts"."runtime_ref" IS NULL AND "criterion_verdicts"."design_workflow_id" IS NULL AND "criterion_verdicts"."design_revision" IS NULL AND "criterion_verdicts"."contract_ref" IS NULL AND "criterion_verdicts"."contract_version" IS NULL));