-- ISS-185: one delivery row per (event, consumer). Each row carries its own status, attempts, next
-- attempt, lease and last error, so one consumer failing never retries or blocks the others, and a
-- delivery that runs out of attempts is `dead` rather than left unprocessed for ever. The event row
-- keeps only the event; `seq` orders an issue's events for each consumer.
ALTER TABLE "pipeline_outbox" ADD COLUMN "seq" bigint;--> statement-breakpoint
UPDATE "pipeline_outbox" o SET "seq" = n."rn"
  FROM (SELECT "id", row_number() OVER (ORDER BY "created_at", "id") AS "rn" FROM "pipeline_outbox") n
 WHERE n."id" = o."id";--> statement-breakpoint
ALTER TABLE "pipeline_outbox" ALTER COLUMN "seq" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "pipeline_outbox" ALTER COLUMN "seq" ADD GENERATED BY DEFAULT AS IDENTITY;--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('"pipeline_outbox"', 'seq'), coalesce((SELECT max("seq") FROM "pipeline_outbox"), 0) + 1, false);--> statement-breakpoint
CREATE TABLE "outbox_deliveries" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "event_id" uuid NOT NULL,
  "consumer" text NOT NULL,
  "issue_id" uuid,
  "seq" bigint NOT NULL,
  "status" text DEFAULT 'pending' NOT NULL,
  "attempts" integer DEFAULT 0 NOT NULL,
  "next_attempt_at" timestamp with time zone DEFAULT now() NOT NULL,
  "leased_until" timestamp with time zone,
  "lease_token" uuid,
  "last_error" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "delivered_at" timestamp with time zone,
  "dead_at" timestamp with time zone,
  CONSTRAINT "outbox_deliveries_status_chk" CHECK ("status" IN ('pending', 'delivered', 'dead'))
);--> statement-breakpoint
ALTER TABLE "outbox_deliveries" ADD CONSTRAINT "outbox_deliveries_event_id_pipeline_outbox_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."pipeline_outbox"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "outbox_deliveries_event_consumer_uq" ON "outbox_deliveries" USING btree ("event_id","consumer");--> statement-breakpoint
CREATE INDEX "outbox_deliveries_due_idx" ON "outbox_deliveries" USING btree ("next_attempt_at") WHERE "status" = 'pending';--> statement-breakpoint
CREATE INDEX "outbox_deliveries_issue_order_idx" ON "outbox_deliveries" USING btree ("consumer","issue_id","seq") WHERE "status" = 'pending' AND "issue_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "outbox_deliveries_dead_idx" ON "outbox_deliveries" USING btree ("dead_at") WHERE "status" = 'dead';--> statement-breakpoint
CREATE INDEX "outbox_deliveries_delivered_idx" ON "outbox_deliveries" USING btree ("delivered_at") WHERE "status" = 'delivered';--> statement-breakpoint

-- An undelivered event gets a delivery for each declared consumer not yet through
-- (`@forge/contracts/outbox-consumers:OUTBOX_CONSUMERS`). One the old worker had given up on (three
-- attempts) is dead, so it is raised and can be replayed; a delivered event gets none. A type with no
-- declared consumer aborts here rather than leaving its rows undelivered.
DO $$
DECLARE orphan text;
BEGIN
  SELECT o."type" INTO orphan FROM "pipeline_outbox" o
   WHERE o."processed_at" IS NULL
     AND o."type" NOT IN ('comment.created', 'comment.deleted', 'comment.mentioned', 'comment.updated', 'dependency.changed', 'error.sighted', 'integration.changed', 'issue.created', 'issue.transitioned', 'issue.updated', 'job.transitioned', 'notification.created', 'notification.read', 'question.answered', 'run.transitioned', 'runner.provisionRequested', 'runner.provisionStatus', 'schedule.fired', 'skill.globalUpdated', 'skill.registered', 'skill.syncRequested', 'source.merged', 'source.pushed', 'source.reviewed', 'task.created', 'task.deleted', 'task.updated', 'user.preferencesChanged')
   LIMIT 1;
  IF orphan IS NOT NULL THEN
    RAISE EXCEPTION 'pipeline_outbox holds an undelivered % event, and no consumer is declared for that type', orphan;
  END IF;
END $$;--> statement-breakpoint
INSERT INTO "outbox_deliveries"
  ("event_id", "consumer", "issue_id", "seq", "status", "attempts", "last_error", "dead_at", "created_at")
SELECT o."id", d."consumer", o."issue_id", o."seq",
       CASE WHEN o."attempts" >= 3 THEN 'dead' ELSE 'pending' END,
       o."attempts", o."last_error",
       CASE WHEN o."attempts" >= 3 THEN now() END,
       o."created_at"
  FROM "pipeline_outbox" o
  JOIN (VALUES
  ('issue.created', 'ws-broadcast'),
  ('issue.created', 'activity-feed'),
  ('issue.created', 'pipeline-orchestrator'),
  ('issue.created', 'master-wake'),
  ('issue.created', 'memory-indexer'),
  ('issue.updated', 'ws-broadcast'),
  ('issue.updated', 'activity-feed'),
  ('issue.updated', 'memory-indexer'),
  ('issue.transitioned', 'ws-broadcast'),
  ('issue.transitioned', 'activity-feed'),
  ('issue.transitioned', 'pipeline-orchestrator'),
  ('issue.transitioned', 'master-wake'),
  ('issue.transitioned', 'notify-transitions'),
  ('issue.transitioned', 'outbound-webhooks'),
  ('issue.transitioned', 'pm'),
  ('issue.transitioned', 'memory-reconcile'),
  ('job.transitioned', 'pm'),
  ('job.transitioned', 'phase-journal-close'),
  ('job.transitioned', 'memory-extraction'),
  ('run.transitioned', 'paused-run-wedge-resolve'),
  ('run.transitioned', 'release-batch-claims'),
  ('dependency.changed', 'pm'),
  ('comment.created', 'activity-feed'),
  ('comment.created', 'master-wake'),
  ('comment.created', 'rocketchat-comment-mirror'),
  ('comment.updated', 'activity-feed'),
  ('comment.deleted', 'activity-feed'),
  ('comment.mentioned', 'activity-feed'),
  ('comment.mentioned', 'notify-mentions'),
  ('question.answered', 'answer-resume'),
  ('task.created', 'ws-broadcast'),
  ('task.updated', 'ws-broadcast'),
  ('task.deleted', 'ws-broadcast'),
  ('schedule.fired', 'ws-broadcast'),
  ('notification.created', 'ws-broadcast'),
  ('notification.read', 'ws-broadcast'),
  ('user.preferencesChanged', 'ws-broadcast'),
  ('skill.syncRequested', 'ws-broadcast'),
  ('skill.registered', 'ws-broadcast'),
  ('skill.globalUpdated', 'ws-broadcast'),
  ('runner.provisionRequested', 'ws-broadcast'),
  ('runner.provisionStatus', 'ws-broadcast'),
  ('source.pushed', 'ecosystem-land'),
  ('source.pushed', 'ecosystem-builder'),
  ('source.pushed', 'live-reading'),
  ('source.merged', 'issue-merge-stamp'),
  ('source.reviewed', 'review-note'),
  ('error.sighted', 'error-intake'),
  ('integration.changed', 'ws-broadcast')
  ) AS d("type", "consumer") ON d."type" = o."type"
 WHERE o."processed_at" IS NULL
   AND NOT (d."consumer" = ANY(o."delivered"));--> statement-breakpoint

DROP INDEX IF EXISTS "idx_outbox_unprocessed";--> statement-breakpoint
ALTER TABLE "pipeline_outbox" DROP COLUMN "delivered";--> statement-breakpoint
ALTER TABLE "pipeline_outbox" DROP COLUMN "processed_at";--> statement-breakpoint
ALTER TABLE "pipeline_outbox" DROP COLUMN "claimed_at";--> statement-breakpoint
ALTER TABLE "pipeline_outbox" DROP COLUMN "attempts";--> statement-breakpoint
ALTER TABLE "pipeline_outbox" DROP COLUMN "last_error";--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "pipeline_outbox_created_idx" ON "pipeline_outbox" USING btree ("created_at");
