//! Provision step — seed Forge orientation for human `claude` sessions opened in
//! a Forge-managed consumer repo (pipeline jobs are oriented separately via the
//! per-stage system preamble; see core `prompt/system.ts`).
//!
//! What it writes names ONE Forge instance (its projectId and slug), so it is
//! per-checkout and never something the repository's own history should carry:
//! the same repository can be worked from two Forge instances, and a run that
//! commits with `git add -A` would otherwise ship the other instance's ids.
//! So a file is written only where git ignores it — an untracked path plus a
//! line in the checkout's `info/exclude` — and a tracked file is never changed:
//!
//!   - `.forge/orientation.md` — the orientation itself. Untracked: written and
//!     excluded. Tracked with exactly these bytes: left alone. Tracked with any
//!     other bytes (a repository committing another instance's orientation):
//!     refused by name, and the committed copy is what the checkout keeps.
//!
//!   - the `@.forge/orientation.md` import — nothing is added where `CLAUDE.md`
//!     or `CLAUDE.local.md` already reaches orientation (a second import would
//!     expand the whole of it into every prompt twice). Otherwise it goes to
//!     `CLAUDE.local.md`, which Claude Code reads beside `CLAUDE.md` and which
//!     is per-checkout by name, so a committed `CLAUDE.md` is never edited. A
//!     tracked `CLAUDE.local.md` that lacks the import is refused by name.

use std::path::Path;

use crate::git_exclude::{self, Ignored};

/// Marks the Forge-managed block. Presence ⇒ already oriented.
const FORGE_BLOCK_MARKER: &str = "<!-- forge:orientation -->";

/// The line that actually reaches the harness. A file holding this is
/// already oriented, whether or not our marker is around it.
const FORGE_IMPORT: &str = "@.forge/orientation.md";

/// Where the orientation is written, relative to the checkout.
pub const ORIENTATION: &str = ".forge/orientation.md";

/// The per-checkout memory file the import goes to.
pub const LOCAL_IMPORT: &str = "CLAUDE.local.md";

/// Why orientation was not (wholly) written.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Refused {
    /// Writing would change a file the repository commits.
    WouldRewriteTracked {
        path: &'static str,
        why: &'static str,
    },
    /// The file could not be made one git ignores.
    NotIgnored { path: &'static str, detail: String },
    /// Reading or writing the file failed.
    Io { path: &'static str, error: String },
}

impl std::fmt::Display for Refused {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Refused::WouldRewriteTracked { path, why } => write!(
                f,
                "PROVISION_WOULD_REWRITE_TRACKED: {path} is committed in this repository and {why}. Forge writes its per-instance files only where git ignores them, so {path} was left as committed — remove it from the index (`git rm --cached {path}`) for this checkout to carry this Forge instance's orientation, or leave it as committed"
            ),
            Refused::NotIgnored { path, detail } => write!(
                f,
                "PROVISION_ORIENTATION_NOT_IGNORED: {path} was not written, because git could not be made to ignore it: {detail}"
            ),
            Refused::Io { path, error } => write!(f, "{path} could not be written: {error}"),
        }
    }
}

/// Full body of `.forge/orientation.md`. Deterministic for a given project so
/// re-provisioning produces byte-identical output (no git churn).
pub fn orientation_body(project_id: &str, slug: &str) -> String {
    format!(
        "# Forge orientation — {slug}\n\
\n\
<!-- Generated by Forge on device provision. Forge-owned; manual edits are overwritten. -->\n\
\n\
This repo is managed by **Forge** — the control plane for its issues, pipeline, and durable\n\
memory. Reach it through the REST API (`forge-runner api <path>`) or the `forge` CLI; the Forge MCP\n\
server in `.mcp.json` carries only what neither covers, and its instructions name those tools.\n\
\n\
- **projectId:** `{project_id}`  ·  **slug:** `{slug}`\n\
- **Recall memory FIRST** — project memory is NOT auto-loaded. Before any task needing\n\
  project context: `POST /api/memory/search {{ \"projectId\": \"{project_id}\", \"query\": <topic>, \"topK\": 5 }}`.\n\
  Treat hits as point-in-time — verify against live code/git before trusting.\n\
- Codebase & project knowledge: `GET /api/projects/{project_id}/knowledge` or `forge knowledge`.\n\
- Issues / tasks / status / dependencies: `forge issue`, `forge new`, `forge comment`, or\n\
  `/api/projects/{project_id}/issues` and `/api/issues/<id>`.\n\
- Before writing, rewriting, or tuning this project's pipeline skills, read the `forge-skills`\n\
  MCP prompt (the always-latest authoring guide).\n\
\n\
## Operating affordances\n\
Forge gives you a REST call for things agents routinely do in prose. When you hit the trigger,\n\
make the call — and avoid the red flag.\n\
\n\
An issue is a unit of WORK with a named deliverable and an owner, whose completion someone\n\
other than the author can verify. A note, a question, an audit finding and a record of\n\
something already done are NOT issues — the four admission gates and where each of those goes\n\
instead: guide `what-is-an-issue`.\n\
\n\
| When you need | Use | Red flag (DON'T) |\n\
|---|---|---|\n\
| Ordering between issues | Blocker known **at create time** → `POST /api/projects/:id/issues` with `relations:[{{ kind:'blocks', dependsOnId }}]` (edge committed BEFORE the `issue.created` event/dispatch — atomic). Both issues already exist → `POST /api/issues/<dependent>/dependencies {{ dependsOnId: <blocker>, kind:'blocks' }}` (retract with `validUntil` in the past). Verify with `GET /api/issues/<id>/dependencies`. | Prose instead of an edge (only a `blocks` edge gates dispatch) · setting a blocks edge AFTER an `open` create — the new issue can dispatch before the edge lands (race); send `relations` on the create or create at `draft` first |\n\
| To record a note, learning, or decision | `POST /api/memory` (durable business logic → repo `docs/`) | Filing it as an issue — `draft` or not, nobody browses the issue list for notes |\n\
| To queue work that must actually happen LATER | create an issue at `draft` | Creating it at `open` — that auto-triages and spawns a pipeline run |\n\
| To report an issue | fill `title`, `description`, `priority`, `category` | Pre-filling `plan`/`acceptanceCriteria` — on a staged project those are written by the clarify/plan steps, on an autonomous one by the driver's own phases |\n\
| To change the project's policy (`qa`, intake, a status's model or permission profile) | GET `/api/projects/:id/policy`, then PUT the whole document with the `baseRevision` you read | Writing it without reading it — a revision that moved is refused by name, never merged |\n\
| To write or change the project's own prose (build commands, a rule, a guide) | `PUT /api/projects/:id/knowledge/<slug>` or `forge knowledge write`, one entry per slug, `injection` deciding whether it reaches every prompt or is fetched on demand | Sending it to the project config as `projectFacts` — that key is refused by name |\n\
| Before you design / fix | `POST /api/memory/search` for prior conventions, gotchas, decisions | Skipping recall and rediscovering (or contradicting) settled work |\n\
| To park work that never started | leave it at `draft` | `on_hold` from `draft` — `on_hold` is a deliberate pause for ACTIVE work only |\n\
| To finish a fix made by hand, outside the pipeline | claim it shipped FIRST — `POST /api/issues/<id>/merge` (or Mark merged on the issue's Properties rail), naming where it landed — then move it to `awaiting_release`, where the release that claims it closes it, and capture a memory learning | Fixing it and forgetting — no merge record, no status move, no learning recorded · reaching for `closed` yourself: an issue closes only through a release that claimed it, and a direct close is refused by name (`CLOSE_ONLY_BY_RELEASE`) |\n\
| An issue you are working turns out NOT to be work (a note, a question, a duplicate, already done) | Act on it yourself — comment saying which gate it fails and where the content went, THEN `needs_info` if a human owes you requirements, or `dropped` if it is not work at all | Leaving it filed for someone else to find · reaching for `closed` — that says the work shipped, and only a release closes an issue (`CLOSE_ONLY_BY_RELEASE`) · moving status with no comment, so the next reader cannot tell why |\n\
| A bug, gap or defect you find WHILE working an issue | **Fix it now, in this issue**, and DECLARE it in your comment under `Extra fixes:` — extra work is REPORTED, never filed | Filing it instead of fixing it. A new `draft` is not a hand-off: nobody owns it, nothing ages it, and a two-minute fix becomes backlog nobody reads |\n\
| A residual genuinely out of reach (needs a human decision, or work no diff here can carry) | ONE of: a `blocks` edge onto the issue that would ship without it · a line in `docs/proposals/` · `needs_info` + `waitingKind` + `reason` when it blocks THIS issue | Filing a new issue to carry it — that is not one of the options. Equally: staying silent because none of the three fit — say it in a comment on the issue you are on |\n\
\n\
**Forge red flags:** prose-deps · open-then-block · open-as-note · draft-as-note · plan-by-hand · wholesale-config-clobber · skip-recall · on_hold-from-draft · fix-by-hand-and-forget · close-as-drop · silent-nonwork · file-instead-of-fix.\n",
    )
}

/// The fixed block that carries the import. Identical across every project (the
/// per-project details are imported from `.forge/orientation.md`).
fn import_block() -> String {
    format!(
        "{FORGE_BLOCK_MARKER}\n\
<!-- Forge-managed pointer (fixed). Project orientation lives in .forge/orientation.md. -->\n\
{FORGE_IMPORT}\n\
<!-- /forge:orientation -->\n",
    )
}

/// Whether git tracks `path` in `repo`; `false` outside a git work tree.
fn tracked(repo: &Path, path: &str) -> bool {
    std::process::Command::new("git")
        .arg("-C")
        .arg(repo)
        .args(["ls-files", "--error-unmatch", "--", path])
        .env_remove("GIT_DIR")
        .env_remove("GIT_WORK_TREE")
        .env_remove("GIT_INDEX_FILE")
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .is_ok_and(|s| s.success())
}

/// Make git ignore `path` before it is written there, by an anchored line in
/// the checkout's exclude file.
fn ignore(repo: &Path, path: &'static str) -> Result<(), Refused> {
    match git_exclude::ensure_ignored_by(repo, path, path, &format!("/{path}")) {
        Ok(Ignored::Yes { .. } | Ignored::NoGit) => Ok(()),
        Err(e) => Err(Refused::NotIgnored {
            path,
            detail: e.to_string(),
        }),
    }
}

fn write(repo: &Path, path: &'static str, body: &str) -> Result<(), Refused> {
    let at = repo.join(path);
    let io = |e: std::io::Error| Refused::Io {
        path,
        error: e.to_string(),
    };
    if let Some(dir) = at.parent() {
        std::fs::create_dir_all(dir).map_err(io)?;
    }
    std::fs::write(at, body).map_err(io)
}

/// Write the orientation and its import where git ignores them, never changing
/// a tracked file. The caller reports a refusal on the provision and goes on:
/// the checkout works without orientation, and says why it has none.
pub fn write_orientation(repo_path: &Path, project_id: &str, slug: &str) -> Result<(), Refused> {
    let body = orientation_body(project_id, slug);
    let held = std::fs::read_to_string(repo_path.join(ORIENTATION)).ok();
    if tracked(repo_path, ORIENTATION) {
        if held.as_deref() != Some(body.as_str()) {
            return Err(Refused::WouldRewriteTracked {
                path: ORIENTATION,
                why: "its content is not what this Forge instance writes (it names another project or another generator version)",
            });
        }
    } else if held.as_deref() != Some(body.as_str()) {
        ignore(repo_path, ORIENTATION)?;
        write(repo_path, ORIENTATION, &body)?;
    } else {
        ignore(repo_path, ORIENTATION)?;
    }

    let reaches = |name: &str| {
        std::fs::read_to_string(repo_path.join(name))
            .map(|s| s.contains(FORGE_IMPORT))
            .unwrap_or(false)
    };
    if reaches("CLAUDE.md") || reaches(LOCAL_IMPORT) {
        return Ok(());
    }
    if tracked(repo_path, LOCAL_IMPORT) {
        return Err(Refused::WouldRewriteTracked {
            path: LOCAL_IMPORT,
            why: "it lacks the `@.forge/orientation.md` import, which would have to be added to it",
        });
    }
    ignore(repo_path, LOCAL_IMPORT)?;
    let existing = std::fs::read_to_string(repo_path.join(LOCAL_IMPORT)).unwrap_or_default();
    let block = import_block();
    let next = if existing.trim().is_empty() {
        block
    } else {
        format!("{block}\n{existing}")
    };
    write(repo_path, LOCAL_IMPORT, &next)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;
    use std::process::Command;

    fn scratch(name: &str) -> PathBuf {
        let dir =
            std::env::temp_dir().join(format!("forge-orient-{name}-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn git(dir: &Path, args: &[&str]) -> String {
        let out = Command::new("git")
            .arg("-C")
            .arg(dir)
            .args(["-c", "user.email=t@example.invalid", "-c", "user.name=t"])
            .args(args)
            .env_remove("GIT_DIR")
            .env_remove("GIT_WORK_TREE")
            .env_remove("GIT_INDEX_FILE")
            .output()
            .unwrap();
        assert!(
            out.status.success(),
            "git {args:?}: {}",
            String::from_utf8_lossy(&out.stderr)
        );
        String::from_utf8_lossy(&out.stdout).into_owned()
    }

    fn repo_with(name: &str, files: &[(&str, &str)]) -> PathBuf {
        let repo = scratch(name);
        git(&repo, &["init", "-q"]);
        for (path, body) in files {
            let at = repo.join(path);
            std::fs::create_dir_all(at.parent().unwrap()).unwrap();
            std::fs::write(&at, body).unwrap();
            git(&repo, &["add", "--", path]);
        }
        if !files.is_empty() {
            git(&repo, &["commit", "-q", "-m", "committed"]);
        }
        repo
    }

    fn porcelain(repo: &Path) -> String {
        git(repo, &["status", "--porcelain", "--untracked-files=all"])
    }

    fn excluded(repo: &Path) -> String {
        std::fs::read_to_string(repo.join(".git/info/exclude")).unwrap_or_default()
    }

    #[test]
    fn epod_a_committed_orientation_of_another_instance_is_refused_and_left_as_committed() {
        let prod = orientation_body("68567cd4-0000-4000-8000-000000000000", "epodsystem-core");
        let repo = repo_with("epod", &[(".forge/orientation.md", &prod)]);
        let said = write_orientation(&repo, "73371520-e588-4540-a9b6-5b992344791d", "epod")
            .err()
            .map(|e| e.to_string())
            .expect("a tracked orientation this instance would change is refused");
        assert!(said.contains("PROVISION_WOULD_REWRITE_TRACKED"), "{said}");
        assert!(said.contains(".forge/orientation.md"), "{said}");
        assert_eq!(
            std::fs::read_to_string(repo.join(".forge/orientation.md")).unwrap(),
            prod
        );
        assert_eq!(porcelain(&repo), "");
    }

    #[test]
    fn a_committed_orientation_this_instance_would_write_is_left_alone() {
        let body = orientation_body("p-1", "same");
        let claude = format!("# Repo\n\n{FORGE_IMPORT}\n");
        let repo = repo_with(
            "same",
            &[(".forge/orientation.md", &body), ("CLAUDE.md", &claude)],
        );
        assert!(write_orientation(&repo, "p-1", "same").is_ok());
        assert_eq!(
            std::fs::read_to_string(repo.join("CLAUDE.md")).unwrap(),
            claude
        );
        assert!(!repo.join("CLAUDE.local.md").exists());
        assert_eq!(porcelain(&repo), "");
    }

    #[test]
    fn catalog_a_committed_claude_md_is_never_rewritten_and_the_import_goes_where_git_ignores_it() {
        let claude = "# Catalog API\n\nRun `php artisan test`.\n";
        let repo = repo_with("catalog", &[("CLAUDE.md", claude)]);
        assert!(
            write_orientation(&repo, "9208f825-a431-430e-8de1-b4cb3ccc45b1", "catalog-api").is_ok()
        );
        assert_eq!(
            std::fs::read_to_string(repo.join("CLAUDE.md")).unwrap(),
            claude
        );
        assert_eq!(
            std::fs::read_to_string(repo.join(".forge/orientation.md")).unwrap(),
            orientation_body("9208f825-a431-430e-8de1-b4cb3ccc45b1", "catalog-api")
        );
        let local = std::fs::read_to_string(repo.join("CLAUDE.local.md")).unwrap();
        assert!(local.contains(FORGE_IMPORT), "{local}");
        let ex = excluded(&repo);
        assert!(ex.lines().any(|l| l == "/.forge/orientation.md"), "{ex}");
        assert!(ex.lines().any(|l| l == "/CLAUDE.local.md"), "{ex}");
        assert_eq!(porcelain(&repo), "");
        // idempotent: a second provision adds nothing
        assert!(
            write_orientation(&repo, "9208f825-a431-430e-8de1-b4cb3ccc45b1", "catalog-api").is_ok()
        );
        assert_eq!(excluded(&repo), ex);
        assert_eq!(
            std::fs::read_to_string(repo.join("CLAUDE.local.md")).unwrap(),
            local
        );
    }

    #[test]
    fn a_fresh_repo_gets_its_orientation_untracked_and_excluded() {
        let repo = repo_with("fresh", &[]);
        assert!(write_orientation(&repo, "p-2", "fresh").is_ok());
        assert!(!repo.join("CLAUDE.md").exists());
        assert!(repo.join(".forge/orientation.md").exists());
        assert!(repo.join("CLAUDE.local.md").exists());
        assert_eq!(porcelain(&repo), "");
    }

    #[test]
    fn a_committed_claude_local_md_without_the_import_is_refused_by_name() {
        let local = "# mine\n";
        let repo = repo_with("local", &[("CLAUDE.local.md", local)]);
        let said = write_orientation(&repo, "p-3", "local")
            .err()
            .map(|e| e.to_string())
            .expect("refused");
        assert!(
            said.contains("PROVISION_WOULD_REWRITE_TRACKED") && said.contains("CLAUDE.local.md"),
            "{said}"
        );
        assert_eq!(
            std::fs::read_to_string(repo.join("CLAUDE.local.md")).unwrap(),
            local
        );
    }
}
