//! Provision step — seed Forge orientation for human `claude` sessions opened in
//! a Forge-managed consumer repo (pipeline jobs are oriented separately via the
//! per-stage system preamble; see core `prompt/system.ts`).
//!
//! Two artifacts, both NON-SECRET — so, unlike `.mcp.json` (which carries the
//! device token and is git-excluded), these are meant to be committed and shared
//! via git:
//!
//!   - `.forge/orientation.md` — Forge owns this file; it is fully overwritten on
//!     every provision. The content is deterministic in the project (projectId +
//!     slug + fixed pointers, nothing device-specific), so two boxes provisioning
//!     the same project write the same bytes.
//!
//!     It is NOT deterministic across versions of this crate, and the tree is
//!     only left clean when the committed copy already matches what
//!     `orientation_body` emits now. A hand edit to this file is lost at the next
//!     provision; the generator is the only place its content can be changed.
//!     On forge-dev the two had drifted apart on two table rows, so every
//!     provision dirtied `main` and silently reverted whichever row the generator
//!     lacked. Both rows are folded back here, and the test
//!     `this_repo_committed_orientation_matches_the_generator` is what keeps the
//!     paragraph above true rather than merely intended (ISS-1108).
//!
//!   - `CLAUDE.md` — gets ONE fixed, marker-delimited block prepended IFF the
//!     file does not already reach orientation. We never rewrite the rest of the
//!     file, never auto-commit, and never git-exclude it — a human commits the
//!     one-time diff. The block is a fixed `@import` pointer at the top, so the
//!     volatile details live in `.forge/orientation.md`, not in the project's
//!     CLAUDE.md.
//!
//!     "Already reaches orientation" is the import and not only our marker. A
//!     repo that wrote `@.forge/orientation.md` by hand and has no marker used to
//!     be given the block anyway, and the import is what the harness acts on — so
//!     the whole of orientation was then expanded into every prompt on that
//!     project twice, once per import. forge-dev's own CLAUDE.md carried the pair
//!     for as long as nobody counted them.

use std::path::Path;

use runner_platform::error::Result;

/// Marks the Forge-managed block in a consumer `CLAUDE.md`. Presence ⇒ already
/// oriented; we leave the file untouched.
const FORGE_BLOCK_MARKER: &str = "<!-- forge:orientation -->";

/// The line that actually reaches the harness. A `CLAUDE.md` holding this is
/// already oriented, whether or not our marker is around it.
const FORGE_IMPORT: &str = "@.forge/orientation.md";

/// Full body of `.forge/orientation.md`. Deterministic for a given project so
/// re-provisioning produces byte-identical output (no git churn).
pub fn orientation_body(project_id: &str, slug: &str) -> String {
    format!(
        "# Forge orientation — {slug}\n\
\n\
<!-- Generated by Forge on device provision. Forge-owned; manual edits are overwritten. -->\n\
\n\
This repo is managed by **Forge** — the control plane for its issues, pipeline, and durable\n\
memory. Reach it through the REST API (`forge-runner api <path>`) or the `forge` CLI; the Forge MCP\n\
server in `.mcp.json` carries only what neither covers, and its instructions name those tools.\n\
\n\
- **projectId:** `{project_id}`  ·  **slug:** `{slug}`\n\
- **Recall memory FIRST** — project memory is NOT auto-loaded. Before any task needing\n\
  project context: `POST /api/memory/search {{ \"projectId\": \"{project_id}\", \"query\": <topic>, \"topK\": 5 }}`.\n\
  Treat hits as point-in-time — verify against live code/git before trusting.\n\
- Codebase & project knowledge: `GET /api/projects/{project_id}/knowledge` or `forge knowledge`.\n\
- Issues / tasks / status / dependencies: `forge issue`, `forge new`, `forge comment`, or\n\
  `/api/projects/{project_id}/issues` and `/api/issues/<id>`.\n\
- Before writing, rewriting, or tuning this project's pipeline skills, read the `forge-skills`\n\
  MCP prompt (the always-latest authoring guide).\n\
\n\
## Operating affordances\n\
Forge gives you a REST call for things agents routinely do in prose. When you hit the trigger,\n\
make the call — and avoid the red flag.\n\
\n\
An issue is a unit of WORK with a named deliverable and an owner, whose completion someone\n\
other than the author can verify. A note, a question, an audit finding and a record of\n\
something already done are NOT issues — the four admission gates and where each of those goes\n\
instead: guide `what-is-an-issue`.\n\
\n\
| When you need | Use | Red flag (DON'T) |\n\
|---|---|---|\n\
| Ordering between issues | Blocker known **at create time** → `POST /api/projects/:id/issues` with `relations:[{{ kind:'blocks', dependsOnId }}]` (edge committed BEFORE the `issue.created` event/dispatch — atomic). Both issues already exist → `POST /api/issues/<dependent>/dependencies {{ dependsOnId: <blocker>, kind:'blocks' }}` (retract with `validUntil` in the past). Verify with `GET /api/issues/<id>/dependencies`. | Prose instead of an edge (only a `blocks` edge gates dispatch) · setting a blocks edge AFTER an `open` create — the new issue can dispatch before the edge lands (race); send `relations` on the create or create at `draft` first |\n\
| To record a note, learning, or decision | `POST /api/memory` (durable business logic → repo `docs/`) | Filing it as an issue — `draft` or not, nobody browses the issue list for notes |\n\
| To queue work that must actually happen LATER | create an issue at `draft` | Creating it at `open` — that auto-triages and spawns a pipeline run |\n\
| To report an issue | fill `title`, `description`, `priority`, `category` | Pre-filling `plan`/`acceptanceCriteria` — on a staged project those are written by the clarify/plan steps, on an autonomous one by the driver's own phases |\n\
| To change the project's policy (`qa`, intake, a status's model or permission profile) | GET `/api/projects/:id/policy`, then PUT the whole document with the `baseRevision` you read | Writing it without reading it — a revision that moved is refused by name, never merged |\n\
| To write or change the project's own prose (build commands, a rule, a guide) | `PUT /api/projects/:id/knowledge/<slug>` or `forge knowledge write`, one entry per slug, `injection` deciding whether it reaches every prompt or is fetched on demand | Sending it to the project config as `projectFacts` — that key is refused by name |\n\
| Before you design / fix | `POST /api/memory/search` for prior conventions, gotchas, decisions | Skipping recall and rediscovering (or contradicting) settled work |\n\
| To park work that never started | leave it at `draft` | `on_hold` from `draft` — `on_hold` is a deliberate pause for ACTIVE work only |\n\
| To finish a fix made by hand, outside the pipeline | claim it shipped FIRST — `POST /api/issues/<id>/merge` (or Mark merged on the issue's Properties rail), naming where it landed — then move it to `awaiting_release`, where the release that claims it closes it, and capture a memory learning | Fixing it and forgetting — no merge record, no status move, no learning recorded · reaching for `closed` yourself: an issue closes only through a release that claimed it, and a direct close is refused by name (`CLOSE_ONLY_BY_RELEASE`) |\n\
| An issue you are working turns out NOT to be work (a note, a question, a duplicate, already done) | Act on it yourself — comment saying which gate it fails and where the content went, THEN `needs_info` if a human owes you requirements, or `dropped` if it is not work at all | Leaving it filed for someone else to find · reaching for `closed` — that says the work shipped, and only a release closes an issue (`CLOSE_ONLY_BY_RELEASE`) · moving status with no comment, so the next reader cannot tell why |\n\
| A bug, gap or defect you find WHILE working an issue | **Fix it now, in this issue**, and DECLARE it in your comment under `Extra fixes:` — extra work is REPORTED, never filed | Filing it instead of fixing it. A new `draft` is not a hand-off: nobody owns it, nothing ages it, and a two-minute fix becomes backlog nobody reads |\n\
| A residual genuinely out of reach (needs a human decision, or work no diff here can carry) | ONE of: a `blocks` edge onto the issue that would ship without it · a line in `docs/proposals/` · `needs_info` + `waitingKind` + `reason` when it blocks THIS issue | Filing a new issue to carry it — that is not one of the options. Equally: staying silent because none of the three fit — say it in a comment on the issue you are on |\n\
\n\
**Forge red flags:** prose-deps · open-then-block · open-as-note · draft-as-note · plan-by-hand · wholesale-config-clobber · skip-recall · on_hold-from-draft · fix-by-hand-and-forget · close-as-drop · silent-nonwork · file-instead-of-fix.\n",
    )
}

/// The fixed block prepended to `CLAUDE.md`. Identical across every project (the
/// per-project details are imported from `.forge/orientation.md`), so it never
/// needs updating once present.
fn claude_md_block() -> String {
    format!(
        "{FORGE_BLOCK_MARKER}\n\
<!-- Forge-managed pointer (fixed). Project orientation lives in .forge/orientation.md. -->\n\
@.forge/orientation.md\n\
<!-- /forge:orientation -->\n",
    )
}

/// Write `.forge/orientation.md` (full overwrite) and ensure `CLAUDE.md` carries
/// the fixed forge block (prepended once, only when the marker is absent).
/// Best-effort by contract — the caller logs and continues on `Err`.
pub fn write_orientation(repo_path: &Path, project_id: &str, slug: &str) -> Result<()> {
    // 1. `.forge/orientation.md` — Forge owns it; overwrite fully.
    let forge_dir = repo_path.join(".forge");
    std::fs::create_dir_all(&forge_dir)?;
    std::fs::write(
        forge_dir.join("orientation.md"),
        orientation_body(project_id, slug),
    )?;

    // 2. `CLAUDE.md` — ensure the fixed block is present at the top. If the
    // marker already exists we leave the whole file untouched (idempotent and
    // never clobbers the project's own content).
    let claude_path = repo_path.join("CLAUDE.md");
    let existing = std::fs::read_to_string(&claude_path).unwrap_or_default();
    if existing.contains(FORGE_BLOCK_MARKER) {
        return Ok(());
    }
    if existing.contains(FORGE_IMPORT) {
        tracing::info!(
            "[provision] {} already imports .forge/orientation.md without Forge's marker around it — leaving the file alone. Prepending the block would give it a second import, and every prompt on this project would then carry the whole of orientation twice.",
            claude_path.display()
        );
        return Ok(());
    }
    let block = claude_md_block();
    let next = if existing.trim().is_empty() {
        block
    } else {
        format!("{block}\n{existing}")
    };
    std::fs::write(&claude_path, next)?;
    Ok(())
}
