//! Provision step — seed Forge orientation for human `claude` sessions opened in
//! a Forge-managed consumer repo (pipeline jobs are oriented separately via the
//! per-stage system preamble; see core `prompt/system.ts`).
//!
//! The body is core's (`prompt/checkout-orientation.ts`, built from the one
//! affordances table the pipeline prompts carry), served on every provision
//! and `me/runners` read. This module writes what it is sent and refuses by
//! name a body core did not send or did not generate.
//!
//! What it writes names ONE Forge instance (its projectId and slug), so it is
//! per-checkout and never something the repository's own history should carry:
//! the same repository can be worked from two Forge instances (forge-core, epod
//! and the catalog repositories commit a `CLAUDE.md` importing
//! `@.forge/orientation.md` and an orientation naming the prod project). So the
//! orientation lives off every tracked path, and no tracked file is changed:
//!
//!   - `CLAUDE.local.md` of the main checkout holds the orientation itself,
//!     inline in a Forge block above anything a person wrote there, behind a
//!     `/CLAUDE.local.md` line in the checkout's `info/exclude`. Claude Code
//!     loads it from the checkout and from every worktree nested under it
//!     (`.claude/worktrees/<name>`), because it reads `CLAUDE.local.md` from
//!     each directory above the session. Inline rather than imported: an import
//!     from a parent directory lands outside a worktree session's directory,
//!     which Claude Code treats as an external import and does not load unasked.
//!   - `.claude/settings.local.json` of the main checkout carries
//!     `claudeMdExcludes` for the checkout's `.forge/orientation.md` and every
//!     worktree's, so a committed orientation of another instance never loads
//!     beside this one. A worktree reads the main checkout's local settings, and
//!     the exclusion applies to imported files.
//!   - `.forge/orientation.md` is the repository's own: left as committed, never
//!     marked, so pull, merge, rebase and checkout move it like any file. An
//!     untracked one an older runner generated is removed, since nothing reads it
//!     and a repository that starts committing the path would refuse the pull.
//!
//! A checkout an older runner held under `skip-worktree` is converted on the
//! next daemon start ([`crate::orientation_record`]), provision or refresh:
//! the mark lifted, the committed bytes restored.
//! A committed orientation this instance would write byte for byte, imported by
//! the committed `CLAUDE.md`, is the checkout's own and nothing is added. A
//! tracked `CLAUDE.local.md` or local settings file is refused by name.

use std::path::Path;

use serde_json::{Map, Value};

use crate::git_exclude::{self, Ignored};

/// Opens the Forge-managed block. Presence ⇒ already oriented.
pub(crate) const FORGE_BLOCK_MARKER: &str = "<!-- forge:orientation -->";

/// Closes the Forge-managed block.
pub(crate) const FORGE_BLOCK_END: &str = "<!-- /forge:orientation -->\n";

/// The line every generated orientation carries under its heading.
const GENERATED_LINE: &str =
    "<!-- Generated by Forge on device provision. Forge-owned; manual edits are overwritten. -->";

/// Whether `body` is an orientation Forge generated, of this crate's version
/// or an older one: its heading, and the line saying Forge owns it.
pub fn is_generated(body: &str) -> bool {
    body.starts_with("# Forge orientation — ") && body.lines().take(4).any(|l| l == GENERATED_LINE)
}

/// `text` with the Forge block taken off the top (the import an older runner
/// prepended, or the orientation this one writes); `None` where it does not
/// start with that block.
pub(crate) fn without_import_block(text: &str) -> Option<&str> {
    let rest = text.strip_prefix(FORGE_BLOCK_MARKER)?;
    let end = rest.find(FORGE_BLOCK_END)? + FORGE_BLOCK_END.len();
    let after = &rest[end..];
    Some(after.strip_prefix('\n').unwrap_or(after))
}

/// The import a repository's committed `CLAUDE.md` reaches its orientation by.
const FORGE_IMPORT: &str = "@.forge/orientation.md";

/// The repository's own orientation path, relative to the checkout.
pub const ORIENTATION: &str = ".forge/orientation.md";

/// The per-checkout memory file this checkout's orientation is written into.
pub const LOCAL: &str = "CLAUDE.local.md";

/// The per-checkout settings file the exclusion is written into.
const SETTINGS: &str = ".claude/settings.local.json";

/// The settings key naming memory files Claude Code does not load.
const EXCLUDES: &str = "claudeMdExcludes";

/// Why orientation was not (wholly) written.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Refused {
    /// Writing would change a file the repository commits.
    WouldRewriteTracked {
        path: &'static str,
        why: &'static str,
    },
    /// The file could not be made one git ignores.
    NotIgnored { path: &'static str, detail: String },
    /// An older runner's skip-worktree mark could not be lifted.
    MarkNotLifted { detail: String },
    /// The committed orientation could not be kept from loading.
    NotExcluded { detail: String },
    /// Reading or writing the file failed.
    Io { path: &'static str, error: String },
    /// Core sent no orientation for the project, so there is nothing to write.
    NotServed { slug: String },
    /// What core sent is not an orientation Forge generated.
    NotGenerated { slug: String },
}

impl std::fmt::Display for Refused {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Refused::WouldRewriteTracked { path, why } => write!(
                f,
                "PROVISION_WOULD_REWRITE_TRACKED: {path} is committed in this repository and {why}. It is not a file Forge owns, so it was left as committed — remove it from the index (`git rm --cached {path}`) for Forge to write this checkout's copy"
            ),
            Refused::MarkNotLifted { detail } => write!(
                f,
                "PROVISION_ORIENTATION_MARK_NOT_LIFTED: {ORIENTATION} is held under skip-worktree by an older runner, which refuses every pull that moves it, and it could not be released (`git update-index --no-skip-worktree {ORIENTATION}`, then `git checkout -- {ORIENTATION}`): {detail}"
            ),
            Refused::NotExcluded { detail } => write!(
                f,
                "PROVISION_ORIENTATION_NOT_EXCLUDED: this checkout's orientation was not written, because a committed {ORIENTATION} could not be kept from loading beside it through `{EXCLUDES}` in {SETTINGS}: {detail}"
            ),
            Refused::NotIgnored { path, detail } => write!(
                f,
                "PROVISION_ORIENTATION_NOT_IGNORED: {path} was not written, because git could not be made to ignore it: {detail}"
            ),
            Refused::Io { path, error } => write!(f, "{path} could not be written: {error}"),
            Refused::NotServed { slug } => write!(
                f,
                "PROVISION_ORIENTATION_NOT_SERVED: core sent no orientation for project {slug}, so nothing was written — core serves it on every provision and assignment read, and a core older than this runner, or a checkout bound only in config.toml while core was unreachable, sends none"
            ),
            Refused::NotGenerated { slug } => write!(
                f,
                "PROVISION_ORIENTATION_MALFORMED: the orientation core sent for project {slug} does not open with `# Forge orientation — ` and the line saying Forge owns it, so it was not written"
            ),
        }
    }
}

/// A body of the shape core serves (`prompt/checkout-orientation.ts`), for the
/// tests: the heading, the generated line, and the project it names.
#[cfg(test)]
pub(crate) fn orientation_body(project_id: &str, slug: &str) -> String {
    format!(
        "# Forge orientation — {slug}\n\n{GENERATED_LINE}\n\n- **projectId:** `{project_id}`  ·  **slug:** `{slug}`\n"
    )
}

/// The Forge block carrying `body` inline at the top of `CLAUDE.local.md`.
fn block(body: &str) -> String {
    let nl = if body.ends_with('\n') { "" } else { "\n" };
    format!(
        "{FORGE_BLOCK_MARKER}\n\
<!-- This checkout's Forge orientation: Forge-owned, rewritten on provision. A committed {ORIENTATION} is kept from loading by {EXCLUDES} in {SETTINGS}. -->\n\
{body}{nl}{FORGE_BLOCK_END}",
    )
}

/// Whether git tracks `path` in `repo`; `false` outside a git work tree.
fn tracked(repo: &Path, path: &str) -> bool {
    git_ok(repo, &["ls-files", "--error-unmatch", "--", path]).is_ok()
}

/// Make git ignore `path` before it is written there, by an anchored line in
/// the checkout's exclude file. Whether that line had to be added.
fn ignore(repo: &Path, path: &'static str) -> Result<bool, Refused> {
    match git_exclude::ensure_ignored_by(repo, path, path, &format!("/{path}")) {
        Ok(Ignored::Yes { added }) => Ok(added.is_some()),
        Ok(Ignored::NoGit) => Ok(false),
        Err(e) => Err(Refused::NotIgnored {
            path,
            detail: e.to_string(),
        }),
    }
}

fn git_ok(repo: &Path, args: &[&str]) -> Result<String, String> {
    let out = std::process::Command::new("git")
        .arg("-C")
        .arg(repo)
        .args(args)
        .env_remove("GIT_DIR")
        .env_remove("GIT_WORK_TREE")
        .env_remove("GIT_INDEX_FILE")
        .stdin(std::process::Stdio::null())
        .output()
        .map_err(|e| e.to_string())?;
    if out.status.success() {
        Ok(String::from_utf8_lossy(&out.stdout).into_owned())
    } else {
        Err(String::from_utf8_lossy(&out.stderr).trim().to_string())
    }
}

/// Release a committed orientation an older runner held under skip-worktree:
/// lift the mark and restore the committed bytes. Answers what the checkout
/// held there (that instance's orientation, where it was one), and `None`
/// where nothing was marked.
pub fn lift_skip_worktree(repo: &Path) -> Result<Option<String>, Refused> {
    let marked =
        git_ok(repo, &["ls-files", "-v", "--", ORIENTATION]).is_ok_and(|l| l.starts_with("S "));
    if !marked {
        return Ok(None);
    }
    let held = std::fs::read_to_string(repo.join(ORIENTATION)).unwrap_or_default();
    git_ok(
        repo,
        &["update-index", "--no-skip-worktree", "--", ORIENTATION],
    )
    .map_err(|detail| Refused::MarkNotLifted { detail })?;
    git_ok(repo, &["checkout", "--", ORIENTATION]).map_err(|detail| Refused::MarkNotLifted {
        detail: format!("the mark is lifted but the committed bytes were not restored: {detail}"),
    })?;
    Ok(Some(held))
}

/// An orientation an older runner generated at the untracked orientation path.
pub fn untracked_generated(repo: &Path) -> Option<String> {
    if tracked(repo, ORIENTATION) {
        return None;
    }
    std::fs::read_to_string(repo.join(ORIENTATION))
        .ok()
        .filter(|b| is_generated(b))
}

/// A checkout's path as a `claudeMdExcludes` glob root: forward slashes, no trailing one, and no
/// `\\?\` verbatim prefix. `std::fs::canonicalize` returns that prefix on Windows, and a pattern
/// written `//?/C:/…` names no path a session ever loads from. The docs say only that "patterns are
/// matched against absolute file paths using glob syntax", with every example written with `/`
/// (code.claude.com/docs/en/memory, "Exclude specific CLAUDE.md files"), so `/` is the one separator
/// the pattern is written in.
fn glob_root(path: &str) -> String {
    let path = match path.strip_prefix("\\\\?\\UNC\\") {
        Some(unc) => format!("\\\\{unc}"),
        None => path.strip_prefix("\\\\?\\").unwrap_or(path).to_string(),
    };
    path.replace('\\', "/").trim_end_matches('/').to_string()
}

/// The `claudeMdExcludes` globs keeping the checkout's and every nested
/// worktree's `.forge/orientation.md` from loading, under the checkout's path
/// as given and, where a symlink makes it differ, as resolved.
fn exclusions(repo: &Path) -> Result<Vec<String>, Refused> {
    let given = std::path::absolute(repo).map_err(|e| Refused::NotExcluded {
        detail: format!("the checkout's absolute path cannot be read: {e}"),
    })?;
    let mut roots = vec![given.clone()];
    if let Ok(real) = std::fs::canonicalize(repo) {
        if real != given {
            roots.push(real);
        }
    }
    Ok(roots
        .iter()
        .flat_map(|root| {
            let root = glob_root(&root.to_string_lossy());
            [
                format!("{root}/{ORIENTATION}"),
                format!("{root}/.claude/worktrees/*/{ORIENTATION}"),
            ]
        })
        .collect())
}

/// `settings` with this checkout's exclusions in its `claudeMdExcludes`, every
/// other key and entry kept, and an orientation exclusion naming another root
/// (a checkout since moved) dropped. `None` where it already reads so.
fn excluded_in(settings: Option<&str>, ours: &[String]) -> Result<Option<String>, String> {
    let mut doc = match settings.filter(|t| !t.trim().is_empty()) {
        None => Map::new(),
        Some(text) => match serde_json::from_str::<Value>(text) {
            Ok(Value::Object(doc)) => doc,
            Ok(_) => return Err("it is not a JSON object".into()),
            Err(e) => return Err(format!("it is not readable JSON: {e}")),
        },
    };
    let held = match doc.get(EXCLUDES) {
        None => Vec::new(),
        Some(Value::Array(list)) => list.clone(),
        Some(_) => return Err(format!("its `{EXCLUDES}` is not an array")),
    };
    let suffix = format!("/{ORIENTATION}");
    let mut next: Vec<Value> = held
        .iter()
        .filter(|v| {
            v.as_str()
                .is_none_or(|s| !s.ends_with(&suffix) || ours.iter().any(|o| o == s))
        })
        .cloned()
        .collect();
    for o in ours {
        if !next.iter().any(|v| v.as_str() == Some(o)) {
            next.push(Value::String(o.clone()));
        }
    }
    if next == held && doc.contains_key(EXCLUDES) {
        return Ok(None);
    }
    doc.insert(EXCLUDES.into(), Value::Array(next));
    serde_json::to_string_pretty(&Value::Object(doc))
        .map(|t| Some(format!("{t}\n")))
        .map_err(|e| e.to_string())
}

/// Keep a committed orientation, in the checkout and in every worktree nested
/// under it, from loading beside this checkout's. Whether anything was written.
fn exclude_committed(repo: &Path) -> Result<bool, Refused> {
    let not = |detail: String| Refused::NotExcluded { detail };
    let ignored_now = match git_exclude::ensure_ignored(repo, SETTINGS) {
        Ok(Ignored::Yes { added }) => added.is_some(),
        Ok(Ignored::NoGit) => false,
        Err(git_exclude::Refused::Tracked) => {
            return Err(Refused::WouldRewriteTracked {
                path: SETTINGS,
                why: "Forge would have to add its `claudeMdExcludes` to it",
            })
        }
        Err(e) => return Err(not(e.to_string())),
    };
    let path = repo.join(SETTINGS);
    let existing = std::fs::read_to_string(&path).ok();
    let Some(next) = excluded_in(existing.as_deref(), &exclusions(repo)?)
        .map_err(|e| not(format!("{SETTINGS} was left as it stands: {e}")))?
    else {
        return Ok(ignored_now);
    };
    let io = |e: std::io::Error| Refused::Io {
        path: SETTINGS,
        error: e.to_string(),
    };
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir).map_err(io)?;
    }
    let tmp = path.with_extension("json.forge-tmp");
    std::fs::write(&tmp, next).map_err(io)?;
    std::fs::rename(&tmp, &path).map_err(|e| {
        let _ = std::fs::remove_file(&tmp);
        io(e)
    })?;
    Ok(true)
}

/// Make `body` this checkout's orientation: the committed one excluded first,
/// so a failure leaves none loading rather than two, then `body` written into
/// the Forge block of `CLAUDE.local.md`. Whether any file was changed: `false`
/// is a checkout that already held exactly this, which a second call always is.
pub fn hold(repo: &Path, body: &str) -> Result<bool, Refused> {
    if tracked(repo, LOCAL) {
        return Err(Refused::WouldRewriteTracked {
            path: LOCAL,
            why: "this checkout's orientation would have to be written into it",
        });
    }
    let mut changed = exclude_committed(repo)?;
    changed |= ignore(repo, LOCAL)?;
    let existing = std::fs::read_to_string(repo.join(LOCAL)).unwrap_or_default();
    let rest = without_import_block(&existing).unwrap_or(&existing);
    let block = block(body);
    let next = if rest.trim().is_empty() {
        block
    } else {
        format!("{block}\n{rest}")
    };
    if next != existing {
        write(repo, LOCAL, &next)?;
        changed = true;
    }
    if untracked_generated(repo).is_some() {
        match std::fs::remove_file(repo.join(ORIENTATION)) {
            Ok(()) => changed = true,
            Err(e) => tracing::warn!(
                "[orientation] {}: the untracked {ORIENTATION} an older runner generated was not removed: {e}",
                repo.display()
            ),
        }
    }
    Ok(changed)
}

fn write(repo: &Path, path: &'static str, body: &str) -> Result<(), Refused> {
    let at = repo.join(path);
    let io = |e: std::io::Error| Refused::Io {
        path,
        error: e.to_string(),
    };
    if let Some(dir) = at.parent() {
        std::fs::create_dir_all(dir).map_err(io)?;
    }
    std::fs::write(at, body).map_err(io)
}

/// What writing a checkout's orientation did.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Oriented {
    /// The checkout already held exactly this orientation; nothing was written.
    Current,
    /// A file was written: a first orientation, another project's, or another build's.
    Written,
    /// An older runner held the committed orientation under skip-worktree; the
    /// mark is lifted and the committed file restored. Carries what to record.
    Converted(String),
}

impl Oriented {
    /// What a provision result records, where there is anything to say.
    pub fn note(&self) -> Option<&str> {
        match self {
            Oriented::Converted(note) => Some(note),
            Oriented::Current | Oriented::Written => None,
        }
    }
}

/// Write the orientation core served for project `slug` into this checkout,
/// converting one an older runner held under skip-worktree. Idempotent: a
/// second call over what the first left answers [`Oriented::Current`] and
/// writes nothing. Core owns the body; a body it did not send, or one that is
/// not a generated orientation, is refused before anything is touched. The
/// caller reports a refusal and goes on: the checkout works without
/// orientation, and says why it has none.
pub fn write_orientation(
    repo_path: &Path,
    served: Option<&str>,
    slug: &str,
) -> Result<Oriented, Refused> {
    let body = match served {
        None => {
            return Err(Refused::NotServed {
                slug: slug.to_string(),
            })
        }
        Some(body) if !is_generated(body) => {
            return Err(Refused::NotGenerated {
                slug: slug.to_string(),
            })
        }
        Some(body) => body.to_string(),
    };
    let note = lift_skip_worktree(repo_path)?.map(|_| {
        format!("{ORIENTATION} was held under skip-worktree by an older runner; the mark is lifted and the committed file restored, so a pull that moves it is no longer refused, and project {slug}'s orientation is in {LOCAL}")
    });
    let committed_is_ours = tracked(repo_path, ORIENTATION)
        && git_ok(repo_path, &["show", &format!(":{ORIENTATION}")])
            .ok()
            .as_deref()
            == Some(body.as_str());
    let imported = std::fs::read_to_string(repo_path.join("CLAUDE.md"))
        .is_ok_and(|s| s.lines().any(|l| l.trim() == FORGE_IMPORT));
    let changed = !(committed_is_ours && imported) && hold(repo_path, &body)?;
    Ok(match note {
        Some(note) => Oriented::Converted(note),
        None if changed => Oriented::Written,
        None => Oriented::Current,
    })
}

/// What Claude Code (2.1.290) puts in front of a session started in `cwd`, a
/// directory of the checkout `main` or of a worktree nested under it, as its
/// memory and settings documents describe and as measured against it: every
/// `CLAUDE.md` and `CLAUDE.local.md` from `main` down to `cwd`; an `@` import
/// resolved against the file holding it, and loaded only where it lands inside
/// `cwd` (one outside is an external import, which an unapproved session does
/// not load); and nothing matching a `claudeMdExcludes` glob of the main
/// checkout's local settings, which a worktree reads at the main checkout's root.
#[cfg(test)]
pub(crate) mod claude_load {
    use std::path::Path;

    pub(crate) fn loaded(main: &Path, cwd: &Path) -> String {
        let excludes: Vec<String> =
            std::fs::read_to_string(main.join(".claude/settings.local.json"))
                .ok()
                .and_then(|t| serde_json::from_str::<serde_json::Value>(&t).ok())
                .and_then(|v| v.get("claudeMdExcludes")?.as_array().cloned())
                .unwrap_or_default()
                .iter()
                .filter_map(|p| p.as_str().map(str::to_string))
                .collect();
        let excluded = |p: &Path| {
            excludes.iter().any(|g| {
                glob(
                    g.as_bytes(),
                    p.to_string_lossy().replace('\\', "/").as_bytes(),
                )
            })
        };
        let mut dirs: Vec<&Path> = cwd
            .ancestors()
            .take_while(|d| d.starts_with(main))
            .collect();
        dirs.reverse();
        let mut out = String::new();
        for dir in dirs {
            for name in ["CLAUDE.md", "CLAUDE.local.md"] {
                let file = dir.join(name);
                if excluded(&file) {
                    continue;
                }
                let Ok(text) = std::fs::read_to_string(&file) else {
                    continue;
                };
                out.push_str(&text);
                for import in text.lines().filter_map(|l| l.trim().strip_prefix('@')) {
                    let at = dir.join(import);
                    if at.starts_with(cwd) && !excluded(&at) {
                        out.push_str(&std::fs::read_to_string(&at).unwrap_or_default());
                    }
                }
            }
        }
        out
    }

    /// `*` matches within one path segment; every other byte matches itself.
    fn glob(p: &[u8], s: &[u8]) -> bool {
        match p.first() {
            None => s.is_empty(),
            Some(b'*') => (0..=s.len())
                .take_while(|&i| i == 0 || s[i - 1] != b'/')
                .any(|i| glob(&p[1..], &s[i..])),
            Some(c) => s.first() == Some(c) && glob(&p[1..], &s[1..]),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::claude_load::loaded;
    use super::*;
    use std::path::PathBuf;
    use std::process::Command;

    const PROD: &str = "da368b0a-8e21-4763-9d90-8f7b9d0c7115";
    const DEV: &str = "d1bb4907-74d9-4228-85ff-76121523af7d";

    /// A seed repository committing `files`, and a clone of it.
    fn cloned(name: &str, files: &[(&str, &str)]) -> (PathBuf, PathBuf) {
        let seed = repo_with(name, files);
        let co = seed.with_file_name(format!(
            "{}-co",
            seed.file_name().unwrap().to_string_lossy()
        ));
        git(
            seed.parent().unwrap(),
            &["clone", "-q", seed.to_str().unwrap(), co.to_str().unwrap()],
        );
        (seed, co)
    }

    fn commit_upstream(seed: &Path, path: &str, body: &str) {
        let at = seed.join(path);
        std::fs::create_dir_all(at.parent().unwrap()).unwrap();
        std::fs::write(at, body).unwrap();
        git(seed, &["add", "--", path]);
        git(seed, &["commit", "-q", "-m", "upstream"]);
    }

    fn pull(co: &Path) -> Result<(), String> {
        let out = Command::new("git")
            .arg("-C")
            .arg(co)
            .args(["pull", "-q", "--ff-only"])
            .env_remove("GIT_DIR")
            .env_remove("GIT_WORK_TREE")
            .env_remove("GIT_INDEX_FILE")
            .output()
            .unwrap();
        out.status
            .success()
            .then_some(())
            .ok_or_else(|| String::from_utf8_lossy(&out.stderr).into_owned())
    }

    fn only_ours(main: &Path, cwd: &Path) {
        let seen = loaded(main, cwd);
        assert!(
            seen.contains(DEV),
            "{}: this instance's orientation does not load:\n{seen}",
            cwd.display()
        );
        assert!(
            !seen.contains(PROD),
            "{}: the other instance's orientation loads beside this one's:\n{seen}",
            cwd.display()
        );
    }

    #[test]
    fn each_repo_shape_loads_only_this_instances_orientation_in_the_checkout_and_a_new_worktree_and_pull_is_never_blocked(
    ) {
        let prod = orientation_body(PROD, "forge-dev");
        let imports = format!("{FORGE_IMPORT}\n\n# Forge\n");
        let shapes: [(&str, Vec<(&str, &str)>); 3] = [
            (
                "forge-core",
                vec![(".forge/orientation.md", &prod), ("CLAUDE.md", &imports)],
            ),
            ("epod", vec![(".forge/orientation.md", &prod)]),
            ("catalog", vec![("CLAUDE.md", "# Catalog API\n")]),
        ];
        for (name, files) in shapes {
            let (seed, co) = cloned(name, &files);
            let said = write_orientation(&co, Some(&orientation_body(DEV, "forge")), "forge");
            assert!(said.is_ok(), "{name}: {said:?}");
            only_ours(&co, &co);
            assert_eq!(porcelain(&co), "", "{name}");
            assert_eq!(staged_by_add_all(&co), "", "{name}");

            let moved = orientation_body(PROD, "forge-dev-moved");
            commit_upstream(&seed, ".forge/orientation.md", &moved);
            if let Err(e) = pull(&co) {
                panic!("{name}: pull --ff-only refused after provisioning: {e}");
            }
            assert_eq!(
                std::fs::read_to_string(co.join(".forge/orientation.md")).unwrap(),
                moved,
                "{name}: the tracked path holds the committed bytes"
            );
            only_ours(&co, &co);
            assert_eq!(porcelain(&co), "", "{name}");

            let wt = co.join(".claude/worktrees/iss-1");
            git(
                &co,
                &["worktree", "add", "-q", wt.to_str().unwrap(), "-b", "iss-1"],
            );
            only_ours(&co, &wt);
            assert_eq!(porcelain(&wt), "", "{name}");
            assert_eq!(porcelain(&co), "", "{name}");
        }
    }

    #[test]
    fn a_windows_checkout_path_is_written_as_a_forward_slash_glob_root() {
        for (given, want) in [
            (
                "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\forge-orient-1-co",
                "C:/Users/RUNNER~1/AppData/Local/Temp/forge-orient-1-co",
            ),
            (
                "\\\\?\\C:\\Users\\runneradmin\\Temp\\co\\",
                "C:/Users/runneradmin/Temp/co",
            ),
            ("\\\\?\\UNC\\srv\\share\\co", "//srv/share/co"),
            ("/home/dev/co", "/home/dev/co"),
        ] {
            assert_eq!(glob_root(given), want, "{given}");
        }
    }

    #[test]
    fn a_checkout_an_older_runner_held_under_skip_worktree_is_converted_on_the_next_provision() {
        let prod = orientation_body(PROD, "forge-dev");
        let imports = format!("{FORGE_IMPORT}\n\n# Forge\n");
        let (seed, co) = cloned(
            "converted",
            &[(".forge/orientation.md", &prod), ("CLAUDE.md", &imports)],
        );
        git(
            &co,
            &["update-index", "--skip-worktree", ".forge/orientation.md"],
        );
        std::fs::write(
            co.join(".forge/orientation.md"),
            orientation_body(DEV, "forge"),
        )
        .unwrap();

        let said = write_orientation(&co, Some(&orientation_body(DEV, "forge")), "forge");
        assert!(said.is_ok(), "{said:?}");
        assert!(
            git(&co, &["ls-files", "-v", ".forge/orientation.md"]).starts_with("H "),
            "the skip-worktree mark is lifted"
        );
        assert_eq!(
            std::fs::read_to_string(co.join(".forge/orientation.md")).unwrap(),
            prod,
            "the committed file is restored"
        );
        only_ours(&co, &co);
        assert_eq!(porcelain(&co), "");
        commit_upstream(&seed, ".forge/orientation.md", "moved\n");
        assert_eq!(pull(&co), Ok(()));
    }

    fn scratch(name: &str) -> PathBuf {
        let dir =
            std::env::temp_dir().join(format!("forge-orient-{name}-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn git(dir: &Path, args: &[&str]) -> String {
        let out = Command::new("git")
            .arg("-C")
            .arg(dir)
            .args(["-c", "user.email=t@example.invalid", "-c", "user.name=t"])
            .args(args)
            .env_remove("GIT_DIR")
            .env_remove("GIT_WORK_TREE")
            .env_remove("GIT_INDEX_FILE")
            .output()
            .unwrap();
        assert!(
            out.status.success(),
            "git {args:?}: {}",
            String::from_utf8_lossy(&out.stderr)
        );
        String::from_utf8_lossy(&out.stdout).into_owned()
    }

    fn repo_with(name: &str, files: &[(&str, &str)]) -> PathBuf {
        let repo = scratch(name);
        git(&repo, &["init", "-q"]);
        for (path, body) in files {
            let at = repo.join(path);
            std::fs::create_dir_all(at.parent().unwrap()).unwrap();
            std::fs::write(&at, body).unwrap();
            git(&repo, &["add", "--", path]);
        }
        if !files.is_empty() {
            // `* -text` is committed so every checkout or worktree of this repo, including ones the product cuts, restores the committed bytes whatever `core.autocrlf` the box ships (Windows: true).
            std::fs::write(repo.join(".gitattributes"), "* -text\n").unwrap();
            git(&repo, &["add", "--", ".gitattributes"]);
            git(&repo, &["commit", "-q", "-m", "committed"]);
        }
        repo
    }

    fn porcelain(repo: &Path) -> String {
        git(repo, &["status", "--porcelain", "--untracked-files=all"])
    }

    fn excluded(repo: &Path) -> String {
        std::fs::read_to_string(repo.join(".git/info/exclude")).unwrap_or_default()
    }

    #[test]
    fn the_generator_recognises_its_own_output_and_its_block() {
        assert!(is_generated(&orientation_body("p", "s")));
        assert!(!is_generated("# Our own notes\n"));
        let body = orientation_body("p", "s");
        assert_eq!(
            without_import_block(&format!("{}\n# A\n", block(&body))),
            Some("# A\n")
        );
        assert_eq!(without_import_block("# A\n"), None);
    }

    fn staged_by_add_all(repo: &Path) -> String {
        git(repo, &["add", "-A"]);
        git(repo, &["diff", "--cached", "--name-only"])
    }

    fn settings(repo: &Path) -> serde_json::Value {
        serde_json::from_str(&std::fs::read_to_string(repo.join(SETTINGS)).unwrap()).unwrap()
    }

    #[test]
    fn an_orientation_core_did_not_send_or_did_not_generate_is_refused_before_anything_is_written()
    {
        let repo = repo_with("unserved", &[]);
        let none = write_orientation(&repo, None, "forge").unwrap_err();
        assert!(
            none.to_string().starts_with(
                "PROVISION_ORIENTATION_NOT_SERVED: core sent no orientation for project forge"
            ),
            "{none}"
        );
        let typed = write_orientation(&repo, Some("# Notes\nwhatever a person wrote\n"), "forge")
            .unwrap_err();
        assert!(
            typed
                .to_string()
                .starts_with("PROVISION_ORIENTATION_MALFORMED"),
            "{typed}"
        );
        assert_eq!(porcelain(&repo), "", "a refused write touched the checkout");
        assert!(!repo.join(LOCAL).exists());
    }

    #[test]
    fn a_committed_orientation_this_instance_would_write_is_left_alone() {
        let body = orientation_body("p-1", "same");
        let claude = format!("# Repo\n\n{FORGE_IMPORT}\n");
        let repo = repo_with(
            "same",
            &[(".forge/orientation.md", &body), ("CLAUDE.md", &claude)],
        );
        assert!(write_orientation(&repo, Some(&orientation_body("p-1", "same")), "same").is_ok());
        assert_eq!(
            std::fs::read_to_string(repo.join("CLAUDE.md")).unwrap(),
            claude
        );
        assert!(!repo.join("CLAUDE.local.md").exists());
        assert!(!repo.join(SETTINGS).exists());
        assert_eq!(porcelain(&repo), "");
    }

    #[test]
    fn catalog_a_committed_claude_md_is_never_rewritten_and_the_orientation_goes_where_git_ignores_it(
    ) {
        let claude = "# Catalog API\n\nRun `php artisan test`.\n";
        let repo = repo_with("catalog", &[("CLAUDE.md", claude)]);
        let id = "9208f825-a431-430e-8de1-b4cb3ccc45b1";
        assert!(write_orientation(
            &repo,
            Some(&orientation_body(id, "catalog-api")),
            "catalog-api"
        )
        .is_ok());
        assert_eq!(
            std::fs::read_to_string(repo.join("CLAUDE.md")).unwrap(),
            claude
        );
        assert!(!repo.join(".forge/orientation.md").exists());
        let local = std::fs::read_to_string(repo.join("CLAUDE.local.md")).unwrap();
        assert_eq!(
            without_import_block(&local),
            Some(""),
            "the block alone: {local}"
        );
        assert!(
            local.contains(&orientation_body(id, "catalog-api")),
            "{local}"
        );
        let ex = excluded(&repo);
        assert!(ex.lines().any(|l| l == "/CLAUDE.local.md"), "{ex}");
        assert!(ex.lines().any(|l| l == ".claude/"), "{ex}");
        assert_eq!(porcelain(&repo), "");
        let first = settings(&repo);
        // idempotent: a second provision adds nothing
        assert!(write_orientation(
            &repo,
            Some(&orientation_body(id, "catalog-api")),
            "catalog-api"
        )
        .is_ok());
        assert_eq!(excluded(&repo), ex);
        assert_eq!(
            std::fs::read_to_string(repo.join("CLAUDE.local.md")).unwrap(),
            local
        );
        assert_eq!(settings(&repo), first);
    }

    #[test]
    fn a_persons_local_notes_are_kept_below_the_block_and_an_older_runners_import_is_replaced() {
        let repo = repo_with("notes", &[]);
        let older = format!(
            "{FORGE_BLOCK_MARKER}\n<!-- Forge-managed pointer (fixed). Project orientation lives in .forge/orientation.md. -->\n{FORGE_IMPORT}\n{FORGE_BLOCK_END}\n# My sandbox URL\n"
        );
        std::fs::write(repo.join("CLAUDE.local.md"), &older).unwrap();
        std::fs::create_dir_all(repo.join(".forge")).unwrap();
        std::fs::write(
            repo.join(".forge/orientation.md"),
            orientation_body("old", "o"),
        )
        .unwrap();
        assert!(write_orientation(&repo, Some(&orientation_body(DEV, "forge")), "forge").is_ok());
        let local = std::fs::read_to_string(repo.join("CLAUDE.local.md")).unwrap();
        assert_eq!(without_import_block(&local), Some("# My sandbox URL\n"));
        assert!(!local.contains(FORGE_IMPORT), "{local}");
        assert!(
            !repo.join(".forge/orientation.md").exists(),
            "the untracked one an older runner generated is removed"
        );
        only_ours(&repo, &repo);
    }

    #[test]
    fn the_settings_keep_every_other_key_and_entry_and_drop_a_moved_checkouts_exclusion() {
        let repo = repo_with("settings", &[]);
        std::fs::create_dir_all(repo.join(".claude")).unwrap();
        std::fs::write(
            repo.join(SETTINGS),
            r#"{"hooks":{"Stop":[]},"claudeMdExcludes":["/elsewhere/CLAUDE.md","/moved/checkout/.forge/orientation.md"]}"#,
        )
        .unwrap();
        assert!(write_orientation(&repo, Some(&orientation_body(DEV, "forge")), "forge").is_ok());
        let doc = settings(&repo);
        assert_eq!(doc["hooks"], serde_json::json!({"Stop": []}));
        let list: Vec<&str> = doc[EXCLUDES]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap())
            .collect();
        let mut want = vec!["/elsewhere/CLAUDE.md".to_string()];
        want.extend(exclusions(&repo).unwrap());
        assert_eq!(list, want);
    }

    #[test]
    fn unreadable_settings_are_refused_by_name_and_nothing_is_written_to_load_beside_the_committed_one(
    ) {
        let prod = orientation_body(PROD, "forge-dev");
        let repo = repo_with(
            "unreadable",
            &[
                (".forge/orientation.md", &prod),
                ("CLAUDE.md", FORGE_IMPORT),
            ],
        );
        std::fs::create_dir_all(repo.join(".claude")).unwrap();
        std::fs::write(repo.join(SETTINGS), "{ not json").unwrap();
        let said = write_orientation(&repo, Some(&orientation_body(DEV, "forge")), "forge")
            .err()
            .map(|e| e.to_string())
            .expect("refused");
        assert!(
            said.contains("PROVISION_ORIENTATION_NOT_EXCLUDED") && said.contains(SETTINGS),
            "{said}"
        );
        assert_eq!(
            std::fs::read_to_string(repo.join(SETTINGS)).unwrap(),
            "{ not json"
        );
        assert!(!repo.join("CLAUDE.local.md").exists());
    }

    #[test]
    fn tracked_local_settings_are_refused_by_name() {
        let repo = repo_with("tracked-settings", &[(SETTINGS, "{}\n")]);
        let said = write_orientation(&repo, Some(&orientation_body(DEV, "forge")), "forge")
            .err()
            .map(|e| e.to_string())
            .expect("refused");
        assert!(
            said.contains("PROVISION_WOULD_REWRITE_TRACKED") && said.contains(SETTINGS),
            "{said}"
        );
        assert!(!repo.join("CLAUDE.local.md").exists());
    }

    #[test]
    fn a_committed_claude_local_md_is_refused_by_name() {
        let local = "# mine\n";
        let repo = repo_with("local", &[("CLAUDE.local.md", local)]);
        let said = write_orientation(&repo, Some(&orientation_body("p-3", "local")), "local")
            .err()
            .map(|e| e.to_string())
            .expect("refused");
        assert!(
            said.contains("PROVISION_WOULD_REWRITE_TRACKED") && said.contains("CLAUDE.local.md"),
            "{said}"
        );
        assert_eq!(
            std::fs::read_to_string(repo.join("CLAUDE.local.md")).unwrap(),
            local
        );
    }
}
