/**
 * ISS-1179 — `forge_issues` takes the display key it answers with, on every input that names an
 * issue, and refuses a key that resolves to nothing BY NAME.
 *
 * Through the real MCP transport against real Postgres, because every claim here is about what a
 * caller receives from the door: the tool's description is the contract, and a caller that
 * followed it was answered `{"code":"invalid_format","format":"uuid","path":["documentId"]}`.
 *
 * The forward cases are generated by iterating `ISSUE_REF_INPUTS` itself, so a pair added to that
 * registry with no handler site fails here, and a pair deleted from it takes its resolution and
 * its case away together. `the handler routes no reference around the registry` is the other
 * direction: a new call site that reads a reference field raw goes red without touching this
 * registry at all.
 */

import { readFileSync } from 'node:fs';
import { sql } from 'drizzle-orm';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { ISSUE_REF_INPUTS, TASK_REF_INPUTS } from '../../src/mcp/tools/issue-ref-input.js';
import {
  createTestProject,
  createTestProjectMember,
  createTestUser,
  setupTestDatabase,
  type TestDatabase,
  truncateAll,
} from '../helpers/index.js';
import { connectClientAsPat } from '../helpers/mcp-harness.js';

let harness: TestDatabase;
let mintPat: typeof import('../../src/auth/pat.js').mintPat;

beforeAll(async () => {
  harness = await setupTestDatabase();
  process.env.DATABASE_URL = harness.url;
  process.env.JWT_SECRET ??= 'test-secret-at-least-32-chars-long-abcdef-123456';
  process.env.DEVICE_TOKEN_PEPPER ??= 'test-device-pepper-at-least-32-chars-long-aa';
  process.env.SMTP_HOST ??= 'localhost';
  process.env.SMTP_PORT ??= '1025';
  process.env.SMTP_USER ??= 'test';
  process.env.SMTP_PASS ??= 'test';
  process.env.SMTP_FROM ??= 'test@example.com';
  process.env.APP_BASE_URL ??= 'http://localhost:3000';
  process.env.CORS_ORIGINS ??= 'http://localhost:3000';
  process.env.NODE_ENV ??= 'test';
  mintPat = (await import('../../src/auth/pat.js')).mintPat;
}, 60_000);

afterAll(async () => {
  if (harness) await harness.cleanup();
});

/** Reference data migration 0245 seeds and `truncateAll` empties. */
async function seedDefs(): Promise<void> {
  const { ATTRIBUTE_REGISTRY } = await import('../../src/issues/attributes/registry.js');
  for (const def of ATTRIBUTE_REGISTRY) {
    await harness.db.execute(sql`
      INSERT INTO issue_attribute_defs (key, label, value_type, cardinality, written_by, surfaces, required)
      VALUES (${def.key}, ${def.label}, ${def.valueType}, ${def.cardinality}, ${def.writtenBy},
              ${JSON.stringify(def.surfaces)}::jsonb, ${def.required})
      ON CONFLICT (key) DO NOTHING
    `);
  }
}

beforeEach(async () => {
  await truncateAll(harness.db);
  await seedDefs();
});

const SEQ = 7;
/** The key `serialize()` renders for SEQ under a project holding no prefix of its own. */
const KEY = `ISS-${SEQ}`;

type World = {
  projectId: string;
  slug: string;
  issueId: string;
  pat: string;
  /** A project the same user is NOT a member of, holding an issue at the same sequence. */
  otherProjectId: string;
  otherSlug: string;
};

async function seed(): Promise<World> {
  const owner = await createTestUser(harness.db, { email: 'owner@test.local' });
  await harness.db.execute(sql`UPDATE users SET email_verified_at = now() WHERE id = ${owner.id}`);
  const project = await createTestProject(harness.db, owner.id);
  await createTestProjectMember(harness.db, {
    userId: owner.id,
    projectId: project.id,
    role: 'admin',
  });

  const stranger = await createTestUser(harness.db, { email: 'stranger@test.local' });
  const other = await createTestProject(harness.db, stranger.id);
  await createTestProjectMember(harness.db, {
    userId: stranger.id,
    projectId: other.id,
    role: 'admin',
  });

  const mkIssue = async (projectId: string, createdBy: string, issSeq: number): Promise<string> => {
    const rows = await harness.db.execute<{ id: string }>(sql`
      INSERT INTO issues (project_id, title, created_by_id, iss_seq)
      VALUES (${projectId}, ${'the subject'}, ${createdBy}, ${issSeq}) RETURNING id
    `);
    return (rows[0] as { id: string }).id;
  };

  await mkIssue(other.id, stranger.id, SEQ);

  return {
    projectId: project.id,
    slug: project.slug,
    issueId: await mkIssue(project.id, owner.id, SEQ),
    pat: (await mintPat({ userId: owner.id, name: 'test-cli' })).plaintext,
    otherProjectId: other.id,
    otherSlug: other.slug,
  };
}

type Answer = { isError: boolean; text: string };

async function call(
  pat: string,
  args: Record<string, unknown>,
  projectSlug: string | null = null,
): Promise<Answer> {
  const ctx = await connectClientAsPat(pat, projectSlug);
  try {
    const res = (await ctx.client.callTool({ name: 'forge_issues', arguments: args })) as {
      isError?: boolean;
      content: Array<{ type: string; text: string }>;
    };
    return { isError: res.isError === true, text: res.content[0]?.text ?? '' };
  } finally {
    await ctx.close();
  }
}

/**
 * One call per registered pair, each written so the ONLY thing under test is that the reference
 * resolved. Keyed by action, and the suite asserts the keys are exactly the registry's.
 */
const ARGS: Record<string, (ref: string, projectId: string) => Record<string, unknown>> = {
  get: (ref) => ({ action: 'get', documentId: ref }),
  update: (ref) => ({ action: 'update', documentId: ref, data: { title: 'renamed by key' } }),
  transition: (ref) => ({
    action: 'transition',
    documentId: ref,
    data: { status: 'in_progress' },
  }),
  setAttributes: (ref) => ({
    action: 'setAttributes',
    documentId: ref,
    attributes: [{ key: 'human_required', value: true }],
  }),
  mark_merged: (ref) => ({
    action: 'mark_merged',
    data: { issueId: ref, target: 'feature' },
  }),
  unmark: (ref) => ({ action: 'unmark', data: { issueId: ref } }),
  createTask: (ref) => ({
    action: 'createTask',
    data: { issueId: ref, taskTitle: 'a task reached by key' },
  }),
  listTasks: (ref) => ({ action: 'listTasks', filters: { issue: ref } }),
};

describe('every registered issue reference takes the display key (ISS-1179)', () => {
  it('has a case for every pair the registry holds, and no other', () => {
    expect(Object.keys(ARGS).sort()).toEqual(ISSUE_REF_INPUTS.map((i) => i.action).sort());
  });

  for (const { action, field } of ISSUE_REF_INPUTS) {
    it(`${action} resolves ${field} given as ${KEY}`, async () => {
      const w = await seed();
      const res = await call(w.pat, {
        ...ARGS[action]?.(KEY, w.projectId),
        projectId: w.projectId,
      });
      expect(res.isError, `${action} refused the key: ${res.text}`).toBe(false);
    });

    it(`${action} still takes ${field} as a uuid`, async () => {
      const w = await seed();
      const res = await call(w.pat, {
        ...ARGS[action]?.(w.issueId, w.projectId),
        projectId: w.projectId,
      });
      expect(res.isError, `${action} refused the uuid: ${res.text}`).toBe(false);
    });
  }

  it('reads the key it answered with, so a round trip through issueId works', async () => {
    const w = await seed();
    const read = await call(w.pat, {
      action: 'get',
      documentId: w.issueId,
      projectId: w.projectId,
    });
    const answered = JSON.parse(read.text).issueId as string;
    expect(answered).toBe(KEY);
    const back = await call(w.pat, {
      action: 'get',
      documentId: answered,
      projectId: w.projectId,
    });
    expect(back.isError).toBe(false);
    expect(JSON.parse(back.text).documentId).toBe(w.issueId);
  });

  it('takes the scope from the X-Forge-Project-Slug header as well as from projectId', async () => {
    const w = await seed();
    const res = await call(w.pat, { action: 'get', documentId: KEY }, w.slug);
    expect(res.isError, res.text).toBe(false);
    expect(JSON.parse(res.text).documentId).toBe(w.issueId);
  });

  it('resolves a prefix the project has retired but still holds', async () => {
    const w = await seed();
    await harness.db.execute(sql`
      INSERT INTO issue_prefix_aliases (project_id, prefix) VALUES (${w.projectId}, ${'FD'})
    `);
    const res = await call(w.pat, {
      action: 'get',
      documentId: `FD-${SEQ}`,
      projectId: w.projectId,
    });
    expect(res.isError, res.text).toBe(false);
    expect(JSON.parse(res.text).documentId).toBe(w.issueId);
  });
});

describe('a key that resolves to nothing is refused by name (ISS-1179)', () => {
  it('quotes the key when the project holds no issue at that number', async () => {
    const w = await seed();
    const res = await call(w.pat, {
      action: 'get',
      documentId: 'ISS-4242',
      projectId: w.projectId,
    });
    expect(res.isError).toBe(true);
    expect(res.text).toContain('`ISS-4242`');
    expect(res.text).toContain('holds no issue at that number');
  });

  it('names the prefix when the project does not answer to it', async () => {
    const w = await seed();
    const res = await call(w.pat, {
      action: 'get',
      documentId: `ZZZ-${SEQ}`,
      projectId: w.projectId,
    });
    expect(res.isError).toBe(true);
    expect(res.text).toContain('`ZZZ`');
    expect(res.text).toContain('does not answer to');
  });

  it('quotes what was sent, and says what a valid one looks like, for a shape that is neither', async () => {
    const w = await seed();
    const res = await call(w.pat, {
      action: 'get',
      documentId: 'not-an-issue-at-all',
      projectId: w.projectId,
    });
    expect(res.isError).toBe(true);
    expect(res.text).toContain('not-an-issue-at-all');
    expect(res.text).toContain('is not an issue reference');
  });

  it('names both ways to set the scope when the call carries none', async () => {
    const w = await seed();
    const res = await call(w.pat, { action: 'get', documentId: KEY });
    expect(res.isError).toBe(true);
    expect(res.text).toContain('X-Forge-Project-Slug');
    expect(res.text).toContain('projectId');
  });

  it('never reports whether a key exists in a project the caller cannot see', async () => {
    const w = await seed();
    const res = await call(w.pat, {
      action: 'get',
      documentId: KEY,
      projectId: w.otherProjectId,
    });
    expect(res.isError).toBe(true);
    expect(res.text).toContain('project not found or not accessible');
    expect(res.text).not.toContain('display key');
  });
});

describe('a task reference takes the task uuid alone (ISS-1179)', () => {
  for (const { action, field } of TASK_REF_INPUTS) {
    it(`${action} refuses a display key in ${field}, saying where the uuid comes from`, async () => {
      const w = await seed();
      const res = await call(w.pat, { action, documentId: KEY, projectId: w.projectId });
      expect(res.isError).toBe(true);
      expect(res.text).toContain('is the TASK uuid');
      expect(res.text).toContain("action 'listTasks'");
    });
  }
});

/**
 * The reverse direction. The forward cases above prove a registered pair resolves; nothing in them
 * would notice a NEW handler site reading a reference field straight out of `input`, which is how
 * the schema and the sentence came apart in the first place. So the source is read: every place
 * the handler names one of the registry's fields must hand it to `refs`.
 */
describe('the handler routes no reference around the registry (ISS-1179)', () => {
  it('passes every read of a reference field to the resolver', () => {
    const src = readFileSync(
      new URL('../../src/mcp/tools/forge-issues.ts', import.meta.url),
      'utf8',
    );
    const handler = src.slice(src.indexOf('handler: async (args)'));
    const reads = [
      ...handler.matchAll(
        /\binput\.documentId\b|\binput\.data\?\.issueId\b|\bdata\.issueId\b|\binput\.filters\?\.issue\b/g,
      ),
    ];
    expect(
      reads.length,
      'no reference field is read at all — this test has lost its subject',
    ).toBeGreaterThan(0);

    /** The locals a `refs.issue`/`refs.task` call is given, so a read bound to one is routed. */
    const routedNames = new Set(
      [...handler.matchAll(/refs\.(?:issue|task)\([^,]+,\s*([A-Za-z_$][\w$.?]*)/g)].map(
        (m) => m[1] ?? '',
      ),
    );

    for (const read of reads) {
      const line = handler
        .slice(handler.lastIndexOf('\n', read.index) + 1, handler.indexOf('\n', read.index))
        .trim();
      const routed = /refs\.(?:issue|task)\(/.test(line);
      const guarded = line.startsWith('if (!');
      const bound = /^const\s+([A-Za-z_$][\w$]*)\s*=/.exec(line);
      const handedOn = bound ? routedNames.has(bound[1] ?? '') : false;
      expect(
        routed || guarded || handedOn,
        `this line reads a reference field and does not hand it to the registry: ${line}`,
      ).toBe(true);
    }
  });

  it('names in those calls exactly the fields the registries hold', () => {
    const src = readFileSync(
      new URL('../../src/mcp/tools/forge-issues.ts', import.meta.url),
      'utf8',
    );
    const handler = src.slice(src.indexOf('handler: async (args)'));
    const named = (kind: string): string[] =>
      [
        ...new Set(
          [...handler.matchAll(new RegExp(`refs\\.${kind}\\('([^']+)'`, 'g'))].map(
            (m) => m[1] ?? '',
          ),
        ),
      ].sort();
    expect(named('issue')).toEqual([...new Set(ISSUE_REF_INPUTS.map((i) => i.field))].sort());
    expect(named('task')).toEqual([...new Set(TASK_REF_INPUTS.map((i) => i.field))].sort());
  });
});
