/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as WorkspaceRouteRouteImport } from './routes/_workspace/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as LinkChatIndexRouteImport } from './routes/link-chat/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/_auth/register/index'
import { Route as WorkspaceAttentionIndexRouteImport } from './routes/_workspace/attention/index'
import { Route as WorkspaceDocsIndexRouteImport } from './routes/_workspace/docs/index'
import { Route as WorkspaceEcosystemsIndexRouteImport } from './routes/_workspace/ecosystems/index'
import { Route as WorkspaceIntegrationsIndexRouteImport } from './routes/_workspace/integrations/index'
import { Route as WorkspaceOpsIndexRouteImport } from './routes/_workspace/ops/index'
import { Route as WorkspaceOrgIndexRouteImport } from './routes/_workspace/org/index'
import { Route as WorkspacePairIndexRouteImport } from './routes/_workspace/pair/index'
import { Route as WorkspaceProjectsIndexRouteImport } from './routes/_workspace/projects/index'
import { Route as WorkspaceProjectsSlugRouteRouteImport } from './routes/_workspace/projects/$slug/route'
import { Route as WorkspaceRunnersIndexRouteImport } from './routes/_workspace/runners/index'
import { Route as WorkspaceSettingsIndexRouteImport } from './routes/_workspace/settings/index'
import { Route as AdminAlertsIndexRouteImport } from './routes/admin/alerts/index'
import { Route as AdminFleetIndexRouteImport } from './routes/admin/fleet/index'
import { Route as AdminGrowthIndexRouteImport } from './routes/admin/growth/index'
import { Route as AdminMcpLogsIndexRouteImport } from './routes/admin/mcp-logs/index'
import { Route as AdminPipelineIndexRouteImport } from './routes/admin/pipeline/index'
import { Route as GuidesSlugIndexRouteImport } from './routes/guides/$slug/index'
import { Route as InviteAcceptIndexRouteImport } from './routes/invite/accept/index'
import { Route as STokenIndexRouteImport } from './routes/s/$token/index'
import { Route as WorkspaceDevDesignIndexRouteImport } from './routes/_workspace/dev/design/index'
import { Route as WorkspaceEcosystemsIdIndexRouteImport } from './routes/_workspace/ecosystems/$id/index'
import { Route as WorkspaceEcosystemsNewIndexRouteImport } from './routes/_workspace/ecosystems/new/index'
import { Route as WorkspaceEcosystemsThreadsIndexRouteImport } from './routes/_workspace/ecosystems/threads/index'
import { Route as WorkspaceProjectsSlugIndexRouteImport } from './routes/_workspace/projects/$slug/index'
import { Route as WorkspaceEcosystemsIdSettingsIndexRouteImport } from './routes/_workspace/ecosystems/$id/settings/index'
import { Route as WorkspaceProjectsSlugAgentsIndexRouteImport } from './routes/_workspace/projects/$slug/agents/index'
import { Route as WorkspaceProjectsSlugAutomationIndexRouteImport } from './routes/_workspace/projects/$slug/automation/index'
import { Route as WorkspaceProjectsSlugContractsIndexRouteImport } from './routes/_workspace/projects/$slug/contracts/index'
import { Route as WorkspaceProjectsSlugDecisionsIndexRouteImport } from './routes/_workspace/projects/$slug/decisions/index'
import { Route as WorkspaceProjectsSlugFeedbackIndexRouteImport } from './routes/_workspace/projects/$slug/feedback/index'
import { Route as WorkspaceProjectsSlugIssuesIndexRouteImport } from './routes/_workspace/projects/$slug/issues/index'
import { Route as WorkspaceProjectsSlugMemoryIndexRouteImport } from './routes/_workspace/projects/$slug/memory/index'
import { Route as WorkspaceProjectsSlugModulesIndexRouteImport } from './routes/_workspace/projects/$slug/modules/index'
import { Route as WorkspaceProjectsSlugOverviewIndexRouteImport } from './routes/_workspace/projects/$slug/overview/index'
import { Route as WorkspaceProjectsSlugPipelineIndexRouteImport } from './routes/_workspace/projects/$slug/pipeline/index'
import { Route as WorkspaceProjectsSlugReleasesIndexRouteImport } from './routes/_workspace/projects/$slug/releases/index'
import { Route as WorkspaceProjectsSlugRequirementsIndexRouteImport } from './routes/_workspace/projects/$slug/requirements/index'
import { Route as WorkspaceProjectsSlugRoadmapIndexRouteImport } from './routes/_workspace/projects/$slug/roadmap/index'
import { Route as WorkspaceProjectsSlugSettingsIndexRouteImport } from './routes/_workspace/projects/$slug/settings/index'
import { Route as WorkspaceProjectsSlugStatusIndexRouteImport } from './routes/_workspace/projects/$slug/status/index'
import { Route as WorkspaceProjectsSlugWorkflowsIndexRouteImport } from './routes/_workspace/projects/$slug/workflows/index'
import { Route as WorkspaceProjectsSlugAgentsSessionIdIndexRouteImport } from './routes/_workspace/projects/$slug/agents/$sessionId/index'
import { Route as WorkspaceProjectsSlugAgentsMasterIndexRouteImport } from './routes/_workspace/projects/$slug/agents/master/index'
import { Route as WorkspaceProjectsSlugEcosystemApiIndexRouteImport } from './routes/_workspace/projects/$slug/ecosystem/api/index'
import { Route as WorkspaceProjectsSlugFeedbackFeedbackIndexRouteImport } from './routes/_workspace/projects/$slug/feedback/$feedback/index'
import { Route as WorkspaceProjectsSlugIssuesIdIndexRouteImport } from './routes/_workspace/projects/$slug/issues/$id/index'
import { Route as WorkspaceProjectsSlugModulesModuleIndexRouteImport } from './routes/_workspace/projects/$slug/modules/$module/index'
import { Route as WorkspaceProjectsSlugReleasesReleaseIndexRouteImport } from './routes/_workspace/projects/$slug/releases/$release/index'
import { Route as WorkspaceProjectsSlugRequirementsRequirementIndexRouteImport } from './routes/_workspace/projects/$slug/requirements/$requirement/index'
import { Route as WorkspaceProjectsSlugRoomsRoomIndexRouteImport } from './routes/_workspace/projects/$slug/rooms/$room/index'
import { Route as WorkspaceProjectsSlugWorkflowsWorkflowIndexRouteImport } from './routes/_workspace/projects/$slug/workflows/$workflow/index'
import { Route as WorkspaceProjectsSlugAgentsRunsRunIdIndexRouteImport } from './routes/_workspace/projects/$slug/agents/runs/$runId/index'
import { Route as WorkspaceProjectsSlugAutomationFiresFireIdIndexRouteImport } from './routes/_workspace/projects/$slug/automation/fires/$fireId/index'
import { Route as WorkspaceProjectsSlugAutomationReportsReportIdIndexRouteImport } from './routes/_workspace/projects/$slug/automation/reports/$reportId/index'
import { Route as WorkspaceProjectsSlugAutomationSchedulesScheduleIdIndexRouteImport } from './routes/_workspace/projects/$slug/automation/schedules/$scheduleId/index'
import { Route as WorkspaceProjectsSlugContractsProviderContractIndexRouteImport } from './routes/_workspace/projects/$slug/contracts/$provider/$contract/index'
import { Route as WorkspaceProjectsSlugEcosystemChannelRefIndexRouteImport } from './routes/_workspace/projects/$slug/ecosystem/channel/$ref/index'
import { Route as WorkspaceProjectsSlugEcosystemChannelNewIndexRouteImport } from './routes/_workspace/projects/$slug/ecosystem/channel/new/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkChatIndexRoute = LinkChatIndexRouteImport.update({
  id: '/link-chat/',
  path: '/link-chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const WorkspaceAttentionIndexRoute = WorkspaceAttentionIndexRouteImport.update({
  id: '/attention/',
  path: '/attention/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceDocsIndexRoute = WorkspaceDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceEcosystemsIndexRoute =
  WorkspaceEcosystemsIndexRouteImport.update({
    id: '/ecosystems/',
    path: '/ecosystems/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceIntegrationsIndexRoute =
  WorkspaceIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceOpsIndexRoute = WorkspaceOpsIndexRouteImport.update({
  id: '/ops/',
  path: '/ops/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceOrgIndexRoute = WorkspaceOrgIndexRouteImport.update({
  id: '/org/',
  path: '/org/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspacePairIndexRoute = WorkspacePairIndexRouteImport.update({
  id: '/pair/',
  path: '/pair/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceProjectsIndexRoute = WorkspaceProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceProjectsSlugRouteRoute =
  WorkspaceProjectsSlugRouteRouteImport.update({
    id: '/projects/$slug',
    path: '/projects/$slug',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceRunnersIndexRoute = WorkspaceRunnersIndexRouteImport.update({
  id: '/runners/',
  path: '/runners/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceSettingsIndexRoute = WorkspaceSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const AdminAlertsIndexRoute = AdminAlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFleetIndexRoute = AdminFleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGrowthIndexRoute = AdminGrowthIndexRouteImport.update({
  id: '/growth/',
  path: '/growth/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMcpLogsIndexRoute = AdminMcpLogsIndexRouteImport.update({
  id: '/mcp-logs/',
  path: '/mcp-logs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPipelineIndexRoute = AdminPipelineIndexRouteImport.update({
  id: '/pipeline/',
  path: '/pipeline/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const GuidesSlugIndexRoute = GuidesSlugIndexRouteImport.update({
  id: '/guides/$slug/',
  path: '/guides/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteAcceptIndexRoute = InviteAcceptIndexRouteImport.update({
  id: '/invite/accept/',
  path: '/invite/accept/',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenIndexRoute = STokenIndexRouteImport.update({
  id: '/s/$token/',
  path: '/s/$token/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceDevDesignIndexRoute = WorkspaceDevDesignIndexRouteImport.update({
  id: '/dev/design/',
  path: '/dev/design/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceEcosystemsIdIndexRoute =
  WorkspaceEcosystemsIdIndexRouteImport.update({
    id: '/ecosystems/$id/',
    path: '/ecosystems/$id/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceEcosystemsNewIndexRoute =
  WorkspaceEcosystemsNewIndexRouteImport.update({
    id: '/ecosystems/new/',
    path: '/ecosystems/new/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceEcosystemsThreadsIndexRoute =
  WorkspaceEcosystemsThreadsIndexRouteImport.update({
    id: '/ecosystems/threads/',
    path: '/ecosystems/threads/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceProjectsSlugIndexRoute =
  WorkspaceProjectsSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceEcosystemsIdSettingsIndexRoute =
  WorkspaceEcosystemsIdSettingsIndexRouteImport.update({
    id: '/ecosystems/$id/settings/',
    path: '/ecosystems/$id/settings/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceProjectsSlugAgentsIndexRoute =
  WorkspaceProjectsSlugAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugAutomationIndexRoute =
  WorkspaceProjectsSlugAutomationIndexRouteImport.update({
    id: '/automation/',
    path: '/automation/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugContractsIndexRoute =
  WorkspaceProjectsSlugContractsIndexRouteImport.update({
    id: '/contracts/',
    path: '/contracts/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugDecisionsIndexRoute =
  WorkspaceProjectsSlugDecisionsIndexRouteImport.update({
    id: '/decisions/',
    path: '/decisions/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugFeedbackIndexRoute =
  WorkspaceProjectsSlugFeedbackIndexRouteImport.update({
    id: '/feedback/',
    path: '/feedback/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugIssuesIndexRoute =
  WorkspaceProjectsSlugIssuesIndexRouteImport.update({
    id: '/issues/',
    path: '/issues/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugMemoryIndexRoute =
  WorkspaceProjectsSlugMemoryIndexRouteImport.update({
    id: '/memory/',
    path: '/memory/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugModulesIndexRoute =
  WorkspaceProjectsSlugModulesIndexRouteImport.update({
    id: '/modules/',
    path: '/modules/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugOverviewIndexRoute =
  WorkspaceProjectsSlugOverviewIndexRouteImport.update({
    id: '/overview/',
    path: '/overview/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugPipelineIndexRoute =
  WorkspaceProjectsSlugPipelineIndexRouteImport.update({
    id: '/pipeline/',
    path: '/pipeline/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugReleasesIndexRoute =
  WorkspaceProjectsSlugReleasesIndexRouteImport.update({
    id: '/releases/',
    path: '/releases/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugRequirementsIndexRoute =
  WorkspaceProjectsSlugRequirementsIndexRouteImport.update({
    id: '/requirements/',
    path: '/requirements/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugRoadmapIndexRoute =
  WorkspaceProjectsSlugRoadmapIndexRouteImport.update({
    id: '/roadmap/',
    path: '/roadmap/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugSettingsIndexRoute =
  WorkspaceProjectsSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugStatusIndexRoute =
  WorkspaceProjectsSlugStatusIndexRouteImport.update({
    id: '/status/',
    path: '/status/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugWorkflowsIndexRoute =
  WorkspaceProjectsSlugWorkflowsIndexRouteImport.update({
    id: '/workflows/',
    path: '/workflows/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugAgentsSessionIdIndexRoute =
  WorkspaceProjectsSlugAgentsSessionIdIndexRouteImport.update({
    id: '/agents/$sessionId/',
    path: '/agents/$sessionId/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugAgentsMasterIndexRoute =
  WorkspaceProjectsSlugAgentsMasterIndexRouteImport.update({
    id: '/agents/master/',
    path: '/agents/master/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugEcosystemApiIndexRoute =
  WorkspaceProjectsSlugEcosystemApiIndexRouteImport.update({
    id: '/ecosystem/api/',
    path: '/ecosystem/api/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugFeedbackFeedbackIndexRoute =
  WorkspaceProjectsSlugFeedbackFeedbackIndexRouteImport.update({
    id: '/feedback/$feedback/',
    path: '/feedback/$feedback/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugIssuesIdIndexRoute =
  WorkspaceProjectsSlugIssuesIdIndexRouteImport.update({
    id: '/issues/$id/',
    path: '/issues/$id/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugModulesModuleIndexRoute =
  WorkspaceProjectsSlugModulesModuleIndexRouteImport.update({
    id: '/modules/$module/',
    path: '/modules/$module/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugReleasesReleaseIndexRoute =
  WorkspaceProjectsSlugReleasesReleaseIndexRouteImport.update({
    id: '/releases/$release/',
    path: '/releases/$release/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugRequirementsRequirementIndexRoute =
  WorkspaceProjectsSlugRequirementsRequirementIndexRouteImport.update({
    id: '/requirements/$requirement/',
    path: '/requirements/$requirement/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugRoomsRoomIndexRoute =
  WorkspaceProjectsSlugRoomsRoomIndexRouteImport.update({
    id: '/rooms/$room/',
    path: '/rooms/$room/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugWorkflowsWorkflowIndexRoute =
  WorkspaceProjectsSlugWorkflowsWorkflowIndexRouteImport.update({
    id: '/workflows/$workflow/',
    path: '/workflows/$workflow/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugAgentsRunsRunIdIndexRoute =
  WorkspaceProjectsSlugAgentsRunsRunIdIndexRouteImport.update({
    id: '/agents/runs/$runId/',
    path: '/agents/runs/$runId/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugAutomationFiresFireIdIndexRoute =
  WorkspaceProjectsSlugAutomationFiresFireIdIndexRouteImport.update({
    id: '/automation/fires/$fireId/',
    path: '/automation/fires/$fireId/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugAutomationReportsReportIdIndexRoute =
  WorkspaceProjectsSlugAutomationReportsReportIdIndexRouteImport.update({
    id: '/automation/reports/$reportId/',
    path: '/automation/reports/$reportId/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugAutomationSchedulesScheduleIdIndexRoute =
  WorkspaceProjectsSlugAutomationSchedulesScheduleIdIndexRouteImport.update({
    id: '/automation/schedules/$scheduleId/',
    path: '/automation/schedules/$scheduleId/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugContractsProviderContractIndexRoute =
  WorkspaceProjectsSlugContractsProviderContractIndexRouteImport.update({
    id: '/contracts/$provider/$contract/',
    path: '/contracts/$provider/$contract/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugEcosystemChannelRefIndexRoute =
  WorkspaceProjectsSlugEcosystemChannelRefIndexRouteImport.update({
    id: '/ecosystem/channel/$ref/',
    path: '/ecosystem/channel/$ref/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)
const WorkspaceProjectsSlugEcosystemChannelNewIndexRoute =
  WorkspaceProjectsSlugEcosystemChannelNewIndexRouteImport.update({
    id: '/ecosystem/channel/new/',
    path: '/ecosystem/channel/new/',
    getParentRoute: () => WorkspaceProjectsSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/link-chat/': typeof LinkChatIndexRoute
  '/projects/$slug': typeof WorkspaceProjectsSlugRouteRouteWithChildren
  '/login/': typeof AuthLoginIndexRoute
  '/register/': typeof AuthRegisterIndexRoute
  '/attention/': typeof WorkspaceAttentionIndexRoute
  '/docs/': typeof WorkspaceDocsIndexRoute
  '/ecosystems/': typeof WorkspaceEcosystemsIndexRoute
  '/integrations/': typeof WorkspaceIntegrationsIndexRoute
  '/ops/': typeof WorkspaceOpsIndexRoute
  '/org/': typeof WorkspaceOrgIndexRoute
  '/pair/': typeof WorkspacePairIndexRoute
  '/projects/': typeof WorkspaceProjectsIndexRoute
  '/runners/': typeof WorkspaceRunnersIndexRoute
  '/settings/': typeof WorkspaceSettingsIndexRoute
  '/admin/alerts/': typeof AdminAlertsIndexRoute
  '/admin/fleet/': typeof AdminFleetIndexRoute
  '/admin/growth/': typeof AdminGrowthIndexRoute
  '/admin/mcp-logs/': typeof AdminMcpLogsIndexRoute
  '/admin/pipeline/': typeof AdminPipelineIndexRoute
  '/guides/$slug/': typeof GuidesSlugIndexRoute
  '/invite/accept/': typeof InviteAcceptIndexRoute
  '/s/$token/': typeof STokenIndexRoute
  '/dev/design/': typeof WorkspaceDevDesignIndexRoute
  '/ecosystems/$id/': typeof WorkspaceEcosystemsIdIndexRoute
  '/ecosystems/new/': typeof WorkspaceEcosystemsNewIndexRoute
  '/ecosystems/threads/': typeof WorkspaceEcosystemsThreadsIndexRoute
  '/projects/$slug/': typeof WorkspaceProjectsSlugIndexRoute
  '/ecosystems/$id/settings/': typeof WorkspaceEcosystemsIdSettingsIndexRoute
  '/projects/$slug/agents/': typeof WorkspaceProjectsSlugAgentsIndexRoute
  '/projects/$slug/automation/': typeof WorkspaceProjectsSlugAutomationIndexRoute
  '/projects/$slug/contracts/': typeof WorkspaceProjectsSlugContractsIndexRoute
  '/projects/$slug/decisions/': typeof WorkspaceProjectsSlugDecisionsIndexRoute
  '/projects/$slug/feedback/': typeof WorkspaceProjectsSlugFeedbackIndexRoute
  '/projects/$slug/issues/': typeof WorkspaceProjectsSlugIssuesIndexRoute
  '/projects/$slug/memory/': typeof WorkspaceProjectsSlugMemoryIndexRoute
  '/projects/$slug/modules/': typeof WorkspaceProjectsSlugModulesIndexRoute
  '/projects/$slug/overview/': typeof WorkspaceProjectsSlugOverviewIndexRoute
  '/projects/$slug/pipeline/': typeof WorkspaceProjectsSlugPipelineIndexRoute
  '/projects/$slug/releases/': typeof WorkspaceProjectsSlugReleasesIndexRoute
  '/projects/$slug/requirements/': typeof WorkspaceProjectsSlugRequirementsIndexRoute
  '/projects/$slug/roadmap/': typeof WorkspaceProjectsSlugRoadmapIndexRoute
  '/projects/$slug/settings/': typeof WorkspaceProjectsSlugSettingsIndexRoute
  '/projects/$slug/status/': typeof WorkspaceProjectsSlugStatusIndexRoute
  '/projects/$slug/workflows/': typeof WorkspaceProjectsSlugWorkflowsIndexRoute
  '/projects/$slug/agents/$sessionId/': typeof WorkspaceProjectsSlugAgentsSessionIdIndexRoute
  '/projects/$slug/agents/master/': typeof WorkspaceProjectsSlugAgentsMasterIndexRoute
  '/projects/$slug/ecosystem/api/': typeof WorkspaceProjectsSlugEcosystemApiIndexRoute
  '/projects/$slug/feedback/$feedback/': typeof WorkspaceProjectsSlugFeedbackFeedbackIndexRoute
  '/projects/$slug/issues/$id/': typeof WorkspaceProjectsSlugIssuesIdIndexRoute
  '/projects/$slug/modules/$module/': typeof WorkspaceProjectsSlugModulesModuleIndexRoute
  '/projects/$slug/releases/$release/': typeof WorkspaceProjectsSlugReleasesReleaseIndexRoute
  '/projects/$slug/requirements/$requirement/': typeof WorkspaceProjectsSlugRequirementsRequirementIndexRoute
  '/projects/$slug/rooms/$room/': typeof WorkspaceProjectsSlugRoomsRoomIndexRoute
  '/projects/$slug/workflows/$workflow/': typeof WorkspaceProjectsSlugWorkflowsWorkflowIndexRoute
  '/projects/$slug/agents/runs/$runId/': typeof WorkspaceProjectsSlugAgentsRunsRunIdIndexRoute
  '/projects/$slug/automation/fires/$fireId/': typeof WorkspaceProjectsSlugAutomationFiresFireIdIndexRoute
  '/projects/$slug/automation/reports/$reportId/': typeof WorkspaceProjectsSlugAutomationReportsReportIdIndexRoute
  '/projects/$slug/automation/schedules/$scheduleId/': typeof WorkspaceProjectsSlugAutomationSchedulesScheduleIdIndexRoute
  '/projects/$slug/contracts/$provider/$contract/': typeof WorkspaceProjectsSlugContractsProviderContractIndexRoute
  '/projects/$slug/ecosystem/channel/$ref/': typeof WorkspaceProjectsSlugEcosystemChannelRefIndexRoute
  '/projects/$slug/ecosystem/channel/new/': typeof WorkspaceProjectsSlugEcosystemChannelNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof WorkspaceIndexRoute
  '/admin': typeof AdminIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/link-chat': typeof LinkChatIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/attention': typeof WorkspaceAttentionIndexRoute
  '/docs': typeof WorkspaceDocsIndexRoute
  '/ecosystems': typeof WorkspaceEcosystemsIndexRoute
  '/integrations': typeof WorkspaceIntegrationsIndexRoute
  '/ops': typeof WorkspaceOpsIndexRoute
  '/org': typeof WorkspaceOrgIndexRoute
  '/pair': typeof WorkspacePairIndexRoute
  '/projects': typeof WorkspaceProjectsIndexRoute
  '/runners': typeof WorkspaceRunnersIndexRoute
  '/settings': typeof WorkspaceSettingsIndexRoute
  '/admin/alerts': typeof AdminAlertsIndexRoute
  '/admin/fleet': typeof AdminFleetIndexRoute
  '/admin/growth': typeof AdminGrowthIndexRoute
  '/admin/mcp-logs': typeof AdminMcpLogsIndexRoute
  '/admin/pipeline': typeof AdminPipelineIndexRoute
  '/guides/$slug': typeof GuidesSlugIndexRoute
  '/invite/accept': typeof InviteAcceptIndexRoute
  '/s/$token': typeof STokenIndexRoute
  '/dev/design': typeof WorkspaceDevDesignIndexRoute
  '/ecosystems/$id': typeof WorkspaceEcosystemsIdIndexRoute
  '/ecosystems/new': typeof WorkspaceEcosystemsNewIndexRoute
  '/ecosystems/threads': typeof WorkspaceEcosystemsThreadsIndexRoute
  '/projects/$slug': typeof WorkspaceProjectsSlugIndexRoute
  '/ecosystems/$id/settings': typeof WorkspaceEcosystemsIdSettingsIndexRoute
  '/projects/$slug/agents': typeof WorkspaceProjectsSlugAgentsIndexRoute
  '/projects/$slug/automation': typeof WorkspaceProjectsSlugAutomationIndexRoute
  '/projects/$slug/contracts': typeof WorkspaceProjectsSlugContractsIndexRoute
  '/projects/$slug/decisions': typeof WorkspaceProjectsSlugDecisionsIndexRoute
  '/projects/$slug/feedback': typeof WorkspaceProjectsSlugFeedbackIndexRoute
  '/projects/$slug/issues': typeof WorkspaceProjectsSlugIssuesIndexRoute
  '/projects/$slug/memory': typeof WorkspaceProjectsSlugMemoryIndexRoute
  '/projects/$slug/modules': typeof WorkspaceProjectsSlugModulesIndexRoute
  '/projects/$slug/overview': typeof WorkspaceProjectsSlugOverviewIndexRoute
  '/projects/$slug/pipeline': typeof WorkspaceProjectsSlugPipelineIndexRoute
  '/projects/$slug/releases': typeof WorkspaceProjectsSlugReleasesIndexRoute
  '/projects/$slug/requirements': typeof WorkspaceProjectsSlugRequirementsIndexRoute
  '/projects/$slug/roadmap': typeof WorkspaceProjectsSlugRoadmapIndexRoute
  '/projects/$slug/settings': typeof WorkspaceProjectsSlugSettingsIndexRoute
  '/projects/$slug/status': typeof WorkspaceProjectsSlugStatusIndexRoute
  '/projects/$slug/workflows': typeof WorkspaceProjectsSlugWorkflowsIndexRoute
  '/projects/$slug/agents/$sessionId': typeof WorkspaceProjectsSlugAgentsSessionIdIndexRoute
  '/projects/$slug/agents/master': typeof WorkspaceProjectsSlugAgentsMasterIndexRoute
  '/projects/$slug/ecosystem/api': typeof WorkspaceProjectsSlugEcosystemApiIndexRoute
  '/projects/$slug/feedback/$feedback': typeof WorkspaceProjectsSlugFeedbackFeedbackIndexRoute
  '/projects/$slug/issues/$id': typeof WorkspaceProjectsSlugIssuesIdIndexRoute
  '/projects/$slug/modules/$module': typeof WorkspaceProjectsSlugModulesModuleIndexRoute
  '/projects/$slug/releases/$release': typeof WorkspaceProjectsSlugReleasesReleaseIndexRoute
  '/projects/$slug/requirements/$requirement': typeof WorkspaceProjectsSlugRequirementsRequirementIndexRoute
  '/projects/$slug/rooms/$room': typeof WorkspaceProjectsSlugRoomsRoomIndexRoute
  '/projects/$slug/workflows/$workflow': typeof WorkspaceProjectsSlugWorkflowsWorkflowIndexRoute
  '/projects/$slug/agents/runs/$runId': typeof WorkspaceProjectsSlugAgentsRunsRunIdIndexRoute
  '/projects/$slug/automation/fires/$fireId': typeof WorkspaceProjectsSlugAutomationFiresFireIdIndexRoute
  '/projects/$slug/automation/reports/$reportId': typeof WorkspaceProjectsSlugAutomationReportsReportIdIndexRoute
  '/projects/$slug/automation/schedules/$scheduleId': typeof WorkspaceProjectsSlugAutomationSchedulesScheduleIdIndexRoute
  '/projects/$slug/contracts/$provider/$contract': typeof WorkspaceProjectsSlugContractsProviderContractIndexRoute
  '/projects/$slug/ecosystem/channel/$ref': typeof WorkspaceProjectsSlugEcosystemChannelRefIndexRoute
  '/projects/$slug/ecosystem/channel/new': typeof WorkspaceProjectsSlugEcosystemChannelNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_workspace': typeof WorkspaceRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_workspace/': typeof WorkspaceIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/link-chat/': typeof LinkChatIndexRoute
  '/_workspace/projects/$slug': typeof WorkspaceProjectsSlugRouteRouteWithChildren
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/_workspace/attention/': typeof WorkspaceAttentionIndexRoute
  '/_workspace/docs/': typeof WorkspaceDocsIndexRoute
  '/_workspace/ecosystems/': typeof WorkspaceEcosystemsIndexRoute
  '/_workspace/integrations/': typeof WorkspaceIntegrationsIndexRoute
  '/_workspace/ops/': typeof WorkspaceOpsIndexRoute
  '/_workspace/org/': typeof WorkspaceOrgIndexRoute
  '/_workspace/pair/': typeof WorkspacePairIndexRoute
  '/_workspace/projects/': typeof WorkspaceProjectsIndexRoute
  '/_workspace/runners/': typeof WorkspaceRunnersIndexRoute
  '/_workspace/settings/': typeof WorkspaceSettingsIndexRoute
  '/admin/alerts/': typeof AdminAlertsIndexRoute
  '/admin/fleet/': typeof AdminFleetIndexRoute
  '/admin/growth/': typeof AdminGrowthIndexRoute
  '/admin/mcp-logs/': typeof AdminMcpLogsIndexRoute
  '/admin/pipeline/': typeof AdminPipelineIndexRoute
  '/guides/$slug/': typeof GuidesSlugIndexRoute
  '/invite/accept/': typeof InviteAcceptIndexRoute
  '/s/$token/': typeof STokenIndexRoute
  '/_workspace/dev/design/': typeof WorkspaceDevDesignIndexRoute
  '/_workspace/ecosystems/$id/': typeof WorkspaceEcosystemsIdIndexRoute
  '/_workspace/ecosystems/new/': typeof WorkspaceEcosystemsNewIndexRoute
  '/_workspace/ecosystems/threads/': typeof WorkspaceEcosystemsThreadsIndexRoute
  '/_workspace/projects/$slug/': typeof WorkspaceProjectsSlugIndexRoute
  '/_workspace/ecosystems/$id/settings/': typeof WorkspaceEcosystemsIdSettingsIndexRoute
  '/_workspace/projects/$slug/agents/': typeof WorkspaceProjectsSlugAgentsIndexRoute
  '/_workspace/projects/$slug/automation/': typeof WorkspaceProjectsSlugAutomationIndexRoute
  '/_workspace/projects/$slug/contracts/': typeof WorkspaceProjectsSlugContractsIndexRoute
  '/_workspace/projects/$slug/decisions/': typeof WorkspaceProjectsSlugDecisionsIndexRoute
  '/_workspace/projects/$slug/feedback/': typeof WorkspaceProjectsSlugFeedbackIndexRoute
  '/_workspace/projects/$slug/issues/': typeof WorkspaceProjectsSlugIssuesIndexRoute
  '/_workspace/projects/$slug/memory/': typeof WorkspaceProjectsSlugMemoryIndexRoute
  '/_workspace/projects/$slug/modules/': typeof WorkspaceProjectsSlugModulesIndexRoute
  '/_workspace/projects/$slug/overview/': typeof WorkspaceProjectsSlugOverviewIndexRoute
  '/_workspace/projects/$slug/pipeline/': typeof WorkspaceProjectsSlugPipelineIndexRoute
  '/_workspace/projects/$slug/releases/': typeof WorkspaceProjectsSlugReleasesIndexRoute
  '/_workspace/projects/$slug/requirements/': typeof WorkspaceProjectsSlugRequirementsIndexRoute
  '/_workspace/projects/$slug/roadmap/': typeof WorkspaceProjectsSlugRoadmapIndexRoute
  '/_workspace/projects/$slug/settings/': typeof WorkspaceProjectsSlugSettingsIndexRoute
  '/_workspace/projects/$slug/status/': typeof WorkspaceProjectsSlugStatusIndexRoute
  '/_workspace/projects/$slug/workflows/': typeof WorkspaceProjectsSlugWorkflowsIndexRoute
  '/_workspace/projects/$slug/agents/$sessionId/': typeof WorkspaceProjectsSlugAgentsSessionIdIndexRoute
  '/_workspace/projects/$slug/agents/master/': typeof WorkspaceProjectsSlugAgentsMasterIndexRoute
  '/_workspace/projects/$slug/ecosystem/api/': typeof WorkspaceProjectsSlugEcosystemApiIndexRoute
  '/_workspace/projects/$slug/feedback/$feedback/': typeof WorkspaceProjectsSlugFeedbackFeedbackIndexRoute
  '/_workspace/projects/$slug/issues/$id/': typeof WorkspaceProjectsSlugIssuesIdIndexRoute
  '/_workspace/projects/$slug/modules/$module/': typeof WorkspaceProjectsSlugModulesModuleIndexRoute
  '/_workspace/projects/$slug/releases/$release/': typeof WorkspaceProjectsSlugReleasesReleaseIndexRoute
  '/_workspace/projects/$slug/requirements/$requirement/': typeof WorkspaceProjectsSlugRequirementsRequirementIndexRoute
  '/_workspace/projects/$slug/rooms/$room/': typeof WorkspaceProjectsSlugRoomsRoomIndexRoute
  '/_workspace/projects/$slug/workflows/$workflow/': typeof WorkspaceProjectsSlugWorkflowsWorkflowIndexRoute
  '/_workspace/projects/$slug/agents/runs/$runId/': typeof WorkspaceProjectsSlugAgentsRunsRunIdIndexRoute
  '/_workspace/projects/$slug/automation/fires/$fireId/': typeof WorkspaceProjectsSlugAutomationFiresFireIdIndexRoute
  '/_workspace/projects/$slug/automation/reports/$reportId/': typeof WorkspaceProjectsSlugAutomationReportsReportIdIndexRoute
  '/_workspace/projects/$slug/automation/schedules/$scheduleId/': typeof WorkspaceProjectsSlugAutomationSchedulesScheduleIdIndexRoute
  '/_workspace/projects/$slug/contracts/$provider/$contract/': typeof WorkspaceProjectsSlugContractsProviderContractIndexRoute
  '/_workspace/projects/$slug/ecosystem/channel/$ref/': typeof WorkspaceProjectsSlugEcosystemChannelRefIndexRoute
  '/_workspace/projects/$slug/ecosystem/channel/new/': typeof WorkspaceProjectsSlugEcosystemChannelNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/'
    | '/guides/'
    | '/link-chat/'
    | '/projects/$slug'
    | '/login/'
    | '/register/'
    | '/attention/'
    | '/docs/'
    | '/ecosystems/'
    | '/integrations/'
    | '/ops/'
    | '/org/'
    | '/pair/'
    | '/projects/'
    | '/runners/'
    | '/settings/'
    | '/admin/alerts/'
    | '/admin/fleet/'
    | '/admin/growth/'
    | '/admin/mcp-logs/'
    | '/admin/pipeline/'
    | '/guides/$slug/'
    | '/invite/accept/'
    | '/s/$token/'
    | '/dev/design/'
    | '/ecosystems/$id/'
    | '/ecosystems/new/'
    | '/ecosystems/threads/'
    | '/projects/$slug/'
    | '/ecosystems/$id/settings/'
    | '/projects/$slug/agents/'
    | '/projects/$slug/automation/'
    | '/projects/$slug/contracts/'
    | '/projects/$slug/decisions/'
    | '/projects/$slug/feedback/'
    | '/projects/$slug/issues/'
    | '/projects/$slug/memory/'
    | '/projects/$slug/modules/'
    | '/projects/$slug/overview/'
    | '/projects/$slug/pipeline/'
    | '/projects/$slug/releases/'
    | '/projects/$slug/requirements/'
    | '/projects/$slug/roadmap/'
    | '/projects/$slug/settings/'
    | '/projects/$slug/status/'
    | '/projects/$slug/workflows/'
    | '/projects/$slug/agents/$sessionId/'
    | '/projects/$slug/agents/master/'
    | '/projects/$slug/ecosystem/api/'
    | '/projects/$slug/feedback/$feedback/'
    | '/projects/$slug/issues/$id/'
    | '/projects/$slug/modules/$module/'
    | '/projects/$slug/releases/$release/'
    | '/projects/$slug/requirements/$requirement/'
    | '/projects/$slug/rooms/$room/'
    | '/projects/$slug/workflows/$workflow/'
    | '/projects/$slug/agents/runs/$runId/'
    | '/projects/$slug/automation/fires/$fireId/'
    | '/projects/$slug/automation/reports/$reportId/'
    | '/projects/$slug/automation/schedules/$scheduleId/'
    | '/projects/$slug/contracts/$provider/$contract/'
    | '/projects/$slug/ecosystem/channel/$ref/'
    | '/projects/$slug/ecosystem/channel/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/guides'
    | '/link-chat'
    | '/login'
    | '/register'
    | '/attention'
    | '/docs'
    | '/ecosystems'
    | '/integrations'
    | '/ops'
    | '/org'
    | '/pair'
    | '/projects'
    | '/runners'
    | '/settings'
    | '/admin/alerts'
    | '/admin/fleet'
    | '/admin/growth'
    | '/admin/mcp-logs'
    | '/admin/pipeline'
    | '/guides/$slug'
    | '/invite/accept'
    | '/s/$token'
    | '/dev/design'
    | '/ecosystems/$id'
    | '/ecosystems/new'
    | '/ecosystems/threads'
    | '/projects/$slug'
    | '/ecosystems/$id/settings'
    | '/projects/$slug/agents'
    | '/projects/$slug/automation'
    | '/projects/$slug/contracts'
    | '/projects/$slug/decisions'
    | '/projects/$slug/feedback'
    | '/projects/$slug/issues'
    | '/projects/$slug/memory'
    | '/projects/$slug/modules'
    | '/projects/$slug/overview'
    | '/projects/$slug/pipeline'
    | '/projects/$slug/releases'
    | '/projects/$slug/requirements'
    | '/projects/$slug/roadmap'
    | '/projects/$slug/settings'
    | '/projects/$slug/status'
    | '/projects/$slug/workflows'
    | '/projects/$slug/agents/$sessionId'
    | '/projects/$slug/agents/master'
    | '/projects/$slug/ecosystem/api'
    | '/projects/$slug/feedback/$feedback'
    | '/projects/$slug/issues/$id'
    | '/projects/$slug/modules/$module'
    | '/projects/$slug/releases/$release'
    | '/projects/$slug/requirements/$requirement'
    | '/projects/$slug/rooms/$room'
    | '/projects/$slug/workflows/$workflow'
    | '/projects/$slug/agents/runs/$runId'
    | '/projects/$slug/automation/fires/$fireId'
    | '/projects/$slug/automation/reports/$reportId'
    | '/projects/$slug/automation/schedules/$scheduleId'
    | '/projects/$slug/contracts/$provider/$contract'
    | '/projects/$slug/ecosystem/channel/$ref'
    | '/projects/$slug/ecosystem/channel/new'
  id:
    | '__root__'
    | '/_auth'
    | '/_workspace'
    | '/admin'
    | '/_workspace/'
    | '/admin/'
    | '/guides/'
    | '/link-chat/'
    | '/_workspace/projects/$slug'
    | '/_auth/login/'
    | '/_auth/register/'
    | '/_workspace/attention/'
    | '/_workspace/docs/'
    | '/_workspace/ecosystems/'
    | '/_workspace/integrations/'
    | '/_workspace/ops/'
    | '/_workspace/org/'
    | '/_workspace/pair/'
    | '/_workspace/projects/'
    | '/_workspace/runners/'
    | '/_workspace/settings/'
    | '/admin/alerts/'
    | '/admin/fleet/'
    | '/admin/growth/'
    | '/admin/mcp-logs/'
    | '/admin/pipeline/'
    | '/guides/$slug/'
    | '/invite/accept/'
    | '/s/$token/'
    | '/_workspace/dev/design/'
    | '/_workspace/ecosystems/$id/'
    | '/_workspace/ecosystems/new/'
    | '/_workspace/ecosystems/threads/'
    | '/_workspace/projects/$slug/'
    | '/_workspace/ecosystems/$id/settings/'
    | '/_workspace/projects/$slug/agents/'
    | '/_workspace/projects/$slug/automation/'
    | '/_workspace/projects/$slug/contracts/'
    | '/_workspace/projects/$slug/decisions/'
    | '/_workspace/projects/$slug/feedback/'
    | '/_workspace/projects/$slug/issues/'
    | '/_workspace/projects/$slug/memory/'
    | '/_workspace/projects/$slug/modules/'
    | '/_workspace/projects/$slug/overview/'
    | '/_workspace/projects/$slug/pipeline/'
    | '/_workspace/projects/$slug/releases/'
    | '/_workspace/projects/$slug/requirements/'
    | '/_workspace/projects/$slug/roadmap/'
    | '/_workspace/projects/$slug/settings/'
    | '/_workspace/projects/$slug/status/'
    | '/_workspace/projects/$slug/workflows/'
    | '/_workspace/projects/$slug/agents/$sessionId/'
    | '/_workspace/projects/$slug/agents/master/'
    | '/_workspace/projects/$slug/ecosystem/api/'
    | '/_workspace/projects/$slug/feedback/$feedback/'
    | '/_workspace/projects/$slug/issues/$id/'
    | '/_workspace/projects/$slug/modules/$module/'
    | '/_workspace/projects/$slug/releases/$release/'
    | '/_workspace/projects/$slug/requirements/$requirement/'
    | '/_workspace/projects/$slug/rooms/$room/'
    | '/_workspace/projects/$slug/workflows/$workflow/'
    | '/_workspace/projects/$slug/agents/runs/$runId/'
    | '/_workspace/projects/$slug/automation/fires/$fireId/'
    | '/_workspace/projects/$slug/automation/reports/$reportId/'
    | '/_workspace/projects/$slug/automation/schedules/$scheduleId/'
    | '/_workspace/projects/$slug/contracts/$provider/$contract/'
    | '/_workspace/projects/$slug/ecosystem/channel/$ref/'
    | '/_workspace/projects/$slug/ecosystem/channel/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  GuidesIndexRoute: typeof GuidesIndexRoute
  LinkChatIndexRoute: typeof LinkChatIndexRoute
  GuidesSlugIndexRoute: typeof GuidesSlugIndexRoute
  InviteAcceptIndexRoute: typeof InviteAcceptIndexRoute
  STokenIndexRoute: typeof STokenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link-chat/': {
      id: '/link-chat/'
      path: '/link-chat'
      fullPath: '/link-chat/'
      preLoaderRoute: typeof LinkChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_workspace/attention/': {
      id: '/_workspace/attention/'
      path: '/attention'
      fullPath: '/attention/'
      preLoaderRoute: typeof WorkspaceAttentionIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/docs/': {
      id: '/_workspace/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof WorkspaceDocsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/ecosystems/': {
      id: '/_workspace/ecosystems/'
      path: '/ecosystems'
      fullPath: '/ecosystems/'
      preLoaderRoute: typeof WorkspaceEcosystemsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/integrations/': {
      id: '/_workspace/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof WorkspaceIntegrationsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/ops/': {
      id: '/_workspace/ops/'
      path: '/ops'
      fullPath: '/ops/'
      preLoaderRoute: typeof WorkspaceOpsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/org/': {
      id: '/_workspace/org/'
      path: '/org'
      fullPath: '/org/'
      preLoaderRoute: typeof WorkspaceOrgIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/pair/': {
      id: '/_workspace/pair/'
      path: '/pair'
      fullPath: '/pair/'
      preLoaderRoute: typeof WorkspacePairIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/projects/': {
      id: '/_workspace/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof WorkspaceProjectsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/projects/$slug': {
      id: '/_workspace/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof WorkspaceProjectsSlugRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/runners/': {
      id: '/_workspace/runners/'
      path: '/runners'
      fullPath: '/runners/'
      preLoaderRoute: typeof WorkspaceRunnersIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/settings/': {
      id: '/_workspace/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof WorkspaceSettingsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/admin/alerts/': {
      id: '/admin/alerts/'
      path: '/alerts'
      fullPath: '/admin/alerts/'
      preLoaderRoute: typeof AdminAlertsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/fleet/': {
      id: '/admin/fleet/'
      path: '/fleet'
      fullPath: '/admin/fleet/'
      preLoaderRoute: typeof AdminFleetIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/growth/': {
      id: '/admin/growth/'
      path: '/growth'
      fullPath: '/admin/growth/'
      preLoaderRoute: typeof AdminGrowthIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/mcp-logs/': {
      id: '/admin/mcp-logs/'
      path: '/mcp-logs'
      fullPath: '/admin/mcp-logs/'
      preLoaderRoute: typeof AdminMcpLogsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pipeline/': {
      id: '/admin/pipeline/'
      path: '/pipeline'
      fullPath: '/admin/pipeline/'
      preLoaderRoute: typeof AdminPipelineIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/guides/$slug/': {
      id: '/guides/$slug/'
      path: '/guides/$slug'
      fullPath: '/guides/$slug/'
      preLoaderRoute: typeof GuidesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/accept/': {
      id: '/invite/accept/'
      path: '/invite/accept'
      fullPath: '/invite/accept/'
      preLoaderRoute: typeof InviteAcceptIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token/': {
      id: '/s/$token/'
      path: '/s/$token'
      fullPath: '/s/$token/'
      preLoaderRoute: typeof STokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/dev/design/': {
      id: '/_workspace/dev/design/'
      path: '/dev/design'
      fullPath: '/dev/design/'
      preLoaderRoute: typeof WorkspaceDevDesignIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/ecosystems/$id/': {
      id: '/_workspace/ecosystems/$id/'
      path: '/ecosystems/$id'
      fullPath: '/ecosystems/$id/'
      preLoaderRoute: typeof WorkspaceEcosystemsIdIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/ecosystems/new/': {
      id: '/_workspace/ecosystems/new/'
      path: '/ecosystems/new'
      fullPath: '/ecosystems/new/'
      preLoaderRoute: typeof WorkspaceEcosystemsNewIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/ecosystems/threads/': {
      id: '/_workspace/ecosystems/threads/'
      path: '/ecosystems/threads'
      fullPath: '/ecosystems/threads/'
      preLoaderRoute: typeof WorkspaceEcosystemsThreadsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/projects/$slug/': {
      id: '/_workspace/projects/$slug/'
      path: '/'
      fullPath: '/projects/$slug/'
      preLoaderRoute: typeof WorkspaceProjectsSlugIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/ecosystems/$id/settings/': {
      id: '/_workspace/ecosystems/$id/settings/'
      path: '/ecosystems/$id/settings'
      fullPath: '/ecosystems/$id/settings/'
      preLoaderRoute: typeof WorkspaceEcosystemsIdSettingsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/projects/$slug/agents/': {
      id: '/_workspace/projects/$slug/agents/'
      path: '/agents'
      fullPath: '/projects/$slug/agents/'
      preLoaderRoute: typeof WorkspaceProjectsSlugAgentsIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/automation/': {
      id: '/_workspace/projects/$slug/automation/'
      path: '/automation'
      fullPath: '/projects/$slug/automation/'
      preLoaderRoute: typeof WorkspaceProjectsSlugAutomationIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/contracts/': {
      id: '/_workspace/projects/$slug/contracts/'
      path: '/contracts'
      fullPath: '/projects/$slug/contracts/'
      preLoaderRoute: typeof WorkspaceProjectsSlugContractsIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/decisions/': {
      id: '/_workspace/projects/$slug/decisions/'
      path: '/decisions'
      fullPath: '/projects/$slug/decisions/'
      preLoaderRoute: typeof WorkspaceProjectsSlugDecisionsIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/feedback/': {
      id: '/_workspace/projects/$slug/feedback/'
      path: '/feedback'
      fullPath: '/projects/$slug/feedback/'
      preLoaderRoute: typeof WorkspaceProjectsSlugFeedbackIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/issues/': {
      id: '/_workspace/projects/$slug/issues/'
      path: '/issues'
      fullPath: '/projects/$slug/issues/'
      preLoaderRoute: typeof WorkspaceProjectsSlugIssuesIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/memory/': {
      id: '/_workspace/projects/$slug/memory/'
      path: '/memory'
      fullPath: '/projects/$slug/memory/'
      preLoaderRoute: typeof WorkspaceProjectsSlugMemoryIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/modules/': {
      id: '/_workspace/projects/$slug/modules/'
      path: '/modules'
      fullPath: '/projects/$slug/modules/'
      preLoaderRoute: typeof WorkspaceProjectsSlugModulesIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/overview/': {
      id: '/_workspace/projects/$slug/overview/'
      path: '/overview'
      fullPath: '/projects/$slug/overview/'
      preLoaderRoute: typeof WorkspaceProjectsSlugOverviewIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/pipeline/': {
      id: '/_workspace/projects/$slug/pipeline/'
      path: '/pipeline'
      fullPath: '/projects/$slug/pipeline/'
      preLoaderRoute: typeof WorkspaceProjectsSlugPipelineIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/releases/': {
      id: '/_workspace/projects/$slug/releases/'
      path: '/releases'
      fullPath: '/projects/$slug/releases/'
      preLoaderRoute: typeof WorkspaceProjectsSlugReleasesIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/requirements/': {
      id: '/_workspace/projects/$slug/requirements/'
      path: '/requirements'
      fullPath: '/projects/$slug/requirements/'
      preLoaderRoute: typeof WorkspaceProjectsSlugRequirementsIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/roadmap/': {
      id: '/_workspace/projects/$slug/roadmap/'
      path: '/roadmap'
      fullPath: '/projects/$slug/roadmap/'
      preLoaderRoute: typeof WorkspaceProjectsSlugRoadmapIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/settings/': {
      id: '/_workspace/projects/$slug/settings/'
      path: '/settings'
      fullPath: '/projects/$slug/settings/'
      preLoaderRoute: typeof WorkspaceProjectsSlugSettingsIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/status/': {
      id: '/_workspace/projects/$slug/status/'
      path: '/status'
      fullPath: '/projects/$slug/status/'
      preLoaderRoute: typeof WorkspaceProjectsSlugStatusIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/workflows/': {
      id: '/_workspace/projects/$slug/workflows/'
      path: '/workflows'
      fullPath: '/projects/$slug/workflows/'
      preLoaderRoute: typeof WorkspaceProjectsSlugWorkflowsIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/agents/$sessionId/': {
      id: '/_workspace/projects/$slug/agents/$sessionId/'
      path: '/agents/$sessionId'
      fullPath: '/projects/$slug/agents/$sessionId/'
      preLoaderRoute: typeof WorkspaceProjectsSlugAgentsSessionIdIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/agents/master/': {
      id: '/_workspace/projects/$slug/agents/master/'
      path: '/agents/master'
      fullPath: '/projects/$slug/agents/master/'
      preLoaderRoute: typeof WorkspaceProjectsSlugAgentsMasterIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/ecosystem/api/': {
      id: '/_workspace/projects/$slug/ecosystem/api/'
      path: '/ecosystem/api'
      fullPath: '/projects/$slug/ecosystem/api/'
      preLoaderRoute: typeof WorkspaceProjectsSlugEcosystemApiIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/feedback/$feedback/': {
      id: '/_workspace/projects/$slug/feedback/$feedback/'
      path: '/feedback/$feedback'
      fullPath: '/projects/$slug/feedback/$feedback/'
      preLoaderRoute: typeof WorkspaceProjectsSlugFeedbackFeedbackIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/issues/$id/': {
      id: '/_workspace/projects/$slug/issues/$id/'
      path: '/issues/$id'
      fullPath: '/projects/$slug/issues/$id/'
      preLoaderRoute: typeof WorkspaceProjectsSlugIssuesIdIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/modules/$module/': {
      id: '/_workspace/projects/$slug/modules/$module/'
      path: '/modules/$module'
      fullPath: '/projects/$slug/modules/$module/'
      preLoaderRoute: typeof WorkspaceProjectsSlugModulesModuleIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/releases/$release/': {
      id: '/_workspace/projects/$slug/releases/$release/'
      path: '/releases/$release'
      fullPath: '/projects/$slug/releases/$release/'
      preLoaderRoute: typeof WorkspaceProjectsSlugReleasesReleaseIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/requirements/$requirement/': {
      id: '/_workspace/projects/$slug/requirements/$requirement/'
      path: '/requirements/$requirement'
      fullPath: '/projects/$slug/requirements/$requirement/'
      preLoaderRoute: typeof WorkspaceProjectsSlugRequirementsRequirementIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/rooms/$room/': {
      id: '/_workspace/projects/$slug/rooms/$room/'
      path: '/rooms/$room'
      fullPath: '/projects/$slug/rooms/$room/'
      preLoaderRoute: typeof WorkspaceProjectsSlugRoomsRoomIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/workflows/$workflow/': {
      id: '/_workspace/projects/$slug/workflows/$workflow/'
      path: '/workflows/$workflow'
      fullPath: '/projects/$slug/workflows/$workflow/'
      preLoaderRoute: typeof WorkspaceProjectsSlugWorkflowsWorkflowIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/agents/runs/$runId/': {
      id: '/_workspace/projects/$slug/agents/runs/$runId/'
      path: '/agents/runs/$runId'
      fullPath: '/projects/$slug/agents/runs/$runId/'
      preLoaderRoute: typeof WorkspaceProjectsSlugAgentsRunsRunIdIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/automation/fires/$fireId/': {
      id: '/_workspace/projects/$slug/automation/fires/$fireId/'
      path: '/automation/fires/$fireId'
      fullPath: '/projects/$slug/automation/fires/$fireId/'
      preLoaderRoute: typeof WorkspaceProjectsSlugAutomationFiresFireIdIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/automation/reports/$reportId/': {
      id: '/_workspace/projects/$slug/automation/reports/$reportId/'
      path: '/automation/reports/$reportId'
      fullPath: '/projects/$slug/automation/reports/$reportId/'
      preLoaderRoute: typeof WorkspaceProjectsSlugAutomationReportsReportIdIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/automation/schedules/$scheduleId/': {
      id: '/_workspace/projects/$slug/automation/schedules/$scheduleId/'
      path: '/automation/schedules/$scheduleId'
      fullPath: '/projects/$slug/automation/schedules/$scheduleId/'
      preLoaderRoute: typeof WorkspaceProjectsSlugAutomationSchedulesScheduleIdIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/contracts/$provider/$contract/': {
      id: '/_workspace/projects/$slug/contracts/$provider/$contract/'
      path: '/contracts/$provider/$contract'
      fullPath: '/projects/$slug/contracts/$provider/$contract/'
      preLoaderRoute: typeof WorkspaceProjectsSlugContractsProviderContractIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/ecosystem/channel/$ref/': {
      id: '/_workspace/projects/$slug/ecosystem/channel/$ref/'
      path: '/ecosystem/channel/$ref'
      fullPath: '/projects/$slug/ecosystem/channel/$ref/'
      preLoaderRoute: typeof WorkspaceProjectsSlugEcosystemChannelRefIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
    '/_workspace/projects/$slug/ecosystem/channel/new/': {
      id: '/_workspace/projects/$slug/ecosystem/channel/new/'
      path: '/ecosystem/channel/new'
      fullPath: '/projects/$slug/ecosystem/channel/new/'
      preLoaderRoute: typeof WorkspaceProjectsSlugEcosystemChannelNewIndexRouteImport
      parentRoute: typeof WorkspaceProjectsSlugRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface WorkspaceProjectsSlugRouteRouteChildren {
  WorkspaceProjectsSlugIndexRoute: typeof WorkspaceProjectsSlugIndexRoute
  WorkspaceProjectsSlugAgentsIndexRoute: typeof WorkspaceProjectsSlugAgentsIndexRoute
  WorkspaceProjectsSlugAutomationIndexRoute: typeof WorkspaceProjectsSlugAutomationIndexRoute
  WorkspaceProjectsSlugContractsIndexRoute: typeof WorkspaceProjectsSlugContractsIndexRoute
  WorkspaceProjectsSlugDecisionsIndexRoute: typeof WorkspaceProjectsSlugDecisionsIndexRoute
  WorkspaceProjectsSlugFeedbackIndexRoute: typeof WorkspaceProjectsSlugFeedbackIndexRoute
  WorkspaceProjectsSlugIssuesIndexRoute: typeof WorkspaceProjectsSlugIssuesIndexRoute
  WorkspaceProjectsSlugMemoryIndexRoute: typeof WorkspaceProjectsSlugMemoryIndexRoute
  WorkspaceProjectsSlugModulesIndexRoute: typeof WorkspaceProjectsSlugModulesIndexRoute
  WorkspaceProjectsSlugOverviewIndexRoute: typeof WorkspaceProjectsSlugOverviewIndexRoute
  WorkspaceProjectsSlugPipelineIndexRoute: typeof WorkspaceProjectsSlugPipelineIndexRoute
  WorkspaceProjectsSlugReleasesIndexRoute: typeof WorkspaceProjectsSlugReleasesIndexRoute
  WorkspaceProjectsSlugRequirementsIndexRoute: typeof WorkspaceProjectsSlugRequirementsIndexRoute
  WorkspaceProjectsSlugRoadmapIndexRoute: typeof WorkspaceProjectsSlugRoadmapIndexRoute
  WorkspaceProjectsSlugSettingsIndexRoute: typeof WorkspaceProjectsSlugSettingsIndexRoute
  WorkspaceProjectsSlugStatusIndexRoute: typeof WorkspaceProjectsSlugStatusIndexRoute
  WorkspaceProjectsSlugWorkflowsIndexRoute: typeof WorkspaceProjectsSlugWorkflowsIndexRoute
  WorkspaceProjectsSlugAgentsSessionIdIndexRoute: typeof WorkspaceProjectsSlugAgentsSessionIdIndexRoute
  WorkspaceProjectsSlugAgentsMasterIndexRoute: typeof WorkspaceProjectsSlugAgentsMasterIndexRoute
  WorkspaceProjectsSlugEcosystemApiIndexRoute: typeof WorkspaceProjectsSlugEcosystemApiIndexRoute
  WorkspaceProjectsSlugFeedbackFeedbackIndexRoute: typeof WorkspaceProjectsSlugFeedbackFeedbackIndexRoute
  WorkspaceProjectsSlugIssuesIdIndexRoute: typeof WorkspaceProjectsSlugIssuesIdIndexRoute
  WorkspaceProjectsSlugModulesModuleIndexRoute: typeof WorkspaceProjectsSlugModulesModuleIndexRoute
  WorkspaceProjectsSlugReleasesReleaseIndexRoute: typeof WorkspaceProjectsSlugReleasesReleaseIndexRoute
  WorkspaceProjectsSlugRequirementsRequirementIndexRoute: typeof WorkspaceProjectsSlugRequirementsRequirementIndexRoute
  WorkspaceProjectsSlugRoomsRoomIndexRoute: typeof WorkspaceProjectsSlugRoomsRoomIndexRoute
  WorkspaceProjectsSlugWorkflowsWorkflowIndexRoute: typeof WorkspaceProjectsSlugWorkflowsWorkflowIndexRoute
  WorkspaceProjectsSlugAgentsRunsRunIdIndexRoute: typeof WorkspaceProjectsSlugAgentsRunsRunIdIndexRoute
  WorkspaceProjectsSlugAutomationFiresFireIdIndexRoute: typeof WorkspaceProjectsSlugAutomationFiresFireIdIndexRoute
  WorkspaceProjectsSlugAutomationReportsReportIdIndexRoute: typeof WorkspaceProjectsSlugAutomationReportsReportIdIndexRoute
  WorkspaceProjectsSlugAutomationSchedulesScheduleIdIndexRoute: typeof WorkspaceProjectsSlugAutomationSchedulesScheduleIdIndexRoute
  WorkspaceProjectsSlugContractsProviderContractIndexRoute: typeof WorkspaceProjectsSlugContractsProviderContractIndexRoute
  WorkspaceProjectsSlugEcosystemChannelRefIndexRoute: typeof WorkspaceProjectsSlugEcosystemChannelRefIndexRoute
  WorkspaceProjectsSlugEcosystemChannelNewIndexRoute: typeof WorkspaceProjectsSlugEcosystemChannelNewIndexRoute
}

const WorkspaceProjectsSlugRouteRouteChildren: WorkspaceProjectsSlugRouteRouteChildren =
  {
    WorkspaceProjectsSlugIndexRoute: WorkspaceProjectsSlugIndexRoute,
    WorkspaceProjectsSlugAgentsIndexRoute:
      WorkspaceProjectsSlugAgentsIndexRoute,
    WorkspaceProjectsSlugAutomationIndexRoute:
      WorkspaceProjectsSlugAutomationIndexRoute,
    WorkspaceProjectsSlugContractsIndexRoute:
      WorkspaceProjectsSlugContractsIndexRoute,
    WorkspaceProjectsSlugDecisionsIndexRoute:
      WorkspaceProjectsSlugDecisionsIndexRoute,
    WorkspaceProjectsSlugFeedbackIndexRoute:
      WorkspaceProjectsSlugFeedbackIndexRoute,
    WorkspaceProjectsSlugIssuesIndexRoute:
      WorkspaceProjectsSlugIssuesIndexRoute,
    WorkspaceProjectsSlugMemoryIndexRoute:
      WorkspaceProjectsSlugMemoryIndexRoute,
    WorkspaceProjectsSlugModulesIndexRoute:
      WorkspaceProjectsSlugModulesIndexRoute,
    WorkspaceProjectsSlugOverviewIndexRoute:
      WorkspaceProjectsSlugOverviewIndexRoute,
    WorkspaceProjectsSlugPipelineIndexRoute:
      WorkspaceProjectsSlugPipelineIndexRoute,
    WorkspaceProjectsSlugReleasesIndexRoute:
      WorkspaceProjectsSlugReleasesIndexRoute,
    WorkspaceProjectsSlugRequirementsIndexRoute:
      WorkspaceProjectsSlugRequirementsIndexRoute,
    WorkspaceProjectsSlugRoadmapIndexRoute:
      WorkspaceProjectsSlugRoadmapIndexRoute,
    WorkspaceProjectsSlugSettingsIndexRoute:
      WorkspaceProjectsSlugSettingsIndexRoute,
    WorkspaceProjectsSlugStatusIndexRoute:
      WorkspaceProjectsSlugStatusIndexRoute,
    WorkspaceProjectsSlugWorkflowsIndexRoute:
      WorkspaceProjectsSlugWorkflowsIndexRoute,
    WorkspaceProjectsSlugAgentsSessionIdIndexRoute:
      WorkspaceProjectsSlugAgentsSessionIdIndexRoute,
    WorkspaceProjectsSlugAgentsMasterIndexRoute:
      WorkspaceProjectsSlugAgentsMasterIndexRoute,
    WorkspaceProjectsSlugEcosystemApiIndexRoute:
      WorkspaceProjectsSlugEcosystemApiIndexRoute,
    WorkspaceProjectsSlugFeedbackFeedbackIndexRoute:
      WorkspaceProjectsSlugFeedbackFeedbackIndexRoute,
    WorkspaceProjectsSlugIssuesIdIndexRoute:
      WorkspaceProjectsSlugIssuesIdIndexRoute,
    WorkspaceProjectsSlugModulesModuleIndexRoute:
      WorkspaceProjectsSlugModulesModuleIndexRoute,
    WorkspaceProjectsSlugReleasesReleaseIndexRoute:
      WorkspaceProjectsSlugReleasesReleaseIndexRoute,
    WorkspaceProjectsSlugRequirementsRequirementIndexRoute:
      WorkspaceProjectsSlugRequirementsRequirementIndexRoute,
    WorkspaceProjectsSlugRoomsRoomIndexRoute:
      WorkspaceProjectsSlugRoomsRoomIndexRoute,
    WorkspaceProjectsSlugWorkflowsWorkflowIndexRoute:
      WorkspaceProjectsSlugWorkflowsWorkflowIndexRoute,
    WorkspaceProjectsSlugAgentsRunsRunIdIndexRoute:
      WorkspaceProjectsSlugAgentsRunsRunIdIndexRoute,
    WorkspaceProjectsSlugAutomationFiresFireIdIndexRoute:
      WorkspaceProjectsSlugAutomationFiresFireIdIndexRoute,
    WorkspaceProjectsSlugAutomationReportsReportIdIndexRoute:
      WorkspaceProjectsSlugAutomationReportsReportIdIndexRoute,
    WorkspaceProjectsSlugAutomationSchedulesScheduleIdIndexRoute:
      WorkspaceProjectsSlugAutomationSchedulesScheduleIdIndexRoute,
    WorkspaceProjectsSlugContractsProviderContractIndexRoute:
      WorkspaceProjectsSlugContractsProviderContractIndexRoute,
    WorkspaceProjectsSlugEcosystemChannelRefIndexRoute:
      WorkspaceProjectsSlugEcosystemChannelRefIndexRoute,
    WorkspaceProjectsSlugEcosystemChannelNewIndexRoute:
      WorkspaceProjectsSlugEcosystemChannelNewIndexRoute,
  }

const WorkspaceProjectsSlugRouteRouteWithChildren =
  WorkspaceProjectsSlugRouteRoute._addFileChildren(
    WorkspaceProjectsSlugRouteRouteChildren,
  )

interface WorkspaceRouteRouteChildren {
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceProjectsSlugRouteRoute: typeof WorkspaceProjectsSlugRouteRouteWithChildren
  WorkspaceAttentionIndexRoute: typeof WorkspaceAttentionIndexRoute
  WorkspaceDocsIndexRoute: typeof WorkspaceDocsIndexRoute
  WorkspaceEcosystemsIndexRoute: typeof WorkspaceEcosystemsIndexRoute
  WorkspaceIntegrationsIndexRoute: typeof WorkspaceIntegrationsIndexRoute
  WorkspaceOpsIndexRoute: typeof WorkspaceOpsIndexRoute
  WorkspaceOrgIndexRoute: typeof WorkspaceOrgIndexRoute
  WorkspacePairIndexRoute: typeof WorkspacePairIndexRoute
  WorkspaceProjectsIndexRoute: typeof WorkspaceProjectsIndexRoute
  WorkspaceRunnersIndexRoute: typeof WorkspaceRunnersIndexRoute
  WorkspaceSettingsIndexRoute: typeof WorkspaceSettingsIndexRoute
  WorkspaceDevDesignIndexRoute: typeof WorkspaceDevDesignIndexRoute
  WorkspaceEcosystemsIdIndexRoute: typeof WorkspaceEcosystemsIdIndexRoute
  WorkspaceEcosystemsNewIndexRoute: typeof WorkspaceEcosystemsNewIndexRoute
  WorkspaceEcosystemsThreadsIndexRoute: typeof WorkspaceEcosystemsThreadsIndexRoute
  WorkspaceEcosystemsIdSettingsIndexRoute: typeof WorkspaceEcosystemsIdSettingsIndexRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceProjectsSlugRouteRoute: WorkspaceProjectsSlugRouteRouteWithChildren,
  WorkspaceAttentionIndexRoute: WorkspaceAttentionIndexRoute,
  WorkspaceDocsIndexRoute: WorkspaceDocsIndexRoute,
  WorkspaceEcosystemsIndexRoute: WorkspaceEcosystemsIndexRoute,
  WorkspaceIntegrationsIndexRoute: WorkspaceIntegrationsIndexRoute,
  WorkspaceOpsIndexRoute: WorkspaceOpsIndexRoute,
  WorkspaceOrgIndexRoute: WorkspaceOrgIndexRoute,
  WorkspacePairIndexRoute: WorkspacePairIndexRoute,
  WorkspaceProjectsIndexRoute: WorkspaceProjectsIndexRoute,
  WorkspaceRunnersIndexRoute: WorkspaceRunnersIndexRoute,
  WorkspaceSettingsIndexRoute: WorkspaceSettingsIndexRoute,
  WorkspaceDevDesignIndexRoute: WorkspaceDevDesignIndexRoute,
  WorkspaceEcosystemsIdIndexRoute: WorkspaceEcosystemsIdIndexRoute,
  WorkspaceEcosystemsNewIndexRoute: WorkspaceEcosystemsNewIndexRoute,
  WorkspaceEcosystemsThreadsIndexRoute: WorkspaceEcosystemsThreadsIndexRoute,
  WorkspaceEcosystemsIdSettingsIndexRoute:
    WorkspaceEcosystemsIdSettingsIndexRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAlertsIndexRoute: typeof AdminAlertsIndexRoute
  AdminFleetIndexRoute: typeof AdminFleetIndexRoute
  AdminGrowthIndexRoute: typeof AdminGrowthIndexRoute
  AdminMcpLogsIndexRoute: typeof AdminMcpLogsIndexRoute
  AdminPipelineIndexRoute: typeof AdminPipelineIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAlertsIndexRoute: AdminAlertsIndexRoute,
  AdminFleetIndexRoute: AdminFleetIndexRoute,
  AdminGrowthIndexRoute: AdminGrowthIndexRoute,
  AdminMcpLogsIndexRoute: AdminMcpLogsIndexRoute,
  AdminPipelineIndexRoute: AdminPipelineIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  GuidesIndexRoute: GuidesIndexRoute,
  LinkChatIndexRoute: LinkChatIndexRoute,
  GuidesSlugIndexRoute: GuidesSlugIndexRoute,
  InviteAcceptIndexRoute: InviteAcceptIndexRoute,
  STokenIndexRoute: STokenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
