import { defineConfig } from 'drizzle-kit';

export default defineConfig({
  dialect: 'postgresql',
  schema: [
    './src/db/schema.ts',
    './src/db/schema-activity.ts',
    './src/db/schema-admin-thresholds.ts',
    './src/db/schema-journal.ts',
    './src/db/schema-master-charter.ts',
    './src/db/schema-project-config.ts',
    './src/db/schema-ecosystem.ts',
    './src/db/schema-ecosystem-links.ts',
    './src/db/schema-workflows.ts',
    './src/db/schema-requirements.ts',
    './src/db/schema-suggestions.ts',
    './src/db/schema-questions.ts',
    './src/db/schema-rocketchat.ts',
    './src/db/schema-agent-session-events.ts',
    './src/db/schema-backfill-markers.ts',
    './src/db/schema-session-inbox.ts',
    './src/db/schema-speaker-links.ts',
    './src/db/schema-memory-chunks.ts',
    './src/db/schema-memory-revisions.ts',
    './src/db/schema-unaudited-transitions.ts',
    './src/db/schema-issue-leases.ts',
    './src/db/schema-issue-work-state.ts',
    './src/db/schema-issue-criteria.ts',
    './src/db/schema-deploy-locks.ts',
    './src/db/schema-run-ledger.ts',
    './src/db/schema-release-ledger.ts',
    './src/db/schema-conversations.ts',
    './src/db/schema-transcript-index.ts',
    './src/db/schema-agent-selves.ts',
    './src/db/schema-project-facts-backup.ts',
    './src/db/schema-repo-projection.ts',
    './src/db/schema-runner-release.ts',
  ],
  out: './drizzle/migrations',
  dbCredentials: {
    url: process.env['DATABASE_URL'] ?? '',
  },
});
