import { describe, expect, it } from 'vitest';
import { API, artifactDrift, firstDifference, MCP, memberCount } from './api-contracts.mjs';

const text = (doc) => `${JSON.stringify(doc, null, 2)}\n`;

const api = (paths) => text({ openapi: '3.1.0', info: { title: 'forge-api' }, paths });
const op = (validated, extra = {}) => ({ 'x-forge-validated': validated, ...extra });

describe('artifactDrift names the route that moved', () => {
  const committed = api({ '/api/a': { get: op([]) }, '/api/b/{id}': { patch: op(['json']) } });

  it('finds nothing when the generated bytes are the committed bytes', () => {
    expect(artifactDrift(API, committed, committed)).toEqual({ findings: [] });
  });

  it('names a route mounted without regenerating', () => {
    const generated = api({
      '/api/a': { get: op([]), post: op([]) },
      '/api/b/{id}': { patch: op(['json']) },
    });
    expect(artifactDrift(API, committed, generated).findings).toEqual([
      'route POST /api/a: served by the code, absent from the committed contract',
    ]);
  });

  it('names a route removed without regenerating', () => {
    const generated = api({ '/api/b/{id}': { patch: op(['json']) } });
    expect(artifactDrift(API, committed, generated).findings).toEqual([
      'route GET /api/a: in the committed contract, no longer served by the code',
    ]);
  });

  it('names a changed validator field by route and JSON pointer', () => {
    const body = (max) => ({
      requestBody: {
        content: { 'application/json': { schema: { properties: { name: { maxLength: max } } } } },
      },
    });
    const before = api({ '/api/b/{id}': { patch: op(['json'], body(64)) } });
    const after = api({ '/api/b/{id}': { patch: op(['json'], body(65)) } });
    expect(artifactDrift(API, before, after).findings).toEqual([
      'route PATCH /api/b/{id}: differs from the committed contract at /requestBody/content/application~1json/schema/properties/name/maxLength',
    ]);
  });

  it('names a difference outside every route', () => {
    const generated = committed.replace('"forge-api"', '"forge-api-2"');
    expect(artifactDrift(API, committed, generated).findings).toEqual([
      `${API.label}: differs outside every route at /info/title`,
    ]);
  });

  it('refuses bytes the generator did not write even when every route matches', () => {
    const reflowed = JSON.stringify(JSON.parse(committed));
    expect(artifactDrift(API, reflowed, committed).findings).toEqual([
      `${API.label}: every route matches, yet the bytes differ — the file was not written by the generator`,
    ]);
  });

  it('reports an absent or unreadable committed artifact as drift, not as a pass', () => {
    expect(artifactDrift(API, null, committed).findings).toEqual([`${API.label} is absent`]);
    expect(artifactDrift(API, '{', committed).findings[0]).toMatch(/is not JSON/);
  });

  it('cannot judge generated output that is not JSON', () => {
    expect(artifactDrift(API, committed, 'nope').unusable).toMatch(/the generated .* is not JSON/);
  });
});

describe('artifactDrift names the tool that moved', () => {
  const tools = (list) => text({ contract: 'forge-mcp', tools: list });
  const tool = (name, required) => ({
    name,
    description: 'd',
    inputSchema: { type: 'object', required },
  });

  it('names an added, a removed and a changed tool', () => {
    const before = tools([tool('forge_a', ['x']), tool('forge_b', [])]);
    const after = tools([tool('forge_a', ['x', 'y']), tool('forge_c', [])]);
    expect(artifactDrift(MCP, before, after).findings).toEqual([
      'tool forge_a: differs from the committed contract at /inputSchema/required/1',
      'tool forge_c: served by the code, absent from the committed contract',
      'tool forge_b: in the committed contract, no longer served by the code',
    ]);
  });

  it('counts the members a generated artifact holds', () => {
    expect(memberCount(MCP, tools([tool('forge_a', [])]))).toBe(1);
    expect(memberCount(API, api({ '/x': { get: op([]), put: op([]) } }))).toBe(2);
  });
});

describe('firstDifference', () => {
  it('returns null for equal values and the first differing pointer otherwise', () => {
    expect(firstDifference({ a: [1, 2] }, { a: [1, 2] })).toBeNull();
    expect(firstDifference({ a: [1, 2] }, { a: [1, 3] })).toBe('/a/1');
    expect(firstDifference({ a: 1 }, { a: 1, b: 2 })).toBe('/b');
    expect(firstDifference({ 'x/y~': 1 }, { 'x/y~': 2 })).toBe('/x~1y~0');
    expect(firstDifference([1], { 0: 1 })).toBe('/');
  });
});
