// The checks verify runs and the parity proof it runs last: data only, imported by verify.mjs and by
// conformance-audit.mjs, which reads the same objects rather than verify's source text.

export const CHECKS = [
  {
    axis: 'language',
    label: 'source-language',
    cmd: ['node', 'scripts/check-source-language.mjs', '--all'],
    scanned: /across (\d+) files/,
  },
  {
    axis: 'record',
    label: 'release-record',
    cmd: ['node', 'scripts/check-release-record.mjs'],
    scanned: /^release-record: (\d+) entr/m,
    unit: 'release entries',
  },
  {
    axis: 'behaviour',
    label: 'test-signal',
    cmd: ['node', 'scripts/check-test-signal.mjs', '--all'],
    scanned: /^test-signal: (\d+) test file/m,
  },
  {
    axis: 'behaviour',
    label: 'test-reachability',
    cmd: ['node', 'scripts/check-test-reachability.mjs'],
    scanned: /^test-reachability: (\d+) tracked test file/m,
    needs: ['deps'],
    unit: 'test files',
  },
  {
    axis: 'behaviour',
    label: 'whole-tree-gates',
    cmd: ['node', 'scripts/check-whole-tree-gates.mjs'],
    scanned: /^whole-tree-gates: (\d+) test file\(s\) read/m,
    unit: 'test files',
  },
  {
    axis: 'knowledge',
    label: 'pat-surface',
    cmd: ['node', 'scripts/check-pat-surface.mjs'],
    needs: ['deps', 'observability-build', 'contracts-build'],
    scanned:
      /^pat-surface: \d+ resource\(s\) · \d+ permission group\(s\) · \d+ covered prefix\(es\) · \d+ router file\(s\) · (\d+) route/m,
    unit: 'PAT-reachable routes',
  },
  {
    axis: 'knowledge',
    label: 'api-contracts',
    cmd: ['node', 'scripts/check-api-contracts.mjs'],
    scanned: /^api-contracts: (\d+) route\(s\)/m,
    needs: ['deps', 'observability-build', 'contracts-build'],
    unit: 'routes',
  },
  {
    axis: 'knowledge',
    label: 'retired-model',
    cmd: ['node', 'scripts/check-retired-model.mjs'],
    scanned: /^check-retired-model: (\d+) files scanned/m,
    unit: 'files',
  },
  {
    axis: 'knowledge',
    label: 'status-tuples',
    cmd: ['node', 'scripts/check-status-tuples.mjs', '--all'],
    scanned: /^status-tuples: (\d+) file\(s\) scanned/m,
    unit: 'files',
  },
  {
    axis: 'knowledge',
    label: 'doc-citations',
    cmd: ['node', 'scripts/check-doc-citations.mjs', '--all'],
    scanned: /^doc-citations: (\d+) document\(s\) scanned/m,
    carries: /^doc-citations worklist: (.+)$/m,
    unit: 'documents',
  },
  {
    axis: 'knowledge',
    label: 'honest-costs',
    cmd: ['node', 'scripts/check-honest-costs.mjs'],
    scanned: /^honest-costs: (\d+) document/m,
    unit: 'documents',
  },
  {
    axis: 'relations',
    label: 'archmap',
    cmd: ['./.forge/archmap/archmap', 'check'],
    exclusive: 'archmap',
    scanned: /archmap · (\d+) files/,
    needs: ['deps', 'archmap-resolver', 'observability-build', 'contracts-build'],
  },
  {
    axis: 'relations',
    label: 'module-boundaries',
    cmd: ['node', 'scripts/check-module-boundaries.mjs'],
    scanned: /^module-boundaries: (\d+) file\(s\) cruised/m,
    needs: ['deps'],
  },
  {
    axis: 'relations',
    label: 'module-shape',
    cmd: ['node', 'scripts/check-module-shape.mjs'],
    scanned: /^module-shape: (\d+) file\(s\) linted/m,
    needs: ['deps'],
  },
  {
    axis: 'form',
    label: 'core lint',
    cmd: ['pnpm', '--filter', '@forge/core', 'lint'],
    scanned: /Checked (\d+)/,
    needs: ['deps'],
  },
  {
    axis: 'form',
    label: 'web lint',
    cmd: ['pnpm', '--filter', 'web-v2', 'lint'],
    scanned: /Checked (\d+)/,
    needs: ['deps'],
  },
  {
    axis: 'form',
    label: 'size-budget',
    cmd: ['node', 'scripts/check-size-budget.mjs', '--all'],
    scanned: /^size-budget: (\d+) file/m,
    needs: ['deps'],
  },
  {
    axis: 'form',
    label: 'provider-literals',
    cmd: ['node', 'scripts/check-provider-literals.mjs', '--all'],
    scanned: /^provider-literals: (\d+) file\(s\) scanned/m,
    unit: 'files',
  },
  {
    axis: 'form',
    label: 'integration-declarations',
    cmd: ['node', 'scripts/check-integration-declarations.mjs', '--all'],
    scanned: /^integration-declarations: (\d+) provider\(s\) declared/m,
    needs: ['deps'],
    unit: 'providers',
  },
  {
    axis: 'relations',
    label: 'merged-at-writers',
    cmd: ['node', 'scripts/check-merged-at-writers.mjs', '--all'],
    scanned: /^merged-at-writers: (\d+) file\(s\) scanned/m,
  },
  {
    axis: 'form',
    label: 'lazy-module-init',
    cmd: ['node', 'scripts/check-lazy-module-init.mjs', '--all'],
    scanned: /^lazy-module-init: (\d+) file\(s\) scanned/m,
    needs: ['deps'],
  },
  {
    axis: 'form',
    label: 'scripts lint',
    cmd: ['pnpm', 'exec', 'biome', 'check', 'scripts'],
    scanned: /^Checked (\d+) files/m,
    needs: ['deps'],
  },
  {
    axis: 'form',
    label: 'core typecheck',
    cmd: ['pnpm', '--filter', '@forge/core', 'exec', 'tsc', '--noEmit', '--extendedDiagnostics'],
    scanned: /^Files:\s+(\d+)/m,
    needs: ['deps', 'observability-build', 'contracts-build'],
  },
  {
    axis: 'runner',
    label: 'cargo gates',
    cmd: ['node', 'scripts/check-runner-gates.mjs'],
    scanned: /^runner-gates: (\d+) crate file\(s\) in scope/m,
    unit: 'crate files',
    scopeMayBeEmpty: true,
  },
  {
    axis: 'meta',
    label: 'lockfile-transport',
    cmd: ['node', 'scripts/check-lockfile-transport.mjs'],
    scanned: /^lockfile-transport: (\d+) resolution\(s\), none over SSH/m,
    unit: 'resolutions',
  },
  {
    axis: 'meta',
    label: 'migration-order',
    cmd: ['node', 'scripts/check-migration-order.mjs'],
    scanned: /^migration-order: (\d+) migration\(s\) landing/m,
    unit: 'migrations landing',
    // 0 is the ordinary reading: most trees land no migration, and the checker says so rather
    // than reading a set it has nothing to compare against.
    scopeMayBeEmpty: true,
  },
  {
    axis: 'meta',
    label: 'conformance levels',
    cmd: ['node', 'scripts/conformance-status.mjs'],
    scanned: /^conformance-status: (\d+) axes measured/m,
    unit: 'axes',
  },
  {
    axis: 'meta',
    label: 'conformance audit',
    cmd: ['node', 'scripts/conformance-audit.mjs'],
    exclusive: 'archmap',
    scanned: /^conformance-audit: (\d+) rules evaluated/m,
    unit: 'rules',
  },
];

/** The parity proof verify runs last; its scan proof is declared like any check's. */
export const CI_PARITY = {
  label: 'ci-parity',
  scanned: /^ci-parity: (\d+) CI step\(s\) declared/m,
  unit: 'CI steps',
};
