// @generated by archmap 0.1.4 — vendored copy, do not edit
import { matchesAny } from '../graph/map.mjs';
import { moduleClosure, witness } from '../graph/normalize.mjs';

const REMEDY = {
  layers:
    'Higher layers may depend on lower ones, never the reverse. Invert the call, or move the shared type down into the lower layer.',
  forbidden:
    'Declare an interface in the depending module and implement it on the other side, or move the shared code into a module both may depend on.',
  independence:
    'Two features share code only through a module both may depend on. Extract the shared contract there — do not reach across.',
  boundary:
    'Import the module through its declared entry point. If what you need is not exported there, export it — do not reach past the surface.',
  'fan-out':
    'This file coordinates too many modules. Split it by responsibility, or push the coordination up into the layer that owns the use case.',
  absence:
    'The model expects this dependency and the code does not have it. Either the dependency has not been implemented yet, or the model has rotted past a refactor — correct whichever one is wrong. Never a gate.',
};

const POLICY = 'Fix the source, not the check: do not widen .arch.json to make this pass.';

function finding(contract, parts) {
  return {
    contract: contract.id,
    type: contract.type,
    status: contract.status,
    remedy: REMEDY[contract.type],
    policy: POLICY,
    ...parts,
  };
}

// cm:guard `relax` only ever removes a contract type from test files. Widening it to source files
//   turns the test glob into a general exemption list, which is the escape route this design
//   exists to close.
function relaxed(manifest, contract, edge) {
  return edge.fromKind === 'test' && manifest.tests.relax.includes(contract.type);
}

function layers(contract, graph, manifest) {
  const rank = new Map(contract.order.map((m, i) => [m, i]));
  const out = [];
  for (const e of graph.edges) {
    if (!rank.has(e.fromModule) || !rank.has(e.toModule)) continue;
    if (e.fromModule === e.toModule) continue;
    if (relaxed(manifest, contract, e)) continue;
    if (rank.get(e.fromModule) > rank.get(e.toModule)) {
      out.push(finding(contract, {
        from: e.fromFile,
        to: e.toFile,
        message: `${e.fromModule} sits below ${e.toModule} and must not depend on it`,
        edge: `${e.fromModule} -> ${e.toModule}`,
      }));
    }
  }
  return out;
}

function forbidden(contract, graph, manifest) {
  const targets = typeof contract.to === 'string' ? [contract.to] : contract.to;
  const wildcard = targets.includes('*');
  const named = new Set(targets.filter((t) => t !== '*' && !t.includes('/') && !t.includes('*')));
  const globs = targets.filter((t) => t !== '*' && (t.includes('/') || t.includes('*')));
  const out = [];

  for (const e of graph.edges) {
    if (e.fromModule !== contract.from) continue;
    if (e.toModule === contract.from) continue;
    if (relaxed(manifest, contract, e)) continue;

    const hit = wildcard
      || (e.toModule !== null && named.has(e.toModule))
      || (globs.length > 0 && matchesAny(e.toFile, globs));
    if (!hit) continue;

    out.push(finding(contract, {
      from: e.fromFile,
      to: e.toFile,
      message: wildcard
        ? `${contract.from} must not depend on anything outside itself`
        : `${contract.from} must not depend on ${e.toModule ?? e.toFile}`,
      edge: `${e.fromModule} -> ${e.toModule ?? e.toFile}`,
    }));
  }
  return out;
}

function independence(contract, graph, manifest) {
  const { direct, closure } = moduleClosure(graph);
  const set = new Set(contract.modules);
  const out = [];

  for (const a of contract.modules) {
    for (const b of closure.get(a) ?? []) {
      if (a === b || !set.has(b)) continue;
      const path = witness(direct, a, b) ?? [a, b];
      const hop = firstEdge(graph, a, path[1] ?? b, manifest, contract);
      if (!hop) continue;
      out.push(finding(contract, {
        from: hop.fromFile,
        to: hop.toFile,
        message: path.length > 2
          ? `${a} reaches ${b} through ${path.slice(1, -1).join(' -> ')}`
          : `${a} must not depend on ${b}`,
        edge: path.join(' -> '),
      }));
    }
  }
  return out;
}

function firstEdge(graph, from, to, manifest, contract) {
  for (const e of graph.edges) {
    if (e.fromModule === from && e.toModule === to && !relaxed(manifest, contract, e)) return e;
  }
  return null;
}

function boundary(contract, graph, manifest) {
  const out = [];
  for (const e of graph.edges) {
    if (e.toModule !== contract.module) continue;
    if (e.fromModule === contract.module) continue;
    if (relaxed(manifest, contract, e)) continue;
    if (matchesAny(e.toFile, contract.public)) continue;
    out.push(finding(contract, {
      from: e.fromFile,
      to: e.toFile,
      message: `${e.toFile} is not part of ${contract.module}'s public surface`,
      edge: `${e.fromModule ?? 'unmapped'} -> ${e.toModule}`,
    }));
  }
  return out;
}

function fanOut(contract, graph, manifest) {
  const reach = new Map();
  for (const e of graph.edges) {
    if (!e.toModule || e.fromModule === e.toModule) continue;
    if (relaxed(manifest, contract, e)) continue;
    const key = contract.scope === 'module' ? e.fromModule : e.fromFile;
    if (!key) continue;
    if (!reach.has(key)) reach.set(key, new Set());
    reach.get(key).add(e.toModule);
  }

  const out = [];
  for (const [key, mods] of reach) {
    if (mods.size <= contract.max_modules) continue;
    out.push(finding(contract, {
      from: key,
      to: null,
      message: `reaches ${mods.size} modules (limit ${contract.max_modules}): ${[...mods].sort().join(', ')}`,
      edge: `${key} -> ${mods.size} modules`,
      // cm:guard the COUNT as its own field, not only inside `edge`. The baseline keys fan-out by
      //   path and compares this number, because a key carrying the count would change when the
      //   file improves — 48 modules down to 47 is a different key, so a freeze at 48 would fail
      //   the build for making the blob smaller. Progress must never be a violation.
      count: mods.size,
    }));
  }
  return out.sort((a, b) => a.from.localeCompare(b.from));
}

// cm:why absence is module-level, like `independence` — the contract names modules, not files, so
//   the finding's from/to are module names. `fanOut` already emits a non-file `from`, so render()
//   tolerates it.
// cm:guard a test-only edge does NOT satisfy an absence contract. The declared model is about the
//   production structure; counting a fixture's import would let a test satisfy an architectural
//   expectation the shipped code does not meet. This is deliberately NOT routed through relaxed():
//   `tests.relax` removes a GATING rule from test files, and absence never gates, so its meaning
//   inverts here — which is why `absence` is absent from RELAXABLE_TYPES.
function absence(contract, graph) {
  const met = graph.edges.some(
    (e) => e.fromModule === contract.from && e.toModule === contract.to && e.fromKind !== 'test',
  );
  if (met) return [];
  return [finding(contract, {
    from: contract.from,
    to: contract.to,
    message: `${contract.from} is expected to depend on ${contract.to}; no edge does`,
    edge: `${contract.from} -> ${contract.to}`,
  })];
}

const EVALUATORS = { layers, forbidden, independence, boundary, 'fan-out': fanOut, absence };

// cm:edge lockstep -> src/manifest.mjs — CONTRACT_TYPES and this set must hold exactly the same
//   members, asserted both ways by 'vocabulary: every contract type has an evaluator' in
//   tests/run.mjs. A type in the vocabulary with no evaluator here is the ISS-2 fail-open.
export const EVALUATED_TYPES = new Set(Object.keys(EVALUATORS));

class ContractError extends Error {}

/**
 * Runs every contract. `absent` is kept separate from `findings` by construction: absence is
 * report-only per SPEC §3, so it must never reach the baseline, the blocking/advisory split or
 * the exit code — a filter downstream is one edit away from being dropped.
 */
export function evaluate(manifest, graph) {
  const findings = [];
  const absent = [];
  for (const contract of manifest.contracts) {
    const run = EVALUATORS[contract.type];
    // cm:guard never skip. A contract that cannot be evaluated stops the gate (exit 2); it does not
    //   drop out of the count. That skip list was the ISS-2 fail-open — a manifest validated clean,
    //   nothing was checked, and the verdict read 0 blocking. Do not reintroduce it.
    if (!run) {
      throw new ContractError(`contract "${contract.id}": no evaluator for type "${contract.type}"`);
    }
    (contract.type === 'absence' ? absent : findings).push(...run(contract, graph, manifest));
  }
  return { findings, absent };
}

export { REMEDY, POLICY, ContractError };
