// @generated by archmap 0.1.4 — vendored copy, do not edit
// cm:why this document is a CONSUMED CONTRACT, not a debug dump. Other tools read it to answer
//   "does A depend on B" with the same graph archmap evaluates its own contracts over — codemap's
//   CM301 today guesses coupling from a basename match and cannot be locked because of it. The
//   `formatVersion` field is the promise: additive fields are a minor change, removing or renaming
//   a field, or changing what one means, bumps it. Nothing in archmap reads this back.
// cm:edge lockstep -> src/install.mjs — this module must be in MODULES or the vendored copy
//   crashes on import and `archmap graph` cannot run at all.

/**
 * Bumped when a field is removed, renamed, or changes meaning. Adding a field is not a bump.
 * Independent of the `.arch.json` manifest `version` on purpose: the manifest grammar and this
 * export are separate contracts with separate audiences.
 */
export const GRAPH_FORMAT_VERSION = 1;

// cm:guard the key ORDER here is part of the byte-identical guarantee — JSON.stringify emits object
//   keys in insertion order, so an edge built field-by-field in this sequence serialises the same
//   way for every entry. Resolved and unresolved entries share it exactly: a consumer iterates ONE
//   list and never branches on record shape (SPEC §10.4).
const EDGE_FIELDS = ['resolved', 'fromFile', 'toFile', 'fromModule', 'toModule', 'fromKind',
  'toKind', 'dynamic', 'spec', 'language', 'why'];

// cm:guard a plain code-unit comparator, never localeCompare — that is locale-dependent, so the
//   same tree would export in a different order on a machine with a different LANG and the
//   byte-identical promise would hold only where it was tested. Nulls sort as '' rather than
//   throwing, because `toFile` is legitimately null on every unresolved entry.
function cmp(a, b) {
  const x = a === null || a === undefined ? '' : String(a);
  const y = b === null || b === undefined ? '' : String(b);
  return x === y ? 0 : x < y ? -1 : 1;
}

// cm:guard tiebroken on EVERY field, not just from/to/spec. A partial sort leaves the remaining
//   order to Array.prototype.sort's handling of equal keys and therefore to which provider ran
//   first — and that failure mode passes a single-run eyeball, then differs on the next machine.
function byEveryField(a, b) {
  for (const f of EDGE_FIELDS) {
    const d = cmp(a[f], b[f]);
    if (d !== 0) return d;
  }
  return 0;
}

/**
 * Serialise `normalize()`'s graph as the versioned export document. Pure: no fs, no manifest
 * evaluation, no exit codes.
 *
 * `toolVersion` is passed in rather than read from src/install.mjs, so this module stays
 * dependency-free instead of adding a graph -> install edge to archmap's own graph. `scope` and
 * `providers` are provenance the graph itself does not carry: which roots were walked, and which
 * language providers actually ran over them.
 */
export function buildGraphDocument(graph, { toolVersion = 'unknown', scope, providers } = {}) {
  // cm:guard `providers` and `scope` have NO default, deliberately. A defaulted `providers = []`
  //   serialises as `complete: true` — a caller that simply forgot the argument would publish a
  //   document swearing every provider ran, which is the precise fail-open this block closes. A
  //   contract other tools read must refuse to be built from missing provenance, not guess it.
  if (!Array.isArray(providers) || providers.length === 0) {
    throw new TypeError('buildGraphDocument: `providers` must be a non-empty [{ language, ok }] list');
  }
  if (!Array.isArray(scope) || scope.length === 0) {
    throw new TypeError('buildGraphDocument: `scope` must be a non-empty list of repo-relative roots');
  }
  // cm:guard every entry of graph.files, INCLUDING the `excluded` and `generated` kinds. They are
  //   counted by coverage, so `files.length === coverage.total` is then an invariant a consumer can
  //   check; dropping them would make a file that has no edges invisible, and "this file depends on
  //   nothing" is a real answer.
  const files = [...graph.files.entries()]
    .map(([path, info]) => ({ path, module: info.module, kind: info.kind }))
    .sort((a, b) => cmp(a.path, b.path));

  const resolved = graph.edges.map((e) => ({
    resolved: true,
    fromFile: e.fromFile,
    toFile: e.toFile,
    fromModule: e.fromModule,
    toModule: e.toModule,
    fromKind: e.fromKind,
    toKind: e.toKind,
    dynamic: e.dynamic,
    spec: e.spec,
    language: e.language,
    why: null,
  }));

  // cm:why unresolved entries are edges in the same list with a null target, never a separate
  //   section — SPEC §9.2/§2.6: a consumer that has to opt in to reading them will read a graph
  //   with holes as a complete one, and "archmap could not see it" is not "it does not exist".
  const unresolved = graph.unresolvable.map((u) => ({
    resolved: false,
    fromFile: u.from,
    toFile: null,
    fromModule: u.module ?? null,
    toModule: null,
    // the record itself carries no kind — normalize() classified the file before pushing, so the
    // answer is in graph.files
    fromKind: graph.files.get(u.from)?.kind ?? null,
    toKind: null,
    // cm:guard null, not false. No provider sets `dynamic` on an unresolvable record; the ts
    //   provider signals it through `why: 'dynamic import'` instead. `false` would be a claim the
    //   data does not support, and deriving it from the `why` text would couple this contract to a
    //   provider's message wording.
    dynamic: null,
    spec: u.spec,
    language: u.language,
    why: u.why,
  }));

  // cm:guard sort only, NEVER dedupe. The resolved-edge count in this document has to equal
  //   `archmap check --json`'s graph.edgeCount over the same tree, which is what makes the two
  //   joinable; a "helpful" dedupe silently breaks that equality.
  const edges = [...resolved, ...unresolved].sort(byEveryField);

  // cm:guard `ok` is `p.ok === true`, never truthiness. Anything that is not an explicit true reads
  //   as a provider that did not run: an unrecognised value must degrade to "incomplete", because
  //   the direction this can be wrong in is a consumer asserting absence over a missing language.
  const providerList = [...providers]
    .map((p) => ({ language: p.language, ok: p.ok === true }))
    .sort((a, b) => cmp(a.language, b.language));

  // cm:guard no absolute path anywhere in the document — not manifest.root, not a resolved cwd, and
  //   not a `scope` root as the operator typed it. Paths stay the repo-relative POSIX keys
  //   normalize() already uses, so an edge joins against an `archmap check` finding without translation
  //   and two machines export the same bytes.
  return {
    formatVersion: GRAPH_FORMAT_VERSION,
    tool: { name: 'archmap', version: toolVersion },
    // cm:why the roots this document was built over. `archmap graph --json src/ui` produces a document
    //   shape-identical to a whole-repo export, so without this a consumer reading a CI-produced
    //   graph.json cannot tell an absence in the code from an absence in the invocation.
    scope: [...scope].sort(cmp),
    // cm:guard the answer to "did a whole language just go missing". `coverage` counts what was
    //   FOUND, so a provider that died leaves every health field reading clean — 100% mapped, zero
    //   unresolvable — over a graph with a language-sized hole in it. Path-free by construction
    //   (a language name and a boolean), so it costs neither the no-absolute-paths rule nor the
    //   byte-identical promise; the free-text reason stays on `archmap check --json`.
    providers: providerList,
    complete: providerList.every((p) => p.ok),
    counts: {
      files: files.length,
      edges: resolved.length,
      unresolved: unresolved.length,
      total: edges.length,
    },
    coverage: graph.coverage,
    unresolvableStats: graph.unresolvableStats,
    // why edges are missing rather than absent: an edge touching a generated or excluded file is
    // dropped before it reaches the graph, and a consumer counting zero needs to know that
    dropped: graph.dropped,
    files,
    edges,
  };
}
