// @generated by archmap 0.1.4 — vendored copy, do not edit
import { buildMapper } from './map.mjs';

/**
 * Folds one or more provider outputs into a single graph keyed by repo-relative path, with each
 * file assigned to at most one module.
 */
export function normalize(manifest, providerResults) {
  const classify = buildMapper(manifest);
  const files = new Map();
  const edges = [];
  const unresolvable = [];
  const dropped = { generated: 0, excluded: 0 };

  const note = (path) => {
    if (files.has(path)) return files.get(path);
    const info = classify(path);
    files.set(path, info);
    return info;
  };

  for (const r of providerResults) {
    if (!r.ok) continue;
    for (const f of r.files) note(f);
    for (const u of r.unresolvable) {
      const info = note(u.from);
      if (info.kind === 'generated' || info.kind === 'excluded') continue;
      unresolvable.push({ ...u, module: info.module, language: r.language });
    }
    for (const e of r.edges) {
      const from = note(e.from);
      const to = note(e.to);
      if (from.kind === 'excluded' || to.kind === 'excluded') { dropped.excluded++; continue; }
      if (from.kind === 'generated' || to.kind === 'generated') { dropped.generated++; continue; }
      edges.push({
        fromFile: e.from,
        toFile: e.to,
        fromModule: from.module,
        toModule: to.module,
        fromKind: from.kind,
        toKind: to.kind,
        dynamic: Boolean(e.dynamic),
        // cm:edge contract -> src/hook/pre-edit.mjs — the import specifier as written, when the
        //   provider knows it. The hook keys its splice on this: edges from the pending file whose
        //   spec survived the edit are kept, the rest are dropped.
        spec: e.spec ?? null,
        language: r.language,
      });
    }
  }

  return {
    files,
    edges,
    unresolvable,
    dropped,
    coverage: coverageOf(files),
    unresolvableStats: unresolvableStats(edges.length, unresolvable.length),
  };
}

// cm:why a ratio, not just the count §9.2 already reported. A count says nothing about whether the
//   graph is mostly holes: 111 unresolvable reads the same as 11 until you know the denominator, and
//   a run whose edges are mostly ABSENT must not be able to present itself as a clean gate.
export const UNRESOLVABLE_RATIO_THRESHOLD = 0.15;
// cm:guard the absolute floor is what keeps the warning from being noise, and noise on a gate is how
//   a gate stops being read: a 2-file repo with one computed `import()` sits at ratio 1.0 forever and
//   has nothing to fix. Below this count the ratio is not evidence of anything.
export const UNRESOLVABLE_MIN_COUNT = 10;

/** Unresolvable as a share of would-be edges. Reporting only — it never moves an exit code. */
export function unresolvableStats(edgeCount, unresolvableCount) {
  const total = edgeCount + unresolvableCount;
  const ratio = total === 0 ? 0 : unresolvableCount / total;
  return {
    count: unresolvableCount,
    resolved: edgeCount,
    total,
    ratio,
    pct: Math.round(ratio * 1000) / 10,
    threshold: UNRESOLVABLE_RATIO_THRESHOLD,
    minCount: UNRESOLVABLE_MIN_COUNT,
    above: unresolvableCount >= UNRESOLVABLE_MIN_COUNT && ratio >= UNRESOLVABLE_RATIO_THRESHOLD,
  };
}

function coverageOf(files) {
  const c = { total: 0, source: 0, test: 0, unmapped: 0, generated: 0, excluded: 0 };
  for (const { kind } of files.values()) {
    c.total++;
    c[kind]++;
  }
  const considered = c.source + c.test + c.unmapped;
  c.mappedPct = considered === 0 ? 0 : Math.round(((c.source + c.test) / considered) * 1000) / 10;
  return c;
}

/**
 * Module-level adjacency with transitive closure. `independence` needs the closure — the common
 * real violation is two features glued together through a shared module neither one names.
 */
export function moduleClosure(graph) {
  const direct = new Map();
  for (const e of graph.edges) {
    if (!e.fromModule || !e.toModule || e.fromModule === e.toModule) continue;
    if (!direct.has(e.fromModule)) direct.set(e.fromModule, new Set());
    direct.get(e.fromModule).add(e.toModule);
  }

  const closure = new Map();
  for (const start of direct.keys()) {
    const seen = new Set();
    const stack = [...(direct.get(start) ?? [])];
    while (stack.length) {
      const m = stack.pop();
      if (seen.has(m)) continue;
      seen.add(m);
      for (const next of direct.get(m) ?? []) if (!seen.has(next)) stack.push(next);
    }
    closure.set(start, seen);
  }
  return { direct, closure };
}

/**
 * One witness path from `a` to `b`, so a transitive finding can name the hop that caused it
 * instead of asserting a relationship the reader has to go and discover.
 *
 * cm:guard the neighbour order is SORTED, not the insertion order of `direct`. That set is built by
 *   walking graph.edges, so without this the chosen path among several equally short ones depends
 *   on which file dependency-cruiser happened to list first — and an independence finding's `edge`
 *   IS this path, which makes it the baseline key. Unsorted, moving an import between two files in
 *   the same position of the graph re-witnesses a PRE-EXISTING finding under a different key: the
 *   pre-write hook reads that as newly introduced and denies, and a frozen baseline entry written
 *   by CI stops matching. Determinism here is a correctness property, not tidiness.
 */
export function witness(direct, a, b) {
  const prev = new Map([[a, null]]);
  const queue = [a];
  while (queue.length) {
    const cur = queue.shift();
    for (const next of [...(direct.get(cur) ?? [])].sort()) {
      if (prev.has(next)) continue;
      prev.set(next, cur);
      if (next === b) {
        const path = [b];
        for (let n = cur; n !== null; n = prev.get(n)) path.unshift(n);
        return path;
      }
      queue.push(next);
    }
  }
  return null;
}
