export type ContractRefusalCode =
  | 'CONTRACT_NOT_PUBLISHED'
  | 'ARTIFACT_MEASURED_FROM_GIT'
  | 'NOTHING_TO_RECORD'
  | 'SEMANTIC_WITH_ARTIFACT'
  | 'SEMANTIC_BELOW_UNKNOWN'
  | 'SEMANTIC_WITHOUT_VERSION'
  | 'VERSION_NOT_IN_SCHEME'
  | 'VERSION_BUMP_TOO_SMALL'
  | 'ELEMENT_NOT_IN_CONTRACT'
  | 'EXAMPLE_NOT_IN_CONTRACT'
  | 'CONTRACT_PATTERN_UNSAFE';
