import { projects } from '../db/schema.js';

export const PATCHED_PROJECT = {
  id: projects.id,
  slug: projects.slug,
  name: projects.name,
  orgId: projects.orgId,
  createdBy: projects.createdBy,
  description: projects.description,
  kind: projects.kind,
  repoPath: projects.repoPath,
  repoUrl: projects.repoUrl,
  workspaceSetup: projects.workspaceSetup,
  baseBranch: projects.baseBranch,
  liveBranch: projects.liveBranch,
  releaseModel: projects.releaseModel,
  releaseStrategy: projects.releaseStrategy,
  defaultDeviceId: projects.defaultDeviceId,
  agentConfig: projects.agentConfig,
  environments: projects.environments,
  webhookSecret: projects.webhookSecret,
  issuePrefix: projects.issuePrefix,
  createdAt: projects.createdAt,
};

/** The GET /:id detail projection: `PATCHED_PROJECT` plus the fields only a read returns. */
export const PROJECT_DETAIL = {
  id: projects.id,
  slug: projects.slug,
  name: projects.name,
  orgId: projects.orgId,
  createdBy: projects.createdBy,
  description: projects.description,
  repoPath: projects.repoPath,
  repoUrl: projects.repoUrl,
  workspaceSetup: projects.workspaceSetup,
  baseBranch: projects.baseBranch,
  liveBranch: projects.liveBranch,
  releaseModel: projects.releaseModel,
  releaseStrategy: projects.releaseStrategy,
  defaultDeviceId: projects.defaultDeviceId,
  agentConfig: projects.agentConfig,
  environments: projects.environments,
  webhookSecret: projects.webhookSecret,
  apiKey: projects.apiKey,
  issuePrefix: projects.issuePrefix,
  archivedAt: projects.archivedAt,
  createdAt: projects.createdAt,
} as const;
